** Introduction
*** Background
Muslim conversions and settlement in the region now referred to as Bangladesh began in the 10th century, primarily from Arab and Persian traders and preachers. Europeans began to set up trading posts in the area in the 16th century. Eventually the area known as Bengal, primarily Hindu in the western section and mostly Muslim in the eastern half, became part of British India. Partition in 1947 resulted in an eastern wing of Pakistan in the Muslim-majority area, which became East Pakistan. Calls for greater autonomy and animosity between the eastern and western wings of Pakistan led to a Bengali independence movement. That movement, led by the Awami League (AL) and supported by India, won independence for Bangladesh in a brief war in 1971, during which at least 300,000 civilians died.
The post-independence, AL government faced daunting challenges and in 1975 was overthrown by the military, triggering a series of military coups that resulted in a military-backed government and subsequent creation of the Bangladesh Nationalist Party (BNP). That government also ended in a coup in 1981, followed by military-backed rule until democratic elections in 1991. The BNP and AL alternated in power between 1991 and 2013, with the exception of a military-backed, emergency caretaker regime that suspended parliamentary elections planned for January 2007 in an effort to reform the political system and root out corruption. That government returned the country to fully democratic rule in December 2008 with the election of the AL and Prime Minister Sheikh HASINA. In January 2014, the incumbent AL won the national election by an overwhelming majority after the BNP boycotted, extending HASINA's term as prime minister. With the help of international development assistance, Bangladesh has made great progress in food security since independence, and the economy has grown at an annual average of about 6% over the last two decades.
** Geography
*** Location
Southern Asia, bordering the Bay of Bengal, between Burma and India
*** Geographic coordinates
24 00 N, 90 00 E
*** Map references
Asia
*** Area
- total :: 148,460 sq km
- land :: 130,170 sq km
- water :: 18,290 sq km
- country comparison to the world :: 95
*** Area - comparative
slightly smaller than Iowa
*** Land boundaries
- total :: 4,413 km
- border countries (2) :: Burma 271 km, India 4,142 km
*** Coastline
580 km
*** Maritime claims
- territorial sea :: 12 nm
- contiguous zone :: 18 nm
- exclusive economic zone :: 200 nm
- continental shelf :: to the outer limits of the continental margin
*** Climate
tropical; mild winter (October to March); hot, humid summer (March to June); humid, warm rainy monsoon (June to October)
*** Terrain
mostly flat alluvial plain; hilly in southeast
*** Elevation extremes
- lowest point :: Indian Ocean 0 m
- highest point :: Keokradong 1,230 m
*** Natural resources
natural gas, arable land, timber, coal
*** Land use
- agricultural land :: 70.1%
arable land 59%; permanent crops 6.5%; permanent pasture 4.6%
- forest :: 11.1%
- other :: 18.8% (2011 est.)
*** Irrigated land
50,500 sq km (2008)
*** Total renewable water resources
1,227 cu km (2011)
*** Freshwater withdrawal (domestic/industrial/agricultural)
- total :: 35.87  cu km/yr (10%/2%/88%)
- per capita :: 238.3  cu m/yr (2008)
*** Natural hazards
droughts; cyclones; much of the country routinely inundated during the summer monsoon season
*** Environment - current issues
many people are landless and forced to live on and cultivate flood-prone land; waterborne diseases prevalent in surface water; water pollution, especially of fishing areas, results from the use of commercial pesticides; ground water contaminated by naturally occurring arsenic; intermittent water shortages because of falling water tables in the northern and central parts of the country; soil degradation and erosion; deforestation; severe overpopulation
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Endangered Species, Environmental Modification, Hazardous Wastes, Law of the Sea, Ozone Layer Protection, Ship Pollution, Wetlands
- signed, but not ratified :: none of the selected agreements
*** Geography - note
most of the country is situated on deltas of large rivers flowing from the Himalayas: the Ganges unites with the Jamuna (main channel of the Brahmaputra) and later joins the Meghna to eventually empty into the Bay of Bengal
** People and Society
*** Nationality
- noun :: Bangladeshi(s)
- adjective :: Bangladeshi
*** Ethnic groups
Bengali at least 98%, ethnic groups 1.1%
- note :: Bangladesh's goverment recognizes 27 ethnic groups under the 2010 Cultural Institution for Small Anthropological Groups Act; other sources estimate there are about 75 ethnic groups; critics of the 2011 census claim that it underestimates the size of Bangladesh's ethnic population (2011 est.)
*** Languages
Bangla 98.8% (official, also known as Bengali), other 1.2% (2011 est.)
*** Religions
Muslim 89.5%, Hindu 9.6%, other 0.9% (includes Buddhist .5%, Christian .3%) (2004 est.)
*** Population
168,957,745 (July 2015 est.)
- country comparison to the world :: 9
*** Age structure
- 0-14 years :: 31.62% (male 27,115,731/female 26,311,130)
- 15-24 years :: 18.86% (male 14,976,910/female 16,880,807)
- 25-54 years :: 38.27% (male 30,608,224/female 34,053,744)
- 55-64 years :: 6.12% (male 5,196,932/female 5,150,199)
- 65 years and over :: 5.13% (male 4,258,664/female 4,405,404) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 52.2%
- youth dependency ratio :: 44.9%
- elderly dependency ratio :: 7.6%
- potential support ratio :: 13.2% (2015 est.)
*** Median age
- total :: 24.7 years
- male :: 24.2 years
- female :: 25.1 years (2015 est.)
*** Population growth rate
1.6% (2015 est.)
- country comparison to the world :: 75
*** Birth rate
21.14 births/1,000 population (2015 est.)
- country comparison to the world :: 76
*** Death rate
5.61 deaths/1,000 population (2015 est.)
- country comparison to the world :: 174
*** Net migration rate
0.46 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 72
*** Urbanization
- urban population :: 34.3% of total population (2015)
- rate of urbanization :: 3.55% annual rate of change (2010-15 est.)
*** Major urban areas - population
DHAKA (capital) 17.598 million; Chittagong 4.539 million; Khulna 1.022 million; Rajshahi 844,000 (2015)
*** Sex ratio
- at birth :: 1.04 male(s)/female
- 0-14 years :: 1.03 male(s)/female
- 15-24 years :: 0.89 male(s)/female
- 25-54 years :: 0.9 male(s)/female
- 55-64 years :: 1.01 male(s)/female
- 65 years and over :: 0.97 male(s)/female
- total population :: 0.95 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 44.09 deaths/1,000 live births
- male :: 46.56 deaths/1,000 live births
- female :: 41.53 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 46
*** Life expectancy at birth
- total population :: 70.94 years
- male :: 69.02 years
- female :: 72.94 years (2015 est.)
- country comparison to the world :: 151
*** Total fertility rate
2.4 children born/woman (2015 est.)
- country comparison to the world :: 82
*** Contraceptive prevalence rate
61.2% (2011)
*** Health expenditures
3.7% of GDP (2013)
- country comparison to the world :: 169
*** Physicians density
0.36 physicians/1,000 population (2011)
*** Hospital bed density
0.6 beds/1,000 population (2011)
*** Drinking water source
- improved :: 
urban: 86.5% of population
rural: 87% of population
total: 86.9% of population
- unimproved :: 
urban: 13.5% of population
rural: 13% of population
total: 13.1% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 57.7% of population
rural: 62.1% of population
total: 60.6% of population
- unimproved :: 
urban: 42.3% of population
rural: 37.9% of population
total: 39.4% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
0.01% (2014 est.)
- country comparison to the world :: 130
*** HIV/AIDS - people living with HIV/AIDS
8,900 (2014 est.)
- country comparison to the world :: 96
*** HIV/AIDS - deaths
700 (2014 est.)
- country comparison to the world :: 75
*** Major infectious diseases
- degree of risk :: high
- food or waterborne diseases :: bacterial and protozoal diarrhea, hepatitis A and E, and typhoid fever
- vectorborne diseases :: dengue fever and malaria are high risks in some locations
- water contact disease :: leptospirosis
- animal contact disease :: rabies
- note :: highly pathogenic H5N1 avian influenza has been identified in this country; it poses a negligible risk with extremely rare cases possible among US citizens who have close contact with birds (2013)
*** Obesity - adult prevalence rate
3.3% (2014)
- country comparison to the world :: 190
*** Children under the age of 5 years underweight
35.1% (2013)
- country comparison to the world :: 5
*** Education expenditures
2.2% of GDP (2009)
- country comparison to the world :: 161
*** Literacy
- definition :: age 15 and over can read and write
- total population :: 61.5%
- male :: 64.6%
- female :: 58.5% (2015 est.)
*** School life expectancy (primary to tertiary education)
- total :: 10 years
- male :: 10 years
- female :: 10 years (2011)
*** Child labor - children ages 5-14
- total number :: 4,485,497
- percentage :: 13% (2006 est.)
*** Unemployment, youth ages 15-24
- total :: 9.3%
- male :: 8%
- female :: 13.6% (2005 est.)
- country comparison to the world :: 105
** Government
*** Country name
- conventional long form :: People's Republic of Bangladesh
- conventional short form :: Bangladesh
- local long form :: Gana Prajatantri Bangladesh
- local short form :: Bangladesh
- former :: East Bengal, East Pakistan
- note :: the name - a compound of the Bengali words "Bangla" (Bengal) and "desh" (country) - means Country of Bengal
*** Government type
parliamentary democracy
*** Capital
- name :: Dhaka
- geographic coordinates :: 23 43 N, 90 24 E
- time difference :: UTC+6 (11 hours ahead of Washington, DC, during Standard Time)
*** Administrative divisions
7 divisions; Barisal, Chittagong, Dhaka, Khulna, Rajshahi, Rangpur, Sylhet
*** Independence
16 December 1971 (from West Pakistan)
*** National holiday
Independence Day, 26 March (1971); Victory Day, 16 December (1971); note - March 1971 is the date of the Awami League's declaration of an independent Bangladesh, and 16 December, known as Victory Day, memorializes the military victory over Pakistan and the official creation of the state of Bangladesh
*** Constitution
previous 1935, 1956, 1962 (preindependence); latest enacted 4 November 1972, effective 16 December 1972, suspended March 1982, restored November 1986; amended many times, last in 2011 (2011)
*** Legal system
mixed legal system of mostly English common law and Islamic law
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; accepts ICCt jurisdiction
*** Citizenship
- birthright citizenship :: no, unless one parent was a citizen of Bangladesh
- dual citizenship recognized :: yes, but limited to select countries
- residency requirement for naturalization :: 5 years
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: President Abdul HAMID (since 24 April 2013); note - Abdul HAMID served as acting president following the death of Zillur RAHMAN in March 2013; HAMID was subsequently indirectly elected by the National Parliament and sworn in 24 April 2013
- head of government :: Prime Minister Sheikh HASINA (since 6 January 2009; reappointed 5 January 2014)
- cabinet :: Cabinet selected by the prime minister, appointed by the president
- elections/appointments :: president indirectly elected by the National Parliament for a 5-year term (eligible for a second term); election last held on 22 April 2013 (next must be held by 2018); the president appoints as prime minister the majority party leader in the National Parliament
- election results :: President Abdul HAMID (AL) elected by the National Parliament unopposed; Sheikh HASINA reappointed prime minister as leader of the majority AL party
*** Legislative branch
- description :: unicameral National Parliament or Jatiya Sangsad (300 seats including 45 reserved for women; members directly elected in single territorial constituencies by simple majority vote; members serve 5-year terms)
- elections :: last held on 5 January 2014 (next to be held by January 2019); note - the 5 January 2014 poll was marred by widespread violence, boycotts, general strikes, and low voter turnout
- election results :: percent of vote by party - AL-led Alliance 79%, JP 34%; seats by party - AL 234, JP 34, other 32
*** Judicial branch
- highest court(s) :: Supreme Court of Bangladesh (organized into the Appellate Division with 7 justices and the High Court Division with 99 justices)
- judge selection and term of office :: chief justice and justices appointed by the president; justices serve until retirement at age 67
- subordinate courts :: civil courts include: Assistant Judge's Court; Joint District Judge's Court; Additional District Judge's Court; District Judge's Court; criminal courts include: Court of Sessions; Court of Metropolitan Sessions; special courts/tribunals; Metropolitan Magistrate Courts; Magistrate Court
*** Political parties and leaders
Awami League or AL [Sheikh HASINA]
Communist Party of Bangladesh or CPB [Manjurul A. KHAN]
Bangladesh Nationalist Front or BNF [Abdul Kalam AZADI]
Bangladesh Nationalist Party or BNP [Khaleda ZIA]
Bikalpa Dhara Bangladesh or BDB [Badrudozza CHOWDHURY]
Islami Oikya Jote or IOJ [multiple leaders]
Jatiya Party or JP (Ershad faction) [Hussain Mohammad ERSHAD]
Liberal Democratic Party or LDP [Oli AHMED]
National Socialist Party or JSD [KHALEQUZZAMAN]
Tarikat Foundation [Syed Nozibul Bashar MAIZBHANDARI]
Workers Party or WP [Rashed Khan MENON]
*** Political pressure groups and leaders
Ain o Salish Kendro (Centre for Law and Mediation) or ASK (legal aid and civil rights)
Bangladesh Center for Worker Solidarity
Bangladesh Rural Advancement Committee or BRAC
Federation of Bangladesh Chambers of Commerce and Industry
Ministry of Women's and Children's Affairs or MoWCA (advocacy group to end gender-based violence)
Odikhar (human rights group)
- other :: associations of madrassa teachers; business associations, including those intended to promote international trade; development and advocacy NGOs associated with the Grameen Bank; environmentalists; Islamist groups; labor rights advocacy groups; NGOs focused on poverty, alleviation, and socioeconomic international trade; religious leaders; tribal groups and advocacy organizations; union leaders
*** International organization participation
ADB, ARF, BIMSTEC, C, CD, CICA (observer), CP, D-8, FAO, G-77, IAEA, IBRD, ICAO, ICC (national committees), ICRM, IDA, IDB, IFAD, IFC, IFRCS, IHO, ILO, IMF, IMO, IMSO, Interpol, IOC, IOM, IPU, ISO, ITSO, ITU, ITUC (NGOs), MIGA, MINURSO, MINUSMA, MONUSCO, NAM, OIC, OPCW, PCA, SAARC, SACEP, UN, UNAMID, UNCTAD, UNESCO, UNHCR, UNIDO, UNIFIL, UNMIL, UNMISS, UNOCI, UNWTO, UPU, WCO, WFTU (NGOs), WHO, WIPO, WMO, WTO
*** Diplomatic representation in the US
- chief of mission :: Ambassador Mohammad ZIAUDDIN (since 18 September 2014)
- chancery :: 3510 International Drive NW, Washington, DC 20008
- telephone :: [1] (202) 244-0183
- FAX :: [1] (202) 244-2771
- consulate(s) general :: Los Angeles, New York
*** Diplomatic representation from the US
- chief of mission :: Ambassador Marcia BERNICAT (since 12 January 2015)
- embassy :: Madani Avenue, Baridhara, Dhaka 1212
- mailing address :: G. P. O. Box 323, Dhaka 1000
- telephone :: [880] (2) 5566-2000
- FAX :: [880] (2) 5566-2915
*** Flag description
green field with a large red disk shifted slightly to the hoist side of center; the red disk represents the rising sun and the sacrifice to achieve independence; the green field symbolizes the lush vegetation of Bangladesh
*** National symbol(s)
Bengal tiger, water lily; national colors: green, red
*** National anthem
- name :: "Amar Shonar Bangla" (My Golden Bengal)
- lyrics/music :: Rabindranath TAGORE
- note :: adopted 1971; Rabindranath TAGORE, a Nobel laureate, also wrote India's national anthem

** Economy
*** Economy - overview
Bangladesh's economy has grown roughly 6% per year since 1996 despite political instability, poor infrastructure, corruption, insufficient power supplies, slow implementation of economic reforms, and the 2008-09 global financial crisis and recession. Although more than half of GDP is generated through the service sector, almost half of Bangladeshis are employed in the agriculture sector with rice as the single-most-important product. Garment exports, the backbone of Bangladesh's industrial sector, accounted for more than 80% of total exports and surpassed $18 billion in 2014. The sector has remained resilient in recent years amidst a series of factory accidents that have killed over 1,000 workers and crippling strikes that shut down virtually all economic activity. Steady garment export growth combined with remittances from overseas Bangladeshis - which totaled $14 billion and 8% of GDP in 2014 - are the largest contributors to Bangladesh's current account surplus and rising foreign exchange holdings.
*** GDP (purchasing power parity)
$533.7 billion (2014 est.)
$503 billion (2013 est.)
$474.2 billion (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 36
*** GDP (official exchange rate)
$185.4 billion (2014 est.)
*** GDP - real growth rate
6.1% (2014 est.)
6.1% (2013 est.)
6.3% (2012 est.)
- country comparison to the world :: 29
*** GDP - per capita (PPP)
$3,400 (2014 est.)
$3,200 (2013 est.)
$3,000 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 180
*** Gross national saving
30% of GDP (2014 est.)
30.4% of GDP (2013 est.)
30.1% of GDP (2012 est.)
- country comparison to the world :: 30
*** GDP - composition, by end use
- household consumption :: 74.1%
- government consumption :: 5.5%
- investment in fixed capital :: 26.3%
- investment in inventories :: 0.4%
- exports of goods and services :: 22.6%
- imports of goods and services :: -28.9%
 (2014 est.)
*** GDP - composition, by sector of origin
- agriculture :: 15.1%
- industry :: 26.5%
- services :: 58.3% (2014 est.)
*** Agriculture - products
rice, jute, tea, wheat, sugarcane, potatoes, tobacco, pulses, oilseeds, spices, fruit; beef, milk, poultry
*** Industries
jute, cotton, garments, paper, leather, fertilizer, iron and steel, cement, petroleum products, tobacco, pharmaceuticals, ceramics, tea, salt, sugar, edible oils, soap and detergent, fabricated metal products, electricity, natural gas
*** Industrial production growth rate
8.4% (2014 est.)
- country comparison to the world :: 19
*** Labor force
80.27 million
- note :: extensive export of labor to Saudi Arabia, Kuwait, UAE, Oman, Qatar, and Malaysia; workers' remittances were $10.9 billion in FY09/10 (2014 est.)
- country comparison to the world :: 7
*** Labor force - by occupation
- agriculture :: 47%
- industry :: 13%
- services :: 40% (2010 est.)
*** Unemployment rate
5% (2014 est.)
5% (2013 est.)
- note :: about 40% of the population is underemployed; many persons counted as employed work only a few hours a week and at low wages
- country comparison to the world :: 48
*** Population below poverty line
31.5% (2010 est.)
*** Household income or consumption by percentage share
- lowest 10% :: 4%
- highest 10% :: 27% (2010 est.)
*** Distribution of family income - Gini index
32.1 (2010)
33.6 (1996)
- country comparison to the world :: 107
*** Budget
- revenues :: $18.09 billion
- expenditures :: $24.33 billion (2014 est.)
*** Taxes and other revenues
9.7% of GDP (2014 est.)
- country comparison to the world :: 206
*** Budget surplus (+) or deficit (-)
-3.3% of GDP (2014 est.)
- country comparison to the world :: 125
*** Public debt
28.6% of GDP (2014 est.)
30.3% of GDP (2013 est.)
- country comparison to the world :: 131
*** Fiscal year
1 July - 30 June
*** Inflation rate (consumer prices)
7% (2014 est.)
7.5% (2013 est.)
- country comparison to the world :: 194
*** Central bank discount rate
5% (31 December 2010)
5% (31 December 2009)
- country comparison to the world :: 76
*** Commercial bank prime lending rate
13% (31 December 2014 est.)
13% (31 December 2013 est.)
- country comparison to the world :: 58
*** Stock of narrow money
$19.69 billion (31 December 2014 est.)
$16.54 billion (31 December 2013 est.)
- country comparison to the world :: 68
*** Stock of broad money
$98.43 billion (31 December 2014 est.)
$84.11 billion (31 December 2013 est.)
- country comparison to the world :: 54
*** Stock of domestic credit
$99.59 billion (31 December 2014 est.)
$89.32 billion (31 December 2013 est.)
- country comparison to the world :: 54
*** Market value of publicly traded shares
$41.73 billion (31 December 2014 est.)
$17.48 billion (31 December 2012)
$23.55 billion (31 December 2011 est.)
- country comparison to the world :: 56
*** Current account balance
-$132 million (2014 est.)
$2.366 billion (2013 est.)
- country comparison to the world :: 46
*** Exports
$31.2 billion (2014 est.)
$28.62 billion (2013 est.)
- country comparison to the world :: 65
*** Exports - commodities
garments, knitwear, agricultural products, frozen food (fish and seafood), jute and jute goods, leather
*** Exports - partners
US 14.3%, Germany 13.6%, UK 7.9%, France 5.2%, Spain 4.3%, Italy 4.1% (2014)
*** Imports
$38.5 billion (2014 est.)
$35 billion (2013 est.)
- country comparison to the world :: 64
*** Imports - commodities
cotton, machinery and equipment, chemicals, iron and steel, foodstuffs
*** Imports - partners
China 18.8%, India 14.8%, Singapore 5.8%, Malaysia 4.2% (2014)
*** Reserves of foreign exchange and gold
$21.46 billion (31 December 2014 est.)
$18.09 billion (31 December 2013 est.)
- country comparison to the world :: 56
*** Debt - external
$33.2 billion (30 June 2014 est.)
$28.26 billion (30 June 2013 est.)
- country comparison to the world :: 70
*** Stock of direct foreign investment - at home
$8.625 billion (30 June 2014 est.)
$8.593 billion (31 December 2013 est.)
- country comparison to the world :: 90
*** Stock of direct foreign investment - abroad
$166.9 million (31 December 2014 est.)
$162.9 million (31 December 2013 est.)
- country comparison to the world :: 89
*** Exchange rates
taka (BDT) per US dollar -
77.57 (2014 est.)
78.103 (2013 est.)
81.86 (2012 est.)
74.152 (2011 est.)
69.649 (2010 est.)
** Energy
*** Electricity - production
42.41 billion kWh (2011 est.)
- country comparison to the world :: 57
*** Electricity - consumption
37.88 billion kWh (2011 est.)
- country comparison to the world :: 56
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 108
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 121
*** Electricity - installed generating capacity
10.26 million kW (2013 est.)
- country comparison to the world :: 56
*** Electricity - from fossil fuels
97.7% of total installed capacity (2013 est.)
- country comparison to the world :: 57
*** Electricity - from nuclear fuels
0% of total installed capacity (2013 est.)
- country comparison to the world :: 49
*** Electricity - from hydroelectric plants
2.3% of total installed capacity (2013 est.)
- country comparison to the world :: 137
*** Electricity - from other renewable sources
0% of total installed capacity (2013 est.)
- country comparison to the world :: 159
*** Crude oil - production
4,200 bbl/day (2013 est.)
- country comparison to the world :: 90
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 83
*** Crude oil - imports
23,620 bbl/day (2010 est.)
- country comparison to the world :: 67
*** Crude oil - proved reserves
28 million bbl (1 January 2014 est.)
- country comparison to the world :: 83
*** Refined petroleum products - production
22,710 bbl/day (2010 est.)
- country comparison to the world :: 91
*** Refined petroleum products - consumption
118,700 bbl/day (2013 est.)
- country comparison to the world :: 73
*** Refined petroleum products - exports
3,288 bbl/day (2010 est.)
- country comparison to the world :: 97
*** Refined petroleum products - imports
84,490 bbl/day (2010 est.)
- country comparison to the world :: 55
*** Natural gas - production
21.86 billion cu m (2012 est.)
- country comparison to the world :: 31
*** Natural gas - consumption
21.86 billion cu m (2012 est.)
- country comparison to the world :: 35
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 62
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 160
*** Natural gas - proved reserves
264.6 billion cu m (1 January 2014 est.)
- country comparison to the world :: 42
*** Carbon dioxide emissions from consumption of energy
63.5 million Mt (2012 est.)
- country comparison to the world :: 54
** Communications
*** Telephones - fixed lines
- total subscriptions :: 1.09 million
- subscriptions per 100 inhabitants :: 1 (2014 est.)
- country comparison to the world :: 74
*** Telephones - mobile cellular
- total :: 120.4 million
- subscriptions per 100 inhabitants :: 72 (2014 est.)
- country comparison to the world :: 12
*** Telephone system
- general assessment :: inadequate for a modern country; introducing digital systems; trunk systems include VHF and UHF microwave radio relay links, and some fiber-optic cable in cities
- domestic :: fixed-line teledensity remains only about 1 per 100 persons; mobile-cellular telephone subscribership has been increasing rapidly and now exceeds 67 telephones per 100 persons
- international :: country code - 880; landing point for the SEA-ME-WE-4 fiber-optic submarine cable system that provides links to Europe, the Middle East, and Asia; satellite earth stations - 6; international radiotelephone communications and landline service to neighboring countries (2011)
*** Broadcast media
state-owned Bangladesh Television (BTV) operates 1 terrestrial TV station, 3 radio networks, and about 10 local stations; 8 private satellite TV stations and 3 private radio stations also broadcasting; foreign satellite TV stations are gaining audience share in the large cities; several international radio broadcasters are available (2007)
*** Radio broadcast stations
AM 17, FM 19, shortwave 2 (2009)
*** Television broadcast stations
17 (2009)
*** Internet country code
.bd
*** Internet users
- total :: 11.4 million
- percent of population :: 6.9% (2014 est.)
- country comparison to the world :: 42
** Transportation
*** Airports
18 (2013)
- country comparison to the world :: 139
*** Airports - with paved runways
- total :: 16
- over 3,047 m :: 2
- 2,438 to 3,047 m :: 2
- 1,524 to 2,437 m :: 6
- 914 to 1,523 m :: 1
- under 914 m :: 5 (2013)
*** Airports - with unpaved runways
- total :: 2
- 1,524 to 2,437 m :: 1
- under 914 m :: 
1 (2013)
*** Heliports
3 (2013)
*** Pipelines
gas 2,950 km (2013)
*** Railways
- total :: 2,460 km
- broad gauge :: 659 km 1.676-m gauge
- narrow gauge :: 1,801 km 1.000-m gauge (2014)
- country comparison to the world :: 60
*** Roadways
- total :: 21,269 km
- paved :: 2,021 km
- unpaved :: 19,248 km (2010)
- country comparison to the world :: 106
*** Waterways
8,370 km (includes up to 3,060 km of main cargo routes; network reduced to 5,200 km in the dry season) (2011)
- country comparison to the world :: 16
*** Merchant marine
- total :: 62
- by type :: bulk carrier 25, cargo 28, chemical tanker 1, container 5, petroleum tanker 3
- foreign-owned :: 8 (China 1, Singapore 7)
- registered in other countries :: 10 (Comoros 1, Hong Kong 1, Panama 5, Saint Vincent and the Grenadines 1, Sierra Leone 1, Singapore 1) (2010)
- country comparison to the world :: 64
*** Ports and terminals
- major seaport(s) :: Chittagong
- river port(s) :: Mongla Port (Sela River)
- container port(s) :: Chittagong (1,392,104) (2011)
*** Transportation - note
the International Maritime Bureau reports the territorial waters of Bangladesh remain a risk for armed robbery against ships; in 2014, attacks against commercial vessels increased to 21 over 12 such incidents in 2013
** Military
*** Military branches
Bangladesh Defense Force: Bangladesh Army (Sena Bahini), Bangladesh Navy (Noh Bahini, BN), Bangladesh Air Force (Biman Bahini, BAF) (2013)
*** Military service age and obligation
16-19 years of age for voluntary military service; Bangladeshi birth and 10th grade education required; initial obligation 15 years (2012)
*** Manpower available for military service
- males age 16-49 :: 36,520,491 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 30,486,086
- females age 16-49 :: 35,616,093 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 1,606,963
- female :: 1,689,442 (2010 est.)
*** Military expenditures
1.15% of GDP (2013)
1.35% of GDP (2012)
1.44% of GDP (2011)
1.35% of GDP (2010)
- country comparison to the world :: 86
** Transnational Issues
*** Disputes - international
Bangladesh referred its maritime boundary claims with Burma and India to the International Tribunal on the Law of the Sea; Indian Prime Minister Singh's September 2011 visit to Bangladesh resulted in the signing of a Protocol to the 1974 Land Boundary Agreement between India and Bangladesh, which had called for the settlement of longstanding boundary disputes over undemarcated areas and the exchange of territorial enclaves, but which had never been implemented; Bangladesh struggles to accommodate 29,000 Rohingya, Burmese Muslim minority from Arakan State, living as refugees in Cox's Bazar; Burmese border authorities are constructing a 200 km (124 mi) wire fence designed to deter illegal cross-border transit and tensions from the military build-up along border
*** Refugees and internally displaced persons
- refugees (country of origin) :: 232,462 (Burma) (2014)
- IDPs :: at least 431,000 (violence, human rights violations, religious persecution, natural disasters) (2015)
*** Illicit drugs
transit country for illegal drugs produced in neighboring countries