** Introduction
*** Background
Various ethnic Burmese and ethnic minority city-states or kingdoms occupied the present borders through the 19th century. Over a period of 62 years (1824-1886), Britain conquered Burma and incorporated the country into its Indian Empire. Burma was administered as a province of India until 1937 when it became a separate, self-governing colony; in 1948, Burma attained independence from the British Commonwealth. Gen. NE WIN dominated the government from 1962 to 1988, first as military ruler, then as self-appointed president, and later as political kingpin. In response to widespread civil unrest, NE WIN resigned in 1988, but within months the military crushed student-led protests and took power.
Multiparty legislative elections in 1990 resulted in the main opposition party - the National League for Democracy (NLD) - winning a landslide victory. Instead of handing over power, the junta placed NLD leader (and Nobel Peace Prize recipient) AUNG SAN SUU KYI (ASSK) under house arrest from 1989 to 1995, 2000 to 2002, and from May 2003 to November 2010. In late September 2007, the ruling junta brutally suppressed protests over increased fuel prices led by prodemocracy activists and Buddhist monks, killing at least 13 people and arresting thousands for participating in the demonstrations. In early May 2008, Burma was struck by Cyclone Nargis, which left over 138,000 dead and tens of thousands injured and homeless. Despite this tragedy, the junta proceeded with its May constitutional referendum, the first vote in Burma since 1990. Parliamentary elections held in November 2010, considered flawed by many in the international community, saw the ruling Union Solidarity and Development Party garner over 75% of the seats.
Parliament convened in January 2011 and selected former Prime Minister THEIN SEIN as president. Although the vast majority of national-level appointees named by THEIN SEIN are former or current military officers, the government has initiated a series of political and economic reforms leading to a substantial opening of the long-isolated country. These reforms have included releasing hundreds of political prisoners, concluding negotiations on a draft nationwide cease-fire with the country's various ethnic armed groups, pursuing legal reform, and gradually reducing restrictions on freedom of the press, association, and civil society. At least due in part to these reforms, ASSK was elected to parliament in April 2012, and now serves as chair of the Committee for Rule of Law and Tranquility. Most political parties have begun building their institutions in preparation for the next round of general elections, scheduled for late 2015. The country served as chair of the Association of Southeast Asian Nations (ASEAN) for 2014.
** Geography
*** Location
Southeastern Asia, bordering the Andaman Sea and the Bay of Bengal, between Bangladesh and Thailand
*** Geographic coordinates
22 00 N, 98 00 E
*** Map references
Southeast Asia
*** Area
- total :: 676,578 sq km
- land :: 653,508 sq km
- water :: 23,070 sq km
- country comparison to the world :: 40
*** Area - comparative
slightly smaller than Texas
- Area comparison map ::  
*** Land boundaries
- total :: 6,522 km
- border countries (5) :: Bangladesh 271 km, China 2,129 km, India 1,468 km, Laos 238 km, Thailand 2,416 km
*** Coastline
1,930 km
*** Maritime claims
- territorial sea :: 12 nm
- contiguous zone :: 24 nm
- exclusive economic zone :: 200 nm
- continental shelf :: 200 nm or to the edge of the continental margin
*** Climate
tropical monsoon; cloudy, rainy, hot, humid summers (southwest monsoon, June to September); less cloudy, scant rainfall, mild temperatures, lower humidity during winter (northeast monsoon, December to April)
*** Terrain
central lowlands ringed by steep, rugged highlands
*** Elevation extremes
- lowest point :: Andaman Sea/Bay of Bengal 0 m
- highest point :: Gamlang Razi 5,870 m
*** Natural resources
petroleum, timber, tin, antimony, zinc, copper, tungsten, lead, coal, marble, limestone, precious stones, natural gas, hydropower, arable land
*** Land use
- agricultural land :: 19.2%
arable land 16.5%; permanent crops 2.2%; permanent pasture 0.5%
- forest :: 48.2%
- other :: 32.6% (2011 est.)
*** Irrigated land
21,100 sq km (2004)
*** Total renewable water resources
1,168 cu km (2011)
*** Freshwater withdrawal (domestic/industrial/agricultural)
- total :: 33.23  cu km/yr (10%/1%/89%)
- per capita :: 728.6  cu m/yr (2005)
*** Natural hazards
destructive earthquakes and cyclones; flooding and landslides common during rainy season (June to September); periodic droughts
*** Environment - current issues
deforestation; industrial pollution of air, soil, and water; inadequate sanitation and water treatment contribute to disease
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Endangered Species, Law of the Sea, Ozone Layer Protection, Ship Pollution, Tropical Timber 83, Tropical Timber 94
- signed, but not ratified :: none of the selected agreements
*** Geography - note
strategic location near major Indian Ocean shipping lanes
** People and Society
*** Nationality
- noun :: Burmese (singular and plural)
- adjective :: Burmese
*** Ethnic groups
Burman 68%, Shan 9%, Karen 7%, Rakhine 4%, Chinese 3%, Indian 2%, Mon 2%, other 5%
*** Languages
Burmese (official)
- note :: minority ethnic groups have their own languages
*** Religions
Buddhist 89%, Christian 4% (Baptist 3%, Roman Catholic 1%), Muslim 4%, Animist 1%, other 2%
*** Population
56,320,206
- note :: estimates for this country take into account the effects of excess mortality due to AIDS; this can result in lower life expectancy, higher infant mortality, higher death rates, lower population growth rates, and changes in the distribution of population by age and sex than would otherwise be expected (July 2015 est.)
- country comparison to the world :: 25
*** Age structure
- 0-14 years :: 26.07% (male 7,485,419/female 7,194,500)
- 15-24 years :: 18.02% (male 5,138,185/female 5,009,470)
- 25-54 years :: 43.31% (male 12,132,302/female 12,261,750)
- 55-64 years :: 7.24% (male 1,919,725/female 2,157,789)
- 65 years and over :: 5.36% (male 1,313,711/female 1,707,355) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 49.1%
- youth dependency ratio :: 41.1%
- elderly dependency ratio :: 8%
- potential support ratio :: 12.5% (2015 est.)
*** Median age
- total :: 28.3 years
- male :: 27.7 years
- female :: 28.9 years (2015 est.)
*** Population growth rate
1.01% (2015 est.)
- country comparison to the world :: 116
*** Birth rate
18.39 births/1,000 population (2015 est.)
- country comparison to the world :: 97
*** Death rate
7.96 deaths/1,000 population (2015 est.)
- country comparison to the world :: 101
*** Net migration rate
-0.28 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 124
*** Urbanization
- urban population :: 34.1% of total population (2015)
- rate of urbanization :: 2.49% annual rate of change (2010-15 est.)
*** Major urban areas - population
RANGOON (Yangon) (capital) 4.802 million; Mandalay 1.167 million; Nay Pyi Taw 1.03 million (2015)
*** Sex ratio
- at birth :: 1.06 male(s)/female
- 0-14 years :: 1.04 male(s)/female
- 15-24 years :: 1.03 male(s)/female
- 25-54 years :: 0.99 male(s)/female
- 55-64 years :: 0.89 male(s)/female
- 65 years and over :: 0.77 male(s)/female
- total population :: 0.99 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 43.55 deaths/1,000 live births
- male :: 49.84 deaths/1,000 live births
- female :: 36.88 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 48
*** Life expectancy at birth
- total population :: 66.29 years
- male :: 63.89 years
- female :: 68.82 years (2015 est.)
- country comparison to the world :: 171
*** Total fertility rate
2.16 children born/woman (2015 est.)
- country comparison to the world :: 102
*** Contraceptive prevalence rate
46% (2009/10)
*** Health expenditures
1.8% of GDP (2013)
- country comparison to the world :: 191
*** Physicians density
0.61 physicians/1,000 population (2012)
*** Hospital bed density
0.6 beds/1,000 population (2006)
*** Drinking water source
- improved :: 
urban: 92.7% of population
rural: 74.4% of population
total: 80.6% of population
- unimproved :: 
urban: 7.3% of population
rural: 25.6% of population
total: 19.4% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 84.3% of population
rural: 73.9% of population
total: 77.4% of population
- unimproved :: 
urban: 15.7% of population
rural: 26.1% of population
total: 22.6% of population (2012 est.)
*** HIV/AIDS - adult prevalence rate
0.69% (2014 est.)
- country comparison to the world :: 55
*** HIV/AIDS - people living with HIV/AIDS
212,600 (2014 est.)
- country comparison to the world :: 27
*** HIV/AIDS - deaths
10,100 (2014 est.)
- country comparison to the world :: 23
*** Major infectious diseases
- degree of risk :: very high
- food or waterborne diseases :: bacterial and protozoal diarrhea, hepatitis A, and typhoid fever
- vectorborne diseases :: dengue fever, malaria, and Japanese encephalitis
- water contact disease :: leptospirosis
- animal contact disease :: rabies
- note :: highly pathogenic H5N1 avian influenza has been identified in this country; it poses a negligible risk with extremely rare cases possible among US citizens who have close contact with birds (2013)
*** Obesity - adult prevalence rate
2.9% (2014)
- country comparison to the world :: 172
*** Children under the age of 5 years underweight
22.6% (2010)
- country comparison to the world :: 27
*** Education expenditures
0.8% of GDP (2011)
- country comparison to the world :: 172
*** Literacy
- definition :: age 15 and over can read and write
- total population :: 93.1%
- male :: 95.2%
- female :: 91.2% (2015 est.)
*** School life expectancy (primary to tertiary education)
- total :: 9 years
- male :: NA
- female :: NA (2007)
** Government
*** Country name
- conventional long form :: Union of Burma
- conventional short form :: Burma
- local long form :: Pyidaungzu Thammada Myanma Naingngandaw (translated as the Republic of the Union of Myanmar)
- local short form :: Myanma Naingngandaw
- former :: Socialist Republic of the Union of Burma, Union of Myanmar
- note :: since 1989 the military authorities in Burma and the current parliamentary government have promoted the name Myanmar as a conventional name for their state; the US Government has not adopted the name
*** Government type
parliamentary government took power in March 2011
*** Capital
- name :: Rangoon (Yangon); note - Nay Pyi Taw is the administrative capital
- geographic coordinates :: 16 48 N, 96 09 E
- time difference :: UTC+6.5 (11.5 hours ahead of Washington, DC, during Standard Time)
*** Administrative divisions
7 regions (taing-myar, singular - taing), 7 states (pyi ne-myar, singular - pyi ne), 1 union territory
- regions :: Ayeyawady (Irrawaddy), Bago, Magway, Mandalay, Sagaing, Taninthayi, Yangon (Rangoon)
- states :: Chin, Kachin, Kayah, Kayin, Mon, Rakhine (Arakan), Shan
- union territory :: Nay Pyi Taw
*** Independence
4 January 1948 (from the UK)
*** National holiday
Independence Day, 4 January (1948); Union Day, 12 February (1947)
*** Constitution
previous 1947, 1974 (suspended until 2008); latest approved by referendum 29 May 2008; reformed 2011 (2011)
*** Legal system
mixed legal system of English common law (as introduced in codifications designed for colonial India) and customary law
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; non-party state to the ICCt
*** Citizenship
- birthright citizenship :: 
- dual citizenship recognized :: no
- residency requirement for naturalization :: 
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: President THEIN SEIN (since 4 February 2011); Vice Presidents SAI MAUK KHAM (since 3 February 2011), NYAN TUN (since 15 August 2012); note - the president is both chief of state and head of government
- head of government :: President THEIN SEIN (since 4 February 2011)
- cabinet :: Cabinet appointmets shared by the president and the commander-in-chief
- elections/appointments :: president indirectly elected by simple majority vote by House of Representative's Presidential Electoral College from among 3 vice presidential nominees - 1 each from the House of Nationalities, the House of Representatives, and military members of the Assembly of the Union (president elected for a 5-year term)
- election results :: THEIN SEIN (USDP) elected president;  Presidential Electoral College vote NA
*** Legislative branch
- description :: bicameral Assembly of the Union or Pyidaungsu consists of the House of Nationalities or Amyotha Hluttaw (224 seats; 168 members directly elected in single-seat constituencies by absolute majority vote with a second round if needed and 56 appointed by the military; members serve 5-year terms) and the House of Representatives or Pyithu Hluttaw (440 seats; 330 members directly elected in single-seat constituencies by simple majority vote and 110 appointed by the military; members serve 5-year terms)
- elections :: last held on 7 November 2010 (next to be held on 8 November 2015)
- election results :: House of Nationalities - percent of vote by party - USDP 74.8%, other (NUP, SNDP, RNDP, NDF, AMRDP) 25.2%; seats by party - USDP 129, other 39; House of Representatives - percent of vote by party - USDP 79.6%, other (NUP, SNDP, RNDP, NDF, AMRDP) 20.4%; seats by party - USDP 259, other 71
*** Judicial branch
- highest court(s) :: Supreme Court of the Union (consists of the chief justice and 7-11 judges)
- judge selection and term of office :: chief justice and judges nominated by the president, with approval of the Pythu Hluttaw, and appointed by the president; judges normally serve until mandatory retirement at age 70
- subordinate courts :: High Courts of the Region; High Courts of the State; Court of the Self-Administered Division; Court of the Self-Administered Zone; district and township courts; special courts (for juvenile, municipal, and traffic offenses); courts martial
*** Political parties and leaders
All Mon Region Democracy Party or AMRDP [NAING NGWE THEIN]
National Democratic Force or NDF [KHIN MAUNG SWE]
National League for Democracy or NLD [AUNG SAN SUU KYI]
National Unity Party or NUP [THAN TIN]
Rakhine Nationalities Development Party or RNDP [Dr. AYE MAUNG]
Shan Nationalities Democratic Party or SNDP [SAI AIK PAUNG]
Union Solidarity and Development Party or USDP [HTAY OO]
numerous smaller parties
*** Political pressure groups and leaders
- Thai border :: Ethnic Nationalities Council or ENC
Federation of Trade Unions-Burma or FTUB (exile trade union and labor advocates)
National Coalition Government of the Union of Burma or NCGUB (self-proclaimed government in exile) ["Prime Minister" Dr. SEIN WIN] consists of individuals, some legitimately elected to the People's Assembly in 1990 (the group fled to a border area and joined insurgents in December 1990 to form a parallel government in exile)
National Council-Union of Burma or NCUB (exile coalition of opposition groups)
United Nationalities Federal Council or UNFC
- inside Burma :: Kachin Independence Organization
Karen National Union or KNU
Karenni National People's Party or KNPP
United Wa State Army or UWSA
88 Generation Students (pro-democracy movement)
several other Chin, Karen, Mon, and Shan factions
- note :: freedom of expression has been highly restricted in Burma; the restrictions are being relaxed by the government; a limited number of political groups, other than parties are approved by the government
*** International organization participation
ADB, ARF, ASEAN, BIMSTEC, CP, EAS, EITI (candidate country), FAO, G-77, IAEA, IBRD, ICAO, ICRM, IDA, IFAD, IFC, IFRCS, IHO, ILO, IMF, IMO, Interpol, IOC, IOM, IPU, ISO (correspondent), ITU, ITUC (NGOs), NAM, OPCW (signatory), SAARC (observer), UN, UNCTAD, UNESCO, UNIDO, UNWTO, UPU, WCO, WHO, WIPO, WMO, WTO
*** Diplomatic representation in the US
- chief of mission :: Ambassador KYAW MYO HTUT (since 3 December 2013)
- chancery :: 2300 S Street NW, Washington, DC 20008
- telephone :: [1] (202) 332-3344
- FAX :: [1] (202) 332-4351
- consulate(s) general :: none; Burma has a Mission to the UN in New York
*** Diplomatic representation from the US
- chief of mission :: Ambassador Derek J. MITCHELL (since 11 July 2012)
- embassy :: 110 University Avenue, Kamayut Township, Rangoon
- mailing address :: Box B, APO AP 96546
- telephone :: [95] (1) 536-509, 535-756, 538-038
- FAX :: [95] (1) 511-069
*** Flag description
design consists of three equal horizontal stripes of yellow (top), green, and red; centered on the green band is a large white five-pointed star that partially overlaps onto the adjacent colored stripes; the design revives the triband colors used by Burma from 1943-45, during the Japanese occupation
*** National symbol(s)
chinthe (mythical lion); national colors: yellow, green, red, white
*** National anthem
- name :: "Kaba Ma Kyei" (Till the End of the World, Myanmar)
- lyrics/music :: SAYA TIN
- note :: adopted 1948; Burma is among a handful of non-European nations that have anthems rooted in indigenous traditions; the beginning portion of the anthem is a traditional Burmese anthem before transitioning into a Western-style orchestrated work

** Economy
*** Economy - overview
Since the transition to a civilian government in 2011, Burma has begun an economic overhaul aimed at attracting foreign investment and reintegrating into the global economy. Economic reforms have included establishing a managed float of the Burmese kyat in 2012, re-writing the Foreign Investment Law in 2012 to allow more foreign investment participation, granting the Central Bank operational independence in July 2013, enacting a new Anti-corruption Law in September 2013, and authorizing a small number of foreign banks to open branch offices for limited operations beginning in 2015. The government’s commitment to reform, and the subsequent easing of most Western sanctions, has begun to pay dividends as growth accelerated in 2013 and 2014. Burma’s abundant natural resources, young labor force, and proximity to Asia’s dynamic economies have attracted foreign investment in the energy sector, garment industry, information technology, and food and beverages. Pledged foreign direct investment grew from US$1.4 billion in FY 2012 to US$4.1 billion in FY 2013. Despite these improvements, living standards have not improved for the majority of the people residing in rural areas. Burma remains one of the poorest countries in Asia – nearly one-third of the country’s 51 million people live in poverty. The previous government’s isolationist policies and economic mismanagement have left Burma with poor infrastructure, endemic corruption, underdeveloped human resources, and inadequate access to capital, which will require a major commitment to reverse. The Burmese government has been slow to address impediments to economic development such as insecure land rights, a restrictive trade licensing system, an opaque revenue collection system, and an antiquated banking system. Key benchmarks of sustained economic progress would include modernizing and opening the financial sector, increasing budget allocations for social services, and accelerating agricultural and land reforms.
*** GDP (purchasing power parity)
$242 billion (2014 est.)
$224.7 billion (2013 est.)
$207.6 billion (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 59
*** GDP (official exchange rate)
$62.8 billion (2014 est.)
*** GDP - real growth rate
7.7% (2014 est.)
8.3% (2013 est.)
7.3% (2012 est.)
- country comparison to the world :: 9
*** GDP - per capita (PPP)
$4,700 (2014 est.)
$4,400 (2013 est.)
$4,000 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 170
*** Gross national saving
18.6% of GDP (2014 est.)
18% of GDP (2013 est.)
13.7% of GDP (2012 est.)
- country comparison to the world :: 84
*** GDP - composition, by end use
- household consumption :: 82%
- government consumption :: 3.8%
- investment in fixed capital :: 19.3%
- investment in inventories :: 0.3%
- exports of goods and services :: 23.7%
- imports of goods and services :: -29.1%
 (2014 est.)
*** GDP - composition, by sector of origin
- agriculture :: 37.1%
- industry :: 21.3%
- services :: 41.6% (2014 est.)
*** Agriculture - products
rice, pulses, beans, sesame, groundnuts, sugarcane; fish and fish products; hardwood
*** Industries
agricultural processing; wood and wood products; copper, tin, tungsten, iron; cement, construction materials; pharmaceuticals; fertilizer; oil and natural gas; garments, jade, gems
*** Industrial production growth rate
12% (2014 est.)
- country comparison to the world :: 5
*** Labor force
35.23 million (2014 est.)
- country comparison to the world :: 18
*** Labor force - by occupation
- agriculture :: 70%
- industry :: 7%
- services :: 23% (2001 est.)
*** Unemployment rate
4% (2014 est.)
5.2% (2013 est.)
- country comparison to the world :: 52
*** Population below poverty line
32.7% (2007 est.)
*** Household income or consumption by percentage share
- lowest 10% :: 2.8%
- highest 10% :: 32.4% (1998)
*** Budget
- revenues :: $2.931 billion
- expenditures :: $4.835 billion (2014 est.)
*** Taxes and other revenues
4.5% of GDP (2014 est.)
- country comparison to the world :: 211
*** Budget surplus (+) or deficit (-)
-2.9% of GDP (2014 est.)
- country comparison to the world :: 115
*** Fiscal year
1 April - 31 March
*** Inflation rate (consumer prices)
5.9% (2014 est.)
5.5% (2013 est.)
- country comparison to the world :: 178
*** Central bank discount rate
9.95% (31 December 2010)
12% (31 December 2009)
- country comparison to the world :: 19
*** Commercial bank prime lending rate
13% (31 December 2014 est.)
13% (31 December 2013 est.)
- country comparison to the world :: 59
*** Stock of narrow money
$15.19 billion (31 December 2014 est.)
$12.28 billion (31 December 2013 est.)
- country comparison to the world :: 71
*** Stock of domestic credit
$19.59 billion (31 December 2014 est.)
$15.82 billion (31 December 2013 est.)
- country comparison to the world :: 88
*** Market value of publicly traded shares
$NA
*** Current account balance
-$4.509 billion (2014 est.)
-$3.09 billion (2013 est.)
- country comparison to the world :: 160
*** Exports
$10.31 billion (2014 est.)
$9.033 billion (2013 est.)
- note :: official export figures are grossly underestimated due to the value of timber, gems, narcotics, rice, and other products smuggled to Thailand, China, and Bangladesh
- country comparison to the world :: 95
*** Exports - commodities
natural gas, wood products, pulses, beans, fish, rice, clothing, jade and gems
*** Exports - partners
China 63%, Thailand 15.8%, India 5.7% (2014)
*** Imports
$12.53 billion (2014 est.)
$10.51 billion (2013 est.)
- note :: import figures are grossly underestimated due to the value of consumer goods, diesel fuel, and other products smuggled in from Thailand, China, Malaysia, and India
- country comparison to the world :: 91
*** Imports - commodities
fabric, petroleum products, fertilizer, plastics, machinery, transport equipment; cement, construction materials, crude oil; food products, edible oil
*** Imports - partners
China 42.4%, Thailand 19%, Singapore 10.9%, Japan 5.4% (2014)
*** Reserves of foreign exchange and gold
$4.5 billion (31 December 2014 est.)
$8.278 billion (31 December 2013 est.)
- country comparison to the world :: 79
*** Debt - external
$2.491 billion (31 December 2014 est.)
$2.56 billion (31 December 2013 est.)
- country comparison to the world :: 144
*** Exchange rates
kyats (MMK) per US dollar -
975.5 (2014 est.)
930.42 (2013 est.)
853.48 (2012 est.)
815 (2011 est.)
5.58 (2010 est.)
** Energy
*** Electricity - production
10.48 billion kWh (2012 est.)
- country comparison to the world :: 108
*** Electricity - consumption
7.77 billion kWh (2012 est.)
- country comparison to the world :: 109
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 111
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 123
*** Electricity - installed generating capacity
3.59 million kW (2012 est.)
- country comparison to the world :: 85
*** Electricity - from fossil fuels
26.1% of total installed capacity (2011 est.)
- country comparison to the world :: 186
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 53
*** Electricity - from hydroelectric plants
73.9% of total installed capacity (2011 est.)
- country comparison to the world :: 21
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 160
*** Crude oil - production
20,000 bbl/day (2013 est.)
- country comparison to the world :: 72
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 85
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 162
*** Crude oil - proved reserves
50 million bbl (1 January 2014 est.)
- country comparison to the world :: 78
*** Refined petroleum products - production
18,920 bbl/day (2010 est.)
- country comparison to the world :: 95
*** Refined petroleum products - consumption
28,120 bbl/day (2013 est.)
- country comparison to the world :: 117
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 155
*** Refined petroleum products - imports
4,855 bbl/day (2010 est.)
- country comparison to the world :: 152
*** Natural gas - production
11.77 billion cu m (2012 est.)
- country comparison to the world :: 42
*** Natural gas - consumption
3.299 billion cu m (2012 est.)
- country comparison to the world :: 72
*** Natural gas - exports
8.468 billion cu m (2012 est.)
- country comparison to the world :: 24
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 163
*** Natural gas - proved reserves
283.2 billion cu m (1 January 2014 est.)
- country comparison to the world :: 39
*** Carbon dioxide emissions from consumption of energy
13.34 million Mt (2012 est.)
- country comparison to the world :: 94
** Communications
*** Telephones - fixed lines
- total subscriptions :: 530,000
- subscriptions per 100 inhabitants :: 1 (2014 est.)
- country comparison to the world :: 96
*** Telephones - mobile cellular
- total :: 26.6 million
- subscriptions per 100 inhabitants :: 48 (2014 est.)
- country comparison to the world :: 47
*** Telephone system
- general assessment :: meets minimum requirements for local and intercity service for business and government
- domestic :: system barely capable of providing basic service; mobile-cellular phone system is grossly underdeveloped
- international :: country code - 95; landing point for the SEA-ME-WE-3 optical telecommunications submarine cable that provides links to Asia, the Middle East, and Europe; satellite earth stations - 2, Intelsat (Indian Ocean) and ShinSat (2011)
*** Broadcast media
government controls all domestic broadcast media; 2 state-controlled TV stations with 1 of the stations controlled by the armed forces; 2 pay-TV stations are joint state-private ventures; access to satellite TV is limited; 1 state-controlled domestic radio station and 9 FM stations that are joint state-private ventures; transmissions of several international broadcasters are available in parts of Burma; the Voice of America (VOA), Radio Free Asia (RFA), BBC Burmese service, the Democratic Voice of Burma (DVB), and Radio Australia use shortwave to broadcast in Burma; VOA, RFA, and DVB produce daily TV news programs that are transmitted by satellite to audiences in Burma
*** Radio broadcast stations
AM 1, FM 2, shortwave 3 (2007)
*** Television broadcast stations
4 (2008)
*** Internet country code
.mm
*** Internet users
- total :: 646,700
- percent of population :: 1.2% (2014 est.)
- country comparison to the world :: 128
** Transportation
*** Airports
64 (2013)
- country comparison to the world :: 76
*** Airports - with paved runways
- total :: 36
- over 3,047 m :: 12
- 2,438 to 3,047 m :: 11
- 1,524 to 2,437 m :: 12
- under 914 m :: 1 (2013)
*** Airports - with unpaved runways
- total :: 28
- over 3,047 m :: 1
- 1,524 to 2,437 m :: 4
- 914 to 1,523 m :: 10
- under 914 m :: 
13 (2013)
*** Heliports
11 (2013)
*** Pipelines
gas 3,739 km; oil 551 km (2013)
*** Railways
- total :: 5,031 km
- narrow gauge :: 5,031 km 1.000-m gauge (2008)
- country comparison to the world :: 36
*** Roadways
- total :: 34,377 km (includes 358 km of expressways) (2010)
- country comparison to the world :: 93
*** Waterways
12,800 km (2011)
- country comparison to the world :: 10
*** Merchant marine
- total :: 29
- by type :: cargo 22, passenger 2, passenger/cargo 3, specialized tanker 1, vehicle carrier 1
- foreign-owned :: 2 (Germany 1, Japan 1)
- registered in other countries :: 3 (Panama 3) (2010)
- country comparison to the world :: 86
*** Ports and terminals
- major seaport(s) :: Moulmein, Sittwe
- river port(s) :: Rangoon (Yangon) (Rangoon River)
** Military
*** Military branches
Myanmar Armed Forces (Tatmadaw): Army (Tatmadaw Kyi), Navy (Tatmadaw Yay), Air Force (Tatmadaw Lay) (2013)
*** Military service age and obligation
18-35 years of age (men) and 18-27 years of age (women) for voluntary military service; no conscription (a 2010 law reintroducing conscription has not yet entered into force); 2-year service obligation; male (ages 18-45) and female (ages 18-35) professionals (including doctors, engineers, mechanics) serve up to 3 years; service terms may be stretched to 5 years in an officially declared emergency; Burma signed the Convention on the Rights of the Child (CRC) on 15 August 1991; on 27 June 2012, the regime signed a Joint Action Plan on prevention of child recruitment; in February 2013, the military formed a new task force to address forced child conscription; approximately 600 children have been released from military service since the signing of the joint action plan (2015)
*** Manpower available for military service
- males age 16-49 :: 14,747,845
- females age 16-49 :: 14,710,871 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 10,451,515
- females age 16-49 :: 11,181,537 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 522,478
- female :: 506,388 (2010 est.)
** Transnational Issues
*** Disputes - international
over half of Burma's population consists of diverse ethnic groups who have substantial numbers of kin in neighboring countries; the Naf River on the border with Bangladesh serves as a smuggling and illegal transit route; Bangladesh struggles to accommodate 29,000 Rohingya, Burmese Muslim minority from Arakan State, living as refugees in Cox's Bazar; Burmese border authorities are constructing a 200 km (124 mi) wire fence designed to deter illegal cross-border transit and tensions from the military build-up along border with Bangladesh in 2010; Bangladesh referred its maritime boundary claims with Burma and India to the International Tribunal on the Law of the Sea; Burmese forces attempting to dig in to the largely autonomous Shan State to rout local militias tied to the drug trade, prompts local residents to periodically flee into neighboring Yunnan Province in China; fencing along the India-Burma international border at Manipur's Moreh town is in progress to check illegal drug trafficking and movement of militants; over 90,000 mostly Karen refugees and asylum seekers fleeing civil strife, political upheaval, and economic stagnation in Burma were living in remote camps in Thailand near the border as of year-end 2013
*** Refugees and internally displaced persons
- IDPs :: up to 662,400 (government offensives against armed ethnic minority groups near its borders with China and Thailand) (2015)
- stateless persons :: 1.45 million (2014); note - Burma's main group of stateless people is the Rohingya, Muslims living in northern Rakhine State; the Burmese Government does not recognize the Rohingya as a "national race" and stripped them of their citizenship under the 1982 Citizenship law, categorizing them as "non-national" or "foreign residents," under the Rakhine State Action Plan drafted in October 2014, the Rohingya must demonstrate their family has lived in Burman for at least 60 years to qualify for a lesser naturalized citizenship and the classification of Bengali or be put in detention camps and face deportation; native-born but non-indigenous people, such as Indians, are also stateless; the Burmese Government does not grant citizenship to children born outside of the country to Burmese parents who left the country illegally or fled persecution, such as those born in Thailand
*** Trafficking in persons
- current situation :: Burma is a source country for men, women, and children trafficked for the purpose of forced labor, and for women and children subjected to sex trafficking in other countries; poor economic conditions have led to increased legal and illegal migration of Burmese adults and children to East Asia, the Middle East, South Asia, and the US where they are subject to forced labor and sex trafficking; men are forced to work in the fishing, manufacturing, and construction industries, while women and girls are forced into prostitution or domestic servitude; some Burmese economic migrants and Rohingya asylum seekers have become forced laborers in Thailand; military personnel and insurgent militia unlawfully conscript child soldiers and continue to be the leading perpetrators of forced labor inside the country; Burmese children are also forced to work in tea shops, home industries, on plantations, and as beggars
- tier rating :: Tier 2 Watch List - Burma does not fully comply with the minimum standards for the elimination of trafficking, but it is making significant efforts to do so; the government has a written plan that, if implemented, would constitute a significant effort toward meeting the minimum standards for eliminating human trafficking; in 2013, an anti-trafficking division was created; authorities continued to investigate and prosecute cross-border sex trafficking offenses but did little to address domestic trafficking; forced labor and forced recruitment of child soldiers remain serious problems; the government continued modest efforts to provide temporary shelter and facilitate safe passage to Burmese victims repatriated from abroad, but its overall victim protection efforts were inadequate and left victims vulnerable to being re-trafficked (2014)
*** Illicit drugs
world's third largest producer of illicit opium with an estimated production in 2012 of 690 metric tons, an increase of 13% over 2011, and poppy cultivation in 2012 totaled 51,000 hectares, a 17% increase over 2011; production in the United Wa State Army's areas of greatest control remains low; Shan state is the source of 94.5% of Burma's poppy cultivation; lack of government will to take on major narcotrafficking groups and lack of serious commitment against money laundering continues to hinder the overall antidrug effort; major source of methamphetamine and heroin for regional consumption (2013)