** Introduction
*** Background
The UK established a protectorate over the Solomon Islands in the 1890s. Some of the bitterest fighting of World War II occurred on this archipelago. Self-government was achieved in 1976 and independence two years later. Ethnic violence, government malfeasance, endemic crime, and a narrow economic base have undermined stability and civil society. In June 2003, then Prime Minister Sir Allan KEMAKEZA sought the assistance of Australia in reestablishing law and order; the following month, an Australian-led multinational force arrived to restore peace and disarm ethnic militias. The Regional Assistance Mission to the Solomon Islands (RAMSI) has generally been effective in restoring law and order and rebuilding government institutions.
** Geography
*** Location
Oceania, group of islands in the South Pacific Ocean, east of Papua New Guinea
*** Geographic coordinates
8 00 S, 159 00 E
*** Map references
Oceania
*** Area
- total :: 28,896 sq km
- land :: 27,986 sq km
- water :: 910 sq km
- country comparison to the world :: 144
*** Area - comparative
slightly smaller than Maryland
*** Land boundaries
0 km
*** Coastline
5,313 km
*** Maritime claims
measured from claimed archipelagic baselines
- territorial sea :: 12 nm
- exclusive economic zone :: 200 nm
- continental shelf :: 200 nm
*** Climate
tropical monsoon; few temperature and weather extremes
*** Terrain
mostly rugged mountains with some low coral atolls
*** Elevation extremes
- lowest point :: Pacific Ocean 0 m
- highest point :: Mount Popomanaseu 2,310 m
*** Natural resources
fish, forests, gold, bauxite, phosphates, lead, zinc, nickel
*** Land use
- agricultural land :: 3.9%
arable land 0.7%; permanent crops 2.9%; permanent pasture 0.3%
- forest :: 78.9%
- other :: 17.2% (2011 est.)
*** Irrigated land
NA
*** Total renewable water resources
44.7 cu km (2011)
*** Natural hazards
typhoons, but rarely destructive; geologically active region with frequent earthquakes, tremors, and volcanic activity; tsunamis
- volcanism :: Tinakula (elev. 851 m) has frequent eruption activity, while an eruption of Savo (elev. 485 m) could affect the capital Honiara on nearby Guadalcanal
*** Environment - current issues
deforestation; soil erosion; many of the surrounding coral reefs are dead or dying
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Environmental Modification, Law of the Sea, Marine Dumping, Marine Life Conservation, Ozone Layer Protection, Whaling
- signed, but not ratified :: none of the selected agreements
*** Geography - note
strategic location on sea routes between the South Pacific Ocean, the Solomon Sea, and the Coral Sea; on 2 April 2007 an undersea earthquake measuring 8.1 on the Richter scale occurred 345 km WNW of the capital Honiara; the resulting tsunami devastated coastal areas of Western and Choiseul provinces with dozens of deaths and thousands dislocated; the provincial capital of Gizo was especially hard hit
** People and Society
*** Nationality
- noun :: Solomon Islander(s)
- adjective :: Solomon Islander
*** Ethnic groups
Melanesian 95.3%, Polynesian 3.1%, Micronesian 1.2%, other 0.3% (2009 est.)
*** Languages
Melanesian pidgin (in much of the country is lingua franca), English (official but spoken by only 1%-2% of the population), 120 indigenous languages
*** Religions
Protestant 73.4% (Church of Melanesia 31.9%, South Sea Evangelical 17.1%, Seventh Day Adventist 11.7%, United Church 10.1%, Christian Fellowship Church 2.5%), Roman Catholic 19.6%, other Christian 2.9%, other 4%, none 0.03%, unspecified 0.1% (2009 est.)
*** Population
622,469 (July 2015 est.)
- country comparison to the world :: 169
*** Age structure
- 0-14 years :: 35.68% (male 114,349/female 107,750)
- 15-24 years :: 20.01% (male 64,036/female 60,512)
- 25-54 years :: 35.73% (male 113,306/female 109,133)
- 55-64 years :: 4.45% (male 13,863/female 13,820)
- 65 years and over :: 4.13% (male 12,315/female 13,385) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 75.1%
- youth dependency ratio :: 69.1%
- elderly dependency ratio :: 5.9%
- potential support ratio :: 16.8% (2015 est.)
*** Median age
- total :: 21.9 years
- male :: 21.7 years
- female :: 22.1 years (2015 est.)
*** Population growth rate
2.02% (2015 est.)
- country comparison to the world :: 49
*** Birth rate
25.77 births/1,000 population (2015 est.)
- country comparison to the world :: 47
*** Death rate
3.85 deaths/1,000 population (2015 est.)
- country comparison to the world :: 210
*** Net migration rate
-1.75 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 162
*** Urbanization
- urban population :: 22.3% of total population (2015)
- rate of urbanization :: 4.25% annual rate of change (2010-15 est.)
*** Major urban areas - population
HONIARA (capital) 73,000 (2014)
*** Sex ratio
- at birth :: 1.05 male(s)/female
- 0-14 years :: 1.06 male(s)/female
- 15-24 years :: 1.06 male(s)/female
- 25-54 years :: 1.04 male(s)/female
- 55-64 years :: 1 male(s)/female
- 65 years and over :: 0.92 male(s)/female
- total population :: 1.04 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 15.65 deaths/1,000 live births
- male :: 17.84 deaths/1,000 live births
- female :: 13.35 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 102
*** Life expectancy at birth
- total population :: 75.12 years
- male :: 72.49 years
- female :: 77.88 years (2015 est.)
- country comparison to the world :: 106
*** Total fertility rate
3.28 children born/woman (2015 est.)
- country comparison to the world :: 47
*** Contraceptive prevalence rate
34.6% (2006/07)
*** Health expenditures
5.1% of GDP (2013)
- country comparison to the world :: 59
*** Physicians density
0.22 physicians/1,000 population (2009)
*** Hospital bed density
1.3 beds/1,000 population (2012)
*** Drinking water source
- improved :: 
urban: 93.2% of population
rural: 77.2% of population
total: 80.8% of population
- unimproved :: 
urban: 6.8% of population
rural: 22.8% of population
total: 19.2% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 81.4% of population
rural: 15% of population
total: 29.8% of population
- unimproved :: 
urban: 18.6% of population
rural: 85% of population
total: 70.2% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
*** Obesity - adult prevalence rate
25% (2014)
- country comparison to the world :: 27
*** Children under the age of 5 years underweight
11.5% (2007)
- country comparison to the world :: 65
*** Education expenditures
9.9% of GDP (2010)
- country comparison to the world :: 18
*** Literacy
- definition :: age 15 and over can read and write
- total population :: 84.1%
- male :: 88.9%
- female :: 79.2% (2009 est.)
*** School life expectancy (primary to tertiary education)
- total :: 9 years
- male :: 10 years
- female :: 9 years (2007)
** Government
*** Country name
- conventional long form :: none
- conventional short form :: Solomon Islands
- local long form :: none
- local short form :: Solomon Islands
- former :: British Solomon Islands
*** Government type
parliamentary democracy and a Commonwealth realm
*** Capital
- name :: Honiara
- geographic coordinates :: 9 26 S, 159 57 E
- time difference :: UTC+11 (16 hours ahead of Washington, DC, during Standard Time)
*** Administrative divisions
9 provinces and 1 city*; Central, Choiseul, Guadalcanal, Honiara*, Isabel, Makira and Ulawa, Malaita, Rennell and Bellona, Temotu, Western
*** Independence
7 July 1978 (from the UK)
*** National holiday
Independence Day, 7 July (1978)
*** Constitution
adopted 31 May 1978, effective 7 July 1978; amended several times, last in 2010 (2012)
*** Legal system
mixed legal system of English common law and customary law
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; non-party state to the ICCt
*** Citizenship
- birthright citizenship :: 
- dual citizenship recognized :: no
- residency requirement for naturalization :: 
*** Suffrage
21 years of age; universal
*** Executive branch
- chief of state :: Queen ELIZABETH II (since 6 February 1952); represented by Governor General Frank KABUI (since 7 July 2009)
- head of government :: Prime Minister Manasseh SOGAVARE (since 9 December 2014)
- cabinet :: Cabinet appointed by the governor general on the advice of the prime minister
- elections/appointments :: the monarchy is hereditary; governor general appointed by the monarch on the advice of the National Parliament for up to 5 years (eligible for a second term); following legislative elections, the leader of the majority party or majority coalition usually elected prime minister by the National Parliament; deputy prime minister appointed by the governor general on the advice of the prime minister from among members of the National Parliament
- election results :: Manasseh SOGAVARE (independent) elected prime minister; National Parliament vote - 31 to 19
*** Legislative branch
- description :: unicameral National Parliament (50 seats; members directly elected in single-seat constituencies by simple majority vote to serve 4-year terms)
- elections :: last held on 19 November 2014 (next to be held in 2018)
- election results :: percent of vote by party - NA; seats by party - independents 32, DAP 7, UDP 5, PAP 3, KPSI 1, SIPFP 1, SIPRA 1
*** Judicial branch
- highest court(s) :: Court of Appeal (consists of the court president, and ex officio members to include the High Court chief justice and its puisne judges); High Court (consists of the chief justice and puisne judges as prescribed by the National Parliament)
- judge selection and term of office :: Court of Appeal and High Court president, chief justices, and puisne judges appointed by the governor-general upon recommendation of the Judicial and Legal Service Commission, chaired by the chief justice to include 5 members, mostly judicial officials and legal professionals; all judges appointed until retirement at age 60
- subordinate courts :: Magistrates' Courts; local courts; Customary Land Appeal Court
*** Political parties and leaders
Democratic Alliance Party or DAP [Steve ABANA]
Kadere Party of Solomon Islands or KPSI [Alfred LEGUA]
People's Alliance Party or PAP [Nathaniel WAENA]
Solomon Islands People First Party or SIPFP [Jimmie RODGERS]
Solomon Islands Party for Rural Advancement or SIPRA [Manasseh MAELANGA]
United Democratic Party [Thomas Ko CHAN]
- note :: in general, Solomon Islands politics is characterized by fluid coalitions
*** Political pressure groups and leaders
Isatabu Freedom Movement or IFM
Malaita Eagle Force or MEF
- note :: these rival armed ethnic factions crippled the Solomon Islands in a wave of violence from 1999 to 2003
*** International organization participation
ACP, ADB, AOSIS, C, EITI (candidate country), ESCAP, FAO, G-77, IBRD, ICAO, ICRM, IDA, IFAD, IFC, IFRCS, ILO, IMF, IMO, IOC, ITU, MIGA, OPCW, PIF, Sparteca, SPC, UN, UNCTAD, UNESCO, UPU, WFTU, WHO, WMO, WTO
*** Diplomatic representation in the US
- chief of mission :: Ambassador Collin David BECK (since 31 March 2004)
- chancery :: 800 Second Avenue, Suite 400L, New York, NY 10017
- telephone :: [1] (212) 599-6192, 6193
- FAX :: [1] (212) 661-8925
*** Diplomatic representation from the US
the US does not have an embassy in the Solomon Islands; the US ambassador to Papua New Guinea is accredited to the Solomon Islands
*** Flag description
divided diagonally by a thin yellow stripe from the lower hoist-side corner; the upper triangle (hoist side) is blue with five white five-pointed stars arranged in an X pattern; the lower triangle is green; blue represents the ocean; green the land; and yellow sunshine; the five stars stand for the five main island groups of the Solomon Islands
*** National symbol(s)
national colors: blue, yellow, green, white
*** National anthem
- name :: "God Save Our Solomon Islands"
- lyrics/music :: Panapasa BALEKANA and Matila BALEKANA/Panapasa BALEKANA
- note :: adopted 1978
** Economy
*** Economy - overview
The bulk of the population depends on agriculture, fishing, and forestry for at least part of its livelihood. Most manufactured goods and petroleum products must be imported. The islands are rich in undeveloped mineral resources such as lead, zinc, nickel, and gold. Prior to the arrival of The Regional Assistance Mission to the Solomon Islands (RAMSI), severe ethnic violence, the closing of key businesses, and an empty government treasury culminated in economic collapse. RAMSI's efforts to restore law and order and economic stability have led to modest growth as the economy rebuilds.
*** GDP (purchasing power parity)
$1.09 billion (2014 est.)
$1.074 billion (2013 est.)
$1.042 billion (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 203
*** GDP (official exchange rate)
$1.155 billion (2014 est.)
*** GDP - real growth rate
1.5% (2014 est.)
3% (2013 est.)
4.7% (2012 est.)
- country comparison to the world :: 199
*** GDP - per capita (PPP)
$1,900 (2014 est.)
$1,900 (2013 est.)
$1,800 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 206
*** Gross national saving
4.2% of GDP (2014 est.)
10.8% of GDP (2013 est.)
18.2% of GDP (2012 est.)
- country comparison to the world :: 166
*** GDP - composition, by sector of origin
- agriculture :: 51.9%
- industry :: 10%
- services :: 38.1% (2014 est.)
*** Agriculture - products
cocoa, coconuts, palm kernels, rice, fruit; cattle, pigs; fish; timber
*** Industries
fish (tuna), mining, timber
*** Industrial production growth rate
-0.4% (2014 est.)
- country comparison to the world :: 174
*** Labor force
202,500 (2007 est.)
- country comparison to the world :: 170
*** Labor force - by occupation
- agriculture :: 75%
- industry :: 5%
- services :: 20% (2000 est.)
*** Unemployment rate
NA%
*** Population below poverty line
NA%
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $450.3 million
- expenditures :: $450.3 million (2014 est.)
*** Taxes and other revenues
38.8% of GDP (2014 est.)
- country comparison to the world :: 43
*** Budget surplus (+) or deficit (-)
0% of GDP (2014 est.)
- country comparison to the world :: 37
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
5.1% (2014 est.) 6.7% (2013 est.)
- country comparison to the world :: 172
*** Commercial bank prime lending rate
10.9% (31 December 2014 est.)
10.77% (31 December 2013 est.)
- country comparison to the world :: 74
*** Stock of narrow money
$404.9 million (31 December 2014 est.)
$366.7 million (31 December 2013 est.)
- country comparison to the world :: 168
*** Stock of broad money
$452.1 million (31 December 2014 est.)
$467.9 million (31 December 2013 est.)
- country comparison to the world :: 182
*** Stock of domestic credit
$27.51 million (31 December 2014 est.)
$24.46 million (31 December 2013 est.)
- country comparison to the world :: 181
*** Current account balance
-$98 million (2014 est.)
-$1.2 million (2012 est.)
- country comparison to the world :: 62
*** Exports
$493.1 million (2012 est.)
$439.8 million (2011 est.)
- country comparison to the world :: 175
*** Exports - commodities
timber, fish, copra, palm oil, cocoa
*** Exports - partners
China 62.9%, Italy 5.8%, Australia 5.4% (2014)
*** Imports
$446 million (2012 est.)
$462.8 million (2012 est.)
- country comparison to the world :: 192
*** Imports - commodities
food, plant and equipment, manufactured goods, fuels, chemicals
*** Imports - partners
Australia 26%, Singapore 16.4%, China 10.3%, Malaysia 5.8%, NZ 5.1%, Indonesia 4.2%, Fiji 4.2%, Papua New Guinea 4.1% (2014)
*** Debt - external
$255.5 million (31 December 2011 est.)
$228.1 million (31 December 2012 est.)
- country comparison to the world :: 185
*** Stock of direct foreign investment - at home
$1.088 billion (31 December 2014 est.)
$1.01 billion (31 December 2013 est.)
- country comparison to the world :: 104
*** Stock of direct foreign investment - abroad
$35.8 million (31 December 2014 est.)
$35.8 million (31 December 2013 est.)
- country comparison to the world :: 96
*** Exchange rates
Solomon Islands dollars (SBD) per US dollar -
7.329 (2014 est.)
7.3021 (2013 est.)
7.36 (2012 est.)
7.6413 (2011 est.)
8.0645 (2010 est.)
** Energy
*** Electricity - production
85 million kWh (2011 est.)
- country comparison to the world :: 203
*** Electricity - consumption
79.05 million kWh (2011 est.)
- country comparison to the world :: 202
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 113
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 124
*** Electricity - installed generating capacity
36,000 kW (2011 est.)
- country comparison to the world :: 197
*** Electricity - from fossil fuels
100% of total installed capacity (2011 est.)
- country comparison to the world :: 8
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 56
*** Electricity - from hydroelectric plants
0% of total installed capacity (2011 est.)
- country comparison to the world :: 161
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 162
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 158
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 88
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 164
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 111
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 125
*** Refined petroleum products - consumption
1,870 bbl/day (2013 est.)
- country comparison to the world :: 193
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 157
*** Refined petroleum products - imports
1,463 bbl/day (2010 est.)
- country comparison to the world :: 187
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 109
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 123
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 67
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 165
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 116
*** Carbon dioxide emissions from consumption of energy
266,000 Mt (2012 est.)
- country comparison to the world :: 194
** Communications
*** Telephones - fixed lines
- total subscriptions :: 7,500
- subscriptions per 100 inhabitants :: 1 (2014 est.)
- country comparison to the world :: 201
*** Telephones - mobile cellular
- total :: 376,700
- subscriptions per 100 inhabitants :: 62 (2014 est.)
- country comparison to the world :: 174
*** Telephone system
- domestic :: mobile-cellular telephone density is about 50 per 100 persons
- international :: country code - 677; satellite earth station - 1 Intelsat (Pacific Ocean) (2011)
*** Broadcast media
Solomon Islands Broadcasting Corporation (SIBC) is the sole TV broadcaster with 1 station; multi-channel pay-TV is available; SIBC operates 2 national radio stations and 2 provincial stations; 2 local commercial radio stations; Radio Australia is available via satellite feed (2009)
*** Radio broadcast stations
AM 1, FM 1, shortwave 1 (2004)
*** Internet country code
.sb
*** Internet users
- total :: 46,400
- percent of population :: 7.6% (2014 est.)
- country comparison to the world :: 187
** Transportation
*** Airports
36 (2013)
- country comparison to the world :: 109
*** Airports - with paved runways
- total :: 1
- 1,524 to 2,437 m :: 1 (2013)
*** Airports - with unpaved runways
- total :: 35
- 1,524 to 2,437 m :: 1
- 914 to 1,523 m :: 10
- under 914 m :: 
24 (2013)
*** Heliports
3 (2013)
*** Roadways
- total :: 1,390 km
- paved :: 34 km
- unpaved :: 1,356 km
- note :: includes 920 km of private plantation roads (2011)
- country comparison to the world :: 179
*** Ports and terminals
- major seaport(s) :: Honiara, Malloco Bay, Viru Harbor, Tulaghi
** Military
*** Military branches
no regular military forces; Royal Solomon Islands Police Force (2013)
*** Manpower available for military service
- males age 16-49 :: 142,913 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 118,921
- females age 16-49 :: 118,164 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 6,483
- female :: 6,098 (2010 est.)
** Transnational Issues
*** Disputes - international
since 2003, the Regional Assistance Mission to Solomon Islands, consisting of police, military, and civilian advisors drawn from 15 countries, has assisted in reestablishing and maintaining civil and political order while reinforcing regional stability and security
*** Trafficking in persons
- current situation :: The Solomon Islands is a source and destination country for local adults and children and Southeast Asian men and women subjected to forced labor and forced prostitution; women from China, Indonesia, Malaysia, and the Philippines are recruited for legitimate work and upon arrival are forced into prostitution; men from Indonesia and Malaysia recruited to work in the Solomon Islands’ mining and logging industries may be subjected to forced labor; local children are forced into prostitution near foreign logging camps, on fishing vessels, and at hotel and other entertainment venues; some local children are also sold by their parents for marriage to foreign workers or put up for “informal adoption” and then find themselves forced into domestic servitude or forced prostitution
- tier rating :: Tier 2 Watch List – The Solomon Islands does not fully comply with the minimum standards for the elimination of trafficking; however, it is making significant efforts to do so; in 2013, the government passed but did not gazette implementing regulations for 2012 legislation prohibiting all forms of human trafficking; authorities investigated an unspecified number of labor trafficking cases in the fishing industry but did not prosecute or convict any suspected offenders or actively assist victims; the government did not allocate funding for national anti-trafficking efforts in 2013; the country lacks systematic procedures for identifying trafficking victims among high-risk groups and a formal mechanism for referring victims to care; civil society and religious organizations provide limited services to victims; no anti-trafficking awareness-raising campaigns were conducted in 2013 (2014)