** Introduction
*** Background
This uninhabited, volcanic, Antarctic island is almost entirely covered by glaciers making it difficult to approach; it is recognized as the most remote island on Earth. Bouvet Island was discovered in 1739 by a French naval officer after whom it is named. No claim was made until 1825, when the British flag was raised. In 1928, the UK waived its claim in favor of Norway, which had occupied the island the previous year. In 1971, Norway designated Bouvet Island and the adjacent territorial waters a nature reserve. Since 1977, Norway has run an automated meteorological station and studied foraging strategies and distribution of fur seals and penguins on the island. In February 2006, an earthquake weakened the station's foundation causing it to be blown out to sea in a winter storm. Norway erected a new research station in 2014 that can hold six people for periods of two to four months.
** Geography
*** Location
island in the South Atlantic Ocean, southwest of the Cape of Good Hope (South Africa)
*** Geographic coordinates
54 26 S, 3 24 E
*** Map references
Antarctic Region
*** Area
- total :: 49 sq km
- land :: 49 sq km
- water :: 0 sq km
- country comparison to the world :: 233
*** Area - comparative
about 0.3 times the size of Washington, DC
*** Land boundaries
0 km
*** Coastline
29.6 km
*** Maritime claims
- territorial sea :: 4 nm
*** Climate
antarctic
*** Terrain
volcanic; coast is mostly inaccessible
*** Elevation extremes
- lowest point :: South Atlantic Ocean 0 m
- highest point :: Olav Peak 935 m
*** Natural resources
none
*** Land use
- agricultural land :: 0%
arable land 0%; permanent crops 0%; permanent pasture 0%
- forest :: 0%
- other :: 100% (93% ice) (2011 est.)
*** Natural hazards
NA
*** Environment - current issues
NA
*** Geography - note
covered by glacial ice; declared a nature reserve by Norway
** People and Society
*** Population
uninhabited
** Government
*** Country name
- conventional long form :: none
- conventional short form :: Bouvet Island
*** Dependency status
territory of Norway; administered by the Polar Department of the Ministry of Justice and Oslo Police
*** Legal system
the laws of Norway, where applicable, apply
*** Flag description
the flag of Norway is used
** Economy
*** Economy - overview
no economic activity; declared a nature reserve
** Communications
*** Internet country code
.bv
*** Communications - note
has an automatic meteorological station
** Transportation
*** Ports and terminals
none; offshore anchorage only
** Military
*** Military - note
defense is the responsibility of Norway
** Transnational Issues
*** Disputes - international
none