** Introduction
*** Background
Equatorial Guinea gained independence in 1968 after 190 years of Spanish rule; it is one of the smallest countries in Africa consisting of a mainland territory and five inhabited islands. The capital of Malabo is located on the island of Bioko, approximately 25 km from the Cameroonian coastline in the Gulf of Guinea. Between 1968 and 1979, autocratic President Francisco MACIAS NGUEMA virtually destroyed all of the country's political, economic, and social institutions before being deposed by his nephew Teodoro OBIANG NGUEMA MBASOGO in a coup. President OBIANG has ruled since October 1979 and plans to stand for reelection in 2016. Although nominally a constitutional democracy since 1991, presidential and legislative elections between 1996 and 2009 were widely seen as flawed. The president exerts almost total control over the political system and has placed legal and bureaucratic barriers that prevent political opposition. Equatorial Guinea has experienced rapid economic growth due to the discovery of large offshore oil reserves, and in the last decade has become Sub-Saharan Africa's third largest oil exporter. Despite the country's economic windfall from oil production, resulting in a massive increase in government revenue in recent years, the drop in global oil prices has placed significant strain on the state budget. Equatorial Guinea continues to seek to diversify its economy and to increase foreign investment despite limited improvements in the population's living standards. Equatorial Guinea is the host of major regional and international conferences and continues to seek a greater role in regional affairs.
** Geography
*** Location
Central Africa, bordering the Bight of Biafra, between Cameroon and Gabon
*** Geographic coordinates
2 00 N, 10 00 E
*** Map references
Africa
*** Area
- total :: 28,051 sq km
- land :: 28,051 sq km
- water :: 0 sq km
- country comparison to the world :: 146
*** Area - comparative
slightly smaller than Maryland
*** Land boundaries
- total :: 528 km
- border countries (2) :: Cameroon 183 km, Gabon 345 km
*** Coastline
296 km
*** Maritime claims
- territorial sea :: 12 nm
- exclusive economic zone :: 200 nm
*** Climate
tropical; always hot, humid
*** Terrain
coastal plains rise to interior hills; islands are volcanic
*** Elevation extremes
- lowest point :: Atlantic Ocean 0 m
- highest point :: Pico Basile 3,008 m
*** Natural resources
petroleum, natural gas, timber, gold, bauxite, diamonds, tantalum, sand and gravel, clay
*** Land use
- agricultural land :: 10.1%
arable land 4.3%; permanent crops 2.1%; permanent pasture 3.7%
- forest :: 57.5%
- other :: 32.4% (2011 est.)
*** Irrigated land
NA
*** Total renewable water resources
26 cu km (2011)
*** Freshwater withdrawal (domestic/industrial/agricultural)
- total :: 0.02  cu km/yr (80%/15%/5%)
- per capita :: 31.41  cu m/yr (2005)
*** Natural hazards
violent windstorms; flash floods
- volcanism :: Santa Isabel (elev. 3,007 m), which last erupted in 1923, is the country's only historically active volcano; Santa Isabel, along with two dormant volcanoes, form Bioko Island in the Gulf of Guinea
*** Environment - current issues
tap water is non-potable; deforestation
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Endangered Species, Hazardous Wastes, Law of the Sea, Marine Dumping, Ozone Layer Protection, Ship Pollution, Wetlands
- signed, but not ratified :: none of the selected agreements
*** Geography - note
insular and continental regions widely separated
** People and Society
*** Nationality
- noun :: Equatorial Guinean(s) or Equatoguinean(s)
- adjective :: Equatorial Guinean or Equatoguinean
*** Ethnic groups
Fang 85.7%, Bubi 6.5%, Mdowe 3.6%, Annobon 1.6%, Bujeba 1.1%, other 1.4% (1994 census)
*** Languages
Spanish (official) 67.6%, other (includes French (official), Fang, Bubi) 32.4% (1994 census)
*** Religions
nominally Christian and predominantly Roman Catholic, pagan practices
*** Population
740,743 (July 2015 est.)
- country comparison to the world :: 166
*** Age structure
- 0-14 years :: 40.47% (male 152,305/female 147,454)
- 15-24 years :: 19.55% (male 73,728/female 71,086)
- 25-54 years :: 31.74% (male 116,937/female 118,148)
- 55-64 years :: 4.24% (male 13,519/female 17,884)
- 65 years and over :: 4.01% (male 12,462/female 17,220) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 72.9%
- youth dependency ratio :: 67.9%
- elderly dependency ratio :: 5%
- potential support ratio :: 20% (2015 est.)
*** Median age
- total :: 19.5 years
- male :: 19 years
- female :: 20 years (2015 est.)
*** Population growth rate
2.51% (2015 est.)
- country comparison to the world :: 23
*** Birth rate
33.31 births/1,000 population (2015 est.)
- country comparison to the world :: 32
*** Death rate
8.19 deaths/1,000 population (2015 est.)
- country comparison to the world :: 89
*** Net migration rate
0 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 99
*** Urbanization
- urban population :: 39.9% of total population (2015)
- rate of urbanization :: 3.12% annual rate of change (2010-15 est.)
*** Major urban areas - population
MALABO (capital) 145,000 (2014)
*** Sex ratio
- at birth :: 1.03 male(s)/female
- 0-14 years :: 1.03 male(s)/female
- 15-24 years :: 1.04 male(s)/female
- 25-54 years :: 0.99 male(s)/female
- 55-64 years :: 0.76 male(s)/female
- 65 years and over :: 0.72 male(s)/female
- total population :: 0.99 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 69.17 deaths/1,000 live births
- male :: 70.21 deaths/1,000 live births
- female :: 68.09 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 14
*** Life expectancy at birth
- total population :: 63.85 years
- male :: 62.76 years
- female :: 64.97 years (2015 est.)
- country comparison to the world :: 183
*** Total fertility rate
4.57 children born/woman (2015 est.)
- country comparison to the world :: 24
*** Contraceptive prevalence rate
12.6% (2011)
*** Health expenditures
3.5% of GDP (2013)
- country comparison to the world :: 149
*** Hospital bed density
2.1 beds/1,000 population (2010)
*** Drinking water source
- improved :: 
urban: 72.5% of population
rural: 31.5% of population
total: 47.9% of population
- unimproved :: 
urban: 27.5% of population
rural: 68.5% of population
total: 52.1% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 79.9% of population
rural: 71% of population
total: 74.5% of population
- unimproved :: 
urban: 20.1% of population
rural: 29% of population
total: 25.5% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
6.16% (2014 est.)
- country comparison to the world :: 11
*** HIV/AIDS - people living with HIV/AIDS
31,600 (2014 est.)
- country comparison to the world :: 70
*** HIV/AIDS - deaths
800 (2014 est.)
- country comparison to the world :: 71
*** Major infectious diseases
- degree of risk :: very high
- food or waterborne diseases :: bacterial and protozoal diarrhea, hepatitis A, and typhoid fever
- vectorborne disease :: malaria and dengue fever
- animal contact disease :: rabies (2013)
*** Obesity - adult prevalence rate
16.2% (2014)
- country comparison to the world :: 129
*** Children under the age of 5 years underweight
5.6% (2010)
- country comparison to the world :: 87
*** Literacy
- definition :: age 15 and over can read and write
- total population :: 95.3%
- male :: 97.4%
- female :: 93% (2015 est.)
*** Child labor - children ages 5-14
- total number :: 35,382
- percentage :: 28% (2000 est.)
** Government
*** Country name
- conventional long form :: Republic of Equatorial Guinea
- conventional short form :: Equatorial Guinea
- local long form :: Republica de Guinea Ecuatorial/Republique de Guinee Equatoriale
- local short form :: Guinea Ecuatorial/Guinee Equatoriale
- former :: Spanish Guinea
*** Government type
republic
*** Capital
- name :: Malabo
- geographic coordinates :: 3 45 N, 8 47 E
- time difference :: UTC+1 (6 hours ahead of Washington, DC, during Standard Time)
*** Administrative divisions
7 provinces (provincias, singular - provincia); Annobon, Bioko Norte, Bioko Sur, Centro Sur, Kie-Ntem, Litoral, Wele-Nzas
*** Independence
12 October 1968 (from Spain)
*** National holiday
Independence Day, 12 October (1968)
*** Constitution
approved by referendum 17 November 1991; amended several times, last in 2012 (2012)
*** Legal system
mixed system of civil and customary law
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; non-party state to the ICCt
*** Citizenship
- birthright citizenship :: no, unless at least one parent is a citizen of Equatorial Guinea
- dual citizenship recognized :: no
- residency requirement for naturalization :: 10 years
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: President Brig. Gen. (Ret.) Teodoro Obiang NGUEMA MGASOGO (since 3 August 1979 when he seized power in a military coup)
- head of government :: Prime Minister Vicente EHATE TOMI (since 22 May 2012); First Deputy Prime Minister Clemente ENGONG NGUEMA ONGUENE; Second Deputy Prime Minister Francisco Pascual OBAMA ASUE; Third Deputy Prime Minister Alfonso NSUE MOKUY
- cabinet :: Council of Ministers appointed by the president
- elections/appointments :: president directly elected by simple majority popular vote for a 7-year term (eligible for a second term); election last held on 29 November 2009 (next to be held in 2016); prime minister and deputy prime ministers appointed by the president
- election results :: Teodoro Obiang NGUEMA MBASOGO reelected president; percent of vote - Teodoro Obiang NGUEMA MBASOGO (PDGE) 95.8%, Placido MICO Abogo (CPDS) 3.6%, other 0.6%
*** Legislative branch
- description :: bicameral National Assembly or Asemblea Nacional, formerly the unicameral Parliament, consists of the Senate or Senado (70 seats; 55 members directly elected by simple majority vote and 15 appointed by the president) and the House of People's Representatives or Camara de Representantes del Pueblo (100 seats; members directly elected in multi-seat constituencies by proportional representation vote to serve 5-year terms); note - the constitutional referendum of 2011 established the Senate which was formed at the time of the May 2013 elections
- elections :: last held on 26 May 2013 (next to be held in 2018)
- election results :: Senate - percent of vote by party - NA; seats by party - PDGE 54, CPDS 1; Chamber of Deputies - percent of vote by party - NA; seats by party - PDGE 99, CPDS 1
*** Judicial branch
- highest court(s) :: Supreme Court of Justice (consists of the chief justice - who is also chief of state - and 9 judges); Constitutional Court (consists of the court president and 4 members)
- judge selection and term of office :: Supreme Court judges appointed by the president for 5-year terms; Constitutional Court members appointed by the president, 2 of which are nominated by the Chamber of Deputies
- subordinate courts :: Court of Guarantees; military courts; Courts of Appeal; first instance tribunals; district and county tribunals
*** Political parties and leaders
Convergence Party for Social Democracy or CPDS [Andres ESONO ONDO]
Democratic Party for Equatorial Guinea or PDGE [Jeronimo OSA OSA ECORO] (ruling party)
Electoral Coalition or EC
Popular Action of Equatorial Guinea or APGE [Carmelo MBA BACALE]
Popular Union or UP [Daniel MARTINEZ AYECABA]
- not officially registered parties :: Democratic Republican Force or FDR [Guillermo NGUEMA ELA]
Independent Candidacy or CI [Gabriel NSE OBIANG OBONO]
Party for Progress of Equatorial Guinea or PPGE [Severo MOTO]
Union for the Center Right or UDC [Avelino MOCACHE MEAENGA]
- note :: in November 2014, the government hosted a National Dialogue process to engage with the political opposition; the opposition particiapated with limited attendance and engagement; on March 18, 2015, the CPDS, FDR, and UP formed a coalition called the Front of Democratic Opposition or FOD
*** Political pressure groups and leaders
ASODEGUE (Madrid-based pressure group for democratic reform)
Coalicion CEIBA (group formed by diverse, exiled political parties)
C.O.R.E.D. (originally led by Raimundo Ela Nsang; based in Paris)
EG Justice (US-based anti-corruption group)
*** International organization participation
ACP, AfDB, AU, BDEAC, CEMAC, CPLP (associate), FAO, FZ, G-77, IBRD, ICAO, ICRM, IDA, IFAD, IFC, IFRCS, ILO, IMF, IMO, Interpol, IOC, IPU, ITSO, ITU, MIGA, NAM, OAS (observer), OIF, OPCW, UN, UNCTAD, UNESCO, UNIDO, UNWTO, UPU, WHO, WIPO, WTO (observer)
*** Diplomatic representation in the US
- chief of mission :: Ambassador Miguel Ntutumu EVUNA ANDEME (since 23 February 2015)
- chancery :: 2020 16th Street NW, Washington, DC 20009
- telephone :: [1] (202) 518-5700
- FAX :: [1] (202) 518-5252
- consul general(s) :: Houston
*** Diplomatic representation from the US
- chief of mission :: Ambassador Mark L. ASQUINO (since 4 October 2012)
- embassy :: Carretera Malabo II, Malabo, Guinea Ecuatorial
- mailing address :: US Embassy Malabo, US Department of State, Washington, DC 20521-2520
- telephone :: [240] 333 09 57 41
*** Flag description
three equal horizontal bands of green (top), white, and red, with a blue isosceles triangle based on the hoist side and the coat of arms centered in the white band; the coat of arms has six yellow six-pointed stars (representing the mainland and five offshore islands) above a gray shield bearing a silk-cotton tree and below which is a scroll with the motto UNIDAD, PAZ, JUSTICIA (Unity, Peace, Justice); green symbolizes the jungle and natural resources, blue represents the sea that connects the mainland to the islands, white stands for peace, and red recalls the fight for independence
*** National symbol(s)
silk cotton tree; national colors: green, white, red, blue
*** National anthem
- name :: "Caminemos pisando la senda" (Let Us Tread the Path)
- lyrics/music :: Atanasio Ndongo MIYONO/Atanasio Ndongo MIYONO or Ramiro Sanchez LOPEZ (disputed)
- note :: adopted 1968
** Economy
*** Economy - overview
Exploitation of oil and gas deposits, beginning in the 1990’s, has driven economic growth in Equatorial Guinea, allowing per capita GDP to rise to over $29,000 in 2014.  Declining revenue from hydrocarbon production, high levels of infrastructure expenditures, lack of economic diversification, and corruption have led to limited improvements in the general population’s living conditions.  Equatorial Guinea hosted two economic diversification symposia in 2014 that focused on attracting investment in five sectors: agriculture and animal ranching, fishing, mining and petrochemicals, tourism, and financial services. Undeveloped mineral resources include gold, zinc, diamonds, columbite-tantalite, and other base metals. Forestry and farming are also minor components of GDP. Subsistence farming is the dominant form of livelihood. Although pre-independence Equatorial Guinea counted on cocoa production for hard currency earnings, the neglect of the rural economy since independence has diminished potential for agriculture-led growth. Foreign assistance programs by the World Bank and the IMF have been cut since 1993 because of corruption and mismanagement and high GDP figures now make Equatorial Guinea ineligible for most donor assistance. The government has been widely criticized for its lack of transparency and misuse of oil revenues and has attempted to address this issue by working towards compliance with the Extractive Industries Transparency Initiative.  US foreign assistance to Equatorial Guinea is limited in part because of US restrictions pursuant to the Trafficking Victims Protection Act.
*** GDP (purchasing power parity)
$25.11 billion (2014 est.)
$25.91 billion (2013 est.)
$27.23 billion (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 133
*** GDP (official exchange rate)
$14.31 billion (2014 est.)
*** GDP - real growth rate
-3.1% (2014 est.)
-4.8% (2013 est.)
3.2% (2012 est.)
- country comparison to the world :: 212
*** GDP - per capita (PPP)
$32,300 (2014 est.)
$33,300 (2013 est.)
$35,000 (2012 est.)
- country comparison to the world :: 52
*** Gross national saving
43.4% of GDP (2014 est.)
46.4% of GDP (2013 est.)
49.9% of GDP (2012 est.)
- country comparison to the world :: 9
*** GDP - composition, by end use
- household consumption :: 15.5%
- government consumption :: 6.4%
- investment in fixed capital :: 57.6%
- investment in inventories :: 1.3%
- exports of goods and services :: 77.4%
- imports of goods and services :: -58.4%
 (2014 est.)
*** GDP - composition, by sector of origin
- agriculture :: 5.1%
- industry :: 85.7%
- services :: 9.2% (2014 est.)
*** Agriculture - products
coffee, cocoa, rice, yams, cassava (manioc, tapioca), bananas, palm oil nuts; livestock; timber
*** Industries
petroleum, natural gas, sawmilling
*** Industrial production growth rate
-4.7% (2014 est.)
- country comparison to the world :: 192
*** Labor force
195,200 (2007 est.)
- country comparison to the world :: 173
*** Unemployment rate
22.3% (2009 est.)
- country comparison to the world :: 169
*** Population below poverty line
NA%
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $5.2 billion
- expenditures :: $6.262 billion (2014 est.)
*** Taxes and other revenues
33.8% of GDP (2014 est.)
- country comparison to the world :: 71
*** Budget surplus (+) or deficit (-)
-6.9% of GDP (2014 est.)
- country comparison to the world :: 188
*** Public debt
8.4% of GDP (2014 est.)
8.9% of GDP (2013 est.)
- country comparison to the world :: 154
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
3% (2014 est.)
6.3% (2013 est.)
- country comparison to the world :: 132
*** Central bank discount rate
8.5% (31 December 2010)
4.25% (31 December 2009)
- country comparison to the world :: 32
*** Commercial bank prime lending rate
15% (31 December 2014 est.)
15% (31 December 2013 est.)
- country comparison to the world :: 41
*** Stock of narrow money
$3.363 billion (31 December 2014 est.)
$3.384 billion (31 December 2013 est.)
- country comparison to the world :: 116
*** Stock of broad money
$3.788 billion (31 December 2014 est.)
$3.841 billion (31 December 2013 est.)
- country comparison to the world :: 141
*** Stock of domestic credit
$-80.51 million (31 December 2014 est.)
$-578 million (31 December 2013 est.)
- country comparison to the world :: 184
*** Current account balance
-$1.878 billion (2014 est.)
-$1.542 billion (2013 est.)
- country comparison to the world :: 137
*** Exports
$13.26 billion (2014 est.)
$14.74 billion (2013 est.)
- country comparison to the world :: 87
*** Exports - commodities
petroleum products, timber
*** Exports - partners
China 26.7%, UK 16%, Brazil 10%, France 8.3%, Japan 7%, Netherlands 6.9%, India 5.9%, Spain 5.8% (2014)
*** Imports
$6.436 billion (2014 est.)
$6.913 billion (2013 est.)
- country comparison to the world :: 118
*** Imports - commodities
petroleum sector equipment, other equipment, construction materials, vehicles
*** Imports - partners
US 23.5%, Spain 17.3%, China 13.6%, France 5.7%, Cote d'Ivoire 4.5% (2014)
*** Reserves of foreign exchange and gold
$2.763 billion (31 December 2014 est.)
$3.507 billion (31 December 2013 est.)
- country comparison to the world :: 115
*** Debt - external
$1.385 billion (31 December 2014 est.)
$1.548 billion (31 December 2013 est.)
- country comparison to the world :: 156
*** Exchange rates
Cooperation Financiere en Afrique Centrale francs (XAF) per US dollar -
491.2 (2014 est.)
494.04 (2013 est.)
510.53 (2012 est.)
471.87 (2011 est.)
495.28 (2010 est.)
** Energy
*** Electricity - production
97 million kWh (2011 est.)
- country comparison to the world :: 200
*** Electricity - consumption
90.21 million kWh (2011 est.)
- country comparison to the world :: 200
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 134
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 141
*** Electricity - installed generating capacity
41,000 kW (2011 est.)
- country comparison to the world :: 196
*** Electricity - from fossil fuels
90.2% of total installed capacity (2011 est.)
- country comparison to the world :: 73
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 83
*** Electricity - from hydroelectric plants
9.8% of total installed capacity (2011 est.)
- country comparison to the world :: 117
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 174
*** Crude oil - production
290,800 bbl/day (2013 est.)
- country comparison to the world :: 34
*** Crude oil - exports
319,100 bbl/day (2010 est.)
- country comparison to the world :: 24
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 180
*** Crude oil - proved reserves
1.1 billion bbl (1 January 2014 est.)
- country comparison to the world :: 41
*** Refined petroleum products - production
3,074 bbl/day (2010 est.)
- country comparison to the world :: 109
*** Refined petroleum products - consumption
2,290 bbl/day (2013 est.)
- country comparison to the world :: 186
*** Refined petroleum products - exports
2,320 bbl/day (2010 est.)
- country comparison to the world :: 101
*** Refined petroleum products - imports
4,561 bbl/day (2010 est.)
- country comparison to the world :: 159
*** Natural gas - production
6.88 billion cu m (2012 est.)
- country comparison to the world :: 47
*** Natural gas - consumption
2.16 billion cu m (2012 est.)
- country comparison to the world :: 79
*** Natural gas - exports
4.72 billion cu m (2012 est.)
- country comparison to the world :: 32
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 188
*** Natural gas - proved reserves
36.81 billion cu m (1 January 2014 est.)
- country comparison to the world :: 66
*** Carbon dioxide emissions from consumption of energy
5.614 million Mt (2012 est.)
- country comparison to the world :: 124
** Communications
*** Telephones - fixed lines
- total subscriptions :: 15,100
- subscriptions per 100 inhabitants :: 2 (2014 est.)
- country comparison to the world :: 194
*** Telephones - mobile cellular
- total :: 516,500
- subscriptions per 100 inhabitants :: 72 (2014 est.)
- country comparison to the world :: 170
*** Telephone system
- general assessment :: digital fixed-line network in most major urban areas and good mobile cellular coverage
- domestic :: fixed-line density is about 2 per 100 persons; mobile-cellular subscribership has been increasing and in 2011 stood at about 60 percent of the population
- international :: country code - 240; international communications from Bata and Malabo to African and European countries; satellite earth station - 1 Intelsat (Indian Ocean) (2011)
*** Broadcast media
state maintains control of broadcast media with domestic broadcast media limited to 1 state-owned TV station, 1 private TV station owned by the president's eldest son, 1 state-owned radio station, and 1 private radio station owned by the president's eldest son; satellite TV service is available; transmissions of multiple international broadcasters are accessible (2013)
*** Radio broadcast stations
AM 0, FM 3, shortwave 5 (2001)
*** Television broadcast stations
1 (2001)
*** Internet country code
.gq
*** Internet users
- total :: 115,100
- percent of population :: 15.9% (2014 est.)
- country comparison to the world :: 167
** Transportation
*** Airports
7 (2013)
- country comparison to the world :: 166
*** Airports - with paved runways
- total :: 6
- over 3,047 m :: 1
- 2,438 to 3,047 m :: 2
- 1,524 to 2,437 m :: 1
- under 914 m :: 2 (2013)
*** Airports - with unpaved runways
- total :: 1
- 2,438 to 3,047 m :: 1 (2013)
*** Pipelines
condensate 42 km; condensate/gas 5 km; gas 79 km; oil 71 km (2013)
*** Roadways
- total :: 2,880 km (2000)
- country comparison to the world :: 169
*** Merchant marine
- total :: 5
- by type :: cargo 1, chemical tanker 1, petroleum tanker 3
- foreign-owned :: 1 (Norway 1) (2010)
- country comparison to the world :: 124
*** Ports and terminals
- major seaport(s) :: Bata, Luba, Malabo
- LNG terminal(s) (export) :: Bioko Island
** Military
*** Military branches
Equatorial Guinea Armed Forces (FAGE): Equatorial Guinea National Guard (Guardia Nacional de Guinea Ecuatorial, GNGE (Army), Navy, Air Force (2013)
*** Military service age and obligation
18 years of age for selective compulsory military service, although conscription is rare in practice; 2-year service obligation; women hold only administrative positions in the Navy (2013)
*** Manpower available for military service
- males age 16-49 :: 151,147
- females age 16-49 :: 150,345 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 113,277
- females age 16-49 :: 115,320 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 7,398
- female :: 7,126 (2010 est.)
** Transnational Issues
*** Disputes - international
in 2002, ICJ ruled on an equidistance settlement of Cameroon-Equatorial Guinea-Nigeria maritime boundary in the Gulf of Guinea, but a dispute between Equatorial Guinea and Cameroon over an island at the mouth of the Ntem River and imprecisely defined maritime coordinates in the ICJ decision delayed final delimitation; UN urged Equatorial Guinea and Gabon to resolve the sovereignty dispute over Gabon-occupied Mbane and lesser islands and to create a maritime boundary in the hydrocarbon-rich Corisco Bay
*** Trafficking in persons
- current situation :: Equatorial Guinea is a source and destination country for women and children subjected to forced labor and sexual exploitation; children are trafficked from nearby countries for work as domestic servants, market laborers, ambulant vendors, and launderers; women may also be trafficked to Equatorial Guinea from Cameroon, Benin, other neighboring countries, and China for forced labor or prostitution; Equatorial Guinean girls may be encouraged by their parents to engage in the sex trade in urban centers to receive groceries, gifts, housing, and money
- tier rating :: Tier 3 – Equatorial Guinea is not making significant efforts to comply with the minimum standards on the elimination of trafficking and is not making significant efforts to do so; in 2013, the government initiated no investigations or prosecutions of suspected trafficking offenses and demonstrated no efforts to identify victims or to provide them with necessary services, despite being required to do so under its 2004 anti-trafficking law; undocumented migrants were deported without screening to assess whether they were trafficking victims; the government did not launch any public anti-trafficking campaigns or implement any programs to address forced child labor (2014)