** Introduction
*** Background
Fiji became independent in 1970 after nearly a century as a British colony. Democratic rule was interrupted by two military coups in 1987 caused by concern over a government perceived as dominated by the Indian community (descendants of contract laborers brought to the islands by the British in the 19th century). The coups and a 1990 constitution that cemented native Melanesian control of Fiji led to heavy Indian emigration; the population loss resulted in economic difficulties, but ensured that Melanesians became the majority. A new constitution enacted in 1997 was more equitable. Free and peaceful elections in 1999 resulted in a government led by an Indo-Fijian, but a civilian-led coup in 2000 ushered in a prolonged period of political turmoil. Parliamentary elections held in 2001 provided Fiji with a democratically elected government led by Prime Minister Laisenia QARASE. Reelected in May 2006, QARASE was ousted in a December 2006 military coup led by Commodore Voreqe BAINIMARAMA, who initially appointed himself acting president but in January 2007 became interim prime minister. Following years of political turmoil, long-delayed legislative elections were held in September 2014 that were deemed "credible" by international observers and that resulted in BAINIMARAMA being reelected.
** Geography
*** Location
Oceania, island group in the South Pacific Ocean, about two-thirds of the way from Hawaii to New Zealand
*** Geographic coordinates
18 00 S, 175 00 E
*** Map references
Oceania
*** Area
- total :: 18,274 sq km
- land :: 18,274 sq km
- water :: 0 sq km
- country comparison to the world :: 157
*** Area - comparative
slightly smaller than New Jersey
*** Land boundaries
0 km
*** Coastline
1,129 km
*** Maritime claims
measured from claimed archipelagic straight baselines
- territorial sea :: 12 nm
- exclusive economic zone :: 200 nm
- continental shelf :: 200-m depth or to the depth of exploitation; rectilinear shelf claim added
*** Climate
tropical marine; only slight seasonal temperature variation
*** Terrain
mostly mountains of volcanic origin
*** Elevation extremes
- lowest point :: Pacific Ocean 0 m
- highest point :: Tomanivi 1,324 m
*** Natural resources
timber, fish, gold, copper, offshore oil potential, hydropower
*** Land use
- agricultural land :: 23.3%
arable land 9%; permanent crops 4.7%; permanent pasture 9.6%
- forest :: 55.7%
- other :: 21% (2011 est.)
*** Irrigated land
30 sq km (2003)
*** Total renewable water resources
28.55 cu km (2011)
*** Freshwater withdrawal (domestic/industrial/agricultural)
- total :: 0.08  cu km/yr (30%/11%/59%)
- per capita :: 100.1  cu m/yr (2005)
*** Natural hazards
cyclonic storms can occur from November to January
*** Environment - current issues
deforestation; soil erosion
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Endangered Species, Law of the Sea, Marine Life Conservation, Ozone Layer Protection, Tropical Timber 83, Tropical Timber 94, Wetlands
- signed, but not ratified :: none of the selected agreements
*** Geography - note
includes 332 islands; approximately 110 are inhabited
** People and Society
*** Nationality
- noun :: Fijian(s)
- adjective :: Fijian
*** Ethnic groups
iTaukei 56.8% (predominantly Melanesian with a Polynesian admixture), Indian 37.5%, Rotuman 1.2%, other 4.5% (European, part European, other Pacific Islanders, Chinese)
- note :: a 2010 law replaces 'Fijian' with 'iTuakei' when referring to the original and native settlers of Fiji (2007 est.)
*** Languages
English (official), Fijian (official), Hindustani
*** Religions
Protestant 45% (Methodist 34.6%, Assembly of God 5.7%, Seventh Day Adventist 3.9%, and Anglican 0.8%), Hindu 27.9%, other Christian 10.4%, Roman Catholic 9.1%, Muslim 6.3%, Sikh 0.3%, other 0.3%, none 0.8% (2007 est.)
*** Population
909,389 (July 2015 est.)
- country comparison to the world :: 162
*** Age structure
- 0-14 years :: 28.03% (male 130,251/female 124,633)
- 15-24 years :: 16.73% (male 77,716/female 74,449)
- 25-54 years :: 41.12% (male 191,393/female 182,571)
- 55-64 years :: 8.04% (male 37,019/female 36,141)
- 65 years and over :: 6.07% (male 25,386/female 29,830) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 52.8%
- youth dependency ratio :: 43.9%
- elderly dependency ratio :: 8.9%
- potential support ratio :: 11.2% (2015 est.)
*** Median age
- total :: 28.2 years
- male :: 28 years
- female :: 28.4 years (2015 est.)
*** Population growth rate
0.67% (2015 est.)
- country comparison to the world :: 149
*** Birth rate
19.43 births/1,000 population (2015 est.)
- country comparison to the world :: 88
*** Death rate
6.04 deaths/1,000 population (2015 est.)
- country comparison to the world :: 163
*** Net migration rate
-6.75 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 203
*** Urbanization
- urban population :: 53.7% of total population (2015)
- rate of urbanization :: 1.45% annual rate of change (2010-15 est.)
*** Major urban areas - population
SUVA (capital) 176,000 (2014)
*** Sex ratio
- at birth :: 1.05 male(s)/female
- 0-14 years :: 1.05 male(s)/female
- 15-24 years :: 1.04 male(s)/female
- 25-54 years :: 1.05 male(s)/female
- 55-64 years :: 1.02 male(s)/female
- 65 years and over :: 0.85 male(s)/female
- total population :: 1.03 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 9.94 deaths/1,000 live births
- male :: 10.97 deaths/1,000 live births
- female :: 8.87 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 138
*** Life expectancy at birth
- total population :: 72.43 years
- male :: 69.79 years
- female :: 75.2 years (2015 est.)
- country comparison to the world :: 141
*** Total fertility rate
2.47 children born/woman (2015 est.)
- country comparison to the world :: 81
*** Health expenditures
4.1% of GDP (2013)
- country comparison to the world :: 160
*** Physicians density
0.43 physicians/1,000 population (2009)
*** Hospital bed density
2 beds/1,000 population (2009)
*** Drinking water source
- improved :: 
urban: 99.5% of population
rural: 91.2% of population
total: 95.7% of population
- unimproved :: 
urban: 0.5% of population
rural: 8.8% of population
total: 4.3% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 93.4% of population
rural: 88.4% of population
total: 91.1% of population
- unimproved :: 
urban: 6.6% of population
rural: 11.6% of population
total: 8.9% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
0.13% (2014 est.)
- country comparison to the world :: 109
*** HIV/AIDS - people living with HIV/AIDS
700 (2014 est.)
- country comparison to the world :: 122
*** HIV/AIDS - deaths
fewer than 100 (2014 est.)
- country comparison to the world :: 120
*** Obesity - adult prevalence rate
35.9% (2014)
- country comparison to the world :: 25
*** Education expenditures
4.2% of GDP (2011)
- country comparison to the world :: 102
** Government
*** Country name
- conventional long form :: Republic of Fiji
- conventional short form :: Fiji
- local long form :: Republic of Fiji/Matanitu ko Viti
- local short form :: Fiji/Viti
*** Government type
republic
*** Capital
- name :: Suva (on Viti Levu)
- geographic coordinates :: 18 08 S, 178 25 E
- time difference :: UTC+12 (17 hours ahead of Washington, DC, during Standard Time)
- daylight saving time :: +1hr, begins fourth Sunday in October; ends third Sunday in January
*** Administrative divisions
14 provinces and 1 dependency*; Ba, Bua, Cakaudrove, Kadavu, Lau, Lomaiviti, Macuata, Nadroga and Navosa, Naitasiri, Namosi, Ra, Rewa, Rotuma*, Serua, Tailevu
*** Independence
10 October 1970 (from the UK)
*** National holiday
Fiji Independence Day, 10 October (1970)
*** Constitution
several previous; latest signed into law September 2013 (2013)
*** Legal system
common law system based on the English model
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; accepts ICCt jurisdiction
*** Citizenship
- birthright citizenship :: no, unless at least one parent is a citizen of Fiji
- dual citizenship recognized :: yes
- residency requirement for naturalization :: 5 years
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: President Ratu Epeli NAILATIKAU (since 30 July 2009)
- head of government :: Prime Minister Voreqe "Frank" BAINIMARAMA (since 22 September 2014)
- cabinet :: Cabinet appointed by the prime minister from among members of Parliament and is responsible to Parliament
- elections/appointments :: under the constitution, president indirectly elected by the Great Council of Chiefs for a 5-year term (eligible for a second term); in 2007, the Great Council of Chiefs was suspended from its role in electing the president and disestablished in 2012; prime minister appointed by the president
- election results :: Ratu Epeli NAILATIKAU (independent) reappointed in November 2012; term ends in 2015
*** Legislative branch
- description :: unicameral Parliament (50 seats; members directly elected in a nationwide, multi-seat constituency by open-list proportional representation vote to serve 4-year terms; the new constitution of 2013 restructured Parliament frome bicameral to unicameral
- elections :: last held on 17 September 2014 (next to be held in 2019)
- election results :: percent of vote by party - Fiji First 59.2%, SDL 28.2%, National Federation Party 5.5%, other 7.1%; seats by party - Fiji First 32, SDL 15, National Federation Party 3
*** Judicial branch
- highest court(s) :: Supreme Court (consists of the chief justice, all justices of the Court of Appeal, and judges appointed specifically as Supreme Court judges); Court of Appeal (consists of the court president, all puisne judges of the High Court, and judges specifically appointed to the Court of Appeal); High Court (chaired by the chief justice and includes a minimum of 10 puisne judges; High Court organized into civil, criminal, family, employment, and tax divisions); note - in 1987, the Supreme Court assumed functions formerly performed by the Judicial Committee of the Privy Council (in London)
- judge selection and term of office :: chief justice appointed by the president of Fiji on the advice of the prime minister following consultation with the parliamentary leader of the opposition; judges of the Supreme Court, the president of the Court of Appeal, the justices of the Court of Appeal, and puisne judges of the High Court appointed by the president of Fiji upon the nomination of the Judicial Service Commission after consulting with the cabinet minister and the committee of the House of Representatives responsible for the administration of justice; the chief justice, Supreme Court judges and justices of Appeal generally required to retire at age 70 but may be waived for one or more sessions of the court; puisne judges appointed for not less than 4 years nor more than 7 years with mandatory retirement at age 65
- subordinate courts :: Magistrates' Court (organized into civil, criminal, juvenile, and small claims divisions)
*** Political parties and leaders
FijiFirst [Aiyaz SAYED-KHAIYUM]
Fiji Labor Party or FLP [Mahendra CHAUDHRY]
Fiji United Freedon Party or FUFP [Jagath KARUNARATNE]
National Federation Party or NFP [Dalip KUMAR] (primarily Indian)
Peoples Democratic Party or PDP [Adi Sivia QORO]
Social Democratic Liberal Party or SODELPA [Pio TABAIWALU]
*** Political pressure groups and leaders
Group Against Racial Discrimination or GARD [Dr. Anirudk SINGH] (suports restoration of a democratic government)
Viti Landowners Association
*** International organization participation
ACP, ADB, AOSIS, C, CP, FAO, G-77, IAEA, IBRD, ICAO, ICCt, ICRM, IDA, IFAD, IFC, IFRCS, IHO, ILO, IMF, IMO, Interpol, IOC, IOM, ISO, ITSO, ITU, ITUC (NGOs), MIGA, OPCW, PCA, PIF, Sparteca (suspended), SPC, UN, UNCTAD, UNDOF, UNESCO, UNIDO, UNMISS, UNWTO, UPU, WCO, WFTU (NGOs), WHO, WIPO, WMO, WTO
*** Diplomatic representation in the US
- chief of mission :: Ambassador Winston THOMPSON (since 20 April 2009)
- chancery :: 2000 M Street NW, Suite 710, Washington, DC 20036
- telephone :: [1] (202) 466-8320
- FAX :: [1] (202) 466-8325
- consulate(s) :: Los Angeles, Portland (OR), San Francisco
*** Diplomatic representation from the US
- chief of mission :: Ambassador Judith CEFKIN (since 3 February 2015); note - also accredited to Kiribati, Nauru, Tonga, and Tuvalu
- embassy :: 158 Princes Rd, Tamavua
- mailing address :: P. O. Box 218, Suva
- telephone :: [679] 331-4466
- FAX :: [679] 330-8685
*** Flag description
light blue with the flag of the UK in the upper hoist-side quadrant and the Fijian shield centered on the outer half of the flag; the blue symbolizes the Pacific ocean and the Union Jack reflects the links with Great Britain; the shield - taken from Fiji's coat of arms - depicts a yellow lion above a white field quartered by the cross of Saint George; the four quarters depict stalks of sugarcane, a palm tree, bananas, and a white dove
*** National symbol(s)
Fijian canoe; national color: light blue
*** National anthem
- name :: "God Bless Fiji"
- lyrics/music :: Michael Francis Alexander PRESCOTT/C. Austin MILES (adapted by Michael Francis Alexander PRESCOTT)
- note :: adopted 1970; known in Fijian as "Meda Dau Doka" (Let Us Show Pride); adapted from the hymn, "Dwelling in Beulah Land," the anthem's English lyrics are generally sung, although they differ in meaning from the official Fijian lyrics

** Economy
*** Economy - overview
Fiji, endowed with forest, mineral, and fish resources, is one of the most developed and connected of the Pacific island economies. Earnings from the tourism industry, with an estimated 692,630 tourists visiting in 2014, and remittances from Fijian’s working abroad are the country’s largest foreign exchange earners. Fiji's sugar remains a significant industry and a major export. The sugar industry reforms since 2010 have improved productivity and returns, but the industry faces the complete withdrawal of European Union preferential prices by 2017. Fiji’s trade imbalance continues to widen with increased imports and sluggish performance of domestic exports. The return to parliamentary democracy and successful elections in September 2014 have boosted investor confidence. Private sector investment in 2014 reached 15% of GDP, compared to 13% in 2013.
*** GDP (purchasing power parity)
$7.293 billion (2014 est.)
$7.007 billion (2013 est.)
$6.696 billion (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 165
*** GDP (official exchange rate)
$4.212 billion (2014 est.)
*** GDP - real growth rate
4.1% (2014 est.)
4.6% (2013 est.)
1.8% (2012 est.)
- country comparison to the world :: 76
*** GDP - per capita (PPP)
$8,200 (2014 est.)
$7,900 (2013 est.)
$7,600 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 140
*** Gross national saving
16.2% of GDP (2014 est.)
7.4% of GDP (2013 est.)
20.1% of GDP (2012 est.)
- country comparison to the world :: 110
*** GDP - composition, by end use
- household consumption :: 81.2%
- government consumption :: 14.9%
- investment in fixed capital :: 21.4%
- investment in inventories :: 0%
- exports of goods and services :: 51.6%
- imports of goods and services :: -69.1%
 (2014 est.)
*** GDP - composition, by sector of origin
- agriculture :: 12.7%
- industry :: 18.2%
- services :: 69.1% (2014 est.)
*** Agriculture - products
sugarcane, coconuts, cassava (manioc, tapioca), rice, sweet potatoes, bananas; cattle, pigs, horses, goats; fish
*** Industries
tourism, sugar, clothing, copra, gold, silver, lumber, small cottage industries
*** Industrial production growth rate
2.5% (2014 est.)
- country comparison to the world :: 116
*** Labor force
345,700 (2014 est.)
- country comparison to the world :: 162
*** Labor force - by occupation
- agriculture :: 70%
- industry and services :: 30% (2001 est.)
*** Unemployment rate
8.8% (2014 est.)
- country comparison to the world :: 83
*** Population below poverty line
31% (2009 est.)
*** Household income or consumption by percentage share
- lowest 10% :: 2.6%
- highest 10% :: 34.9% (2009 est.)
*** Budget
- revenues :: $1.369 billion
- expenditures :: $1.451 billion (2014 est.)
*** Taxes and other revenues
32.8% of GDP (2014 est.)
- country comparison to the world :: 108
*** Budget surplus (+) or deficit (-)
-1.9% of GDP (2014 est.)
- country comparison to the world :: 99
*** Public debt
49.7% of GDP (2014 est.)
51.4% of GDP (2013 est.)
- country comparison to the world :: 64
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
0.1% (2014 est.)
3.4% (2013 est.)
- country comparison to the world :: 30
*** Central bank discount rate
1.75% (31 December 2010)
3% (31 December 2009)
- country comparison to the world :: 123
*** Commercial bank prime lending rate
5.71% (31 December 2014 est.)
5.84% (31 December 2013 est.)
- country comparison to the world :: 141
*** Stock of narrow money
$1.864 billion (31 December 2014 est.)
$1.849 billion (31 December 2013 est.)
- country comparison to the world :: 131
*** Stock of broad money
$3.078 billion (31 December 2014 est.)
$2.953 billion (31 December 2013 est.)
- country comparison to the world :: 143
*** Stock of domestic credit
$2.773 billion (31 December 2014 est.)
$2.585 billion (31 December 2013 est.)
- country comparison to the world :: 132
*** Market value of publicly traded shares
$452.5 million (31 December 2012 est.)
$392.2 million (31 December 2011)
$418.8 million (31 December 2010 est.)
- country comparison to the world :: 114
*** Current account balance
-$354.6 million (2014 est.)
-$581.4 million (2013 est.)
- country comparison to the world :: 91
*** Exports
$1.188 billion (2014 est.)
$1.38 billion (2013 est.)
- country comparison to the world :: 157
*** Exports - commodities
sugar, garments, gold, timber, fish, molasses, coconut oil
*** Exports - partners
US 11.8%, Australia 10%, UK 6.4%, Samoa 6.2%, Tonga 5.5% (2014)
*** Imports
$2.241 billion (2014 est.)
$2.692 billion (2013 est.)
- country comparison to the world :: 160
*** Imports - commodities
manufactured goods, machinery and transport equipment, petroleum products, food, chemicals
*** Imports - partners
Singapore 18.4%, South Korea 14%, NZ 13.7%, China 13.1%, Australia 12.9% (2014)
*** Reserves of foreign exchange and gold
$911 million (31 December 2014 est.)
$936.9 million (31 December 2013 est.)
- country comparison to the world :: 136
*** Debt - external
$587.4 million (31 December 2014 est.)
$569.6 million (31 December 2013 est.)
- country comparison to the world :: 177
*** Stock of direct foreign investment - at home
$3.889 billion (31 December 2014 est.)
$3.581 billion (31 December 2013 est.)
- country comparison to the world :: 97
*** Stock of direct foreign investment - abroad
$50.08 million (31 December 2014 est.)
$49.65 million (31 December 2013 est.)
- country comparison to the world :: 95
*** Exchange rates
Fijian dollars (FJD) per US dollar -
1.9877 (2014 est.)
1.8979 (2013 est.)
1.79 (2012 est.)
1.7932 (2011 est.)
1.9183 (2010 est.)
** Energy
*** Electricity - production
857.5 million kWh (2013 est.)
- country comparison to the world :: 151
*** Electricity - consumption
777.6 million kWh (2011 est.)
- country comparison to the world :: 160
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 137
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 144
*** Electricity - installed generating capacity
245,100 kW (2011 est.)
- country comparison to the world :: 156
*** Electricity - from fossil fuels
49% of total installed capacity (2011 est.)
- country comparison to the world :: 153
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 88
*** Electricity - from hydroelectric plants
45.3% of total installed capacity (2011 est.)
- country comparison to the world :: 51
*** Electricity - from other renewable sources
5.7% of total installed capacity (2011 est.)
- country comparison to the world :: 50
*** Crude oil - production
30 bbl/day (2013 est.)
- country comparison to the world :: 118
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 111
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 184
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 132
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 142
*** Refined petroleum products - consumption
11,380 bbl/day (2013 est.)
- country comparison to the world :: 153
*** Refined petroleum products - exports
692 bbl/day (2010 est.)
- country comparison to the world :: 109
*** Refined petroleum products - imports
10,050 bbl/day (2010 est.)
- country comparison to the world :: 129
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 130
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 142
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 96
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 192
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 137
*** Carbon dioxide emissions from consumption of energy
1.543 million Mt (2012 est.)
- country comparison to the world :: 159
** Communications
*** Telephones - fixed lines
- total subscriptions :: 74,700
- subscriptions per 100 inhabitants :: 8 (2014 est.)
- country comparison to the world :: 150
*** Telephones - mobile cellular
- total :: 876,200
- subscriptions per 100 inhabitants :: 97 (2014 est.)
- country comparison to the world :: 161
*** Telephone system
- general assessment :: modern local, interisland, and international (wire/radio integrated) public and special-purpose telephone, telegraph, and teleprinter facilities; regional radio communications center
- domestic :: telephone or radio telephone links to almost all inhabited islands; most towns and large villages have automatic telephone exchanges and direct dialing; combined fixed-line and mobile-cellular teledensity roughly 100 per 100 persons
- international :: country code - 679; access to important cable links between US and Canada, as well as between NZ and Australia; satellite earth stations - 2 Inmarsat (Pacific Ocean) (2011)
*** Broadcast media
Fiji TV, a publicly traded company, operates a free-to-air channel, as well as Sky Fiji and Sky Pacific multi-channel pay-TV services; state-owned commercial company, Fiji Broadcasting Corporation, Ltd, operates 6 radio stations - 2 public broadcasters and 4 commercial broadcasters with multiple repeaters; 5 radio stations with repeaters operated by Communications Fiji, Ltd; transmissions of multiple international broadcasters are available (2009)
*** Radio broadcast stations
AM 13, FM 40, shortwave 0 (1998)
*** Television broadcast stations
NA
*** Internet country code
.fj
*** Internet users
- total :: 331,700
- percent of population :: 36.7% (2014 est.)
- country comparison to the world :: 139
** Transportation
*** Airports
28 (2013)
- country comparison to the world :: 121
*** Airports - with paved runways
- total :: 4
- over 3,047 m :: 1
- 1,524 to 2,437 m :: 1
- 914 to 1,523 m :: 2 (2013)
*** Airports - with unpaved runways
- total :: 24
- 914 to 1,523 m :: 5
- under 914 m :: 
19 (2013)
*** Railways
- total :: 597 km
- narrow gauge :: 597 km 0.600-m gauge
- note :: belongs to the government-owned Fiji Sugar Corporation; used to haul sugarcane during the harvest season, which runs from May to December (2008)
- country comparison to the world :: 109
*** Roadways
- total :: 3,440 km
- paved :: 1,686 km
- unpaved :: 1,754 km (2011)
- country comparison to the world :: 163
*** Waterways
203 km (122 km are navigable by motorized craft and 200-metric-ton barges) (2012)
- country comparison to the world :: 97
*** Merchant marine
- total :: 11
- by type :: passenger 4, passenger/cargo 4, refrigerated cargo 1, roll on/roll off 2
- foreign-owned :: 2 (Australia 2) (2010)
- country comparison to the world :: 108
*** Ports and terminals
- major seaport(s) :: Lautoka, Levuka, Suva
** Military
*** Military branches
Republic of Fiji Military Forces (RFMF): Land Forces, Naval Forces (2011)
*** Military service age and obligation
18 years of age for voluntary military service; mandatory retirement at age 55 (2013)
*** Manpower available for military service
- males age 16-49 :: 233,240
- females age 16-49 :: 222,587 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 183,730
- females age 16-49 :: 188,325 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 8,403
- female :: 8,039 (2010 est.)
*** Military expenditures
1.47% of GDP (2012)
1.44% of GDP (2011)
1.47% of GDP (2010)
- country comparison to the world :: 61
** Transnational Issues
*** Disputes - international
none