** Introduction
*** Background
Carib Indians inhabited Grenada when Christopher COLUMBUS discovered the island in 1498, but it remained uncolonized for more than a century. The French settled Grenada in the 17th century, established sugar estates, and imported large numbers of African slaves. Britain took the island in 1762 and vigorously expanded sugar production. In the 19th century, cacao eventually surpassed sugar as the main export crop; in the 20th century, nutmeg became the leading export. In 1967, Britain gave Grenada autonomy over its internal affairs. Full independence was attained in 1974 making Grenada one of the smallest independent countries in the Western Hemisphere. Grenada was seized by a Marxist military council on 19 October 1983. Six days later the island was invaded by US forces and those of six other Caribbean nations, which quickly captured the ringleaders and their hundreds of Cuban advisers. Free elections were reinstituted the following year and have continued since then.
** Geography
*** Location
Caribbean, island between the Caribbean Sea and Atlantic Ocean, north of Trinidad and Tobago
*** Geographic coordinates
12 07 N, 61 40 W
*** Map references
Central America and the Caribbean
*** Area
- total :: 344 sq km
- land :: 344 sq km
- water :: 0 sq km
- country comparison to the world :: 207
*** Area - comparative
twice the size of Washington, DC
*** Land boundaries
0 km
*** Coastline
121 km
*** Maritime claims
- territorial sea :: 12 nm
- exclusive economic zone :: 200 nm
*** Climate
tropical; tempered by northeast trade winds
*** Terrain
volcanic in origin with central mountains
*** Elevation extremes
- lowest point :: Caribbean Sea 0 m
- highest point :: Mount Saint Catherine 840 m
*** Natural resources
timber, tropical fruit, deepwater harbors
*** Land use
- agricultural land :: 32.3%
arable land 8.8%; permanent crops 20.6%; permanent pasture 2.9%
- forest :: 50%
- other :: 17.7% (2011 est.)
*** Irrigated land
2.19 sq km (2003)
*** Total renewable water resources
NA
*** Natural hazards
lies on edge of hurricane belt; hurricane season lasts from June to November
*** Environment - current issues
NA
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Endangered Species, Law of the Sea, Ozone Layer Protection, Whaling
- signed, but not ratified :: none of the selected agreements
*** Geography - note
the administration of the islands of the Grenadines group is divided between Saint Vincent and the Grenadines and Grenada
** People and Society
*** Nationality
- noun :: Grenadian(s)
- adjective :: Grenadian
*** Ethnic groups
African descent 89.4%, mixed 8.2%, East Indian 1.6%, other 0.9% (includes indigenous) (2001 est.)
*** Languages
English (official), French patois
*** Religions
Roman Catholic 44.6%, Protestant 43.5% (includes Anglican 11.5%, Pentecostal 11.3%, Seventh Day Adventist 10.5%, Baptist 2.9%, Church of God 2.6%, Methodist 1.8%, Evangelical 1.6%, other 1.3%), Jehovah's Witness 1.1%, Rastafarian 1.1%, other 6.2%, none 3.6%
*** Population
110,694 (July 2015 est.)
- country comparison to the world :: 191
*** Age structure
- 0-14 years :: 24.35% (male 13,958/female 12,998)
- 15-24 years :: 16.02% (male 8,830/female 8,906)
- 25-54 years :: 40.35% (male 22,891/female 21,771)
- 55-64 years :: 9.65% (male 5,482/female 5,204)
- 65 years and over :: 9.62% (male 4,888/female 5,766) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 50.7%
- youth dependency ratio :: 39.9%
- elderly dependency ratio :: 10.8%
- potential support ratio :: 9.3% (2015 est.)
*** Median age
- total :: 30.4 years
- male :: 30.4 years
- female :: 30.4 years (2015 est.)
*** Population growth rate
0.48% (2015 est.)
- country comparison to the world :: 161
*** Birth rate
16.03 births/1,000 population (2015 est.)
- country comparison to the world :: 120
*** Death rate
8.08 deaths/1,000 population (2015 est.)
- country comparison to the world :: 96
*** Net migration rate
-3.13 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 182
*** Urbanization
- urban population :: 35.6% of total population (2015)
- rate of urbanization :: 0.33% annual rate of change (2010-15 est.)
*** Major urban areas - population
SAINT GEORGE'S (capital) 38,000 (2014)
*** Sex ratio
- at birth :: 1.1 male(s)/female
- 0-14 years :: 1.07 male(s)/female
- 15-24 years :: 0.99 male(s)/female
- 25-54 years :: 1.05 male(s)/female
- 55-64 years :: 1.05 male(s)/female
- 65 years and over :: 0.85 male(s)/female
- total population :: 1.03 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 10.21 deaths/1,000 live births
- male :: 9.59 deaths/1,000 live births
- female :: 10.9 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 136
*** Life expectancy at birth
- total population :: 74.05 years
- male :: 71.47 years
- female :: 76.88 years (2015 est.)
- country comparison to the world :: 125
*** Total fertility rate
2.06 children born/woman (2015 est.)
- country comparison to the world :: 112
*** Health expenditures
6.3% of GDP (2013)
- country comparison to the world :: 97
*** Physicians density
0.66 physicians/1,000 population (2006)
*** Hospital bed density
3.5 beds/1,000 population (2012)
*** Drinking water source
- improved :: 
urban: 99% of population
rural: 95.3% of population
total: 96.6% of population
- unimproved :: 
urban: 1% of population
rural: 4.7% of population
total: 3.4% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 97.5% of population
rural: 98.3% of population
total: 98% of population
- unimproved :: 
urban: 2.5% of population
rural: 1.7% of population
total: 2% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
*** Obesity - adult prevalence rate
24.6% (2014)
- country comparison to the world :: 78
*** School life expectancy (primary to tertiary education)
- total :: 16 years
- male :: 15 years
- female :: 16 years (2009)
** Government
*** Country name
- conventional long form :: none
- conventional short form :: Grenada
*** Government type
parliamentary democracy and a Commonwealth realm
*** Capital
- name :: Saint George's
- geographic coordinates :: 12 03 N, 61 45 W
- time difference :: UTC-4 (1 hour ahead of Washington, DC, during Standard Time)
*** Administrative divisions
6 parishes and 1 dependency*; Carriacou and Petite Martinique*, Saint Andrew, Saint David, Saint George, Saint John, Saint Mark, Saint Patrick
*** Independence
7 February 1974 (from the UK)
*** National holiday
Independence Day, 7 February (1974)
*** Constitution
previous 1967; latest presented 19 December 1973, came into operation 7 February 1974, some provisions suspended 1979; amended 1991 (Constitutional Judicature Act, 1991 - restored provisions suspended in 1979), 1992 (2008)
*** Legal system
common law based on English model
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; accepts ICCt jurisdiction
*** Citizenship
- birthright citizenship :: yes
- dual citizenship recognized :: 
- residency requirement for naturalization :: 
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: Queen ELIZABETH II (since 6 February 1952); represented by Governor General Cecile LA GRENADE (since 7 May 2013)
- head of government :: Prime Minister Keith MITCHELL (since 20 February 2013)
- cabinet :: Cabinet appointed by the governor general on the advice of the prime minister
- elections/appointments :: the monarchy is hereditary; governor general appointed by the monarch; following legislative elections, the leader of the majority party or majority coalition usually appointed prime minister by the governor general
*** Legislative branch
- description :: bicameral Parliament consists of the Senate (13 seats; members appointed by the governor general - 10 on the advice of the prime minister and 3 on the advice of the opposition party leader; members serve 5-year terms) and the House of Representatives (15 seats; members directly elected in single-seat constituencies by simple majority vote to serve 5-year terms)
- elections :: last held on 19 February 2013 (next to be held in 2018)
- election results :: House of Representatives - percent of vote by party - NNP 59%, NDC 41%; seats by party - NNP 15
*** Judicial branch
- highest court(s) :: Supreme Court of Grenada (consists of the High Court with 3 justices and a 2-tier Court of Appeal with NA justices); note - the Eastern Caribbean Supreme Court (ECSC) is the itinerant superior court of record for the 9-member Organization of Eastern Caribbean States to include Grenada; the ECSC - with its headquarters on St. Lucia - is headed by the chief justice and is comprised of the Court of Appeal with 3 justices and the High Court with 16 judges; sittings of the Court of Appeal and High Court rotate among the member states
- judge selection and term of office :: justice selection and tenure NA
- subordinate courts :: magistrates' courts; Court of Magisterial Appeals
*** Political parties and leaders
Grenada United Labor Party or GULP [Wilfred HAYES]
National Democratic Congress or NDC [Tillman THOMAS]
New National Party or NNP [Keith MITCHELL]
*** Political pressure groups and leaders
Committee for Human Rights in Grenada or CHRG
New Jewel Movement Support Group
The British Grenada Friendship Society
The New Jewel 19 Committee
*** International organization participation
ACP, AOSIS, C, Caricom, CDB, CELAC, FAO, G-77, IBRD, ICAO, ICCt (signatory), ICRM, IDA, IFAD, IFC, IFRCS, ILO, IMF, IMO, Interpol, IOC, ITU, ITUC, LAES, MIGA, NAM, OAS, OECS, OPANAL, OPCW, Petrocaribe, UN, UNCTAD, UNESCO, UNIDO, UPU, WHO, WIPO, WTO
*** Diplomatic representation in the US
- chief of mission :: Ambassador Ethelstan A. FRIDAY (since 3 September 2013)
- chancery :: 1701 New Hampshire Avenue NW, Washington, DC 20009
- telephone :: [1] (202) 265-2561
- FAX :: [1] (202) 265-2468
- consulate(s) general :: Miami
- consulate(s) :: Chicago, Detroit (MI), New York
*** Diplomatic representation from the US
- chief of mission :: the US does not have an embassy in Grenada; the US Ambassador to Barbados is accredited to Grenada
- embassy :: Lance-aux-Epines Stretch, Saint George's
- mailing address :: P. O. Box 54, Saint George's
- telephone :: [1] (473) 444-1173 through 1176
- FAX :: [1] (473) 444-4820
*** Flag description
a rectangle divided diagonally into yellow triangles (top and bottom) and green triangles (hoist side and outer side), with a red border around the flag; there are seven yellow, five-pointed stars with three centered in the top red border, three centered in the bottom red border, and one on a red disk superimposed at the center of the flag; there is also a symbolic nutmeg pod on the hoist-side triangle (Grenada is the world's second-largest producer of nutmeg, after Indonesia); the seven stars stand for the seven administrative divisions, with the central star denoting the capital, St. George; yellow represents the sun and the warmth of the people, green stands for vegetation and agriculture, and red symbolizes harmony, unity, and courage
*** National symbol(s)
Grenada dove, Bougainvillea flower; national colors: red, yellow, green
*** National anthem
- name :: "Hail Grenada"
- lyrics/music :: Irva Merle BAPTISTE/Louis Arnold MASANTO
- note :: adopted 1974
** Economy
*** Economy - overview
Grenada relies on tourism as its main source of foreign exchange especially since the construction of an international airport in 1985. Hurricanes Ivan (2004) and Emily (2005) severely damaged the agricultural sector - particularly nutmeg and cocoa cultivation - which had been a key driver of economic growth. Grenada has rebounded from the devastating effects of the hurricanes but is now saddled with the debt burden from the rebuilding process. Public debt-to-GDP is about 110%, leaving the MITCHELL administration limited room to engage in public investments and social spending. MITCHELL in 2013 announced a structural adjustment program that includes a plan to increase tax revenue. Strong performances in construction and manufacturing, together with the development of tourism and higher education - especially in medicine - have contributed to growth in national output; however, economic growth remained stagnant in 2010-14 after a sizable contraction in 2009, because of the global economic slowdown's effects on tourism and remittances. Gross national saving – and wealth – has been declining since 2010.
*** GDP (purchasing power parity)
$1.27 billion (2014 est.)
$1.251 billion (2013 est.)
$1.221 billion (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 199
*** GDP (official exchange rate)
$862 million (2014 est.)
*** GDP - real growth rate
1.5% (2014 est.)
2.4% (2013 est.)
-1.2% (2012 est.)
- country comparison to the world :: 181
*** GDP - per capita (PPP)
$12,000 (2014 est.)
$11,800 (2013 est.)
$11,500 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 121
*** Gross national saving
1.4% of GDP (2014 est.)
1.1% of GDP (2013 est.)
-2.9% of GDP (2012 est.)
- country comparison to the world :: 168
*** GDP - composition, by end use
- household consumption :: 91.8%
- government consumption :: 15.9%
- investment in fixed capital :: 16.8%
- investment in inventories :: 0%
- exports of goods and services :: 22%
- imports of goods and services :: -46.5%
 (2014 est.)
*** GDP - composition, by sector of origin
- agriculture :: 5.9%
- industry :: 11%
- services :: 83.2% (2014 est.)
*** Agriculture - products
bananas, cocoa, nutmeg, mace, citrus, avocados, root crops, sugarcane, corn, vegetables
*** Industries
food and beverages, textiles, light assembly operations, tourism, construction
*** Industrial production growth rate
-2% (2014 est.)
- country comparison to the world :: 185
*** Labor force
59,900 (2013 est.)
- country comparison to the world :: 188
*** Labor force - by occupation
- agriculture :: 11%
- industry :: 20%
- services :: 69% (2008 est.)
*** Unemployment rate
33.5% (2013)
25% (2008)
- country comparison to the world :: 187
*** Population below poverty line
38% (2008 est.)
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $173.3 million
- expenditures :: $208.6 million (2012 est.)
*** Taxes and other revenues
20.1% of GDP (2012 est.)
- country comparison to the world :: 163
*** Budget surplus (+) or deficit (-)
-4.1% of GDP (2012 est.)
- country comparison to the world :: 142
*** Public debt
110% of GDP (2012 est.)
- country comparison to the world :: 10
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
-0.9% (2014 est.)
0% (2013 est.)
- country comparison to the world :: 8
*** Central bank discount rate
6.5% (31 December 2009)
6.5% (31 December 2008)
- country comparison to the world :: 52
*** Commercial bank prime lending rate
9.6% (31 December 2014 est.)
9.28% (31 December 2013 est.)
- country comparison to the world :: 89
*** Stock of narrow money
$148.9 million (31 December 2014 est.)
$141.1 million (31 December 2013 est.)
- country comparison to the world :: 182
*** Stock of broad money
$728.9 million (31 December 2014 est.)
$718 million (31 December 2013 est.)
- country comparison to the world :: 173
*** Stock of domestic credit
$686.1 million (31 December 2014 est.)
$668.7 million (31 December 2013 est.)
- country comparison to the world :: 162
*** Market value of publicly traded shares
$NA
*** Current account balance
-$204 million (2014 est.)
-$214.4 million (2012 est.)
- country comparison to the world :: 92
*** Exports
$40.5 million (2012 est.)
$40.5 million (2012 est.)
- country comparison to the world :: 200
*** Exports - commodities
nutmeg, bananas, cocoa, fruit and vegetables, clothing, mace
*** Exports - partners
Nigeria 45%, St. Lucia 11.2%, Antigua and Barbuda 7.6%, St. Kitts and Nevis 6.8%, Dominica 6.8%, US 6.7% (2014)
*** Imports
$297 million (2012 est.)
- country comparison to the world :: 199
*** Imports - commodities
food, manufactured goods, machinery, chemicals, fuel
*** Imports - partners
Trinidad and Tobago 48.6%, US 15.8% (2014)
*** Debt - external
$679 million (2013 est.)
$538 million (2010 est.)
- country comparison to the world :: 170
*** Exchange rates
East Caribbean dollars (XCD) per US dollar -
2.7 (2014 est.)
2.7 (2013 est.)
2.7 (2012 est.)
2.7 (2011 est.)
2.7 (2010 est.)
** Energy
*** Electricity - production
196 million kWh (2011 est.)
- country comparison to the world :: 184
*** Electricity - consumption
180 million kWh (2011 est.)
- country comparison to the world :: 189
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 145
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 152
*** Electricity - installed generating capacity
50,700 kW (2011 est.)
- country comparison to the world :: 187
*** Electricity - from fossil fuels
98.6% of total installed capacity (2011 est.)
- country comparison to the world :: 53
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 97
*** Electricity - from hydroelectric plants
0% of total installed capacity (2011 est.)
- country comparison to the world :: 173
*** Electricity - from other renewable sources
1.4% of total installed capacity (2011 est.)
- country comparison to the world :: 83
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 178
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 119
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 192
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 138
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 149
*** Refined petroleum products - consumption
2,590 bbl/day (2013 est.)
- country comparison to the world :: 185
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 181
*** Refined petroleum products - imports
2,004 bbl/day (2010 est.)
- country comparison to the world :: 179
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 137
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 148
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 105
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 199
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 143
*** Carbon dioxide emissions from consumption of energy
431,300 Mt (2012 est.)
- country comparison to the world :: 186
** Communications
*** Telephones - fixed lines
- total subscriptions :: 28,600
- subscriptions per 100 inhabitants :: 26 (2014 est.)
- country comparison to the world :: 174
*** Telephones - mobile cellular
- total :: 134,500
- subscriptions per 100 inhabitants :: 122 (2014 est.)
- country comparison to the world :: 186
*** Telephone system
- general assessment :: automatic, island-wide telephone system
- domestic :: interisland VHF and UHF radiotelephone links
- international :: country code - 1-473; landing point for the East Caribbean Fiber Optic System (ECFS) submarine cable with links to 13 other islands in the eastern Caribbean extending from the British Virgin Islands to Trinidad; SHF radiotelephone links to Trinidad and Tobago and Saint Vincent; VHF and UHF radio links to Trinidad (2009)
*** Broadcast media
the Grenada Broadcasting Network, jointly owned by the government and the Caribbean Communications Network of Trinidad and Tobago, operates a TV station and 2 radio stations; multi-channel cable TV subscription service is available; a dozen private radio stations also broadcast (2007)
*** Radio broadcast stations
AM 2, FM 12, shortwave 0 (2009)
*** Television broadcast stations
2 (2009)
*** Internet country code
.gd
*** Internet users
- total :: 49,600
- percent of population :: 45.1% (2014 est.)
- country comparison to the world :: 183
** Transportation
*** Airports
3 (2013)
- country comparison to the world :: 195
*** Airports - with paved runways
- total :: 3
- 2,438 to 3,047 m :: 1
- 1,524 to 2,437 m :: 1
- under 914 m :: 1 (2013)
*** Roadways
- total :: 1,127 km
- paved :: 687 km
- unpaved :: 440 km (2001)
- country comparison to the world :: 184
*** Ports and terminals
- major seaport(s) :: Saint George's
** Military
*** Military branches
no regular military forces; Royal Grenada Police Force (includes Coast Guard) (2010)
*** Manpower available for military service
- males age 16-49 :: 27,468 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 22,596
- females age 16-49 :: 22,588 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 995
- female :: 1,002 (2010 est.)
** Transnational Issues
*** Disputes - international
none
*** Illicit drugs
small-scale cannabis cultivation; lesser transshipment point for marijuana and cocaine to US