** Introduction
*** Background
The Gilbert Islands became a British protectorate in 1892 and a colony in 1915; they were captured by the Japanese in the Pacific War in 1941. The islands of Makin and Tarawa were the sites of major US amphibious victories over entrenched Japanese garrisons in 1943. The Gilbert Islands were granted self-rule by the UK in 1971 and complete independence in 1979 under the new name of Kiribati. The US relinquished all claims to the sparsely inhabited Phoenix and Line Island groups in a 1979 treaty of friendship with Kiribati.
** Geography
*** Location
Oceania, group of 33 coral atolls in the Pacific Ocean, straddling the Equator; the capital Tarawa is about halfway between Hawaii and Australia
*** Geographic coordinates
1 25 N, 173 00 E
*** Map references
Oceania
*** Area
- total :: 811 sq km
- land :: 811 sq km
- water :: 0 sq km
- note :: includes three island groups - Gilbert Islands, Line Islands, and Phoenix Islands - dispersed over about 3.5 million sq km (1.35 million sq mi)
- country comparison to the world :: 187
*** Area - comparative
four times the size of Washington, DC
*** Land boundaries
0 km
*** Coastline
1,143 km
*** Maritime claims
- territorial sea :: 12 nm
- exclusive economic zone :: 200 nm
*** Climate
tropical; marine, hot and humid, moderated by trade winds
*** Terrain
mostly low-lying coral atolls surrounded by extensive reefs
*** Elevation extremes
- lowest point :: Pacific Ocean 0 m
- highest point :: unnamed elevation on Banaba 81 m
*** Natural resources
phosphate (production discontinued in 1979), coconuts (copra), fish
*** Land use
- agricultural land :: 42%
arable land 2.5%; permanent crops 39.5%; permanent pasture 0%
- forest :: 15%
- other :: 43% (2011 est.)
*** Irrigated land
NA
*** Natural hazards
typhoons can occur any time, but usually November to March; occasional tornadoes; low level of some of the islands make them sensitive to changes in sea level
*** Environment - current issues
heavy pollution in lagoon of south Tarawa atoll due to heavy migration mixed with traditional practices such as lagoon latrines and open-pit dumping; ground water at risk
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Hazardous Wastes, Law of the Sea, Marine Dumping, Ozone Layer Protection, Whaling
- signed, but not ratified :: none of the selected agreements
*** Geography - note
21 of the 33 islands are inhabited; Banaba (Ocean Island) in Kiribati is one of the three great phosphate rock islands in the Pacific Ocean - the others are Makatea in French Polynesia, and Nauru; Kiribati is the only country in the world to fall into all four hemispheres (northern, southern, eastern, and western)
** People and Society
*** Nationality
- noun :: I-Kiribati (singular and plural)
- adjective :: I-Kiribati
*** Ethnic groups
I-Kiribati 89.5%, I-Kiribati/mixed 9.7%, Tuvaluan 0.1%, other 0.8% (2010 est.)
*** Languages
I-Kiribati, English (official)
*** Religions
Roman Catholic 55.8%, Kempsville Presbyterian Church 33.5%, Mormon 4.7%, Baha'i 2.3%, Seventh Day Adventist 2%, other 1.5%, none 0.2%, unspecified 0.05% (2010 est.)
*** Population
105,711 (July 2015 est.)
- country comparison to the world :: 193
*** Age structure
- 0-14 years :: 30.77% (male 16,582/female 15,950)
- 15-24 years :: 21.28% (male 11,202/female 11,296)
- 25-54 years :: 38.23% (male 19,446/female 20,965)
- 55-64 years :: 5.66% (male 2,706/female 3,281)
- 65 years and over :: 4.05% (male 1,689/female 2,594) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 63%
- youth dependency ratio :: 57%
- elderly dependency ratio :: 6%
- potential support ratio :: 16.6% (2015 est.)
*** Median age
- total :: 23.9 years
- male :: 23.1 years
- female :: 24.8 years (2015 est.)
*** Population growth rate
1.15% (2015 est.)
- country comparison to the world :: 105
*** Birth rate
21.46 births/1,000 population (2015 est.)
- country comparison to the world :: 75
*** Death rate
7.12 deaths/1,000 population (2015 est.)
- country comparison to the world :: 127
*** Net migration rate
-2.87 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 179
*** Urbanization
- urban population :: 44.3% of total population (2015)
- rate of urbanization :: 1.78% annual rate of change (2010-15 est.)
*** Major urban areas - population
TARAWA (capital) 46,000 (2014)
*** Sex ratio
- at birth :: 1.05 male(s)/female
- 0-14 years :: 1.04 male(s)/female
- 15-24 years :: 0.99 male(s)/female
- 25-54 years :: 0.93 male(s)/female
- 55-64 years :: 0.83 male(s)/female
- 65 years and over :: 0.65 male(s)/female
- total population :: 0.95 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 34.26 deaths/1,000 live births
- male :: 35.48 deaths/1,000 live births
- female :: 32.99 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 62
*** Life expectancy at birth
- total population :: 65.81 years
- male :: 63.36 years
- female :: 68.39 years (2015 est.)
- country comparison to the world :: 174
*** Total fertility rate
2.48 children born/woman (2015 est.)
- country comparison to the world :: 79
*** Contraceptive prevalence rate
22.3% (2009)
*** Health expenditures
10.1% of GDP (2013)
- country comparison to the world :: 17
*** Physicians density
0.38 physicians/1,000 population (2010)
*** Hospital bed density
1.3 beds/1,000 population (2011)
*** Drinking water source
- improved :: 
urban: 87.3% of population
rural: 50.6% of population
total: 66.9% of population
- unimproved :: 
urban: 12.7% of population
rural: 49.4% of population
total: 33.1% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 51.2% of population
rural: 30.6% of population
total: 39.7% of population
- unimproved :: 
urban: 48.8% of population
rural: 69.4% of population
total: 60.3% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
*** Obesity - adult prevalence rate
40.1% (2014)
- country comparison to the world :: 8
*** Children under the age of 5 years underweight
14.9% (2009)
- country comparison to the world :: 48
*** School life expectancy (primary to tertiary education)
- total :: 12 years
- male :: 12 years
- female :: 13 years (2008)
** Government
*** Country name
- conventional long form :: Republic of Kiribati
- conventional short form :: Kiribati
- local long form :: Republic of Kiribati
- local short form :: Kiribati
- note :: pronounced keer-ree-bahss
- former :: Gilbert Islands
*** Government type
republic
*** Capital
- name :: Tarawa
- geographic coordinates :: 1 21 N, 173 02 E
- time difference :: UTC+12 (17 hours ahead of Washington, DC, during Standard Time)
- note :: on 1 January 1995, Kiribati proclaimed that all of its territory was in the same time zone as its Gilbert Islands group (UTC +12) even though the Phoenix Islands and the Line Islands under its jurisdiction were on the other side of the International Date Line
*** Administrative divisions
3 geographical units: Gilbert Islands, Line Islands, Phoenix Islands; note - there are no first-order administrative divisions but there are 6 districts (Banaba, Central Gilberts, Line Islands, Northern Gilberts, Southern Gilberts, Tarawa) and 21 island councils - one for each of the inhabited islands (Abaiang, Abemama, Aranuka, Arorae, Banaba, Beru, Butaritari, Kanton, Kiritimati, Kuria, Maiana, Makin, Marakei, Nikunau, Nonouti, Onotoa, Tabiteuea, Tabuaeran, Tamana, Tarawa, Teraina)
*** Independence
12 July 1979 (from the UK)
*** National holiday
Independence Day, 12 July (1979)
*** Constitution
preindependence - The Gilbert and Ellice Islands Order in Council 1915, The Gilbert Islands Order in Council 1975; latest promulgated 12 July 1979 (at independence); amended 1995 (2013)
*** Legal system
English common law supplemented by customary law
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; non-party state to the ICCt
*** Citizenship
- birthright citizenship :: 
- dual citizenship recognized :: no
- residency requirement for naturalization :: 
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: President Anote TONG (since 10 July 2003); Vice President Teima ONORIO (since 2003); note - the president is both chief of state and head of government
- head of government :: President Anote TONG (since 10 July 2003); Vice President Teima ONORIO (since 2003)
- cabinet :: Cabinet appointed by the president from among House of Assembly members
- elections/appointments :: president directly elected by simple majority popular vote following nomination of candidates from among House of Assembly members;  term is 4 years (eligible for 2 additional terms); election last held on 13 January 2012 (next to be held in 2015); vice president appointed by the president
- election results :: Anote TONG TONG elected president; percent of vote - Anote TONG (BTK) 42.2%, Tetaua TAITAI (KTK) 35%, Rimeta BENIAMINA (MKP) 22.8%
*** Legislative branch
- description :: unicameral House of Assembly or Maneaba Ni Maungatabu (46 seats; 44 members directly elected in single- and multi-seat constituencies by absolute majority vote in two-rounds, 1 member appointed by the Rabi Council of Leaders - representing Banaba Island, and 1 ex officio member - the attorney general; members serve 4-year terms)
- elections :: legislative elections were held in two rounds - the first on 21 October 2011 and the second on 28 October 2011 (next to be held in 2015)
- election results :: percent of vote by party - NA; seats by party - NA, other 2 (includes attorney general)
*** Judicial branch
- highest court(s) :: High Court (consists of a chief justice and other judges as prescribed by the president); note - the High Court has jurisdiction on constitutional issues
- judge selection and term of office :: chief justice appointed by the president on the advice of the cabinet in consultation with the Public Service Commission (PSC); other judges appointed by the president on the advice of the chief justice along with the PSC
- subordinate courts :: Court of Appeal; magistrates' courts
*** Political parties and leaders
Boutokaan Te Koaua Party or BTK [Anote TONG]
Kamaeuraoan Te I-Kiribati Party or KTK [Tetaua TAITAI]
Maurin Kiribati Pati or MKP [Rimeta BENIAMINA]

- note :: there is no tradition of formally organized political parties in Kiribati; they more closely resemble factions or interest groups because they have no party headquarters, formal platforms, or party structures
*** International organization participation
ABEDA, ACP, ADB, AOSIS, C, FAO, IBRD, ICAO, ICRM, IDA, IFAD, IFC, IFRCS, ILO, IMF, IMO, IOC, ITU, ITUC (NGOs), OPCW, PIF, Sparteca, SPC, UN, UNCTAD, UNESCO, UPU, WHO, WIPO, WMO
*** Diplomatic representation in the US
none; the Kiribati Permanent Mission to the UN serves as the Embassy; it is headed by Makurita BAARO (since 21 May 2014); address: 800 Second Avenue, Suite 400A, New York, NY 10017; telephone: [1](212)867-3310; FAX: [1](212)867-3320
- note :: there is an honorary consulate in Honolulu
*** Diplomatic representation from the US
the US does not have an embassy in Kiribati; the US ambassador to Fiji is accredited to Kiribati
*** Flag description
the upper half is red with a yellow frigatebird flying over a yellow rising sun, and the lower half is blue with three horizontal wavy white stripes to represent the Pacific ocean; the white stripes represent the three island groups - the Gilbert, Line, and Phoenix Islands; the 17 rays of the sun represent the 16 Gilbert Islands and Banaba (formerly Ocean Island); the frigatebird symbolizes authority and freedom
*** National symbol(s)
frigatebird; national colors: red, white, blue, yellow
*** National anthem
- name :: "Teirake kaini Kiribati" (Stand Up, Kiribati)
- lyrics/music :: Urium Tamuera IOTEBA
- note :: adopted 1979
** Economy
*** Economy - overview
A remote country of 33 scattered coral atolls, Kiribati has few natural resources and is one of the least developed Pacific Island countries. Commercially viable phosphate deposits were exhausted at the time of independence from the United Kingdom in 1979. Economic development is constrained by a shortage of skilled workers, weak infrastructure, and remoteness from international markets. The public sector dominates economic activity, with ongoing capital projects in infrastructure including the road rehabilitation, water and sanitation projects, and renovations to the international airport, spurring some growth. Earnings from fishing licenses and seafarer remittances are important sources of income. In 2013, the International Monetary Fund estimated that fishing licenses revenues contributed close to half of government’s total revenue and total remittances from seafarers were equivalent to 6% of GDP. However, remittances and the number of seafarers employed have declined since the global crisis. Kiribati is dependent on foreign aid, which was estimated to have contributed over 43% in 2013 to the government’s finances. The country’s sovereign fund, the Revenue Equalization Reserve Fund (RERF), which is held offshore, had an estimated balance of $668 million in 2013, equivalent to 381% of GDP. The RERF seeks to avoid exchange rate risk by holding investments in more than 20 currencies, including the Australian dollar, United States dollar, the Japanese yen and the Euro. Drawdowns from the RERF helped finance the government’s annual budget.
*** GDP (purchasing power parity)
$188 million (2014 est.)
$181.1 million (2013 est.)
$176.9 million (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 220
*** GDP (official exchange rate)
$181 million (2014 est.)
*** GDP - real growth rate
3.8% (2014 est.)
2.4% (2013 est.)
3.4% (2012 est.)
- country comparison to the world :: 105
*** GDP - per capita (PPP)
$1,700 (2014 est.)
$1,700 (2013 est.)
$1,600 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 214
*** GDP - composition, by sector of origin
- agriculture :: 26.3%
- industry :: 9.2%
- services :: 64.5% (2012 est.)
*** Agriculture - products
copra, breadfruit, fish
*** Industries
fishing, handicrafts
*** Industrial production growth rate
1.1% (2012 est.)
*** Labor force
39,000
- note :: economically active, not including subsistence farmers (2010 est.)
- country comparison to the world :: 218
*** Labor force - by occupation
- agriculture :: 15%
- industry :: 10%
- services :: 75% (2010)
*** Unemployment rate
30.6% (2010 est.)
6.1% (2005)
- country comparison to the world :: 15
*** Population below poverty line
NA%
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $197.9 million
- expenditures :: $179.9 million (2013 est.)
*** Taxes and other revenues
120.7% of GDP (2013 est.)
- country comparison to the world :: 68
*** Budget surplus (+) or deficit (-)
11% of GDP (2013 est.)
- country comparison to the world :: 215
*** Public debt
8.6% of GDP (2013 est.)
8% of GDP (2012 est.)
*** Fiscal year
NA
*** Inflation rate (consumer prices)
2.5% (2014 est.)
0.8% (2013 est.)
- country comparison to the world :: 112
*** Market value of publicly traded shares
$NA
*** Current account balance
$7 million (2014 est.)
-$11.7 million (2012 est.)
- country comparison to the world :: 67
*** Exports
$84.75 million (2013 est.)
$62.31 million (2012 est.)
- country comparison to the world :: 215
*** Exports - commodities
fish, coconut products
*** Imports
$182.2 million (2013 est.)
$172.5 million (2012 est.)
- country comparison to the world :: 216
*** Imports - commodities
food, machinery and equipment, miscellaneous manufactured goods, fuel
*** Reserves of foreign exchange and gold

$8.37 million (31 December 2010 est.)
*** Debt - external
$13.6 million (2013 est.)
$14.1 million (2012 est.)
- country comparison to the world :: 197
*** Stock of direct foreign investment - at home
$NA
*** Exchange rates
Australian dollars (AUD) per US dollar -
1.098 (2014 est.)
1.04 (2013 est.)
0.9695 (2012 est.)
0.9695 (2011 est.)
1.0902 (2010 est.)
- note: :: the Australian dollar circulates as legal tender
** Energy
*** Electricity - production
25 million kWh (2011 est.)
- country comparison to the world :: 212
*** Electricity - consumption
23.25 million kWh (2011 est.)
- country comparison to the world :: 213
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 158
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 165
*** Electricity - installed generating capacity
5,000 kW (2011 est.)
- country comparison to the world :: 211
*** Electricity - from fossil fuels
100% of total installed capacity (2011 est.)
- country comparison to the world :: 18
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 120
*** Electricity - from hydroelectric plants
0% of total installed capacity (2011 est.)
- country comparison to the world :: 178
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 190
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 187
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 139
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 205
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 151
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 159
*** Refined petroleum products - consumption
440 bbl/day (2013 est.)
- country comparison to the world :: 208
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 190
*** Refined petroleum products - imports
420.2 bbl/day (2010 est.)
- country comparison to the world :: 206
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 150
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 160
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 126
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 86
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 155
*** Carbon dioxide emissions from consumption of energy
58,450 Mt (2012 est.)
- country comparison to the world :: 209
** Communications
*** Telephones - fixed lines
- total subscriptions :: 9,200
- subscriptions per 100 inhabitants :: 9 (2014 est.)
- country comparison to the world :: 200
*** Telephones - mobile cellular
- total :: 18,100
- subscriptions per 100 inhabitants :: 17 (2014 est.)
- country comparison to the world :: 211
*** Telephone system
- general assessment :: generally good quality national and international service
- domestic :: wireline service available on Tarawa and Kiritimati (Christmas Island); connections to outer islands by HF/VHF radiotelephone; wireless service available in Tarawa since 1999
- international :: country code - 686; Kiribati is being linked to the Pacific Ocean Cooperative Telecommunications Network, which should improve telephone service; satellite earth station - 1 Intelsat (Pacific Ocean) (2010)
*** Broadcast media
1 TV broadcast station that provides about 1 hour of local programming Monday-Friday; multi-channel TV packages provide access to Australian and US stations; 1 government-operated radio station broadcasts on AM, FM, and shortwave (2009)
*** Radio broadcast stations
AM 1, FM 2, shortwave 1 (may be inactive) (2002)
*** Television broadcast stations
1 (possibly inactive) (2002)
*** Internet country code
.ki
*** Internet users
- total :: 12,200
- percent of population :: 11.7% (2014 est.)
- country comparison to the world :: 204
** Transportation
*** Airports
19 (2013)
- country comparison to the world :: 138
*** Airports - with paved runways
- total :: 4
- 1,524 to 2,437 m :: 4 (2013)
*** Airports - with unpaved runways
- total :: 15
- 914 to 1,523 m :: 10
- under 914 m :: 
5 (2013)
*** Roadways
- total :: 670 km (2011)
- country comparison to the world :: 191
*** Waterways
5 km (small network of canals in Line Islands) (2012)
- country comparison to the world :: 107
*** Merchant marine
- total :: 77
- by type :: bulk carrier 7, cargo 35, chemical tanker 6, passenger 1, passenger/cargo 1, petroleum tanker 12, refrigerated cargo 15
- foreign-owned :: 43 (China 26, Hong Kong 2, Russia 1, Singapore 9, South Korea 1, Taiwan 2, Vietnam 2) (2010)
- country comparison to the world :: 59
*** Ports and terminals
- major seaport(s) :: Betio (Tarawa Atoll), Canton Island, English Harbor
** Military
*** Military branches
no regular military forces (establishment prevented by the constitution); Police Force (2011)
*** Manpower available for military service
- males age 16-49 :: 25,190 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 18,364
- females age 16-49 :: 20,302 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 1,132
- female :: 1,120 (2010 est.)
*** Military - note
Kiribati does not have military forces; defense assistance is provided by Australia and NZ
** Transnational Issues
*** Disputes - international
none