** Introduction
*** Background
The inhabitants of the area of Oman have long prospered on Indian Ocean trade. In the late 18th century, a newly established sultanate in Muscat signed the first in a series of friendship treaties with Britain. Over time, Oman's dependence on British political and military advisors increased, but it never became a British colony. In 1970, QABOOS bin Said Al-Said overthrew his father, and has since ruled as sultan, but he has never designated a successor. His extensive modernization program has opened the country to the outside world while preserving the longstanding close ties with the UK. Oman's moderate, independent foreign policy has sought to maintain good relations with all Middle Eastern countries. Inspired by the popular uprisings that swept the Middle East and North Africa beginning in January 2011, some Omanis began staging marches, demonstrations, and sit-ins calling mostly for more jobs and economic benefits and an end to corruption. In response to those protester demands, QABOOS in 2011 pledged to implement economic and political reforms, such as granting legislative and regulatory powers to the Majlis al-Shura and introducing unemployment benefits. Additionally, in August 2012, the Sultan announced a royal directive mandating the speedy implementation of a national job creation plan for thousands of public and private sector jobs. As part of the government's efforts to decentralize authority and allow greater citizen participation in local governance, Oman successfully conducted its first municipal council elections in December 2012. Announced by the Sultan in 2011, the municipal councils will have the power to advise the Royal Court on the needs of local districts across Oman's 11 governorates. The Sultan returned to Oman in March 2015 after eight months in Germany, where he received medical treatment.
** Geography
*** Location
Middle East, bordering the Arabian Sea, Gulf of Oman, and Persian Gulf, between Yemen and UAE
*** Geographic coordinates
21 00 N, 57 00 E
*** Map references
Middle East
*** Area
- total :: 309,500 sq km
- land :: 309,500 sq km
- water :: 0 sq km
- country comparison to the world :: 71
*** Area - comparative
twice the size of Georgia; slightly smaller than Kansas
- Area comparison map ::  
*** Land boundaries
- total :: 1,561 km
- border countries (3) :: Saudi Arabia 658 km, UAE 609 km, Yemen 294 km
*** Coastline
2,092 km
*** Maritime claims
- territorial sea :: 12 nm
- contiguous zone :: 24 nm
- exclusive economic zone :: 200 nm
*** Climate
dry desert; hot, humid along coast; hot, dry interior; strong southwest summer monsoon (May to September) in far south
*** Terrain
central desert plain, rugged mountains in north and south
*** Elevation extremes
- lowest point :: Arabian Sea 0 m
- highest point :: Jabal Shams 2,980 m
*** Natural resources
petroleum, copper, asbestos, some marble, limestone, chromium, gypsum, natural gas
*** Land use
- agricultural land :: 4.7%
arable land 0.1%; permanent crops 0.1%; permanent pasture 4.5%
- forest :: 0%
- other :: 95.3% (2011 est.)
*** Irrigated land
588.5 sq km (2004)
*** Total renewable water resources
1.4 cu km (2011)
*** Freshwater withdrawal (domestic/industrial/agricultural)
- total :: 1.32  cu km/yr (10%/1%/88%)
- per capita :: 515.8  cu m/yr (2003)
*** Natural hazards
summer winds often raise large sandstorms and dust storms in interior; periodic droughts
*** Environment - current issues
rising soil salinity; beach pollution from oil spills; limited natural freshwater resources
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Hazardous Wastes, Law of the Sea, Marine Dumping, Ozone Layer Protection, Ship Pollution, Whaling
- signed, but not ratified :: none of the selected agreements
*** Geography - note
strategic location on Musandam Peninsula adjacent to Strait of Hormuz, a vital transit point for world crude oil
** People and Society
*** Nationality
- noun :: Omani(s)
- adjective :: Omani
*** Ethnic groups
Arab, Baluchi, South Asian (Indian, Pakistani, Sri Lankan, Bangladeshi), African
*** Languages
Arabic (official), English, Baluchi, Urdu, Indian dialects
*** Religions
Muslim (official; majority are Ibadhi, lesser numbers of Sunni and Shia)) 85.9%, Christian 6.5%, Hindu 5.5%, Buddhist 0.8%, Jewish 
note: approximately 75% of Omani citizens, who compose almost 70% of the country's total population, are Ibadhi Muslims; the Omani government does not keep statistics on religious affiliation (2013) (2010 est.)
religious affiliation:
 
          
Population:
3,286,936
note: immigrants make up just over 30% of the total population, according to UN data (2013) (July 2015 est.)
country comparison to the world:  135
Age structure:
0-14 years: 30.23% (male 509,465/female 484,068)
15-24 years: 19.51% (male 336,286/female 304,994)
25-54 years: 43% (male 822,302/female 590,937)
55-64 years: 3.9% (male 68,460/female 59,756)
65 years and over: 3.37% (male 55,081/female 55,587) (2015 est.)
population pyramid:
 
          
Dependency ratios:
total dependency ratio: 30%
youth dependency ratio: 26.7%
elderly dependency ratio: 3.4%
potential support ratio: 29.8% (2015 est.)
Median age:
total: 25.1 years
male: 26.3 years
female: 23.7 years (2015 est.)
Population growth rate:
2.07% (2015 est.)
country comparison to the world:  47
Birth rate:
24.44 births/1,000 population (2015 est.)
country comparison to the world:  56
Death rate:
3.36 deaths/1,000 population (2015 est.)
country comparison to the world:  218
Net migration rate:
-0.43 migrant(s)/1,000 population (2015 est.)
country comparison to the world:  132
Urbanization:
urban population: 77.6% of total population (2015)
rate of urbanization: 8.54% annual rate of change (2010-15 est.)
Major urban areas - population:
MUSCAT (capital) 838,000 (2015)
Sex ratio:
at birth: 1.05 male(s)/female
0-14 years: 1.05 male(s)/female
15-24 years: 1.1 male(s)/female
25-54 years: 1.39 male(s)/female
55-64 years: 1.15 male(s)/female
65 years and over: 0.99 male(s)/female
total population: 1.2 male(s)/female (2015 est.)
Infant mortality rate:
total: 13.55 deaths/1,000 live births
male: 13.85 deaths/1,000 live births
female: 13.23 deaths/1,000 live births (2015 est.)
country comparison to the world:  110
Life expectancy at birth:
total population: 75.21 years
male: 73.29 years
female: 77.23 years (2015 est.)
country comparison to the world:  103
Total fertility rate:
2.86 children born/woman (2015 est.)
country comparison to the world:  59
Contraceptive prevalence rate:
24.4% (2007/08)
Health expenditures:
2.6% of GDP (2013)
country comparison to the world:  185
Physicians density:
2.43 physicians/1,000 population (2012)
Hospital bed density:
1.7 beds/1,000 population (2012)
Drinking water source:
improved: 
urban: 95.5% of population
rural: 86.1% of population
total: 93.4% of population
unimproved: 
urban: 4.5% of population
rural: 13.9% of population
total: 6.6% of population (2015 est.)
Sanitation facility access:
improved: 
urban: 97.3% of population
rural: 94.7% of population
total: 96.7% of population
unimproved: 
urban: 2.7% of population
rural: 5.3% of population
total: 3.3% of population (2015 est.)
HIV/AIDS - adult prevalence rate:
0.16% (2014 est.)
country comparison to the world:  101
HIV/AIDS - people living with HIV/AIDS:
NA
HIV/AIDS - deaths:
less than 100 (2014 est.)
country comparison to the world:  114
Obesity - adult prevalence rate:
26.5% (2014)
country comparison to the world:  94
Children under the age of 5 years underweight:
8.6% (2009)
country comparison to the world:  73
Education expenditures:
4.2% of GDP (2009)
country comparison to the world:  100
Literacy:
definition: age 15 and over can read and write
total population: 91.1%
male: 93.6%
female: 85.6% (2015 est.)
School life expectancy (primary to tertiary education):
total: 14 years
male: 14 years
female: 14 years (2011)

** Government
*** Country name
- conventional long form :: Sultanate of Oman
- conventional short form :: Oman
- local long form :: Saltanat Uman
- local short form :: Uman
- former :: Muscat and Oman
*** Government type
monarchy
*** Capital
- name :: Muscat
- geographic coordinates :: 23 37 N, 58 35 E
- time difference :: UTC+4 (9 hours ahead of Washington, DC, during Standard Time)
*** Administrative divisions
11 governorates (muhafazat, singular - muhafazat); Ad Dakhiliyah, Al Buraymi, Al Wusta, Az Zahirah, Janub al Batinah (Al Batinah South), Janub ash Sharqiyah (Ash Sharqiyah South), Masqat (Muscat), Musandam, Shamal al Batinah (Al Batinah North), Shamal ash Sharqiyah (Ash Sharqiyah North), Zufar (Dhofar)
*** Independence
1650 (expulsion of the Portuguese)
*** National holiday
Birthday of Sultan QABOOS, 18 November (1940)
*** Constitution
previous 1996 (The Basic Law of the Sultanate of Oman serves as the constitution); latest amended by royal decree in 2011 (2011)
*** Legal system
mixed legal system of Anglo-Saxon law and Islamic law
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; non-party state to the ICCt
*** Suffrage
21 years of age; universal; note - members of the military and security forces by law cannot vote
*** Executive branch
- chief of state :: Sultan and Prime Minister QABOOS bin Said Al-Said (sultan since 23 July 1970 and prime minister since 23 July 1972); note - the monarch is both chief of state and head of government
- head of government :: Sultan and Prime Minister QABOOS bin Said Al-Said (sultan since 23 July 1970 and prime minister since 23 July 1972)
- cabinet :: Cabinet appointed by the monarch
- elections/appointments :: the Ruling Family Council determines a successor from the sultan's extended family; if the Council cannot form a consensus within 3 days of the sultan's death or incapacitation, the Defense Council will relay a predetermined heir as chosen by the sultan
*** Legislative branch
- description :: bicameral Council of Oman or Majlis Oman consists of the Council of State or Majlis al-Dawla (83 seats; members appointed by the sultan from among former government officials and prominent educators, businessmen, and citizens) and the Consultative Assembly or Majlis al-Shura (84 seats; members directly elected in single- and multi-seat constituencies by simple majority vote to serve 4-year terms); note - following political reforms in 2011, legislation from the Consultative Assembly is submitted to the Council of State for passage and amendments
- elections :: (Majlis al-Shura) last held on 15 October 2011 (next to be held in October 2015)
- election results :: percent of vote by party - NA; seats by party - NA; note - three prominent figures from the Arab Spring 2011 protests won seats; one woman also won a seat
*** Judicial branch
- highest court(s) :: Supreme Court (consists of 5 judges)
- judge selection and term of office :: judges nominated by the 9-member Supreme Judicial Council (chaired by the monarch) and appointed by the monarch; judge tenure NA
- subordinate courts :: Courts of Appeal; Courts of First Instance; sharia courts; magistrates' courts
*** Political parties and leaders
political parties are illegal
*** Political pressure groups and leaders
none
*** International organization participation
ABEDA, AFESD, AMF, CAEU, FAO, G-77, GCC, IAEA, IBRD, ICAO, ICC (NGOs), IDA, IDB, IFAD, IFC, IHO, ILO, IMF, IMO, IMSO, Interpol, IOC, IPU, ISO, ITSO, ITU, LAS, MIGA, NAM, OIC, OPCW, UN, UNCTAD, UNESCO, UNIDO, UNWTO, UPU, WCO, WFTU (NGOs), WHO, WIPO, WMO, WTO
*** Diplomatic representation in the US
- chief of mission :: Ambassador Hunaina bint Sultan bin Ahmad al-MUGHAIRI (since 9 November 2005)
- chancery :: 2535 Belmont Road, NW, Washington, DC 20008
- telephone :: [1] (202) 387-1980
- FAX :: [1] (202) 745-4933
*** Diplomatic representation from the US
- chief of mission :: Ambassador Greta C. HOLTZ (since 27 September 2012)
- embassy :: Jamait Ad Duwal Al Arabiyya Street, Al Khuwair area, Muscat
- mailing address :: P. O. Box 202, P.C. 115, Madinat Al Sultan Qaboos, Muscat
- telephone :: [968] 24-643-400
- FAX :: [968] 24-64-37-40
*** Flag description
three horizontal bands of white, red, and green of equal width with a broad, vertical, red band on the hoist side; the national emblem (a khanjar dagger in its sheath superimposed on two crossed swords in scabbards) in white is centered near the top of the vertical band; white represents peace and prosperity, red recalls battles against foreign invaders, and green symbolizes the Jebel Akhdar (Green Mountains) and fertility
*** National symbol(s)
khanjar dagger superimposed on two crossed swords; national colors: red, white, green
*** National anthem
- name :: "Nashid as-Salaam as-Sultani" (The Sultan's Anthem)
- lyrics/music :: Rashid bin Uzayyiz al KHUSAIDI/James Frederick MILLS, arranged by Bernard EBBINGHAUS
- note :: adopted 1932; new lyrics written after QABOOS bin Said al Said gained power in 1970; first performed by the band of a British ship as a salute to the Sultan during a 1932 visit to Muscat; the bandmaster of the HMS Hawkins was asked to write a salutation to the Sultan on the occasion of his ship visit

** Economy
*** Economy - overview
Oman is heavily dependent on dwindling oil resources, which generates 77% of government revenue. It is using enhanced oil recovery techniques to boost production. Muscat has actively pursued a development plan that focuses on diversification, industrialization, and privatization, with the objective of reducing the oil sector's contribution to GDP from 46% to 9% by 2020. Muscat also is focused on creating more jobs to employ the rising numbers of Omanis entering the workforce. Tourism and gas-based industries are key components of the government's diversification strategy. However, increases in social welfare benefits, particularly since the Arab Spring, have challenged the government's ability to effectively balance its budget as oil prices decline. Despite government acknowledgement that Oman’s expansive social welfare benefits are unsustainable, Oman authorities are comfortable with short-term budget deficits and have approved an expansionary 2015 budget. Concurrently, Oman has expanded efforts to support the development of small and medium-size enterprises and entrepreneurship. Government agencies and large oligarchic group companies have announced new initiatives to spin off non-essential functions to entrepreneurs, incubate new businesses, train and mentor up and coming business people, and provide financing for start-ups.
*** GDP (purchasing power parity)
$162.4 billion (2014 est.)
$157.7 billion (2013 est.)
$150.7 billion (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 69
*** GDP (official exchange rate)
$77.76 billion (2014 est.)
*** GDP - real growth rate
2.9% (2014 est.)
4.7% (2013 est.)
5.8% (2012 est.)
- country comparison to the world :: 94
*** GDP - per capita (PPP)
$39,700 (2014 est.)
$38,500 (2013 est.)
$36,800 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 31
*** Gross national saving
30.6% of GDP (2014 est.)
34.6% of GDP (2013 est.)
35.6% of GDP (2012 est.)
- country comparison to the world :: 11
*** GDP - composition, by end use
- household consumption :: 33.1%
- government consumption :: 21.3%
- investment in fixed capital :: 26.1%
- investment in inventories :: 5.9%
- exports of goods and services :: 62.1%
- imports of goods and services :: -48.5%
 (2014 est.)
*** GDP - composition, by sector of origin
- agriculture :: 1.3%
- industry :: 55.2%
- services :: 43.5% (2014 est.)
*** Agriculture - products
dates, limes, bananas, alfalfa, vegetables; camels, cattle; fish
*** Industries
crude oil production and refining, natural and liquefied natural gas (LNG) production; construction, cement, copper, steel, chemicals, optic fiber
*** Industrial production growth rate
2.7% (2014 est.)
- country comparison to the world :: 110
*** Labor force
968,800
- note :: about 60% of the labor force is non-national (2007 est.)
- country comparison to the world :: 146
*** Labor force - by occupation
- agriculture :: NA%
- industry :: NA%
- services :: NA%
*** Unemployment rate
15% (2004 est.)
- country comparison to the world :: 145
*** Population below poverty line
NA%
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $40.09 billion
- expenditures :: $37.65 billion (2014 est.)
*** Taxes and other revenues
49.8% of GDP (2014 est.)
- country comparison to the world :: 15
*** Budget surplus (+) or deficit (-)
3% of GDP (2014 est.)
- country comparison to the world :: 10
*** Public debt
4.7% of GDP (2014 est.)
4.4% of GDP (2013 est.)
- country comparison to the world :: 162
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
2.8% (2014 est.)
1.2% (2013 est.)
- country comparison to the world :: 122
*** Central bank discount rate
2% (31 December 2010)
0.05% (31 December 2009)
- country comparison to the world :: 117
*** Commercial bank prime lending rate
5.5% (31 December 2014 est.)
5.41% (31 December 2013 est.)
- country comparison to the world :: 147
*** Stock of narrow money
$11.18 billion (31 December 2014 est.)
$10.28 billion (31 December 2013 est.)
- country comparison to the world :: 77
*** Stock of broad money
$34.21 billion (31 December 2014 est.)
$30.79 billion (31 December 2013 est.)
- country comparison to the world :: 75
*** Stock of domestic credit
$33.72 billion (31 December 2014 est.)
$28.8 billion (31 December 2013 est.)
- country comparison to the world :: 73
*** Market value of publicly traded shares
$20.19 billion (31 December 2014 est.)
$19.07 billion (31 December 2013 est.)
$20.27 billion (31 December 2010 est.)
- country comparison to the world :: 66
*** Current account balance
$7.978 billion (2014 est.)
$9.184 billion (2013 est.)
- country comparison to the world :: 30
*** Exports
$58.74 billion (2014 est.)
$56.61 billion (2013 est.)
- country comparison to the world :: 56
*** Exports - commodities
petroleum, reexports, fish, metals, textiles
*** Exports - partners
China 43%, UAE 10.3%, South Korea 8.2% (2014)
*** Imports
$34.37 billion (2014 est.)
$30.46 billion (2013 est.)
- country comparison to the world :: 66
*** Imports - commodities
machinery and transport equipment, manufactured goods, food, livestock, lubricants
*** Imports - partners
UAE 32.5%, Japan 12.2%, China 4.8%, India 4.3%, US 4.3%, Saudi Arabia 4.1% (2014)
*** Reserves of foreign exchange and gold
$17.85 billion (31 December 2014 est.)
$15.95 billion (31 December 2013 est.)
- country comparison to the world :: 65
*** Debt - external
$11.3 billion (31 December 2014 est.)
$10.83 billion (31 December 2013 est.)
- country comparison to the world :: 102
*** Stock of direct foreign investment - at home
$NA
*** Stock of direct foreign investment - abroad
$NA
*** Exchange rates
Omani rials (OMR) per US dollar -
0.3845 (2014 est.)
0.3845 (2013 est.)
0.3845 (2012 est.)
0.3845 (2011 est.)
0.3845 (2010 est.)
** Energy
*** Electricity - production
20.07 billion kWh (2011 est.)
- country comparison to the world :: 74
*** Electricity - consumption
17.23 billion kWh (2011 est.)
- country comparison to the world :: 74
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 173
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 176
*** Electricity - installed generating capacity
4.861 million kW (2011 est.)
- country comparison to the world :: 75
*** Electricity - from fossil fuels
100% of total installed capacity (2011 est.)
- country comparison to the world :: 24
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 144
*** Electricity - from hydroelectric plants
0% of total installed capacity (2011 est.)
- country comparison to the world :: 186
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 205
*** Crude oil - production
944,800 bbl/day (2013 est.)
- country comparison to the world :: 21
*** Crude oil - exports
833,400 bbl/day (2013 est.)
- country comparison to the world :: 16
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 97
*** Crude oil - proved reserves
5.5 billion bbl (1 January 2014 est.)
- country comparison to the world :: 24
*** Refined petroleum products - production
164,600 bbl/day (2010 est.)
- country comparison to the world :: 61
*** Refined petroleum products - consumption
153,800 bbl/day (2013 est.)
- country comparison to the world :: 64
*** Refined petroleum products - exports
47,710 bbl/day (2010 est.)
- country comparison to the world :: 60
*** Refined petroleum products - imports
2,390 bbl/day (2010 est.)
- country comparison to the world :: 177
*** Natural gas - production
29.29 billion cu m (2012 est.)
- country comparison to the world :: 29
*** Natural gas - consumption
20.26 billion cu m (2012 est.)
- country comparison to the world :: 37
*** Natural gas - exports
10.87 billion cu m (2012 est.)
- country comparison to the world :: 18
*** Natural gas - imports
1.836 billion cu m (2012 est.)
- country comparison to the world :: 51
*** Natural gas - proved reserves
849.5 billion cu m (1 January 2014 est.)
- country comparison to the world :: 28
*** Carbon dioxide emissions from consumption of energy
62.85 million Mt (2012 est.)
- country comparison to the world :: 55
** Communications
*** Telephones - fixed lines
- total subscriptions :: 380,000
- subscriptions per 100 inhabitants :: 12 (2014 est.)
- country comparison to the world :: 108
*** Telephones - mobile cellular
- total :: 6.2 million
- subscriptions per 100 inhabitants :: 192 (2014 est.)
- country comparison to the world :: 109
*** Telephone system
- general assessment :: modern system consisting of open-wire, microwave, and radiotelephone communication stations; limited coaxial cable; domestic satellite system with 8 earth stations
- domestic :: fixed-line and mobile-cellular subscribership both increasing with fixed-line phone service gradually being introduced to remote villages using wireless local loop systems
- international :: country code - 968; the Fiber-Optic Link Around the Globe (FLAG) and the SEA-ME-WE-3 submarine cable provide connectivity to Asia, the Middle East, and Europe; satellite earth stations - 2 Intelsat (Indian Ocean), 1 Arabsat (2008)
*** Broadcast media
1 state-run TV broadcaster; TV stations transmitting from Saudi Arabia, the UAE, and Yemen available via satellite TV; state-run radio operates multiple stations; first private radio station began operating in 2007 and 2 additional stations now operating (2007)
*** Radio broadcast stations
AM 3, FM 9, shortwave 2 (1999)
*** Television broadcast stations
13 (plus 25 repeaters) (1999)
*** Internet country code
.om
*** Internet users
- total :: 2.1 million
- percent of population :: 65.8% (2014 est.)
- country comparison to the world :: 96
** Transportation
*** Airports
132 (2013)
- country comparison to the world :: 44
*** Airports - with paved runways
- total :: 13
- over 3,047 m :: 7
- 2,438 to 3,047 m :: 5
- 914 to 1,523 m :: 1 (2013)
*** Airports - with unpaved runways
- total :: 119
- over 3,047 m :: 2
- 2,438 to 3,047 m :: 7
- 1,524 to 2,437 m :: 51
- 914 to 1,523 m :: 33
- under 914 m :: 
26 (2013)
*** Heliports
3 (2013)
*** Pipelines
condensate 106 km; gas 4,224 km; oil 3,558 km; oil/gas/water 33 km; refined products 264 km (2013)
*** Roadways
- total :: 60,230 km
- paved :: 29,685 km (includes 1,943 km of expressways)
- unpaved :: 30,545 km (2012)
- country comparison to the world :: 69
*** Merchant marine
- total :: 5
- by type :: chemical tanker 1, passenger 1, passenger/cargo 3
- registered in other countries :: 15 (Malta 5, Panama 10) (2010)
- country comparison to the world :: 128
*** Ports and terminals
- major seaport(s) :: Mina' Qabus, Salalah, Suhar
- container port(s) (TEUs) :: Salalah (3,200,000)
- LNG terminal(s) (export) :: Qalhat
** Military
*** Military branches
Sultan's Armed Forces (SAF): Royal Army of Oman, Royal Navy of Oman, Royal Air Force of Oman (al-Quwwat al-Jawwiya al-Sultanat Oman) (2013)
*** Military service age and obligation
18-30 years of age for voluntary military service; no conscription (2012)
*** Manpower available for military service
- males age 16-49 :: 985,957
- females age 16-49 :: 737,812 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 837,886
- females age 16-49 :: 642,427 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 31,959
- female :: 30,264 (2010 est.)
*** Military expenditures
8.61% of GDP (2012)
6.13% of GDP (2011)
8.61% of GDP (2010)
- country comparison to the world :: 3
** Transnational Issues
*** Disputes - international
boundary agreement reportedly signed and ratified with UAE in 2003 for entire border, including Oman's Musandam Peninsula and Al Madhah exclave, but details of the alignment have not been made public
*** Refugees and internally displaced persons
- refugees (country of origin) :: 5,000 (Yemen) (2015)