** Introduction
*** Background
British influence and control over what would become Nigeria and Africa's most populous country grew through the 19th century. A series of constitutions after World War II granted Nigeria greater autonomy; independence came in 1960. Following nearly 16 years of military rule, a new constitution was adopted in 1999, and a peaceful transition to civilian government was completed. The government continues to face the daunting task of reforming a petroleum-based economy, whose revenues have been squandered through corruption and mismanagement, and institutionalizing democracy. In addition, Nigeria continues to experience longstanding ethnic and religious tensions. Although both the 2003 and 2007 presidential elections were marred by significant irregularities and violence, Nigeria is currently experiencing its longest period of civilian rule since independence. The general elections of April 2007 marked the first civilian-to-civilian transfer of power in the country's history and the elections of 2011 were generally regarded as credible. In January 2014, Nigeria assumed a nonpermanent seat on the UN Security Council for the 2014-15 term.
** Geography
*** Location
Western Africa, bordering the Gulf of Guinea, between Benin and Cameroon
*** Geographic coordinates
10 00 N, 8 00 E
*** Map references
Africa
*** Area
- total :: 923,768 sq km
- land :: 910,768 sq km
- water :: 13,000 sq km
- country comparison to the world :: 32
*** Area - comparative
about six times the size of Georgia; slightly more than twice the size of California
- Area comparison map ::  
*** Land boundaries
- total :: 4,477 km
- border countries (4) :: Benin 809 km, Cameroon 1,975 km, Chad 85 km, Niger 1,608 km
*** Coastline
853 km
*** Maritime claims
- territorial sea :: 12 nm
- exclusive economic zone :: 200 nm
- continental shelf :: 200-m depth or to the depth of exploitation
*** Climate
varies; equatorial in south, tropical in center, arid in north
*** Terrain
southern lowlands merge into central hills and plateaus; mountains in southeast, plains in north
*** Elevation extremes
- lowest point :: Atlantic Ocean 0 m
- highest point :: Chappal Waddi 2,419 m
*** Natural resources
natural gas, petroleum, tin, iron ore, coal, limestone, niobium, lead, zinc, arable land
*** Land use
- agricultural land :: 78%
arable land 37.3%; permanent crops 7.4%; permanent pasture 33.3%
- forest :: 9.5%
- other :: 12.5% (2011 est.)
*** Irrigated land
2,932 sq km (2004)
*** Total renewable water resources
286.2 cu km (2011)
*** Freshwater withdrawal (domestic/industrial/agricultural)
- total :: 13.11  cu km/yr (31%/15%/54%)
- per capita :: 89.21  cu m/yr (2005)
*** Natural hazards
periodic droughts; flooding
*** Environment - current issues
soil degradation; rapid deforestation; urban air and water pollution; desertification; oil pollution - water, air, and soil; has suffered serious damage from oil spills; loss of arable land; rapid urbanization
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Endangered Species, Hazardous Wastes, Law of the Sea, Marine Dumping, Marine Life Conservation, Ozone Layer Protection, Ship Pollution, Wetlands
- signed, but not ratified :: none of the selected agreements
*** Geography - note
the Niger River enters the country in the northwest and flows southward through tropical rain forests and swamps to its delta in the Gulf of Guinea
** People and Society
*** Nationality
- noun :: Nigerian(s)
- adjective :: Nigerian
*** Ethnic groups
Nigeria, Africa's most populous country, is composed of more than 250 ethnic groups; the most populous and politically influential are: Hausa and the Fulani 29%, Yoruba 21%, Igbo (Ibo) 18%, Ijaw 10%, Kanuri 4%, Ibibio 3.5%, Tiv 2.5%
*** Languages
English (official), Hausa, Yoruba, Igbo (Ibo), Fulani, over 500 additional indigenous languages
*** Religions
Muslim 50%, Christian 40%, indigenous beliefs 10%
*** Population
181,562,056
- note :: estimates for this country explicitly take into account the effects of excess mortality due to AIDS; this can result in lower life expectancy, higher infant mortality, higher death rates, lower population growth rates, and changes in the distribution of population by age and sex than would otherwise be expected (July 2015 est.)
- country comparison to the world :: 8
*** Age structure
- 0-14 years :: 43.01% (male 39,960,275/female 38,123,266)
- 15-24 years :: 19.38% (male 17,978,154/female 17,210,308)
- 25-54 years :: 30.56% (male 28,470,583/female 27,018,101)
- 55-64 years :: 3.94% (male 3,491,784/female 3,669,348)
- 65 years and over :: 3.11% (male 2,687,373/female 2,952,864) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 87.7%
- youth dependency ratio :: 82.6%
- elderly dependency ratio :: 5.1%
- potential support ratio :: 19.5% (2015 est.)
*** Median age
- total :: 18.2 years
- male :: 18.2 years
- female :: 18.3 years (2015 est.)
*** Population growth rate
2.45% (2015 est.)
- country comparison to the world :: 27
*** Birth rate
37.64 births/1,000 population (2015 est.)
- country comparison to the world :: 12
*** Death rate
12.9 deaths/1,000 population (2015 est.)
- country comparison to the world :: 18
*** Net migration rate
-0.22 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 121
*** Urbanization
- urban population :: 47.8% of total population (2015)
- rate of urbanization :: 4.66% annual rate of change (2010-15 est.)
*** Major urban areas - population
Lagos 13.123 million; Kano 3.587 million; Ibadan 3.16 million; ABUJA (capital) 2.44 million; Port Harcourt 2.343 million; Benin City 1.496 million (2015)
*** Sex ratio
- at birth :: 1.06 male(s)/female
- 0-14 years :: 1.05 male(s)/female
- 15-24 years :: 1.05 male(s)/female
- 25-54 years :: 1.05 male(s)/female
- 55-64 years :: 0.95 male(s)/female
- 65 years and over :: 0.91 male(s)/female
- total population :: 1.04 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 72.7 deaths/1,000 live births
- male :: 77.55 deaths/1,000 live births
- female :: 67.55 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 10
*** Life expectancy at birth
- total population :: 53.02 years
- male :: 52 years
- female :: 54.1 years (2015 est.)
- country comparison to the world :: 213
*** Total fertility rate
5.19 children born/woman (2015 est.)
- country comparison to the world :: 13
*** Contraceptive prevalence rate
15.1% (2013)
*** Health expenditures
3.9% of GDP (2013)
- country comparison to the world :: 109
*** Physicians density
0.41 physicians/1,000 population (2009)
*** Hospital bed density
0.53 beds/1,000 population (2004)
*** Drinking water source
- improved :: 
urban: 80.8% of population
rural: 57.3% of population
total: 68.5% of population
- unimproved :: 
urban: 19.2% of population
rural: 42.7% of population
total: 31.5% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 32.8% of population
rural: 25.4% of population
total: 29% of population
- unimproved :: 
urban: 67.2% of population
rural: 74.6% of population
total: 71% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
3.17% (2014 est.)
- country comparison to the world :: 20
*** HIV/AIDS - people living with HIV/AIDS
3,228,600 (2013 est.)
- country comparison to the world :: 2
*** HIV/AIDS - deaths
174,300 (2014 est.)
- country comparison to the world :: 1
*** Major infectious diseases
- degree of risk :: very high
- food or waterborne diseases :: bacterial and protozoal diarrhea, hepatitis A and E, and typhoid fever
- vectorborne diseases :: malaria, dengue fever, and yellow fever
- water contact diseases :: leptospirosis and schistosomiasis
- respiratory disease :: meningococcal meningitis
- aerosolized dust or soil contact disease :: one of the most highly endemic areas for Lassa fever
- animal contact disease :: rabies
- note :: highly pathogenic H5N1 avian influenza has been identified in this country; it poses a negligible risk with extremely rare cases possible among US citizens who have close contact with birds (2013)
*** Obesity - adult prevalence rate
9.7% (2014)
- country comparison to the world :: 146
*** Children under the age of 5 years underweight
31% (2013)
- country comparison to the world :: 12
*** Education expenditures
NA
*** Literacy
- definition :: age 15 and over can read and write
- total population :: 59.6%
- male :: 69.2%
- female :: 49.7% (2015 est.)
*** School life expectancy (primary to tertiary education)
- total :: 9 years
- male :: 10 years
- female :: 8 years (2005)
*** Child labor - children ages 5-14
- total number :: 11,396,823
- percentage :: 29% (2007 est.)
** Government
*** Country name
- conventional long form :: Federal Republic of Nigeria
- conventional short form :: Nigeria
*** Government type
federal republic
*** Capital
- name :: Abuja
- geographic coordinates :: 9 05 N, 7 32 E
- time difference :: UTC+1 (6 hours ahead of Washington, DC, during Standard Time)
*** Administrative divisions
36 states and 1 territory*; Abia, Adamawa, Akwa Ibom, Anambra, Bauchi, Bayelsa, Benue, Borno, Cross River, Delta, Ebonyi, Edo, Ekiti, Enugu, Federal Capital Territory*, Gombe, Imo, Jigawa, Kaduna, Kano, Katsina, Kebbi, Kogi, Kwara, Lagos, Nasarawa, Niger, Ogun, Ondo, Osun, Oyo, Plateau, Rivers, Sokoto, Taraba, Yobe, Zamfara
*** Independence
1 October 1960 (from the UK)
*** National holiday
Independence Day (National Day), 1 October (1960)
*** Constitution
several previous; latest adopted 5 May 1999, effective 29 May 1999; amended 2010 (2010)
*** Legal system
mixed legal system of English common law, Islamic law (in 12 northern states), and traditional law
*** International law organization participation
accepts compulsory ICJ jurisdiction with reservations; accepts ICCt jurisdiction
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: President Maj. Gen. (ret.) Muhammadu BUHARI (since 29 May 2015); Vice President Oluyemi "Yemi" OSINBAJO (since 29 May 2015); note - the president is both chief of state and head of government
- head of government :: President Maj.Gen. (ret.) Muhammadu BUHARI (since 29 May 2015); Vice President Oluyemi "Yemi" OSINBAJO (since 29 May 2015)
- cabinet :: Federal Executive Council appointed by the president
- elections/appointments :: president directly elected by 'qualified' majority popular vote and at least 25% of the votes cast in 24 of Nigeria's 36 states; president elected for a 4-year term (eligible for a second term); election last held on 28-29 March 2015 (next to be held in February 2019)
- election results :: Muhammadu BUHARI elected president; percent of vote - Muhammadu BUHARI (CPC) 53%, Goodluck JONATHAN (PDP) 46%
*** Legislative branch
- description :: bicameral National Assembly consists of the Senate (109 seats - 3 each for the 36 states and 1 for Abuja; members directly elected in single-seat constituencies by simple majority vote to serve 4-year terms) and the House of Representatives (360 seats; members directly elected in single-seat constituencies by simple majority vote to serve 4-year terms)
- elections :: Senate - last held on 28-29 March 2015 (next to be held in February 2019); House of Representatives - last held on 28-29 March 2015 (next to be held in 2019)
- election results :: Senate - percent of vote by party - NA; seats by party - APC 60, PDP 49; House of Representatives - percent of vote by party - NA; seats by party - APC 225, PDP 125, other 10
*** Judicial branch
- highest court(s) :: Supreme Court (consists of the chief justice and 15 justices)
- judge selection and term of office :: judges appointed by the president on the recommendation of the National Judicial Council, a 23-member independent body of federal and state judicial officials; judge appointments confirmed by the Senate; judges serve until age 65
- subordinate courts :: Court of Appeal; Federal High Court; High Court of the Federal Capital Territory; Sharia Court of Appeal of the Federal Capital Territory; Customary Court of Appeal of the Federal Capital Territory; state court system similar in structure to federal system
*** Political parties and leaders
Accord Party or ACC [Mohammad Lawal MALADO]
Action Congress of Nigeria or ACN [Adebisi Bamidele AKANDE]
All Nigeria Peoples Party or ANPP [Ogbonnaya C. ONU]
All Progressives Congress [Adebisi Bamidele AKANDE, acting]
All Progressives Grand Alliance or APGA [Victor C. UMEH]
Congress for Progressive Change or CPC [Tony MOMOH]
Democratic Peoples Party or DPP [Biodun OGUNBIYI]
Labor Party or LP [Chief Dan NWANYANWU]
Peoples Democratic Party or PDP [Adamu MU'AZU]
*** Political pressure groups and leaders
Academic Staff Union for Universities or ASUU
Campaign for Democracy or CD
Civil Liberties Organization or CLO
Committee for the Defense of Human Rights or CDHR
Constitutional Right Project or CRP
Human Right Africa
National Association of Democratic Lawyers or NADL
National Association of Nigerian Students or NANS
Nigerian Bar Association or NBA
Nigerian Labor Congress or NLC
Nigerian Medical Association or NMA
Universal Defenders of Democracy or UDD
- other :: the press
*** International organization participation
ACP, AfDB, AU, C, CD, D-8, ECOWAS, EITI (compliant country), FAO, G-15, G-24, G-77, IAEA, IBRD, ICAO, ICC (national committees), ICCt, ICRM, IDA, IDB, IFAD, IFC, IFRCS, IHO, ILO, IMF, IMO, IMSO, Interpol, IOC, IOM, IPU, ISO, ITSO, ITU, ITUC (NGOs), MIGA, MINURSO, MINUSMA, MONUSCO, NAM, OAS (observer), OIC, OPCW, OPEC, PCA, UN, UN Security Council (temporary), UNAMID, UNCTAD, UNESCO, UNHCR, UNIDO, UNIFIL, UNISFA, UNITAR, UNMIL, UNMISS, UNOCI, UNWTO, UPU, WCO, WFTU (NGOs), WHO, WIPO, WMO, WTO
*** Diplomatic representation in the US
- chief of mission :: Ambassador (vacant); Charge d'Affaires Hakeem Toyin BALOGUN (since 27 August 2015)
- chancery :: 3519 International Court NW, Washington, DC 20008
- telephone :: [1] (202) 986-8400
- FAX :: [1] (202) 362-6541
- consulate(s) general :: Atlanta, New York
*** Diplomatic representation from the US
- chief of mission :: Ambassador James F. ENTWISTLE (since 26 November 2013)
- embassy :: Plot 1075 Diplomatic Drive, Central District Area, Abuja
- mailing address :: P. O. Box 5760, Garki, Abuja
- telephone :: [234] (9) 461-4000
- FAX :: [234] (9) 461-4171
*** Flag description
three equal vertical bands of green (hoist side), white, and green; the color green represents the forests and abundant natural wealth of the country, white stands for peace and unity
*** National symbol(s)
eagle; national colors: green, white
*** National anthem
- name :: "Arise Oh Compatriots, Nigeria's Call Obey"
- lyrics/music :: John A. ILECHUKWU, Eme Etim AKPAN, B. A. OGUNNAIKE, Sotu OMOIGUI and P. O. ADERIBIGBE/Benedict Elide ODIASE
- note :: adopted 1978; lyrics are a mixture of the five top entries in a national contest

** Economy
*** Economy - overview
Following an April 2014 statistical "rebasing" exercise, Nigeria has emerged as Africa's largest economy, with 2014 GDP estimated at US$479 billion. Oil has been a dominant source of government revenues since the 1970s. Regulatory constraints and security risks have limited new investment in oil and natural gas, and Nigeria's oil production contracted in 2012 and 2013. Nevertheless, the Nigerian economy has continued to grow at a rapid 6%-8% per annum (pre-rebasing), driven by growth in agriculture, telecommunications, and services, and the medium-term outlook for Nigeria is good, assuming oil output stabilizes and oil prices remain strong. Fiscal authorities pursued countercyclical policies in 2011-13, significantly reducing the budget deficit. Monetary policy has also been contractionary. Following the 2008-9 global financial crises, the banking sector was effectively recapitalized and regulation enhanced. Despite its strong fundamentals, oil-rich Nigeria has been hobbled by inadequate power supply, lack of infrastructure, delays in the passage of legislative reforms, an inefficient property registration system, restrictive trade policies, an inconsistent regulatory environment, a slow and ineffective judicial system, unreliable dispute resolution mechanisms, insecurity, and pervasive corruption. Economic diversification and strong growth have not translated into a significant decline in poverty levels - over 62% of Nigeria's 170 million people live in extreme poverty. President JONATHAN has established an economic team that includes experienced and reputable members and has announced plans to increase transparency, continue to diversify production, and further improve fiscal management. The government is working to develop stronger public-private partnerships for roads, agriculture, and power.
*** GDP (purchasing power parity)
$1.049 trillion (2014 est.)
$986.8 billion (2013 est.)
$936.3 billion (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 21
*** GDP (official exchange rate)
$573.7 billion (2014 est.)
*** GDP - real growth rate
6.3% (2014 est.)
5.4% (2013 est.)
4.3% (2012 est.)
- country comparison to the world :: 19
*** GDP - per capita (PPP)
$6,000 (2014 est.)
$5,700 (2013 est.)
$5,400 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 159
*** Gross national saving
17.4% of GDP (2014 est.)
18.6% of GDP (2013 est.)
19.3% of GDP (2012 est.)
- country comparison to the world :: 90
*** GDP - composition, by end use
- household consumption :: 72.5%
- government consumption :: 8.4%
- investment in fixed capital :: 16.4%
- investment in inventories :: 0%
- exports of goods and services :: 14.9%
- imports of goods and services :: -12.1%
 (2014 est.)
*** GDP - composition, by sector of origin
- agriculture :: 20.6%
- industry :: 25.6%
- services :: 53.8% (2014 est.)
*** Agriculture - products
cocoa, peanuts, cotton, palm oil, corn, rice, sorghum, millet, cassava (manioc, tapioca), yams, rubber; cattle, sheep, goats, pigs; timber; fish
*** Industries
crude oil, coal, tin, columbite; rubber products, wood; hides and skins, textiles, cement and other construction materials, food products, footwear, chemicals, fertilizer, printing, ceramics, steel
*** Industrial production growth rate
4.6% (2014 est.)
- country comparison to the world :: 57
*** Labor force
54.97 million (2014 est.)
- country comparison to the world :: 11
*** Labor force - by occupation
- agriculture :: 70%
- industry :: 10%
- services :: 20% (1999 est.)
*** Unemployment rate
23.9% (2011 est.)
4.9% (2011 est.)
- country comparison to the world :: 171
*** Population below poverty line
70% (2010 est.)
*** Household income or consumption by percentage share
- lowest 10% :: 1.8%
- highest 10% :: 38.2% (2010 est.)
*** Distribution of family income - Gini index
43.7 (2003)
50.6 (1997)
- country comparison to the world :: 47
*** Budget
- revenues :: $22.77 billion
- expenditures :: $34.62 billion (2014 est.)
*** Taxes and other revenues
3.8% of GDP (2014 est.)
- country comparison to the world :: 212
*** Budget surplus (+) or deficit (-)
-2% of GDP (2014 est.)
- country comparison to the world :: 85
*** Public debt
11.7% of GDP (2014 est.)
10.5% of GDP (2013 est.)
- country comparison to the world :: 149
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
8.1% (2014 est.)
8.5% (2013 est.)
- country comparison to the world :: 202
*** Central bank discount rate
4.25% (31 December 2010)
6% (31 December 2009)
- country comparison to the world :: 89
*** Commercial bank prime lending rate
17% (31 December 2014 est.)
16.72% (31 December 2013 est.)
- country comparison to the world :: 29
*** Stock of narrow money
$45.44 billion (31 December 2014 est.)
$44.59 billion (31 December 2013 est.)
- country comparison to the world :: 53
*** Stock of broad money
$108.7 billion (31 December 2014 est.)
$99.64 billion (31 December 2013 est.)
- country comparison to the world :: 52
*** Stock of domestic credit
$119.6 billion (31 December 2014 est.)
$109.6 billion (31 December 2013 est.)
- country comparison to the world :: 50
*** Market value of publicly traded shares
$56.39 billion (31 December 2012 est.)
$39.27 billion (31 December 2011)
$50.88 billion (31 December 2010 est.)
- country comparison to the world :: 50
*** Current account balance
$12.67 billion (2014 est.)
$21.85 billion (2013 est.)
- country comparison to the world :: 22
*** Exports
$93.01 billion (2014 est.)
$96.74 billion (2013 est.)
- country comparison to the world :: 43
*** Exports - commodities
petroleum and petroleum products 95%, cocoa, rubber (2012 est.)
*** Exports - partners
India 15.4%, Brazil 10.2%, Netherlands 8.5%, Spain 8.5%, South Africa 5.5%, France 5.4%, Germany 5.1%, Japan 4.4% (2014)
*** Imports
$52.79 billion (2014 est.)
$51.38 billion (2013 est.)
- country comparison to the world :: 54
*** Imports - commodities
machinery, chemicals, transport equipment, manufactured goods, food and live animals
*** Imports - partners
China 25.3%, US 9.7%, India 4.7% (2014)
*** Reserves of foreign exchange and gold
$37.44 billion (31 December 2014 est.)
$45.66 billion (31 December 2013 est.)
- country comparison to the world :: 48
*** Debt - external
$22.01 billion (31 December 2014 est.)
$18.63 billion (31 December 2013 est.)
- country comparison to the world :: 82
*** Stock of direct foreign investment - at home
$81.72 billion (31 December 2013 est.)
$76.75 billion (31 December 2012 est.)
- country comparison to the world :: 48
*** Stock of direct foreign investment - abroad
$10.87 billion (31 December 2014 est.)
$9.113 billion (31 December 2013 est.)
- country comparison to the world :: 55
*** Exchange rates
nairas (NGN) per US dollar -
157.3 (2014 est.)
157.31 (2013 est.)
156.81 (2012 est.)
154.7 (2011 est.)
150.3 (2010 est.)
** Energy
*** Electricity - production
25.7 billion kWh (2011 est.)
- country comparison to the world :: 69
*** Electricity - consumption
23.11 billion kWh (2011 est.)
- country comparison to the world :: 68
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 179
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 181
*** Electricity - installed generating capacity
5.9 million kW (2011 est.)
- country comparison to the world :: 72
*** Electricity - from fossil fuels
67.1% of total installed capacity (2011 est.)
- country comparison to the world :: 117
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 152
*** Electricity - from hydroelectric plants
32.8% of total installed capacity (2011 est.)
- country comparison to the world :: 69
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 210
*** Crude oil - production
2.367 million bbl/day (2013 est.)
- country comparison to the world :: 13
*** Crude oil - exports
2.341 million bbl/day (2010 est.)
- country comparison to the world :: 5
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 105
*** Crude oil - proved reserves
37.14 billion bbl (1 January 2014 est.)
- country comparison to the world :: 10
*** Refined petroleum products - production
101,300 bbl/day (2010 est.)
- country comparison to the world :: 73
*** Refined petroleum products - consumption
302,000 bbl/day (2013 est.)
- country comparison to the world :: 42
*** Refined petroleum products - exports
18,750 bbl/day (2010 est.)
- country comparison to the world :: 72
*** Refined petroleum products - imports
151,700 bbl/day (2010 est.)
- country comparison to the world :: 35
*** Natural gas - production
33.71 billion cu m (2012 est.)
- country comparison to the world :: 27
*** Natural gas - consumption
6.916 billion cu m (2012 est.)
- country comparison to the world :: 55
*** Natural gas - exports
26.79 billion cu m (2012 est.)
- country comparison to the world :: 14
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 108
*** Natural gas - proved reserves
5.118 trillion cu m (1 January 2014 est.)
- country comparison to the world :: 9
*** Carbon dioxide emissions from consumption of energy
86.4 million Mt (2012 est.)
- country comparison to the world :: 44
** Communications
*** Telephones - fixed lines
- total subscriptions :: 180,000
- subscriptions per 100 inhabitants :: less than 1 (2014 est.)
- country comparison to the world :: 130
*** Telephones - mobile cellular
- total :: 139 million
- subscriptions per 100 inhabitants :: 78 (2014 est.)
- country comparison to the world :: 9
*** Telephone system
- general assessment :: further expansion and modernization of the fixed-line telephone network is needed; network quality remains a problem
- domestic :: the addition of a second fixed-line provider in 2002 resulted in faster growth, but subscribership remains only about 1 per 100 persons; mobile-cellular services growing rapidly, in part responding to the shortcomings of the fixed-line network; multiple cellular providers operate nationally with subscribership base approaching 60 per 100 persons
- international :: country code - 234; landing point for the SAT-3/WASC fiber-optic submarine cable that provides connectivity to Europe and Asia; satellite earth stations - 3 Intelsat (2 Atlantic Ocean and 1 Indian Ocean) (2010)
*** Broadcast media
nearly 70 federal government-controlled national and regional TV stations; all 36 states operate TV stations; several private TV stations operational; cable and satellite TV subscription services are available; network of federal government-controlled national, regional, and state radio stations; roughly 40 state government-owned radio stations typically carry their own programs except for news broadcasts; about 20 private radio stations; transmissions of international broadcasters are available (2007)
*** Radio broadcast stations
AM 83, FM 36, shortwave 11 (2001)
*** Television broadcast stations
3 (the government controls 2 of the broadcasting stations and 15 repeater stations) (2001)
*** Internet country code
.ng
*** Internet users
- total :: 66.6 million
- percent of population :: 37.6% (2014 est.)
- country comparison to the world :: 9
** Transportation
*** Airports
54 (2013)
- country comparison to the world :: 88
*** Airports - with paved runways
- total :: 40
- over 3,047 m :: 10
- 2,438 to 3,047 m :: 12
- 1,524 to 2,437 m :: 9
- 914 to 1,523 m :: 6
- under 914 m :: 3 (2013)
*** Airports - with unpaved runways
- total :: 14
- 1,524 to 2,437 m :: 2
- 914 to 1,523 m :: 9
- under 914 m :: 
3 (2013)
*** Heliports
5 (2013)
*** Pipelines
condensate 124 km; gas 4,045 km; liquid petroleum gas 164 km; oil 4,441 km; refined products 3,940 km (2013)
*** Railways
- total :: 3,798 km
- standard gauge :: 293 km 1.435-m gauge
- narrow gauge :: 3,505 km 1.067-m gauge (2014)
- country comparison to the world :: 50
*** Roadways
- total :: 193,200 km
- paved :: 28,980 km
- unpaved :: 164,220 km (2004)
- country comparison to the world :: 27
*** Waterways
8,600 km (Niger and Benue Rivers and smaller rivers and creeks) (2011)
- country comparison to the world :: 15
*** Merchant marine
- total :: 89
- by type :: cargo 2, chemical tanker 28, liquefied gas 1, passenger/cargo 1, petroleum tanker 56, specialized tanker 1
- foreign-owned :: 3 (India 1, UK 2)
- registered in other countries :: 33 (Bahamas 2, Bermuda 11, Comoros 1, Italy 1, Liberia 4, North Korea 1, Panama 6, Seychelles 1, unknown 6) (2010)
- country comparison to the world :: 54
*** Ports and terminals
- major seaport(s) :: Bonny Inshore Terminal, Calabar, Lagos
- LNG terminal(s) (export) :: Bonny Island
*** Transportation - note
the International Maritime Bureau reports the territorial and offshore waters in the Niger Delta and Gulf of Guinea as high risk for piracy and armed robbery of ships; in 2014, 18 commercial vessels were boarded or attacked compared with 31 attacks in 2013; crews were robbed and stores or cargoes stolen; Nigerian pirates have extended the range of their attacks to as far away as Cote d'Ivoire
** Military
*** Military branches
Nigerian Armed Forces: Army, Navy, Air Force (2013)
*** Military service age and obligation
18 years of age for voluntary military service; no conscription (2012)
*** Manpower available for military service
- males age 16-49 :: 37,087,711
- females age 16-49 :: 35,232,127 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 20,839,976
- females age 16-49 :: 19,867,683 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 1,767,428
- female :: 1,687,719 (2010 est.)
*** Military expenditures
0.89% of GDP (2012)
0.98% of GDP (2011)
0.89% of GDP (2010)
- country comparison to the world :: 108
** Transnational Issues
*** Disputes - international
Joint Border Commission with Cameroon reviewed 2002 ICJ ruling on the entire boundary and bilaterally resolved differences, including June 2006 Greentree Agreement that immediately cedes sovereignty of the Bakassi Peninsula to Cameroon with a phaseout of Nigerian control within two years while resolving patriation issues; the ICJ ruled on an equidistance settlement of Cameroon-Equatorial Guinea-Nigeria maritime boundary in the Gulf of Guinea, but imprecisely defined coordinates in the ICJ decision and a sovereignty dispute between Equatorial Guinea and Cameroon over an island at the mouth of the Ntem River all contribute to the delay in implementation; only Nigeria and Cameroon have heeded the Lake Chad Commission's admonition to ratify the delimitation treaty which also includes the Chad-Niger and Niger-Nigeria boundaries; location of Benin-Niger-Nigeria tripoint is unresolved
*** Refugees and internally displaced persons
- IDPs :: 1,538,982 (Boko Haram attacks and counterinsurgency efforts in northern Nigeria; communal violence between Christians and Muslims in the middle belt region, political violence; flooding; forced evictions; cattle rustling; competition for resources) (2015)
*** Illicit drugs
a transit point for heroin and cocaine intended for European, East Asian, and North American markets; consumer of amphetamines; safe haven for Nigerian narcotraffickers operating worldwide; major money-laundering center; massive corruption and criminal activity; Nigeria has improved some anti-money-laundering controls, resulting in its removal from the Financial Action Task Force's (FATF's) Noncooperative Countries and Territories List in June 2006; Nigeria's anti-money-laundering regime continues to be monitored by FATF