** Introduction
*** Background
In 1974, ethnic differences within the British colony of the Gilbert and Ellice Islands caused the Polynesians of the Ellice Islands to vote for separation from the Micronesians of the Gilbert Islands. The following year, the Ellice Islands became the separate British colony of Tuvalu. Independence was granted in 1978. In 2000, Tuvalu negotiated a contract leasing its Internet domain name ".tv" for $50 million in royalties over a 12-year period. The agreement was subsequently renegotiated but details were not disclosed.
** Geography
*** Location
Oceania, island group consisting of nine coral atolls in the South Pacific Ocean, about half way from Hawaii to Australia
*** Geographic coordinates
8 00 S, 178 00 E
*** Map references
Oceania
*** Area
- total :: 26 sq km
- land :: 26 sq km
- water :: 0 sq km
- country comparison to the world :: 238
*** Area - comparative
0.1 times the size of Washington, DC
*** Land boundaries
0 km
*** Coastline
24 km
*** Maritime claims
- territorial sea :: 12 nm
- contiguous zone :: 24 nm
- exclusive economic zone :: 200 nm
*** Climate
tropical; moderated by easterly trade winds (March to November); westerly gales and heavy rain (November to March)
*** Terrain
low-lying and narrow coral atolls
*** Elevation extremes
- lowest point :: Pacific Ocean 0 m
- highest point :: unnamed location 5 m
*** Natural resources
fish, coconut (copra)
*** Land use
- agricultural land :: 60%
arable land 0%; permanent crops 60%; permanent pasture 0%
- forest :: 33.3%
- other :: 6.7% (2011 est.)
*** Irrigated land
NA
*** Natural hazards
severe tropical storms are usually rare, but in 1997 there were three cyclones; low levels of islands make them sensitive to changes in sea level
*** Environment - current issues
since there are no streams or rivers and groundwater is not potable, most water needs must be met by catchment systems with storage facilities; beachhead erosion because of the use of sand for building materials; excessive clearance of forest undergrowth for use as fuel; damage to coral reefs from increasing ocean temperatures and acidification; Tuvalu is concerned about global increases in greenhouse gas emissions and their effect on rising sea levels, which threaten the country's underground water table; in 2000, the government appealed to Australia and New Zealand to take in Tuvaluans if rising sea levels should make evacuation necessary
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Law of the Sea, Ozone Layer Protection, Ship Pollution, Whaling
- signed, but not ratified :: none of the selected agreements
*** Geography - note
one of the smallest and most remote countries on Earth; six of the nine coral atolls - Nanumea, Nui, Vaitupu, Nukufetau, Funafuti, and Nukulaelae - have lagoons open to the ocean; Nanumaya and Niutao have landlocked lagoons; Niulakita does not have a lagoon
** People and Society
*** Nationality
- noun :: Tuvaluan(s)
- adjective :: Tuvaluan
*** Ethnic groups
Polynesian 96%, Micronesian 4%
*** Languages
Tuvaluan (official), English (official), Samoan, Kiribati (on the island of Nui)
*** Religions
Protestant 98.4% (Church of Tuvalu (Congregationalist) 97%, Seventh-Day Adventist 1.4%), Baha'i 1%, other 0.6%
*** Population
10,869 (July 2015 est.)
- country comparison to the world :: 223
*** Age structure
- 0-14 years :: 29.4% (male 1,639/female 1,557)
- 15-24 years :: 20.27% (male 1,157/female 1,046)
- 25-54 years :: 36.35% (male 1,946/female 2,005)
- 55-64 years :: 8.41% (male 373/female 541)
- 65 years and over :: 5.57% (male 247/female 358) (2015 est.)
- population pyramid ::  
*** Median age
- total :: 25.2 years
- male :: 24.1 years
- female :: 26.6 years (2015 est.)
*** Population growth rate
0.82% (2015 est.)
- country comparison to the world :: 135
*** Birth rate
23.74 births/1,000 population (2015 est.)
- country comparison to the world :: 62
*** Death rate
8.74 deaths/1,000 population (2015 est.)
- country comparison to the world :: 71
*** Net migration rate
-6.81 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 204
*** Urbanization
- urban population :: 59.7% of total population (2015)
- rate of urbanization :: 1.9% annual rate of change (2010-15 est.)
*** Major urban areas - population
FUNAFUTI (capital) 6,000 (2014)
*** Sex ratio
- at birth :: 1.05 male(s)/female
- 0-14 years :: 1.05 male(s)/female
- 15-24 years :: 1.11 male(s)/female
- 25-54 years :: 0.97 male(s)/female
- 55-64 years :: 0.69 male(s)/female
- 65 years and over :: 0.69 male(s)/female
- total population :: 0.97 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 30.8 deaths/1,000 live births
- male :: 33.46 deaths/1,000 live births
- female :: 28.01 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 66
*** Life expectancy at birth
- total population :: 66.16 years
- male :: 64.01 years
- female :: 68.41 years (2015 est.)
- country comparison to the world :: 173
*** Total fertility rate
3 children born/woman (2015 est.)
- country comparison to the world :: 54
*** Contraceptive prevalence rate
30.5% (2007)
*** Health expenditures
19.7% of GDP (2013)
- country comparison to the world :: 4
*** Physicians density
1.09 physicians/1,000 population (2009)
*** Hospital bed density
5.6 beds/1,000 population (2001)
*** Drinking water source
- improved :: 
urban: 98.3% of population
rural: 97% of population
total: 97.7% of population
- unimproved :: 
urban: 1.7% of population
rural: 3% of population
total: 2.3% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 86.3% of population
rural: 80.2% of population
total: 83.3% of population
- unimproved :: 
urban: 13.7% of population
rural: 19.8% of population
total: 16.7% of population (2012 est.)
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
*** Obesity - adult prevalence rate
39.6% (2014)
*** Children under the age of 5 years underweight
1.6% (2007)
- country comparison to the world :: 126
*** Education expenditures
NA
** Government
*** Country name
- conventional long form :: none
- conventional short form :: Tuvalu
- local long form :: none
- local short form :: Tuvalu
- former :: Ellice Islands
- note :: "Tuvalu" means "group of eight" referring to the country's eight traditionally inhabited islands
*** Government type
parliamentary democracy and a Commonwealth realm
*** Capital
- name :: Funafuti; note - administrative offices are in Vaiaku Village on Fongafale Islet
- geographic coordinates :: 8 31 S, 179 13 E
- time difference :: UTC+12 (17 hours ahead of Washington, DC, during Standard Time)
*** Administrative divisions
7 island councils and 1 town council*; Funafuti*, Nanumaga, Nanumea, Niutao, Nui, Nukufetau, Nukulaelae, Vaitupu
*** Independence
1 October 1978 (from the UK)
*** National holiday
Independence Day, 1 October (1978)
*** Constitution
previous 1978 (at independence); latest effective 1 October 1986; amended 2007, 2010 (2010)
*** Legal system
mixed legal system of English common law and local customary law
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; non-party state to the ICCt
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: Queen ELIZABETH II (since 6 February 1952); represented by Governor General Iakoba TAEIA Italeli (since 16 April 2010)
- head of government :: Prime Minister Enele SOPOAGA (since 5 August 2013)
- cabinet :: Cabinet appointed by the governor general on recommendation of the prime minister
- elections/appointments :: the monarchy is hereditary; governor general appointed by the monarch on recommendation of the prime minister; prime minister and deputy prime minister elected by and from members of House of Assembly following parliamentary elections
- election results :: Enele SOPOAGA elected prime minister by House of Assembly; House of Assembly vote count on 4 August 2013 - 8 to 5; note - Willie TELAVI removed as prime minister by the governor general on 1 August 2013
*** Legislative branch
- description :: unicameral  House of Assembly or Fale I Fono (15 seats; members directly elected in single- and multi-seat constituencies by simple majority vote to serve 4-year terms)
- elections :: last held on 16 September 2010 (next to be held in 2014)
- election results :: percent of vote - NA; seats - independents 15; 10 members reelected
*** Judicial branch
- highest court(s) :: Court of Appeal is the Fiji Court of Appeal on Fiji Island (consists of the chief justice who visits twice a year); High Court, located on Fiji, consists of the chief justice of Fiji who presides over its sessions
- judge selection and term of office :: chief justice appointed by the president of Fiji on the advice of the prime minister following consultation with the parliamentary leader of the opposition; justices of the Court of Appeal, and puisne judges of the High Court are appointed by the president of Fiji, upon the nomination of the Judicial Service Commission, after consulting with the Cabinet Minister and the committee of the House of Representatives responsible for the administration of justice; the chief justice and justices of Appeal generally required to retire at age 70; puisine judges appointed for not less than 4 years nor more than 7 years with mandatory retirement at age 65
- subordinate courts :: magistrates' courts; island courts; lands courts
*** Political parties and leaders
there are no political parties but members of parliament usually align themselves in informal groupings
*** Political pressure groups and leaders
none
*** International organization participation
ACP, ADB, AOSIS, C, FAO, IBRD, IDA, IFAD, IFRCS (observer), ILO, IMF, IMO, IOC, ITU, OPCW, PIF, Sparteca, SPC, UN, UNCTAD, UNESCO, UNIDO, UPU, WHO, WIPO, WMO
*** Diplomatic representation in the US
- chief of mission :: Ambassador Aunese Makoi SIMATI (since 11 January 2013)
- chancery :: note - Tuvalu does not have an embassy in Washington, D.C.; UN office located at 800 2nd Avenue, Suite 400D, New York, NY 10017
- telephone :: [1] (212) 490-0534
- FAX :: [1] (212) 937-0692
*** Diplomatic representation from the US
the US does not have an embassy in Tuvalu; the US ambassador to Fiji is accredited to Tuvalu
*** Flag description
light blue with the flag of the UK in the upper hoist-side quadrant; the outer half of the flag represents a map of the country with nine yellow, five-pointed stars on a blue field symbolizing the nine atolls in the ocean
*** National symbol(s)
maneapa (native meeting house); national colors: light blue, yellow
*** National anthem
- name :: "Tuvalu mo te Atua" (Tuvalu for the Almighty)
- lyrics/music :: Afaese MANOA
- note :: adopted 1978; the anthem's name is also the nation's motto
** Economy
*** Economy - overview
Tuvalu consists of a densely populated, scattered group of nine coral atolls with poor soil. Only eight of the atolls are inhabited. It is one of the smallest countries in the world, with its highest point at 4.6 meters above sea level. The country is isolated, almost entirely dependent on imports, particularly of food and fuel, and vulnerable to climate change and rising sea levels, which pose significant challenges to development. The public sector dominates economic activity. Tuvalu has few natural resources, except for its fisheries. Earnings from fish exports and fishing licenses for Tuvalu’s territorial waters are a significant source of government revenue. In 2013, revenue from fishing licenses doubled and totaled more than 45% of GDP. Official aid from foreign development partners has also increased. Tuvalu has substantial assets abroad. The Tuvalu Trust Fund, an international trust fund established in 1987 by development partners, has grown to $141 million in 2013 and is an important cushion for meeting shortfalls in the government's budget. While remittances are another substantial source of income, the value of remittances has declined since the global financial crisis of 2008. Growing income inequality is one of many concerns for the nation.
*** GDP (purchasing power parity)
$35 million (2014 est.)
$34.23 million (2013 est.)
$33.8 million (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 227
*** GDP (official exchange rate)
$38 million (2014 est.)
*** GDP - real growth rate
2.2% (2014 est.)
1.3% (2013 est.)
0.2% (2012 est.)
- country comparison to the world :: 144
*** GDP - per capita (PPP)
$3,300 (2014 est.)
$3,200 (2013 est.)
$3,200 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 186
*** GDP - composition, by sector of origin
- agriculture :: 24.5%
- industry :: 5.6%
- services :: 70% (2012 est.)
*** Agriculture - products
coconuts; fish
*** Industries
fishing
*** Industrial production growth rate
-26.1% (2012 est.)
*** Labor force
3,615 (2004 est.)
- country comparison to the world :: 223
*** Labor force - by occupation
- note :: people make a living mainly through exploitation of the sea, reefs, and atolls and through overseas remittances (mostly from workers in the phosphate industry and sailors)
*** Unemployment rate
NA%
*** Population below poverty line
26.3% (2010 est.)
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $42.68 million
- expenditures :: $32.46 million (2013 est.)
*** Taxes and other revenues
109.4% of GDP (2013 est.)
- country comparison to the world :: 8
*** Budget surplus (+) or deficit (-)
26.2% of GDP (2013 est.)
- country comparison to the world :: 138
*** Public debt
41.1% of GDP (2013 est.)
43.1% of GDP (2012 est.)
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
3.3% (2014 est.)
1.4% (2012)
- country comparison to the world :: 142
*** Commercial bank prime lending rate
10.6% (2013 est.)
10.6% (2012 est.)
*** Market value of publicly traded shares
$0 (2014)
*** Current account balance
$10 million (2014 est.)
-$11.68 million (2003)
- country comparison to the world :: 64
*** Exports
$600,000 (2010 est.)
$1 million (2004 est.)
- country comparison to the world :: 218
*** Exports - commodities
copra, fish
*** Imports
$136.5 million (2013 est.)
$238.6 million (2012 est.)
- country comparison to the world :: 221
*** Imports - commodities
food, animals, mineral fuels, machinery, manufactured goods
*** Debt - external
$NA
*** Exchange rates
Tuvaluan dollars or Australian dollars (AUD) per US dollar -
1.098 (2013)
1.67 (2013 est.)
1.2822 (2009 est.)
** Energy
*** Electricity - production
11.8 million kWh (2011)
*** Electricity - exports
0 kWh (2014 est.)
*** Electricity - imports
0 kWh (2014)
*** Electricity - installed generating capacity
5,100 kW (2011)
- country comparison to the world :: 210
*** Electricity - from fossil fuels
96% of total installed capacity (2015 est.)
*** Electricity - from nuclear fuels
0% of total installed capacity (2014)
*** Electricity - from hydroelectric plants
0% of total installed capacity (2014)
*** Crude oil - production
0 bbl/day (2014)
*** Crude oil - exports
0 bbl/day (2014)
*** Crude oil - imports
0 bbl/day (2014)
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
*** Refined petroleum products - production
0 bbl/day (2014)
*** Natural gas - production
0 cu m (2014)
*** Natural gas - consumption
0 cu m (2014)
*** Natural gas - exports
0 cu m (2014)
*** Natural gas - imports
0 cu m (2014)
** Communications
*** Telephones - fixed lines
- total subscriptions :: 1,500
- subscriptions per 100 inhabitants :: 14 (2014 est.)
- country comparison to the world :: 215
*** Telephones - mobile cellular
- total :: 3,800
- subscriptions per 100 inhabitants :: 35 (2014 est.)
- country comparison to the world :: 217
*** Telephone system
- general assessment :: serves particular needs for internal communications
- domestic :: radiotelephone communications between islands
- international :: country code - 688; international calls can be made by satellite (2007)
*** Broadcast media
no TV stations; many households use satellite dishes to watch foreign TV stations; 1 government-owned radio station, Radio Tuvalu, includes relays of programming from international broadcasters (2009)
*** Radio broadcast stations
AM 1, FM 1, shortwave 0 (2004)
*** Television broadcast stations
0 (2004)
*** Internet country code
.tv
*** Internet users
- total :: 4,100
- percent of population :: 38.1% (2014 est.)
- country comparison to the world :: 206
** Transportation
*** Airports
1 (2013)
- country comparison to the world :: 235
*** Airports - with unpaved runways
- total :: 1
- 1,524 to 2,437 m :: 1 (2013)
*** Roadways
- total :: 8 km
- paved :: 8 km (2011)
- country comparison to the world :: 223
*** Merchant marine
- total :: 58
- by type :: bulk carrier 4, cargo 24, chemical tanker 15, container 1, passenger 2, passenger/cargo 1, petroleum tanker 10, refrigerated cargo 1
- foreign-owned :: 33 (China 4, Indonesia 1, Maldives 1, Singapore 19, South Korea 1, Turkey 1, Vietnam 6) (2010)
- country comparison to the world :: 67
*** Ports and terminals
- major seaport(s) :: Funafuti
** Military
*** Military branches
no regular military forces; Tuvalu Police Force (2012)
*** Manpower fit for military service
- males age 16-49 :: 2,021
- females age 16-49 :: 2,026 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 119
- female :: 111 (2010 est.)
** Transnational Issues
*** Disputes - international
none