** Introduction
*** Background
Discovered and claimed for Spain in 1499, Aruba was acquired by the Dutch in 1636. The island's economy has been dominated by three main industries. A 19th century gold rush was followed by prosperity brought on by the opening in 1924 of an oil refinery. The last decades of the 20th century saw a boom in the tourism industry. Aruba seceded from the Netherlands Antilles in 1986 and became a separate, autonomous member of the Kingdom of the Netherlands. Movement toward full independence was halted at Aruba's request in 1990.
** Geography
*** Location
Caribbean, island in the Caribbean Sea, north of Venezuela
*** Geographic coordinates
12 30 N, 69 58 W
*** Map references
Central America and the Caribbean
*** Area
- total :: 180 sq km
- land :: 180 sq km
- water :: 0 sq km
- country comparison to the world :: 218
*** Area - comparative
slightly larger than Washington, DC
*** Land boundaries
0 km
*** Coastline
68.5 km
*** Maritime claims
- territorial sea :: 12 nm
*** Climate
tropical marine; little seasonal temperature variation
*** Terrain
flat with a few hills; scant vegetation
*** Elevation extremes
- lowest point :: Caribbean Sea 0 m
- highest point :: Ceru Jamanota 188 m
*** Natural resources
NEGL; white sandy beaches foster tourism
*** Land use
- agricultural land :: 11.1%
arable land 11.1%; permanent crops 0%; permanent pasture 0%
- forest :: 2.3%
- other :: 86.6% (2011 est.)
*** Irrigated land
NA
*** Natural hazards
hurricanes; lies outside the Caribbean hurricane belt and is rarely threatened
*** Environment - current issues
NA
*** Geography - note
a flat, riverless island renowned for its white sand beaches; its tropical climate is moderated by constant trade winds from the Atlantic Ocean; the temperature is almost constant at about 27 degrees Celsius (81 degrees Fahrenheit)
** People and Society
*** Nationality
- noun :: Aruban(s)
- adjective :: Aruban; Dutch
*** Ethnic groups
Dutch 82.1%, Colombian 6.6%, Venezuelan 2.2%, Dominican 2.2%, Haitian 1.2%, other 5.5%, unspecified 0.1% (2010 est.)
*** Languages
Papiamento (a Spanish-Portuguese-Dutch-English dialect) 69.4%, Spanish 13.7%, English (widely spoken) 7.1%, Dutch (official) 6.1%, Chinese 1.5%, other 1.7%, unspecified 0.4% (2010 est.)
*** Religions
Roman Catholic 75.3%, Protestant 4.9% (includes Methodist .9%, Adventist .9%, Anglican .4%, other Protestant 2.7%), Jehovah's Witness 1.7%, other 12%, none 5.5%, unspecified 0.5% (2010 est.)
*** Population
112,162 (July 2015 est.)
- country comparison to the world :: 190
*** Age structure
- 0-14 years :: 17.69% (male 9,953/female 9,888)
- 15-24 years :: 13.27% (male 7,470/female 7,417)
- 25-54 years :: 42.59% (male 23,015/female 24,750)
- 55-64 years :: 13.73% (male 7,114/female 8,287)
- 65 years and over :: 12.72% (male 5,591/female 8,677) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 44%
- youth dependency ratio :: 26.4%
- elderly dependency ratio :: 17.6%
- potential support ratio :: 5.7% (2015 est.)
*** Median age
- total :: 39 years
- male :: 37.1 years
- female :: 40.8 years (2015 est.)
*** Population growth rate
1.33% (2015 est.)
- country comparison to the world :: 89
*** Birth rate
12.56 births/1,000 population (2015 est.)
- country comparison to the world :: 157
*** Death rate
8.18 deaths/1,000 population (2015 est.)
- country comparison to the world :: 92
*** Net migration rate
8.92 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 12
*** Urbanization
- urban population :: 41.5% of total population (2015)
- rate of urbanization :: -0.28% annual rate of change (2010-15 est.)
*** Major urban areas - population
ORANJESTAD (capital) 29,000 (2014)
*** Sex ratio
- at birth :: 1.02 male(s)/female
- 0-14 years :: 1.01 male(s)/female
- 15-24 years :: 1.01 male(s)/female
- 25-54 years :: 0.93 male(s)/female
- 55-64 years :: 0.86 male(s)/female
- 65 years and over :: 0.64 male(s)/female
- total population :: 0.9 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 11.37 deaths/1,000 live births
- male :: 14.94 deaths/1,000 live births
- female :: 7.74 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 127
*** Life expectancy at birth
- total population :: 76.56 years
- male :: 73.5 years
- female :: 79.68 years (2015 est.)
- country comparison to the world :: 83
*** Total fertility rate
1.84 children born/woman (2015 est.)
- country comparison to the world :: 146
*** Drinking water source
- improved :: 
urban: 98.1% of population
rural: 98.1% of population
total: 98.1% of population
- unimproved :: 
urban: 1.9% of population
rural: 1.9% of population
total: 1.9% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 97.7% of population
rural: 97.7% of population
total: 97.7% of population
- unimproved :: 
urban: 2.3% of population
rural: 2.3% of population
total: 2.3% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
*** Education expenditures
6% of GDP (2011)
- country comparison to the world :: 41
*** Literacy
- definition :: age 15 and over can read and write
- total population :: 97.5%
- male :: 97.5%
- female :: 97.5% (2015 est.)
*** School life expectancy (primary to tertiary education)
- total :: 13 years
- male :: 13 years
- female :: 14 years (2012)
*** Unemployment, youth ages 15-24
- total :: 23.2%
- male :: 23.5%
- female :: 22.9% (2007 est.)
- country comparison to the world :: 43
** Government
*** Country name
- conventional long form :: none
- conventional short form :: Aruba
*** Dependency status
constituent country of the Kingdom of the Netherlands; full autonomy in internal affairs obtained in 1986 upon separation from the Netherlands Antilles; Dutch Government responsible for defense and foreign affairs
*** Government type
parliamentary democracy
*** Capital
- name :: Oranjestad
- geographic coordinates :: 12 31 N, 70 02 W
- time difference :: UTC-4 (1 hour ahead of Washington, DC, during Standard Time)
*** Administrative divisions
none (part of the Kingdom of the Netherlands)
*** Independence
none (part of the Kingdom of the Netherlands)
*** National holiday
Flag Day, 18 March (1976)
*** Constitution
previous 1947, 1955; latest drafted and approved August 1985, enacted 1 January 1986 (regulates governance of Aruba, but is subordinate to the Charter for the Kingdom of the Netherlands); note - in October 2010, following dissolution of the Netherlands Antilles, Aruba became a constituent country within the Kingdom of the Netherlands (2013)
*** Legal system
civil law system based on the Dutch civil code
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: King WILLEM-ALEXANDER of the Netherlands (since 30 April 2013); represented by Governor General Fredis REFUNJOL (since 11 May 2004)
- head of government :: Prime Minister Michiel "Mike" Godfried EMAN (since 30 October 2009)
- cabinet :: Council of Ministers elected by the Legislature (Staten)
- elections/appointments :: the monarchy is hereditary; governor general appointed by the monarch for a 6-year term; prime minister and deputy prime minister indirectly elected by the Staten for 4-year tern; election last held on 25 September 2009 (next to be held by September 2013)
- election results :: Michiel "Mike" Godfried EMAN (AVP) elected prime minister; percent of legislative vote - NA
*** Legislative branch
- description :: unicameral Legislature or Staten (21 seats; members directly elected in a single nationwide constituency by proportional representation vote; members serve 4-year terms)
- elections :: last held on 27 September 2013 (next to be held in 2017)
- election results :: percent of vote by party - NA; seats by party - AVP 13, MEP 8
*** Judicial branch
- highest court(s) :: Joint Court of Justice of Aruba, Curacao, Sint Maarten, and of Bonaire, Sint Eustatitus and Saba or "Joint Court of Justice" (consists of the presiding judge, NA members, and NA substitutes); final appeals heard by the Supreme Court, in The Hague, Netherlands
note - prior to 2010, the Joint Court of Justice was the Common Court of Justice of the Netherlands Antilles and Aruba
- judge selection and term of office :: Joint Court judges appointed by the monarch for life
- subordinate courts :: Courts in First Instance
*** Political parties and leaders
Aliansa/Aruban Social Movement or MSA [Robert WEVER]
Aruban Liberal Organization or OLA [Glenbert CROES]
Aruban Patriotic Movement or MPA [Monica ARENDS-KOCK]
Aruban Patriotic Party or PPA [Benny NISBET]
Aruban People's Party or AVP [Michiel "Mike" EMAN]
People's Electoral Movement Party or MEP [Nelson O. ODUBER]
Real Democracy or PDR [Andin BIKKER]
RED [Rudy LAMPE]
Workers Political Platform or PTT [Gregorio WOLFF]
*** Political pressure groups and leaders
- other :: environmental groups
*** International organization participation
Caricom (observer), FATF, ILO, IMF, Interpol, IOC, ITUC (NGOs), UNESCO (associate), UNWTO (associate), UPU
*** Diplomatic representation in the US
none (represented by the Kingdom of the Netherlands); note - there is a Minister Plenipotentiary for Aruba at the Embassy of the Kingdom of the Netherlands
*** Diplomatic representation from the US
the US does not have an embassy in Aruba; the Consul General to Curacao is accredited to Aruba
*** Flag description
blue, with two narrow, horizontal, yellow stripes across the lower portion and a red, four-pointed star outlined in white in the upper hoist-side corner; the star represents Aruba and its red soil and white beaches, its four points the four major languages (Papiamento, Dutch, Spanish, English) as well as the four points of a compass, to indicate that its inhabitants come from all over the world; the blue symbolizes Caribbean waters and skies; the stripes represent the island's two main "industries": the flow of tourists to the sun-drenched beaches and the flow of minerals from the earth
*** National symbol(s)
Hooiberg (Haystack) Hill; national colors: blue, yellow, red, white
*** National anthem
- name :: "Aruba Deshi Tera" (Aruba Precious Country)
- lyrics/music :: Juan Chabaya 'Padu' LAMPE/Rufo Inocencio WEVER
- note :: local anthem adopted 1986; as part of the Kingdom of the Netherlands, "Het Wilhelmus" is official (see Netherlands)

** Economy
*** Economy - overview
Tourism, petroleum bunkering, hospitality, and financial and business services are the mainstays of the small open Aruban economy. Tourist arrivals have rebounded strongly following a dip after the 2008 global financial crisis. Tourism now accounts for over 80% of economic activity. Over 1.5 million tourists per year visit Aruba, with 75% of those from the US. The rapid growth of the tourism sector has resulted in a substantial expansion of other activities. Construction continues to boom with hotel capacity five times the 1985 level. Aruba is heavily dependent on imports and is making efforts to expand exports to achieve a more desirable trade balance. Almost all consumer and capital goods are imported, with the US, the Netherlands, and Panama being the major suppliers. Aruba weathered two major shocks in recent years: fallout from the global financial crisis, which had its largest impact on tourism, and the closure of its oil refinery in 2009. However, tourism and related industries have continued to grow, and the Aruban government is working to attract more diverse industries. Aruba's banking sector withstood the recession well, and unemployment has significantly decreased.
*** GDP (purchasing power parity)
$2.516 billion (2009 est.)
$2.258 billion (2005 est.)
$2.205 billion (2004 est.)
- country comparison to the world :: 188
*** GDP (official exchange rate)
$2.516 billion (2009 est.)
*** GDP - real growth rate
2.4% (2005 est.)
- country comparison to the world :: 136
*** GDP - per capita (PPP)
$25,300 (2011 est.)
- country comparison to the world :: 67
*** GDP - composition, by end use
- household consumption :: 62.9%
- government consumption :: 26%
- investment in fixed capital :: NA%
- investment in inventories :: NA%
- exports of goods and services :: NA%
- imports of goods and services :: -87.6%
 (2011 est.)
*** GDP - composition, by sector of origin
- agriculture :: 0.4%
- industry :: 33.3%
- services :: 66.3% (2002 est.)
*** Agriculture - products
aloes; livestock; fish
*** Industries
tourism, petroleum transshipment facilities, banking
*** Industrial production growth rate
NA%
*** Labor force
51,610
- note :: of the 51,610 workers aged 15 and over in the labor force, 32,252 were born in Aruba and 19,353 came from abroad; foreign workers are 38% of the employed population (2007 est.)
- country comparison to the world :: 192
*** Labor force - by occupation
- agriculture :: NA%
- industry :: NA%
- services :: NA%
- note :: most employment is in wholesale and retail trade, followed by hotels and restaurants
*** Unemployment rate
6.9% (2005 est.)
- country comparison to the world :: 73
*** Population below poverty line
NA%
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $622.5 million
- expenditures :: $808.2 million (2014 est.)
*** Taxes and other revenues
24.7% of GDP (2014 est.)
- country comparison to the world :: 119
*** Budget surplus (+) or deficit (-)
-7.4% of GDP (2014 est.)
- country comparison to the world :: 195
*** Public debt
67% of GDP (2013)
55% of GDP (2012)
- country comparison to the world :: 45
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
0.5% (2014 est.)
-2.4% (2013 est.)
- country comparison to the world :: 46
*** Central bank discount rate
1% (31 December 2010)
3% (31 December 2009)
- country comparison to the world :: 126
*** Commercial bank prime lending rate
8.3% (31 December 2014 est.)
8.5% (31 December 2013 est.)
- country comparison to the world :: 112
*** Stock of narrow money
$957.9 million (31 December 2013 est.)
$957.9 million (31 December 2013 est.)
- country comparison to the world :: 152
*** Stock of broad money
$1.839 billion (31 December 2013 est.)
$1.91 billion (31 December 2012 est.)
- country comparison to the world :: 157
*** Stock of domestic credit
$1.659 billion (31 December 2013 est.)
$1.659 billion (31 December 2013 est.)
- country comparison to the world :: 145
*** Exports
$312.7 million (2014 est.)
$284.3 million (2013 est.)
- country comparison to the world :: 180
*** Exports - commodities
live animals and animal products, art and collectibles, machinery and electrical equipment, transport equipment
*** Exports - partners
Colombia 31.2%, Netherlands Antilles 21.7%, US 15.7%, Venezuela 12.4%, Netherlands 6.1% (2014)
*** Imports
$1.528 billion (2014 est.)
$1.364 billion (2013 est.)
- country comparison to the world :: 172
*** Imports - commodities
machinery and electrical equipment, refined oil for bunkering and reexport, chemicals; foodstuffs
*** Imports - partners
US 56%, Netherlands 11.3% (2014)
*** Debt - external
$533.4 million (2005 est.)
- country comparison to the world :: 176
*** Exchange rates
Aruban guilders/florins per US dollar -
1.79 (2014 est.)
1.79 (2013 est.)
1.79 (2012 est.)
1.79 (2011 est.)
** Energy
*** Electricity - production
980 million kWh (2011 est.)
- country comparison to the world :: 147
*** Electricity - consumption
911.4 million kWh (2011 est.)
- country comparison to the world :: 154
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 97
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 111
*** Electricity - installed generating capacity
320,000 kW (2011 est.)
- country comparison to the world :: 151
*** Electricity - from fossil fuels
90.6% of total installed capacity (2011 est.)
- country comparison to the world :: 72
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 32
*** Electricity - from hydroelectric plants
0% of total installed capacity (2011 est.)
- country comparison to the world :: 152
*** Electricity - from other renewable sources
9.4% of total installed capacity (2011 est.)
- country comparison to the world :: 34
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 148
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 73
*** Crude oil - imports
228,800 bbl/day (2010 est.)
- country comparison to the world :: 31
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 102
*** Refined petroleum products - production
234,200 bbl/day (2010 est.)
- country comparison to the world :: 51
*** Refined petroleum products - consumption
5,970 bbl/day (2013 est.)
- country comparison to the world :: 163
*** Refined petroleum products - exports
234,200 bbl/day (2010 est.)
- country comparison to the world :: 26
*** Refined petroleum products - imports
6,725 bbl/day (2010 est.)
- country comparison to the world :: 138
*** Natural gas - production
1 cu m (2012 est.)
- country comparison to the world :: 98
*** Natural gas - consumption
1 cu m (2012 est.)
- country comparison to the world :: 115
*** Natural gas - exports
1 cu m (2012 est.)
- country comparison to the world :: 50
*** Natural gas - imports
1 cu m (2012 est.)
- country comparison to the world :: 77
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 106
*** Carbon dioxide emissions from consumption of energy
876,400 Mt (2012 est.)
- country comparison to the world :: 169
** Communications
*** Telephones - fixed lines
- total subscriptions :: 35,000
- subscriptions per 100 inhabitants :: 32 (2014 est.)
- country comparison to the world :: 169
*** Telephones - mobile cellular
- total :: 139,700
- subscriptions per 100 inhabitants :: 126 (2014 est.)
- country comparison to the world :: 185
*** Telephone system
- general assessment :: modern fully automatic telecommunications system
- domestic :: increased competition through privatization; 3 mobile-cellular service providers are now licensed
- international :: country code - 297; landing site for the PAN-AM submarine telecommunications cable system that extends from the US Virgin Islands through Aruba to Venezuela, Colombia, Panama, and the west coast of South America; extensive interisland microwave radio relay links (2007)
*** Broadcast media
2 commercial TV stations; cable TV subscription service provides access to foreign channels; about 20 commercial radio stations broadcast (2007)
*** Radio broadcast stations
AM 2, FM 16, shortwave 0 (2004)
*** Television broadcast stations
1 (1997)
*** Internet country code
.aw
*** Internet users
- total :: 87,700
- percent of population :: 79.2% (2014 est.)
- country comparison to the world :: 172
** Transportation
*** Airports
1 (2013)
- country comparison to the world :: 210
*** Airports - with paved runways
- total :: 1
- 2,438 to 3,047 m :: 1 (2013)
*** Ports and terminals
- major seaport(s) :: Barcadera, Oranjestad
- oil terminal(s) :: Sint Nicolaas
- cruise port(s) :: Oranjestad
** Military
*** Military branches
no regular military forces (2011)
*** Manpower available for military service
- males age 16-49 :: 24,891
- females age 16-49 :: 26,202 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 20,527
- females age 16-49 :: 21,493 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 767
- female :: 743 (2010 est.)
*** Military - note
defense is the responsibility of the Netherlands; the Aruba security services focus on organized crime and terrorism
** Transnational Issues
*** Disputes - international
none
*** Illicit drugs
transit point for US- and Europe-bound narcotics with some accompanying money-laundering activity; relatively high percentage of population consumes cocaine