** Introduction
*** Background
Settled as early as 1000 B.C., Samoa was not reached by European explorers until the 18th century. International rivalries in the latter half of the 19th century were settled by an 1899 treaty in which Germany and the US divided the Samoan archipelago. The US formally occupied its portion - a smaller group of eastern islands with the excellent harbor of Pago Pago - the following year.
** Geography
*** Location
Oceania, group of islands in the South Pacific Ocean, about halfway between Hawaii and New Zealand
*** Geographic coordinates
14 20 S, 170 00 W
*** Map references
Oceania
*** Area
- total :: 199 sq km
- land :: 199 sq km
- water :: 0 sq km
- note :: includes Rose Island and Swains Island
- country comparison to the world :: 216
*** Area - comparative
slightly larger than Washington, DC
*** Land boundaries
0 km
*** Coastline
116 km
*** Maritime claims
- territorial sea :: 12 nm
- exclusive economic zone :: 200 nm
*** Climate
tropical marine, moderated by southeast trade winds; annual rainfall averages about 3 m; rainy season (November to April), dry season (May to October); little seasonal temperature variation
*** Terrain
five volcanic islands with rugged peaks and limited coastal plains, two coral atolls (Rose Island, Swains Island)
*** Elevation extremes
- lowest point :: Pacific Ocean 0 m
- highest point :: Lata Mountain 964 m
*** Natural resources
pumice, pumicite
*** Land use
- agricultural land :: 21.7%
arable land 13.3%; permanent crops 8.4%; permanent pasture 0%
- forest :: 78.3%
- other :: 0% (2011 est.)
*** Irrigated land
NA
*** Natural hazards
typhoons common from December to March
- volcanism :: limited volcanic activity on the Ofu and Olosega Islands; neither has erupted since the 19th century
*** Environment - current issues
limited natural freshwater resources; the water division of the government has spent substantial funds in the past few years to improve water catchments and pipelines
*** Geography - note
Pago Pago has one of the best natural deepwater harbors in the South Pacific Ocean, sheltered by shape from rough seas and protected by peripheral mountains from high winds; strategic location in the South Pacific Ocean
** People and Society
*** Nationality
- noun :: American Samoan(s) (US nationals)
- adjective :: American Samoan
*** Ethnic groups
Native Hawaiian and other Pacific Islander 92.6% (includes Samoan 88.9%, Tongan 2.9%, other .8%), Asian 3.6% (includes Filipino 2.2%, other 1.4%), mixed 2.7%, other 1.2% (2010 est.)
*** Languages
Samoan 88.6% (closely related to Hawaiian and other Polynesian languages), English 3.9%, Tongan 2.7%, other Pacific islander 3%, other 1.8%
- note :: most people are bilingual (2010 est.)
*** Religions
Christian 98.3%, other 1%, unaffiliated 0.7% (2010 est.)
*** Population
54,343 (July 2015 est.)
- country comparison to the world :: 208
*** Age structure
- 0-14 years :: 24.45% (male 6,506/female 6,780)
- 15-24 years :: 19.61% (male 5,264/female 5,395)
- 25-54 years :: 42.1% (male 11,775/female 11,105)
- 55-64 years :: 8.69% (male 2,326/female 2,397)
- 65 years and over :: 5.14% (male 1,287/female 1,508) (2015 est.)
- population pyramid ::  
*** Median age
- total :: 28.8 years
- male :: 29.4 years
- female :: 28.3 years (2015 est.)
*** Population growth rate
-0.3% (2015 est.)
- country comparison to the world :: 219
*** Birth rate
22.89 births/1,000 population (2015 est.)
- country comparison to the world :: 70
*** Death rate
4.75 deaths/1,000 population (2015 est.)
- country comparison to the world :: 197
*** Net migration rate
-21.13 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 222
*** Urbanization
- urban population :: 87.2% of total population (2015)
- rate of urbanization :: -0.13% annual rate of change (2010-15 est.)
*** Major urban areas - population
PAGO PAGO (capital) 48,000 (2014)
*** Sex ratio
- at birth :: 1.06 male(s)/female
- 0-14 years :: 0.96 male(s)/female
- 15-24 years :: 0.98 male(s)/female
- 25-54 years :: 1.06 male(s)/female
- 55-64 years :: 0.97 male(s)/female
- 65 years and over :: 0.85 male(s)/female
- total population :: 1 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 8.69 deaths/1,000 live births
- male :: 11.16 deaths/1,000 live births
- female :: 6.09 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 149
*** Life expectancy at birth
- total population :: 75.14 years
- male :: 72.18 years
- female :: 78.28 years (2015 est.)
- country comparison to the world :: 105
*** Total fertility rate
2.92 children born/woman (2015 est.)
- country comparison to the world :: 56
*** Drinking water source
- improved :: 
urban: 100% of population
rural: 100% of population
total: 100% of population
- unimproved :: 
urban: 0% of population
rural: 0% of population
total: 0% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 62.5% of population
rural: 62.5% of population
total: 62.5% of population
- unimproved :: 
urban: 37.5% of population
rural: 37.5% of population
total: 37.5% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
*** Education expenditures
NA
** Government
*** Country name
- conventional long form :: Territory of American Samoa
- conventional short form :: American Samoa
- abbreviation :: AS
- note :: the name "Samoa" is composed of two parts, "sa" meaning sacred and "moa" meaning center, so the name can mean Holy Center; alternatively, it can mean "place of the sacred moa bird" of Polynesian mythology
*** Dependency status
unincorporated and unorganized territory of the US; administered by the Office of Insular Affairs, US Department of the Interior
*** Government type
NA
*** Capital
- name :: Pago Pago
- geographic coordinates :: 14 16 S, 170 42 W
- time difference :: UTC-11 (6 hours behind Washington, DC, during Standard Time)
*** Administrative divisions
none (territory of the US); there are no first-order administrative divisions as defined by the US Government, but there are 3 districts and 2 islands* at the second order; Eastern, Manu'a, Rose Island*, Swains Island*, Western
*** Independence
none (territory of the US)
*** National holiday
Flag Day, 17 April (1900)
*** Constitution
ratified 2 June 1966, effective 1 July 1967 (2013)
*** Legal system
mixed legal system of US common law and customary law
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: President Barack H. OBAMA (since 20 January 2009); Vice President Joseph R. BIDEN (since 20 January 2009)
- head of government :: Governor Lolo Matalasi MOLIGA (since 3 January 2013)
- cabinet :: Cabinet consists of 12 department directors appointed by the governor with the consent of the Legislative Assembly
- elections/appointments :: president and vice president indirectly elected on the same ballot by an Electoral College of 'electors' chosen from each state to serve a 4-year term (eligible for a second term); under the US Constitution, residents of unincorporated territories, such as American Samoa, do not vote in elections for US president and vice president; however, they may vote in Democratic and Republican presidential primary elections; governor and lieutenant governor directly elected on the same ballot by absolute majority popular vote in 2 rounds if needed for a 4-year term (eligible for a second term); election last held on 6 November 2012 with a runoff on 20 November 2012 (next to be held in November 2016)
- election results :: Lolo Matalasi MOLIGA elected governor; percent of vote in second round - Lolo Matalasi MOLIGA (independent) 52.9%, Faoa Aitofele SUNIA (Democratic Party) 47.1%
*** Legislative branch
- description :: bicameral Fono or Legislative Assembly consists of the Senate (18 seats; members indirectly selected by regional governing councils to serve 4-year terms) and the House of Representatives (21 seats; 20 members directly elected by simple majority vote and 1 decided by public meeting on Swains Island; members serve 2-year terms)
- elections :: House of Representatives - last held on 4 November 2014 (next to be held in November 2016); Senate - last held on 6 November 2012 (next to be held in November 2016)
- election results :: Senate - percent of vote by party - NA; seats by party - independents 18; House of Representatives - percent of vote by party - NA; seats by party - independents 20
- note :: American Samoa elects 1 member by simple majority vote to serve a 2-year term as a delegate to the US House of Representatives; the delegate can vote when serving on a committee and when the House meets as the Committee of the Whole House, but not when legislation is submitted for a “full floor” House vote; election of delegate last held on 4 November 2014 (next to be held on November 2016)
*** Judicial branch
- highest court(s) :: High Court of American Samoa (consists of the chief justice, associate chief justice, and 6 Samoan associate judges and organized into trial, family, drug, and appellate divisions)
note - American Samoa has no US federal courts
- judge selection and term of office :: chief justice and associate chief justice appointed by the US Secretary of the Interior to serve for life; Samoan associate judges appointed by the governor to serve for life
- subordinate courts :: district and village courts
*** Political parties and leaders
Democratic Party [Oreta M. TOGAFAU]
Republican Party [Tautai A. F. FAALEVAO]
*** International organization participation
AOSIS (observer), Interpol (subbureau), IOC, PIF (observer), SPC
*** Diplomatic representation in the US
none (territory of the US)
*** Diplomatic representation from the US
none (territory of the US)
*** Flag description
blue, with a white triangle edged in red that is based on the fly side and extends to the hoist side; a brown and white American bald eagle flying toward the hoist side is carrying two traditional Samoan symbols of authority, a war club known as a "fa'alaufa'i" (upper; left talon), and a coconut fiber fly whisk known as a "fue" (lower; right talon); the combination of symbols broadly mimics that seen on the US Great Seal and reflects the relationship between the United States and American Samoa
*** National symbol(s)
a fue (coconut fiber fly whisk) crossed with a to'oto'o (staff); national colors: red, white, blue
*** National anthem
- name :: "Amerika Samoa" (American Samoa)
- lyrics/music :: Mariota Tiumalu TUIASOSOPO/Napoleon Andrew TUITELELEAPAGA
- note :: local anthem adopted 1950; as a territory of the United States, "The Star-Spangled Banner" is official (see United States)
** Economy
*** Economy - overview
American Samoa has a traditional Polynesian economy in which more than 90% of the land is communally owned. Economic activity is strongly linked to the US with which American Samoa conducts most of its commerce. Tuna fishing and tuna processing plants are the backbone of the private sector with canned tuna the primary export. The two tuna canneries accounted for 13.1% of employment in 2013. In late September 2009, an earthquake and the resulting tsunami devastated American Samoa and nearby Samoa, disrupting transportation and power generation, and resulting in about 200 deaths. The US Federal Emergency Management Agency oversaw a relief program of nearly $25 million. Transfers from the US Government add substantially to American Samoa's economic well-being. Attempts by the government to develop a larger and broader economy are restrained by Samoa's remote location, its limited transportation, and its devastating hurricanes. Tourism is a promising developing sector. In 2015, a new fish processing company completed refurbishing the processing facilities left behind by one of the two canneries that closed in 2009 and opened a new cannery. With two operating canneries once again, fish processing and exports will rise in 2015 and beyond.
*** GDP (purchasing power parity)
$711 million (2013 est.)
$718 million (2012 est.)
$647 million (2011 est.)
- country comparison to the world :: 211
*** GDP (official exchange rate)
$748.6 million (2005)
*** GDP - real growth rate
-2.4% (2013 est.)
-2.7% (2012 est.)
0.6% (2012 est.)
- country comparison to the world :: 111
*** GDP - per capita (PPP)
$13,000 (2013 est.)
$13,100 (2012 est.)
$11,700 (2011 est.)
- country comparison to the world :: 145
*** GDP - composition, by end use
- household consumption :: 54.6%
- government consumption :: 52.8%
- investment if fixed capital :: 2.7%
- investment in inventories :: 2.3%
- exports of goods and services :: 54.4%
- imports of goods and services :: -66.8% (2012)
*** GDP - composition, by sector of origin
- agriculture :: 27.4%
- industry :: 12.4%
- services :: 60.2% (2012)
*** Agriculture - products
bananas, coconuts, vegetables, taro, breadfruit, yams, copra, pineapples, papayas; dairy products, livestock
*** Industries
tuna canneries (largely supplied by foreign fishing vessels), handicrafts
*** Industrial production growth rate
NA%
*** Labor force
16,090 (2013)
- country comparison to the world :: 212
*** Labor force - by occupation
- agriculture :: NA
- industry :: 13.1%
- services :: 86.9% (2013)
*** Unemployment rate
29.8% (2005)
- country comparison to the world :: 180
*** Population below poverty line
NA%
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $241.2 million
- expenditures :: $243.7 million (2013 est.)
*** Taxes and other revenues
32.2% of GDP (2013 est.)
- country comparison to the world :: 72
*** Budget surplus (+) or deficit (-)
-0.3% of GDP (2013 est.)
- country comparison to the world :: 185
*** Fiscal year
1 October - 30 September
*** Inflation rate (consumer prices)
2.1% (2013)
3.5% (2012)
- country comparison to the world :: 103
*** Exports
$459 million (2013 est.)
$489 million (2012)
- country comparison to the world :: 177
*** Exports - commodities
canned tuna 93%
*** Exports - partners
US 100%
*** Imports
$564 million (2013 est.)
$508 million (2012)
- country comparison to the world :: 198
*** Imports - commodities
raw materials for canneries, food, petroleum products, machinery and parts
*** Debt - external
$NA
*** Exchange rates
the US dollar is used
** Energy
*** Electricity - production
156.4 million kWh (2013 est.)
- country comparison to the world :: 189
*** Electricity - consumption
144.2 million kWh (2011 est.)
- country comparison to the world :: 194
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 102
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 116
*** Electricity - installed generating capacity
45,000 kW (2011 est.)
- country comparison to the world :: 191
*** Electricity - from fossil fuels
100% of total installed capacity (2013 est.)
- country comparison to the world :: 3
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 41
*** Electricity - from hydroelectric plants
0% of total installed capacity (2011 est.)
- country comparison to the world :: 155
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 154
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 151
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 77
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 154
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 105
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 119
*** Refined petroleum products - consumption
4,090 bbl/day (2013 est.)
- country comparison to the world :: 175
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 149
*** Refined petroleum products - imports
2,003 bbl/day (2010 est.)
- country comparison to the world :: 180
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 101
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 117
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 56
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 154
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 109
*** Carbon dioxide emissions from consumption of energy
607,000 Mt (2012 est.)
- country comparison to the world :: 177
** Communications
*** Telephones - fixed lines
- total subscriptions :: 9,900
- subscriptions per 100 inhabitants :: 18 (2014 est.)
- country comparison to the world :: 199
*** Telephone system
- general assessment :: good telex, telegraph, facsimile, and cellular telephone services
- domestic :: domestic satellite system with 1 Comsat earth station
- international :: country code - 1-684; satellite earth station - 1 (Intelsat-Pacific Ocean)
*** Broadcast media
3 TV stations; multi-channel pay TV services are available; about a dozen radio stations, some of which are repeater stations (2009)
*** Radio broadcast stations
AM 2, FM 3, shortwave 0 (2005)
*** Television broadcast stations
1 (2006)
*** Internet country code
.as
*** Internet users
NA
** Transportation
*** Airports
3 (2013)
- country comparison to the world :: 192
*** Airports - with paved runways
- total :: 3
- over 3,047 m :: 1
- 914 to 1,523 m :: 1
- under 914 m :: 1 (2013)
*** Roadways
- total :: 241 km (2008)
- country comparison to the world :: 207
*** Ports and terminals
- major seaport(s) :: Pago Pago
** Military
*** Manpower fit for military service
- males age 16-49 :: 14,562
- females age 16-49 :: 14,129 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 775
- female :: 762 (2010 est.)
*** Military - note
defense is the responsibility of the US
** Transnational Issues
*** Disputes - international
Tokelau included American Samoa's Swains Island (Olosega) in its 2006 draft independence constitution