** Introduction
*** Background
The Sultanate of Brunei's influence peaked between the 15th and 17th centuries when its control extended over coastal areas of northwest Borneo and the southern Philippines. Brunei subsequently entered a period of decline brought on by internal strife over royal succession, colonial expansion of European powers, and piracy. In 1888, Brunei became a British protectorate; independence was achieved in 1984. The same family has ruled Brunei for over six centuries. Brunei benefits from extensive petroleum and natural gas fields, the source of one of the highest per capita GDPs in the world.
** Geography
*** Location
Southeastern Asia, along the northern coast of the island of Borneo, bordering the South China Sea and Malaysia
*** Geographic coordinates
4 30 N, 114 40 E
*** Map references
Southeast Asia
*** Area
- total :: 5,765 sq km
- land :: 5,265 sq km
- water :: 500 sq km
- country comparison to the world :: 173
*** Area - comparative
slightly smaller than Delaware
*** Land boundaries
- total :: 266 km
- border countries (1) :: Malaysia 266 km
*** Coastline
161 km
*** Maritime claims
- territorial sea :: 12 nm
- exclusive economic zone :: 200 nm or to median line
*** Climate
tropical; hot, humid, rainy
*** Terrain
flat coastal plain rises to mountains in east; hilly lowland in west
*** Elevation extremes
- lowest point :: South China Sea 0 m
- highest point :: Bukit Pagon 1,850 m
*** Natural resources
petroleum, natural gas, timber
*** Land use
- agricultural land :: 2.5%
arable land 0.8%; permanent crops 1.1%; permanent pasture 0.6%
- forest :: 71.8%
- other :: 25.7% (2011 est.)
*** Irrigated land
10 sq km (2003)
*** Total renewable water resources
8.5 cu km (2011)
*** Freshwater withdrawal (domestic/industrial/agricultural)
- total :: 0.09  cu km/yr (97%/0%/3%)
- per capita :: 301.6  cu m/yr (2009)
*** Natural hazards
typhoons, earthquakes, and severe flooding are rare
*** Environment - current issues
seasonal smoke/haze resulting from forest fires in Indonesia
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Desertification, Endangered Species, Hazardous Wastes, Law of the Sea, Ozone Layer Protection, Ship Pollution
- signed, but not ratified :: none of the selected agreements
*** Geography - note
close to vital sea lanes through South China Sea linking Indian and Pacific Oceans; two parts physically separated by Malaysia; almost an enclave within Malaysia
** People and Society
*** Nationality
- noun :: Bruneian(s)
- adjective :: Bruneian
*** Ethnic groups
Malay 65.7%, Chinese 10.3%, other indigenous 3.4%, other 20.6% (2011 est.)
*** Languages
Malay (official), English, Chinese dialects
*** Religions
Muslim (official) 78.8%, Christian 8.7%, Buddhist 7.8%, other (includes indigenous beliefs) 4.7% (2011 est.)
*** Population
429,646 (July 2015 est.)
- country comparison to the world :: 175
*** Age structure
- 0-14 years :: 23.82% (male 52,750/female 49,579)
- 15-24 years :: 17.13% (male 36,485/female 37,127)
- 25-54 years :: 46.9% (male 97,228/female 104,286)
- 55-64 years :: 7.88% (male 17,366/female 16,470)
- 65 years and over :: 4.27% (male 8,925/female 9,430) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 38%
- youth dependency ratio :: 31.9%
- elderly dependency ratio :: 6.1%
- potential support ratio :: 16.4% (2015 est.)
*** Median age
- total :: 29.6 years
- male :: 29.2 years
- female :: 29.9 years (2015 est.)
*** Population growth rate
1.62% (2015 est.)
- country comparison to the world :: 72
*** Birth rate
17.32 births/1,000 population (2015 est.)
- country comparison to the world :: 107
*** Death rate
3.52 deaths/1,000 population (2015 est.)
- country comparison to the world :: 215
*** Net migration rate
2.43 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 41
*** Urbanization
- urban population :: 77.2% of total population (2015)
- rate of urbanization :: -1.79% annual rate of change (2010-15 est.)
*** Major urban areas - population
BANDAR SERI BEGAWAN (capital) 241,000
- note :: the boundaries of the capital city were expanded in 2007, greatly increasing the city area; the population of the capital increased tenfold (2011)
*** Sex ratio
- at birth :: 1.05 male(s)/female
- 0-14 years :: 1.06 male(s)/female
- 15-24 years :: 0.98 male(s)/female
- 25-54 years :: 0.93 male(s)/female
- 55-64 years :: 1.05 male(s)/female
- 65 years and over :: 0.95 male(s)/female
- total population :: 0.98 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 10.16 deaths/1,000 live births
- male :: 12.09 deaths/1,000 live births
- female :: 8.14 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 137
*** Life expectancy at birth
- total population :: 76.97 years
- male :: 74.64 years
- female :: 79.41 years (2015 est.)
- country comparison to the world :: 76
*** Total fertility rate
1.8 children born/woman (2015 est.)
- country comparison to the world :: 152
*** Health expenditures
2.5% of GDP (2013)
- country comparison to the world :: 188
*** Physicians density
1.44 physicians/1,000 population (2012)
*** Hospital bed density
2.8 beds/1,000 population (2012)
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
*** Obesity - adult prevalence rate
18.6% (2014)
- country comparison to the world :: 141
*** Education expenditures
3.8% of GDP (2014)
- country comparison to the world :: 126
*** Literacy
- definition :: age 15 and over can read and write
- total population :: 96%
- male :: 97.5%
- female :: 94.5% (2015 est.)
*** School life expectancy (primary to tertiary education)
- total :: 15 years
- male :: 14 years
- female :: 15 years (2012)
** Government
*** Country name
- conventional long form :: Brunei Darussalam
- conventional short form :: Brunei
- local long form :: Negara Brunei Darussalam
- local short form :: Brunei
*** Government type
constitutional sultanate (locally known as Malay Islamic Monarchy or MIB)
*** Capital
- name :: Bandar Seri Begawan
- geographic coordinates :: 4 53 N, 114 56 E
- time difference :: UTC+8 (13 hours ahead of Washington, DC, during Standard Time)
*** Administrative divisions
4 districts (daerah-daerah, singular - daerah); Belait, Brunei-Muara, Temburong, Tutong
*** Independence
1 January 1984 (from the UK)
*** National holiday
National Day, 23 February (1984); note - 1 January 1984 was the date of independence from the UK, 23 February 1984 was the date of independence from British protection
*** Constitution
drafted 1954 to 1959, signed 29 September 1959; amended 1984, 2004, 2011; note - some constitutional provisions suspended since 1962 under a State of Emergency, others since independence in 1984 (2011)
*** Legal system
mixed legal system based on English common law and Islamic law; note - in May 2014, the first phase of a sharia-based penal codes was instituted, which applies to Muslims and non-Muslims and exists in parallel to the existing common law-based code
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; non-party state to the ICCt
*** Citizenship
- birthright citizenship :: no, unless the father is a citizen of Brunei
- dual citizenship recognized :: no
- residency requirement for naturalization :: 12 years
*** Suffrage
18 years of age for village elections; universal
*** Executive branch
- chief of state :: Sultan and Prime Minister Sir HASSANAL Bolkiah (since 5 October 1967); note - the monarch is both chief of state and head of government
- head of government :: Sultan and Prime Minister Sir HASSANAL Bolkiah (since 5 October 1967)
- cabinet :: Council of Ministers appointed and presided over by the monarch; note - 4 additional advisory councils appointed by the monarch are the Religious Council, Privy Council for constitutional issues, Council of Succession, and Legislative Council
- elections/appointments :: none; the monarchy is hereditary
*** Legislative branch
- description :: Legislative Council or Majlis Mesyuarat Negara Brunei (36 seats; members appointed by the sultan including 3 ex-officio members - the speaker and first and second secretaries; meets annually for approximately two weeks)
- elections :: last held in March 1962 (date of next election NA)
*** Judicial branch
- highest resident court(s) :: Supreme Court (consists of Court of Appeal and High Court, each with a chief justice and 2 judges); Sharia Court of Appeal (consists of judges appointed by the monarch); note - Brunei has a dual judicial system of secular and sharia (religious) courts; the Judicial Committee of Privy Council in London serves as the final appellate court for civil cases only
- judge selection and term of office :: Supreme Court judges appointed by the monarch to serve until age 65, and older if approved by the monarch; Sharia Court of Appeal judges appointed by the monarch; judge tenure NA
- subordinate courts :: Intermediate Court; Magistrate's Courts; Juvenile Court; small claims courts; lower sharia courts
*** Political parties and leaders
National Development Party or NDP [YASSIN Affendi]
- note :: Brunei National Solidarity Party or PPKB [Abdul LATIF bin Chuchu] and People's Awareness Party or PAKAR [Awang Haji MAIDIN bin Haji Ahmad] were deregistered in 2007; parties are small and have limited activity
*** Political pressure groups and leaders
NA
*** International organization participation
ADB, APEC, ARF, ASEAN, C, CP, EAS, FAO, G-77, IAEA, IBRD, ICAO, ICC (NGOs), ICRM, IDA, IFRCS, ILO, IMF, IMO, IMSO, Interpol, IOC, ISO (correspondent), ITSO, ITU, NAM, OIC, OPCW, UN, UNCTAD, UNESCO, UNIFIL, UNWTO, UPU, WCO, WHO, WIPO, WMO, WTO
*** Diplomatic representation in the US
- chief of mission :: Ambassador (vacant); Charge d'Affaires Dk Norhashimah Pg Mohd HASSAN
- chancery :: 3520 International Court NW, Washington, DC 20008
- telephone :: [1] (202) 237-1838
- FAX :: [1] (202) 885-0560
- consulate(s) :: New York
*** Diplomatic representation from the US
- chief of mission :: Ambassador Craig B. ALLEN (since 9 March 2015)
- embassy :: Simpang 336-52-16-9, Jalan Datu, Bandar Seri Begawan, BC4115
- mailing address :: Unit 4280, Box 40, FPO AP 96507; P.O. Box 2991, Bandar Seri Begawan BS8675, Negara Brunei Darussalam
- telephone :: [673] 238-4616
- FAX :: [673] 238-4604
*** Flag description
yellow with two diagonal bands of white (top, almost double width) and black starting from the upper hoist side; the national emblem in red is superimposed at the center; yellow is the color of royalty and symbolizes the sultanate; the white and black bands denote Brunei's chief ministers; the emblem includes five main components: a swallow-tailed flag, the royal umbrella representing the monarchy, the wings of four feathers symbolizing justice, tranquility, prosperity, and peace, the two upraised hands signifying the government's pledge to preserve and promote the welfare of the people, and the crescent moon denoting Islam, the state religion; the state motto "Always render service with God's guidance" appears in yellow Arabic script on the crescent; a ribbon below the crescent reads "Brunei, the Abode of Peace"
*** National symbol(s)
royal parasol; national colors: yellow, white, black
*** National anthem
- name :: "Allah Peliharakan Sultan" (God Bless His Majesty)
- lyrics/music :: Pengiran Haji Mohamed YUSUF bin Pengiran Abdul Rahim/Awang Haji BESAR bin Sagap
- note :: adopted 1951

** Economy
*** Economy - overview
Brunei has a small well-to-do economy that depends on revenue from natural resource extraction but is also characterized by a mixture of foreign and domestic entrepreneurship, government regulation, welfare measures, and village tradition. Crude oil and natural gas production account for 70% of GDP and more than 90% of exports, with Japan and Korea as the primary export markets. Per capita GDP is among the highest in the world, and substantial income from overseas investment supplements income from domestic hydrocarbon production. For Bruneian citizens, who pay no taxes, the government provides for all medical services and free education through the university level. The government of Brunei has been emphasizing through policy and resource investments its strong desire to diversify its economy both within the oil and gas sector and to new sectors. Brunei is a founding member of the 12-nation Trans-Pacific Partnership (TPP) free trade agreement negotiations as well as the Regional Comprehensive Economic Partnership (RCEP) and, with the nine other ASEAN members, will form the ASEAN Economic Community in 2015.
*** GDP (purchasing power parity)
$30.21 billion (2014 est.)
$30.42 billion (2013 est.)
$30.97 billion (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 122
*** GDP (official exchange rate)
$15.1 billion (2014 est.)
*** GDP - real growth rate
-0.7% (2014 est.)
-1.8% (2013 est.)
0.9% (2012 est.)
- country comparison to the world :: 50
*** GDP - per capita (PPP)
$73,200 (2014 est.)
$73,700 (2013 est.)
$75,100 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 9
*** Gross national saving
56.1% of GDP (2014 est.)
54.3% of GDP (2013 est.)
47.1% of GDP (2012 est.)
- country comparison to the world :: 1
*** GDP - composition, by end use
- household consumption :: 20.6%
- government consumption :: 19.9%
- investment in fixed capital :: 16.8%
- investment in inventories :: 0%
- exports of goods and services :: 78.2%
- imports of goods and services :: -35.5%
 (2014 est.)
*** GDP - composition, by sector of origin
- agriculture :: 0.8%
- industry :: 66.5%
- services :: 32.8% (2014 est.)
*** Agriculture - products
rice, vegetables, fruits; chickens, water buffalo, cattle, goats, eggs
*** Industries
petroleum, petroleum refining, liquefied natural gas, construction, agriculture, transportation
*** Industrial production growth rate
-3% (2014 est.)
- country comparison to the world :: 187
*** Labor force
205,800 (2011 est.)
- country comparison to the world :: 169
*** Labor force - by occupation
- agriculture :: 4.2%
- industry :: 62.8%
- services :: 33% (2008 est.)
*** Unemployment rate
2.7% (2014 est.)
2.7% (2010)
- country comparison to the world :: 19
*** Population below poverty line
NA%
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $8.762 billion
- expenditures :: $6.27 billion (2014 est.)
*** Taxes and other revenues
50.3% of GDP (2014 est.)
- country comparison to the world :: 14
*** Budget surplus (+) or deficit (-)
14.3% of GDP (2014 est.)
- country comparison to the world :: 3
*** Fiscal year
1 April - 31 March
*** Inflation rate (consumer prices)
-0.2% (2014 est.)
0.4% (2013 est.)
- country comparison to the world :: 21
*** Commercial bank prime lending rate
5.5% (31 December 2014 est.)
5.5% (31 December 2013 est.)
- country comparison to the world :: 144
*** Stock of narrow money
$3.531 billion (31 December 2014 est.)
$3.517 billion (31 December 2013 est.)
- country comparison to the world :: 115
*** Stock of broad money
$11.92 billion (31 December 2013 est.)
$11.41 billion (31 December 2012 est.)
- country comparison to the world :: 101
*** Stock of domestic credit
$3.939 billion (31 December 2014 est.)
$3.452 billion (31 December 2013 est.)
- country comparison to the world :: 126
*** Market value of publicly traded shares
$NA
*** Current account balance
$3.558 billion (2014 est.)
$6.283 billion (2013 est.)
- country comparison to the world :: 32
*** Exports
$11.38 billion (2014 est.)
$11.46 billion (2013 est.)
- country comparison to the world :: 92
*** Exports - commodities
crude oil, natural gas, garments
*** Exports - partners
Japan 39%, South Korea 12.5%, Australia 9.7%, India 9.2%, Thailand 6.4%, Indonesia 5.8% (2014)
*** Imports
$4.308 billion (2014 est.)
$4.075 billion (2013 est.)
- country comparison to the world :: 139
*** Imports - commodities
iron and steel, motor vehicles, machinery and transport equipment, manufactured goods, food, chemicals
*** Imports - partners
Singapore 29.2%, China 26.9%, Malaysia 13.2%, US 8.5%, South Korea 4.5%, UK 4.1% (2014)
*** Debt - external
$0 (2005)
- note :: public external debt only; private external debt unavailable
- country comparison to the world :: 203
*** Exchange rates
Bruneian dollars (BND) per US dollar -
1.244 (2014 est.)
1.2512 (2013 est.)
1.25 (2012 est.)
1.2579 (2011 est.)
1.3635 (2010 est.)
** Energy
*** Electricity - production
3.5 billion kWh (2011 est.)
- country comparison to the world :: 127
*** Electricity - consumption
3.233 billion kWh (2011 est.)
- country comparison to the world :: 129
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 114
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 125
*** Electricity - installed generating capacity
759,000 kW (2011 est.)
- country comparison to the world :: 130
*** Electricity - from fossil fuels
100% of total installed capacity (2011 est.)
- country comparison to the world :: 9
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 58
*** Electricity - from hydroelectric plants
0% of total installed capacity (2011 est.)
- country comparison to the world :: 162
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 164
*** Crude oil - production
135,100 bbl/day (2013 est.)
- country comparison to the world :: 42
*** Crude oil - exports
147,900 bbl/day (2010 est.)
- country comparison to the world :: 34
*** Crude oil - imports
0 bbl/day (2011 est.)
- country comparison to the world :: 166
*** Crude oil - proved reserves
1.1 billion bbl (1 January 2014 est.)
- country comparison to the world :: 42
*** Refined petroleum products - production
13,500 bbl/day (2010 est.)
- country comparison to the world :: 102
*** Refined petroleum products - consumption
18,000 bbl/day (2013 est.)
- country comparison to the world :: 136
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 159
*** Refined petroleum products - imports
3,198 bbl/day (2010 est.)
- country comparison to the world :: 169
*** Natural gas - production
12.06 billion cu m (2012 est.)
- country comparison to the world :: 38
*** Natural gas - consumption
3.022 billion cu m (2012 est.)
- country comparison to the world :: 75
*** Natural gas - exports
9.039 billion cu m (2012 est.)
- country comparison to the world :: 22
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 167
*** Natural gas - proved reserves
390.8 billion cu m (1 January 2014 est.)
- country comparison to the world :: 34
*** Carbon dioxide emissions from consumption of energy
8.678 million Mt (2012 est.)
- country comparison to the world :: 108
** Communications
*** Telephones - fixed lines
- total subscriptions :: 48,200
- subscriptions per 100 inhabitants :: 11 (2014 est.)
- country comparison to the world :: 164
*** Telephones - mobile cellular
- total :: 465,800
- subscriptions per 100 inhabitants :: 110 (2014 est.)
- country comparison to the world :: 171
*** Telephone system
- general assessment :: service throughout the country is good; international service is good to Southeast Asia, Middle East, Western Europe, and the US
- domestic :: every service available
- international :: country code - 673; landing point for the SEA-ME-WE-3 optical telecommunications submarine cable that provides links to Asia, the Middle East, and Europe; the Asia-America Gateway submarine cable network provides new links to Asia and the US; satellite earth stations - 2 Intelsat (1 Indian Ocean and 1 Pacific Ocean) (2011)
*** Broadcast media
state-controlled Radio Television Brunei (RTB) operates 5 channels; 3 Malaysian TV stations are available; foreign TV broadcasts are available via satellite and cable systems; RTB operates 5 radio networks and broadcasts on multiple frequencies; British Forces Broadcast Service (BFBS) provides radio broadcasts on 2 FM stations; some radio broadcast stations from Malaysia are available via repeaters (2009)
*** Radio broadcast stations
AM 1, FM 2 (transmitting on 18 different frequencies), shortwave 0 (British Forces Broadcasting Service (BFBS) station transmits two FM signals with English and Nepali service) (2006)
*** Television broadcast stations
4 (includes 2 UHF stations broadcasting a subscription service) (2006)
*** Internet country code
.bn
*** Internet users
- total :: 277,200
- percent of population :: 65.6% (2014 est.)
- country comparison to the world :: 146
** Transportation
*** Airports
1 (2013)
- country comparison to the world :: 214
*** Airports - with paved runways
- total :: 1
- over 3,047 m :: 1 (2013)
*** Heliports
3 (2013)
*** Pipelines
condensate 33 km; condensate/gas 86 km; gas 628 km; oil 492 km (2013)
*** Roadways
- total :: 3,029 km
- paved :: 2,425 km
- unpaved :: 604 km (2010)
- country comparison to the world :: 167
*** Waterways
209 km (navigable by craft drawing less than 1.2 m; the Belait, Brunei, and Tutong rivers are major transport links) (2012)
- country comparison to the world :: 96
*** Merchant marine
- total :: 9
- by type :: chemical tanker 1, liquefied gas 8
- foreign-owned :: 2 (UK 2) (2010)
- country comparison to the world :: 115
*** Ports and terminals
- major seaport(s) :: Muara
- oil terminal(s) :: Lumut, Seria
- LNG terminal (export) :: Lumut
** Military
*** Military branches
Royal Brunei Armed Forces: Royal Brunei Land Forces, Royal Brunei Navy, Royal Brunei Air Force (Tentera Udara Diraja Brunei) (2013)
*** Military service age and obligation
17 years of age for voluntary military service; non-Malays are ineligible to serve; recruits from the army, navy, and air force all undergo 43-week initial training (2013)
*** Manpower available for military service
- males age 16-49 :: 112,688
- females age 16-49 :: 117,536 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 95,141
- females age 16-49 :: 99,386 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 3,572
- female :: 3,465 (2010 est.)
*** Military expenditures
2.43% of GDP (2012)
2.54% of GDP (2011)
2.43% of GDP (2010)
- country comparison to the world :: 30
** Transnational Issues
*** Disputes - international
per Letters of Exchange signed in 2009, Malaysia in 2010 ceded two hydrocarbon concession blocks to Brunei in exchange for Brunei's sultan dropping claims to the Limbang corridor, which divides Brunei; nonetheless, Brunei claims a maritime boundary extending as far as a median with Vietnam, thus asserting an implicit claim to Louisa Reef
*** Refugees and internally displaced persons
- stateless persons :: 20,524 (2014); note - thousands of stateless persons, often ethnic Chinese, are permanent residents and their families have lived in Brunei for generations; obtaining citizenship is difficult and requires individuals to pass rigorous tests on Malay culture, customs, and language; stateless residents receive an International Certificate of Identity, which enables them to travel overseas; the government is considering changing the law prohibiting non-Bruneians, including stateless permanent residents, from owning land
*** Illicit drugs
drug trafficking and illegally importing controlled substances are serious offenses in Brunei and carry a mandatory death penalty