** Introduction
*** Background
The archipelago of the Comoros in the Indian Ocean, composed of the islands of Mayotte, Anjouan, Moheli, and Grand Comore declared independence from France on 6 July 1975. France did not recognize the independence of Mayotte, which remains under French administration. Since independence, Comoros has endured political instability through realized and attempted coups. In 1997, the islands of Anjouan and Moheli declared independence from Comoros. In 1999, military chief Col. AZALI Assoumani seized power of the entire government in a bloodless coup; he initiated the 2000 Fomboni Accords, a power-sharing agreement in which the federal presidency rotates among the three islands, and each island maintains its local government. AZALI won the 2002 federal presidential election as president from Grand Comore island, and each island in the archipelago elected its president. AZALI stepped down in 2006 and President SAMBI was elected to office as president from Anjouan. In 2007, Mohamed BACAR effected Anjouan's de-facto secession from the Union of Comoros, refusing to step down when Comoros' other islands held legitimate elections in July. The African Union (AU) initially attempted to resolve the political crisis by applying sanctions and a naval blockade to Anjouan, but in March 2008 the AU and Comoran soldiers seized the island. The island's inhabitants generally welcomed the move. In May 2011, Ikililou DHOININE won the presidency in peaceful elections widely deemed to be free and fair.
** Geography
*** Location
Southern Africa, group of islands at the northern mouth of the Mozambique Channel, about two-thirds of the way between northern Madagascar and northern Mozambique
*** Geographic coordinates
12 10 S, 44 15 E
*** Map references
Africa
*** Area
- total :: 2,235 sq km
- land :: 2,235 sq km
- water :: 0 sq km
- country comparison to the world :: 180
*** Area - comparative
slightly more than 12 times the size of Washington, DC
*** Land boundaries
0 km
*** Coastline
340 km
*** Maritime claims
- territorial sea :: 12 nm
- exclusive economic zone :: 200 nm
*** Climate
tropical marine; rainy season (November to May)
*** Terrain
volcanic islands, interiors vary from steep mountains to low hills
*** Elevation extremes
- lowest point :: Indian Ocean 0 m
- highest point :: Karthala 2,360 m
*** Natural resources
fish
*** Land use
- agricultural land :: 84.4%
arable land 46.7%; permanent crops 29.6%; permanent pasture 8.1%
- forest :: 1.4%
- other :: 14.2% (2011 est.)
*** Irrigated land
1.3 sq km NA (2003)
*** Total renewable water resources
1.2 cu km (2011)
*** Freshwater withdrawal (domestic/industrial/agricultural)
- total :: 0.01  cu km/yr (48%/5%/47%)
- per capita :: 16.86  cu m/yr (1999)
*** Natural hazards
cyclones possible during rainy season (December to April); volcanic activity on Grand Comore
- volcanism :: Karthala (elev. 2,361 m) on Grand Comore Island last erupted in 2007; a 2005 eruption forced thousands of people to be evacuated and produced a large ash cloud
*** Environment - current issues
soil degradation and erosion results from crop cultivation on slopes without proper terracing; deforestation
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Endangered Species, Hazardous Wastes, Law of the Sea, Ozone Layer Protection, Ship Pollution, Wetlands
- signed, but not ratified :: none of the selected agreements
*** Geography - note
important location at northern end of Mozambique Channel
** People and Society
*** Nationality
- noun :: Comoran(s)
- adjective :: Comoran
*** Ethnic groups
Antalote, Cafre, Makoa, Oimatsaha, Sakalava
*** Languages
Arabic (official), French (official), Shikomoro (official; a blend of Swahili and Arabic) (Comorian)
*** Religions
Sunni Muslim 98%, Roman Catholic 2%
*** Population
780,971 (July 2015 est.)
- country comparison to the world :: 164
*** Age structure
- 0-14 years :: 40.77% (male 158,654/female 159,722)
- 15-24 years :: 18.98% (male 71,694/female 76,500)
- 25-54 years :: 32.25% (male 119,595/female 132,299)
- 55-64 years :: 4.17% (male 14,414/female 18,135)
- 65 years and over :: 3.84% (male 14,018/female 15,940) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 75.6%
- youth dependency ratio :: 70.7%
- elderly dependency ratio :: 4.9%
- potential support ratio :: 20.4% (2015 est.)
*** Median age
- total :: 19.4 years
- male :: 18.7 years
- female :: 20 years (2015 est.)
*** Population growth rate
1.77% (2015 est.)
- country comparison to the world :: 67
*** Birth rate
27.84 births/1,000 population (2015 est.)
- country comparison to the world :: 45
*** Death rate
7.57 deaths/1,000 population (2015 est.)
- country comparison to the world :: 111
*** Net migration rate
-2.53 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 175
*** Urbanization
- urban population :: 28.3% of total population (2015)
- rate of urbanization :: 2.67% annual rate of change (2010-15 est.)
*** Major urban areas - population
MORONI (capital) 56,000 (2014)
*** Sex ratio
- at birth :: 1.03 male(s)/female
- 0-14 years :: 0.99 male(s)/female
- 15-24 years :: 0.94 male(s)/female
- 25-54 years :: 0.9 male(s)/female
- 55-64 years :: 0.8 male(s)/female
- 65 years and over :: 0.88 male(s)/female
- total population :: 0.94 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 63.55 deaths/1,000 live births
- male :: 74.18 deaths/1,000 live births
- female :: 52.6 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 19
*** Life expectancy at birth
- total population :: 63.85 years
- male :: 61.57 years
- female :: 66.19 years (2015 est.)
- country comparison to the world :: 182
*** Total fertility rate
3.6 children born/woman (2015 est.)
- country comparison to the world :: 43
*** Contraceptive prevalence rate
19.4% (2012)
*** Health expenditures
5.8% of GDP (2013)
- country comparison to the world :: 153
*** Hospital bed density
2.2 beds/1,000 population (2006)
*** Drinking water source
- improved :: 
urban: 92.6% of population
rural: 89.1% of population
total: 90.1% of population
- unimproved :: 
urban: 7.4% of population
rural: 10.9% of population
total: 9.9% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 48.3% of population
rural: 30.9% of population
total: 35.8% of population
- unimproved :: 
urban: 51.7% of population
rural: 69.1% of population
total: 35.8% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
*** Obesity - adult prevalence rate
5.8% (2014)
- country comparison to the world :: 164
*** Children under the age of 5 years underweight
16.9% (2012)
- country comparison to the world :: 39
*** Education expenditures
7.6% of GDP (2008)
- country comparison to the world :: 15
*** Literacy
- definition :: age 15 and over can read and write
- total population :: 77.8%
- male :: 81.8%
- female :: 73.7% (2015 est.)
*** School life expectancy (primary to tertiary education)
- total :: 11 years
- male :: NA
- female :: NA (2013)
*** Child labor - children ages 5-14
- total number :: 39,550
- percentage :: 27% (2000 est.)
** Government
*** Country name
- conventional long form :: Union of the Comoros
- conventional short form :: Comoros
- local long form :: Udzima wa Komori (Comorian); Union des Comores (French); Jumhuriyat al Qamar al Muttahidah (Arabic)
- local short form :: Komori (Comorian); Comores (French); Juzur al Qamar (Arabic)
*** Government type
republic
*** Capital
- name :: Moroni
- geographic coordinates :: 11 42 S, 43 14 E
- time difference :: UTC+3 (8 hours ahead of Washington, DC, during Standard Time)
*** Administrative divisions
3 islands and 4 municipalities*; Anjouan (Ndzuwani), Domoni*, Fomboni*, Grande Comore (N'gazidja), Moheli (Mwali), Moroni*, Moutsamoudou*
*** Independence
6 July 1975 (from France)
*** National holiday
Independence Day, 6 July (1975)
*** Constitution
several previous; latest adopted 23 December 2001; amended 2009, last in 2014 (2015)
*** Legal system
mixed legal system of Islamic religious law, the French civil code of 1975, and customary law
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; accepts ICCt jurisdiction
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: President Ikililou DHOININE (since 26 May 2011); note - the president is both chief of state and head of government
- head of government :: President Ikililou DHOININE (since 26 May 2011)
- cabinet :: Council of Ministers appointed by the president
- elections/appointments :: presidency rotates every 4 years among the elected presidents of the Union's 3 main islands; Union president directly elected by absolute majority popular vote in 2 rounds if needed (first round by the island voters only; second round by simple majority vote of all island voters; election last held on 7 November and 26 December 2010 (next to be held in 2015)
- election results :: Ikililou DHOININE elected president; percent of vote in second round - Ikililou DHOININE 61.1%, Mohamed Said FAZUL 32.7%, Abdou DJABIR 6.2%
*** Legislative branch
- description :: unicameral Assembly of the Union (33 seats; 24 members elected by absolute majority vote in two rounds if needed and 9 members indirectly selected by island assemblies; members serve 5-year terms)
- elections :: last held on 25 January - 22 February 2015 (next to be held in 2020)
- election results :: percent of vote by party - NA; seats by party - UPDC 8, Juwa 7, Democratic Rally of the Comoros 2, Convention for the Revival of the Comoros 2, RADHI 1, Party for the Comorian Agreement 1, independents 3; note - in addition 9 seats will be filled by nominations from the three island assemblies
*** Judicial branch
- highest court(s) :: Supreme Court or Cour Supreme (consists of 7 judges); Constitutional Court (consists of 8 members)
- judge selection and term of office :: Supreme Court judges - 2 selected by the president of the Union, 2 by the Assembly of the Union, and 1 each by the 3 island councils; judges appointed for life; Constitutional Court members appointed - 1 by the president, 1 each by the 3 vice presidents, 1 by the Assembly, and 1 each by the island executives; all members serve 6-year renewable terms
- subordinate courts :: Court of Appeals (in Moroni); Tribunal de premiere instance; island village (community) courts; religious courts
*** Political parties and leaders
Convention for the Renewal of the Comoros or CRC [AZALI Assoumani]
Democratic Rally of the Comoros [Mouigni MARAKA]
Front National pour la Justice or FNJ [Ahmed RACHID] (Islamic party in opposition)
Juwa [Ahmed Abdallah SAMBI]
National Alliance for the Comoros or ANC [Mahmoud ALI]
Orange Party [Niganned "Kiki" DAOUDI]
Party for the Comorian Agreement (Partie Pour l'Entente Commorienne) or PEC [Fahmi Said IBRAHIM]
Rally for an Alternative of Harmonious and Integrated Development or RADHI
Rassemblement Democratique des Comores [Mougini Baraka Said SOILIHI]
Rassemblement National pour le Development or RND [Omar TAMOU, Abdoulhamid AFFRAITANE]
Rally with a Deveopment Initive with Warned Youth or RIDJA [Said Larifou]
Union for the Development of the Comoros or UPDC [Ikililou DHOININE]
Union Nationale pour la Democratie aux Comores or UNDC [Hassani HARUNA]
*** Political pressure groups and leaders
Federation Comorienne des Consomateurs or FCC [Mohamed Said Abdallah MCHANGANA]
Mouvement des Entreprises comorienne or MODEC [Faharate HOUSSEIN]
Union des Chambres de Commerce et de l'Industrie et de l'Agriculture or UCCIA [Fahmy THABIT]
Confederation des Travailleurs Comoriens or CTC
- other :: environmentalists
*** International organization participation
ACP, AfDB, AMF, AOSIS, AU, CAEU (candidates), COMESA, FAO, FZ, G-77, IBRD, ICAO, ICCt, ICRM, IDA, IDB, IFAD, IFC, IFRCS, ILO, IMF, IMO, IMSO, InOC, Interpol, IOC, IOM, ITSO, ITU, ITUC (NGOs), LAS, MIGA, NAM, OIC, OIF, OPCW, UN, UNCTAD, UNESCO, UNIDO, UPU, WCO, WHO, WIPO, WMO, WTO (observer)
*** Diplomatic representation in the US
- chief of mission :: Ambassador Mohamed SOILIH (since 18 November 2014)
- chancery :: Mission to the US, 866 United Nations Plaza, Suite 418, New York, NY 10017
- telephone :: [1] (212) 750-1637
- FAX :: [1] (212) 750-1657
*** Diplomatic representation from the US
the US does not have an embassy in Comoros; the ambassador to Madagascar is accredited to Comoros
*** Flag description
four equal horizontal bands of yellow (top), white, red, and blue, with a green isosceles triangle based on the hoist; centered within the triangle is a white crescent with the convex side facing the hoist and four white, five-pointed stars placed vertically in a line between the points of the crescent; the horizontal bands and the four stars represent the four main islands of the archipelago - Mwali, N'gazidja, Ndzuwani, and Mahore (Mayotte - department of France, but claimed by Comoros)
- note :: the crescent, stars, and color green are traditional symbols of Islam
*** National symbol(s)
four stars and crescent; national colors: green, white
*** National anthem
- name :: "Udzima wa ya Masiwa" (The Union of the Great Islands)
- lyrics/music :: Said Hachim SIDI ABDEREMANE/Said Hachim SIDI ABDEREMANE and Kamildine ABDALLAH
- note :: adopted 1978

** Economy
*** Economy - overview
One of the world's poorest countries, Comoros is made up of three islands that are hampered by inadequate transportation links, a young and rapidly increasing population, and few natural resources. The low educational level of the labor force contributes to a subsistence level of economic activity, high unemployment, and a heavy dependence on foreign grants and technical assistance. Currently, authorities are negotiating with the IMF for triennial program assistance. Agriculture, including fishing, hunting, and forestry, accounts for 50% of GDP, employs 80% of the labor force, and provides most of the exports. Export income is heavily reliant on the three main crops of vanilla, cloves, and ylang-ylang; and Comoros' export earnings are easily disrupted by disasters such as fires and extreme weather. Despite agriculture’s importance to the economy, the country imports roughly 70% of its food; rice, the main staple, accounts for the bulk of imports. The government - which is racked by internal political disputes - is struggling to provide basic services, upgrade education and technical training, privatize commercial and industrial enterprises, improve health services, diversify exports, promote tourism, and reduce the high population growth rate. Recurring political instability, sometimes initiated  from outside  the country,  has inhibited growth. Remittances from about 200,000 Comoran diaspora contribute about 25% of the country’s GDP. In December 2012, IMF and the World Bank's International Development Association supported $176 million in debt relief for Comoros, resulting in a 59% reduction of its future external debt service over a period of 40 years. In late 2013, a US-based investment company invested $200 million in a project to explore for hydrocarbons in Comoran territorial waters, the largest financial investment in the country’s history.
*** GDP (purchasing power parity)
$1.202 billion (2014 est.)
$1.163 billion (2013 est.)
$1.124 billion (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 201
*** GDP (official exchange rate)
$717 million (2014 est.)
*** GDP - real growth rate
3.3% (2014 est.)
3.5% (2013 est.)
3% (2012 est.)
- country comparison to the world :: 74
*** GDP - per capita (PPP)
$1,500 (2014 est.)
$1,500 (2013 est.)
$1,400 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 213
*** Gross national saving
12.1% of GDP (2014 est.)
9.3% of GDP (2013 est.)
8.5% of GDP (2012 est.)
- country comparison to the world :: 153
*** GDP - composition, by end use
- household consumption :: 99%
- government consumption :: 17.3%
- investment in fixed capital :: 18.5%
- investment in inventories :: 6.3%
- exports of goods and services :: 14.5%
- imports of goods and services :: -55.6%
 (2014 est.)
*** GDP - composition, by sector of origin
- agriculture :: 50.4%
- industry :: 13.7%
- services :: 35.9% (2014 est.)
*** Agriculture - products
vanilla, cloves, ylang-ylang (perfume essence), coconuts, bananas, cassava (manioc)
*** Industries
fishing, tourism, perfume distillation
*** Industrial production growth rate
4.5% (2014 est.)
- country comparison to the world :: 61
*** Labor force
239,000 (2012 est.)
- country comparison to the world :: 168
*** Labor force - by occupation
- agriculture :: 80%
- industry and services :: 20% (1996 est.)
*** Unemployment rate
20% (1996 est.)
- country comparison to the world :: 163
*** Population below poverty line
60% (2002 est.)
*** Household income or consumption by percentage share
- lowest 10% :: 0.9%
- highest 10% :: 55.2% (2004)
*** Budget
- revenues :: $175.6 million
- expenditures :: $183.3 million (2014 est.)
*** Taxes and other revenues
24.3% of GDP (2014 est.)
- country comparison to the world :: 122
*** Budget surplus (+) or deficit (-)
-1.1% of GDP (2014 est.)
- country comparison to the world :: 61
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
2.9% (2014 est.)
1.6% (2013 est.)
- country comparison to the world :: 129
*** Central bank discount rate
1.93% (31 December 2010)
2.21% (31 December 2009)
- country comparison to the world :: 120
*** Commercial bank prime lending rate
10.5% (31 December 2014 est.)
10.5% (31 December 2013 est.)
- country comparison to the world :: 78
*** Stock of narrow money
$171.9 million (31 December 2014 est.)
$159.4 million (31 December 2013 est.)
- country comparison to the world :: 180
*** Stock of broad money
$269.6 million (31 December 2014 est.)
$251.9 million (31 December 2013 est.)
- country comparison to the world :: 186
*** Stock of domestic credit
$179.1 million (31 December 2014 est.)
$167.3 million (31 December 2013 est.)
- country comparison to the world :: 177
*** Current account balance
-$76 million (2014 est.)
-$35.5 million (2013 est.)
- country comparison to the world :: 69
*** Exports
$24.3 million (2014 est.)
$22.8 million (2013 est.)
- country comparison to the world :: 206
*** Exports - commodities
vanilla, ylang-ylang (perfume essence), cloves
*** Exports - partners
India 28.4%, Singapore 13.2%, France 13%, Germany 12.9%, Saudi Arabia 5.9%, US 4.9%, Netherlands 4.6% (2014)
*** Imports
$235.8 million (2014 est.)
$231.4 million (2013 est.)
- country comparison to the world :: 202
*** Imports - commodities
rice and other foodstuffs, consumer goods, petroleum products, cement and construction materials, transport equipment
*** Imports - partners
China 14.6%, Pakistan 13.9%, France 13.6%, Algeria 11.8%, UAE 9.5%, India 5.9% (2014)
*** Debt - external
$251.6 million (31 December 2014 est.)
$251.4 million (31 December 2013 est.)
- country comparison to the world :: 186
*** Exchange rates
Comoran francs (KMF) per US dollar -
364.4 (2014 est.)
370.53 (2013 est.)
382.9 (2012 est.)
353.9 (2011 est.)
371.46 (2010 est.)
** Energy
*** Electricity - production
43 million kWh (2011 est.)
- country comparison to the world :: 209
*** Electricity - consumption
39.99 million kWh (2011 est.)
- country comparison to the world :: 209
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 124
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 131
*** Electricity - installed generating capacity
22,000 kW (2011 est.)
- country comparison to the world :: 202
*** Electricity - from fossil fuels
95.5% of total installed capacity (2011 est.)
- country comparison to the world :: 65
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 68
*** Electricity - from hydroelectric plants
4.5% of total installed capacity (2011 est.)
- country comparison to the world :: 129
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 171
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 163
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 96
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 173
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 118
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 132
*** Refined petroleum products - consumption
1,080 bbl/day (2013 est.)
- country comparison to the world :: 200
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 166
*** Refined petroleum products - imports
877.1 bbl/day (2010 est.)
- country comparison to the world :: 197
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 117
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 131
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 79
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 177
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 124
*** Carbon dioxide emissions from consumption of energy
157,400 Mt (2012 est.)
- country comparison to the world :: 203
** Communications
*** Telephones - fixed lines
- total subscriptions :: 23,500
- subscriptions per 100 inhabitants :: 3 (2014 est.)
- country comparison to the world :: 178
*** Telephones - mobile cellular
- total :: 383,000
- subscriptions per 100 inhabitants :: 50 (2014 est.)
- country comparison to the world :: 173
*** Telephone system
- general assessment :: sparse system of microwave radio relay and HF radiotelephone communication stations
- domestic :: fixed-line connections only about 3 per 100 persons; mobile cellular usage about 30 per 100 persons
- international :: country code - 269; landing point for the EASSy fiber-optic submarine cable system connecting East Africa with Europe and North America; HF radiotelephone communications to Madagascar and Reunion (2010)
*** Broadcast media
national state-owned TV station and a TV station run by Anjouan regional government; national state-owned radio; regional governments on the islands of Grande Comore and Anjouan each operate a radio station; a few independent and small community radio stations operate on the islands of Grande Comore and Moheli, and these two islands have access to Mayotte Radio and French TV (2007)
*** Radio broadcast stations
AM 1, FM 4, shortwave 1 (2001)
*** Television broadcast stations
NA
*** Internet country code
.km
*** Internet users
- total :: 50,200
- percent of population :: 6.6% (2014 est.)
- country comparison to the world :: 182
** Transportation
*** Airports
4 (2013)
- country comparison to the world :: 186
*** Airports - with paved runways
- total :: 4
- 2,438 to 3,047 m :: 1
- 914 to 1,523 m :: 3 (2013)
*** Roadways
- total :: 880 km
- paved :: 673 km
- unpaved :: 207 km (2002)
- country comparison to the world :: 187
*** Merchant marine
- total :: 149
- by type :: bulk carrier 16, cargo 83, carrier 5, chemical tanker 5, container 2, passenger 2, passenger/cargo 1, petroleum tanker 17, refrigerated cargo 10, roll on/roll off 8
- foreign-owned :: 73 (Bangladesh 1, Bulgaria 4, China 1, Cyprus 2, Greece 4, Kenya 2, Kuwait 1, Latvia 2, Lebanon 2, Lithuania 1, Nigeria 1, Norway 1, Pakistan 5, Russia 12, Syria 5, Turkey 8, UAE 8, UK 1, Ukraine 10, US 2) (2010)
- country comparison to the world :: 39
*** Ports and terminals
- major seaport(s) :: Moroni, Mutsamudu
** Military
*** Military branches
National Army for Development (l'Armee Nationale de Developpement, AND): Comoran Security Force (also called Comoran Defense Force (Force Comorienne de Defense, FCD), includes Gendarmerie), Comoran Coast Guard, Comoran Federal Police (2015)
*** Military service age and obligation
18 years of age for 2-year voluntary male and female military service; no conscription (2015)
*** Manpower available for military service
- males age 16-49 :: 184,236
- females age 16-49 :: 183,363 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 134,562
- females age 16-49 :: 145,797 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 8,831
- female :: 8,809 (2010 est.)
** Transnational Issues
*** Disputes - international
claims French-administered Mayotte and challenges France's and Madagascar's claims to Banc du Geyser, a drying reef in the Mozambique Channel; in May 2008, African Union forces assisted the Comoros military recapture Anjouan Island from rebels who seized it in 2001
*** Trafficking in persons
- current situation :: Comoros is a source country for children subjected to forced labor and, reportedly, sex trafficking; Comoran children are forced to labor within the country in domestic service, roadside and street vending, baking, fishing, and agriculture; some Comoran students at Koranic schools are exploited for forced agricultural or domestic labor, sometimes being subjected to physical and sexual abuse; Comoros may be particularly vulnerable to transnational trafficking because of inadequate border controls, government corruption, and the presence of criminal networks and may be a destination for the forced labor of Malagasy and East African women
- tier rating :: Tier 2 Watch List – Comoros does not comply fully with the minimum standards for the elimination of trafficking; however, it is making significant efforts to do so; the government has a written plan that, if implemented, would constitute a significant effort toward meeting the minimum standards for eliminating human trafficking; the penal code was revised to include prohibitions against and penalties for human trafficking, but these modifications await parliamentary adoption; authorities failed to vigorously investigate or prosecute trafficking offenses, including official complicity in these crimes; although the government provided some funding to NGO-run centers, victim protection provisions remained very modest (2014)