** Introduction
*** Background
The native Amerindian population of Cuba began to decline after the European discovery of the island by Christopher COLUMBUS in 1492 and following its development as a Spanish colony during the next several centuries. Large numbers of African slaves were imported to work the coffee and sugar plantations, and Havana became the launching point for the annual treasure fleets bound for Spain from Mexico and Peru. Spanish rule eventually provoked an independence movement and occasional rebellions that were harshly suppressed. US intervention during the Spanish-American War in 1898 assisted the Cubans in overthrowing Spanish rule. Subsequently, the 1901 Platt Amendment to the Cuban constitution authorized the US to intervene in Cuba in the event of instability. The Treaty of Paris established Cuban independence from the US in 1902 after which the island experienced a string of governments mostly dominated by the military and corrupt politicians. Fidel CASTRO led a rebel army to victory in 1959; his authoritarian rule held the subsequent regime together for nearly five decades. He stepped down as president in February 2008 in favor of his younger brother Raul CASTRO. Cuba's communist revolution, with Soviet support, was exported throughout Latin America and Africa during the 1960s, 1970s, and 1980s.
The country faced a severe economic downturn in 1990 following the withdrawal of former Soviet subsidies worth $4-6 billion annually. Cuba at times portrays the US embargo, in place since 1961, as the source of its difficulties. Illicit migration to the US - using homemade rafts, alien smugglers, air flights, or via the US's southern border - is a continuing problem. In FY 2014, the US Coast Guard interdicted 2,111 Cuban nationals at sea, the highest number since FY 2008. Also in FY 2014, 24,289 Cuban migrants presented themselves at various land border ports of entry throughout the US. As a result of efforts begun in December 2014 by President OBAMA to re-establishment diplomatic relations with the Cuban government, which were severed in January 1961, the United States and Cuba reopened embassies in their respective countries on 20 July 2015. Over the past decade, there has been growing communication with the Cuban government to address national interests.
** Geography
*** Location
Caribbean, island between the Caribbean Sea and the North Atlantic Ocean, 150 km south of Key West, Florida
*** Geographic coordinates
21 30 N, 80 00 W
*** Map references
Central America and the Caribbean
*** Area
- total :: 110,860 sq km
- land :: 109,820 sq km
- water :: 1,040 sq km
- country comparison to the world :: 106
*** Area - comparative
slightly smaller than Pennsylvania
- Area comparison map ::  
*** Land boundaries
- total :: 28.5 km
- border countries :: US Naval Base at Guantanamo Bay 28.5 km
- note :: Guantanamo Naval Base is leased by the US and remains part of Cuba
*** Coastline
3,735 km
*** Maritime claims
- territorial sea :: 12 nm
- contiguous zone :: 24 nm
- exclusive economic zone :: 200 nm
*** Climate
tropical; moderated by trade winds; dry season (November to April); rainy season (May to October)
*** Terrain
mostly flat to rolling plains, with rugged hills and mountains in the southeast
*** Elevation extremes
- lowest point :: Caribbean Sea 0 m
- highest point :: Pico Turquino 2,005 m
*** Natural resources
cobalt, nickel, iron ore, chromium, copper, salt, timber, silica, petroleum, arable land
*** Land use
- agricultural land :: 60.3%
arable land 33.8%; permanent crops 3.6%; permanent pasture 22.9%
- forest :: 27.3%
- other :: 12.4% (2011 est.)
*** Irrigated land
8,703 sq km (2003)
*** Total renewable water resources
38.12 cu km (2011)
*** Freshwater withdrawal (domestic/industrial/agricultural)
- total :: 4.42  cu km/yr (22%/14%/65%)
- per capita :: 392.6  cu m/yr (2010)
*** Natural hazards
the east coast is subject to hurricanes from August to November (in general, the country averages about one hurricane every other year); droughts are common
*** Environment - current issues
air and water pollution; biodiversity loss; deforestation
*** Environment - international agreements
- party to :: Antarctic Treaty, Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Endangered Species, Environmental Modification, Hazardous Wastes, Law of the Sea, Marine Dumping, Ozone Layer Protection, Ship Pollution, Wetlands
- signed, but not ratified :: Marine Life Conservation
*** Geography - note
largest country in Caribbean and westernmost island of the Greater Antilles
** People and Society
*** Nationality
- noun :: Cuban(s)
- adjective :: Cuban
*** Ethnic groups
white 64.1%, mestizo 26.6%, black 9.3% (2012 est.)
*** Languages
Spanish (official)
*** Religions
nominally Roman Catholic 85%, Protestant, Jehovah's Witnesses, Jewish, Santeria
- note :: prior to CASTRO assuming power
*** Population
11,031,433 (July 2015 est.)
- country comparison to the world :: 80
*** Age structure
- 0-14 years :: 15.96% (male 904,800/female 855,309)
- 15-24 years :: 13.29% (male 752,160/female 714,384)
- 25-54 years :: 47.16% (male 2,620,536/female 2,581,344)
- 55-64 years :: 10.65% (male 562,207/female 612,438)
- 65 years and over :: 12.95% (male 639,515/female 788,740) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 43.4%
- youth dependency ratio :: 23.4%
- elderly dependency ratio :: 20%
- potential support ratio :: 5% (2015 est.)
*** Median age
- total :: 40.4 years
- male :: 39.5 years
- female :: 41.3 years (2015 est.)
*** Population growth rate
-0.15% (2015 est.)
- country comparison to the world :: 210
*** Birth rate
9.9 births/1,000 population (2015 est.)
- country comparison to the world :: 196
*** Death rate
7.72 deaths/1,000 population (2015 est.)
- country comparison to the world :: 106
*** Net migration rate
-3.66 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 188
*** Urbanization
- urban population :: 77.1% of total population (2015)
- rate of urbanization :: 0.07% annual rate of change (2010-15 est.)
*** Major urban areas - population
HAVANA (capital) 2.137 million (2015)
*** Sex ratio
- at birth :: 1.06 male(s)/female
- 0-14 years :: 1.06 male(s)/female
- 15-24 years :: 1.05 male(s)/female
- 25-54 years :: 1.02 male(s)/female
- 55-64 years :: 0.92 male(s)/female
- 65 years and over :: 0.81 male(s)/female
- total population :: 0.99 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 4.63 deaths/1,000 live births
- male :: 4.97 deaths/1,000 live births
- female :: 4.27 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 180
*** Life expectancy at birth
- total population :: 78.39 years
- male :: 76.08 years
- female :: 80.84 years (2015 est.)
- country comparison to the world :: 59
*** Total fertility rate
1.47 children born/woman (2015 est.)
- country comparison to the world :: 200
*** Contraceptive prevalence rate
74.3% (2010/11)
*** Health expenditures
8.8% of GDP (2013)
- country comparison to the world :: 47
*** Physicians density
6.72 physicians/1,000 population (2010)
*** Hospital bed density
5.3 beds/1,000 population (2012)
*** Drinking water source
- improved :: 
urban: 96.4% of population
rural: 89.8% of population
total: 94.9% of population
- unimproved :: 
urban: 3.6% of population
rural: 10.2% of population
total: 5.1% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 94.4% of population
rural: 89.1% of population
total: 93.2% of population
- unimproved :: 
urban: 5.6% of population
rural: 10.9% of population
total: 6.8% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
0.25% (2014 est.)
- country comparison to the world :: 94
*** HIV/AIDS - people living with HIV/AIDS
17,100 (2014 est.)
- country comparison to the world :: 82
*** HIV/AIDS - deaths
100 (2014 est.)
- country comparison to the world :: 126
*** Major infectious diseases
- degree of risk :: intermediate
- food or waterborne diseases :: bacterial diarrhea and hepatitis A
- vectorborne diseases :: dengue fever (2013)
*** Obesity - adult prevalence rate
27.2% (2014)
- country comparison to the world :: 85
*** Children under the age of 5 years underweight
3.4% (2000)
- country comparison to the world :: 107
*** Education expenditures
12.8% of GDP (2010)
- country comparison to the world :: 2
*** Literacy
- definition :: age 15 and over can read and write
- total population :: 99.8%
- male :: 99.9%
- female :: 99.8% (2015 est.)
*** School life expectancy (primary to tertiary education)
- total :: 14 years
- male :: 13 years
- female :: 14 years (2013)
*** Unemployment, youth ages 15-24
- total :: 3.1%
- male :: 2.8%
- female :: 3.5% (2008 est.)
- country comparison to the world :: 131
*** People - note
illicit emigration is a continuing problem; Cubans attempt to depart the island and enter the US using homemade rafts, alien smugglers, direct flights, or falsified visas; Cubans also use non-maritime routes to enter the US including direct flights to Miami and over-land via the southwest border
** Government
*** Country name
- conventional long form :: Republic of Cuba
- conventional short form :: Cuba
- local long form :: Republica de Cuba
- local short form :: Cuba
*** Government type
Communist state
*** Capital
- name :: Havana
- geographic coordinates :: 23 07 N, 82 21 W
- time difference :: UTC-5 (same time as Washington, DC, during Standard Time)
- daylight saving time :: +1hr, begins second Sunday in March; ends first Sunday in November; note - Cuba has been known to alter the schedule of DST on short notice in an attempt to conserve electricity for lighting
*** Administrative divisions
15 provinces (provincias, singular - provincia) and 1 special municipality* (municipio especial); Artemisa, Camaguey, Ciego de Avila, Cienfuegos, Granma, Guantanamo, Holguin, Isla de la Juventud*, La Habana, Las Tunas, Matanzas, Mayabeque, Pinar del Rio, Sancti Spiritus, Santiago de Cuba, Villa Clara
*** Independence
20 May 1902 (from Spain 10 December 1898; administered by the US from 1898 to 1902); not acknowledged by the Cuban Government as a day of independence
*** National holiday
Triumph of the Revolution (Liberation Day), 1 January (1959)
*** Constitution
several previous; latest adopted by referendum 15 February 1976, effective 24 February 1976; amended 1978, 1992, 2002 (2010)
*** Legal system
civil law system based on Spanish civil code
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; non-party state to the ICCt
*** Suffrage
16 years of age; universal
*** Executive branch
- chief of state :: President of the Council of State and President of the Council of Ministers Gen. Raul CASTRO Ruz (president since 24 February 2008); First Vice President of the Council of State and First Vice President of the Council of Ministers Miguel DIAZ-CANEL Bermudez (since 24 February 2013); note - the president is both chief of state and head of government
- head of government :: President of the Council of State and President of the Council of Ministers Gen. Raul CASTRO Ruz (president since 24 February 2008); First Vice President of the Council of State and First Vice President of the Council of Ministers Miguel DIAZ-CANEL Bermudez (since 24 February 2013)
- cabinet :: Council of Ministers proposed by the president of the Council of State, appointed by the National Assembly or the 28-member Council of State, and elected by the assembly to act on its behalf when it is not in session
- elections/appointments :: president and vice presidents indirectly elected by the National Assembly for a 5-year term (no term limit); election last held on 24 February 2013 (next to be held in 2018)
- election results :: Gen. Raul CASTRO Ruz (PPC) reelected president; percent of National Assembly vote - 100%; Miguel DIAZ-CANEL (PPC) Bermudez elected vice president; percent of National Assembly vote- 100%
*** Legislative branch
- description :: unicameral National Assembly of People's Power or Asemblea Nacional del Poder Popular (614 seats; members directly elected by absolute majority in a modified two-round vote; members serve 5-year terms); note - the National Candidature Commission submits a slate of approved candidates who must obtain 50-percent of valid votes to be elected; if not, a byelection may be held or the seat remains vacant
- elections :: last held on 3 February 2013 (next to be held in 2018)
- election results :: Cuba's Communist Party is the only legal party, and officially sanctioned candidates run unopposed
*** Judicial branch
- highest court(s) :: People's Supreme Court (consists of court president, vice president, 41 professional justices, and NA lay judges; organized into the "Whole," State Council, and criminal, civil, administrative, labor, crimes against the state, and military courts)
- judge selection and term of office :: professional judges elected by the National Assembly to serve 2.5-year terms; lay judges nominated by workplace collectives and neighborhood associations and elected by municipal or provincial assemblies; lay judges appointed for 5-year terms and serve up to 30 days per year
- subordinate courts :: People's Provincial Courts; People's Regional Courts; People's Courts
*** Political parties and leaders
Cuban Communist Party or PCC [Raul CASTRO Ruz, first secretary]
*** Political pressure groups and leaders
Cuban Commission for Human Rights and National Reconciliation
Damas de Blanco (Ladies in White)
National Association of Small Farmers
Patriotic Union of Cuba
- other :: political dissidents and bloggers
*** International organization participation
ACP, ALBA, AOSIS, CELAC, FAO, G-77, IAEA, ICAO, ICC (national committees), ICRM, IFAD, IFRCS, IHO, ILO, IMO, IMSO, Interpol, IOC, IOM (observer), IPU, ISO, ITSO, ITU, LAES, LAIA, NAM, OAS (excluded from formal participation since 1962), OPANAL, OPCW, PCA, Petrocaribe, PIF (partner), UN, UNCTAD, UNESCO, UNIDO, Union Latina, UNWTO, UPU, WCO, WFTU (NGOs), WHO, WIPO, WMO, WTO
*** Diplomatic representation in the US
- chief of mission :: Ambassador (vacant); Charge d'Affaires Jose Ramon CABANAS Rodriguez (since 20 July 2015)
- chancery :: 2630 16th Street NW, Washington, DC 20009
- telephone :: [1] (202) 797-8518
- FAX :: NA
- consulate(s) general :: NA
*** Diplomatic representation from the US
- chief of mission :: Ambassador (vacant); Charge d'Affaires Jeffrey DELAURENTIS (since 20 July 2015)
- embassy :: Calzada between L & M Streets, Vedado, Havana
- mailing address :: use embassy street address
- telephone :: [53] (7) 839-4100
- FAX :: NA
*** Flag description
five equal horizontal bands of blue (top, center, and bottom) alternating with white; a red equilateral triangle based on the hoist side bears a white, five-pointed star in the center; the blue bands refer to the three old divisions of the island: central, occidental, and oriental; the white bands describe the purity of the independence ideal; the triangle symbolizes liberty, equality, and fraternity, while the red color stands for the blood shed in the independence struggle; the white star, called La Estrella Solitaria (the Lone Star) lights the way to freedom and was taken from the flag of Texas
- note :: design similar to the Puerto Rican flag, with the colors of the bands and triangle reversed
*** National symbol(s)
royal palm; national colors: red, white, blue
*** National anthem
- name :: "La Bayamesa" (The Bayamo Song)
- lyrics/music :: Pedro FIGUEREDO
- note :: adopted 1940; Pedro FIGUEREDO first performed "La Bayamesa" in 1868 during the Ten Years War against the Spanish; a leading figure in the uprising, FIGUEREDO was captured in 1870 and executed by a firing squad; just prior to the fusillade he is reputed to have shouted, "Morir por la Patria es vivir" (To die for the country is to live), a line from the anthem

** Economy
*** Economy - overview
The government continues to balance the need for loosening its socialist economic system against a desire for firm political control. The government in April 2011 held the first Cuban Communist Party Congress in almost 13 years, during which leaders approved a plan for wide-ranging economic changes. Since then, the Cuban government has slowly and incrementally implemented limited economic reforms, including allowing Cubans to buy electronic appliances and cell phones, stay in hotels, and buy and sell used cars. As the Cuban government has cut state sector jobs as part of the reform process, it has opened up some retail services to "self-employment," leading to the rise of so-called "cuentapropistas" or entrepreneurs.  Approximately 476,000 Cuban workers are currently registered as self-employed. Recent moves include permitting the private ownership and sale of real estate and new vehicles, allowing private farmers to sell agricultural goods directly to hotels, allowing the creation of non-agricultural cooperatives, adopting a new foreign investment law, and launching a “Special Development Zone” around the Mariel port. Despite these reforms, the average Cuban's standard of living remains at a lower level than before the collapse of the Soviet Union and the resulting downturn of the 1990s. Since late 2000, Venezuela has been providing oil on preferential terms, and it supplied nearly 160,000 barrels per day of petroleum products. Cuba has been paying for the oil, in part, with the services of Cuban personnel in Venezuela, including some 30,000 medical professionals.  However, in 2013 Venezuela’s economic woes forced an estimated 24% reduction in oil exports to Cuba. This downward trend continued in 2014.
*** GDP (purchasing power parity)
$128.5 billion (2014 est.)
$126.9 billion (2013 est.)
$123.5 billion (2012 est.)
- note :: data are in 2012 US dollars
- country comparison to the world :: 76
*** GDP (official exchange rate)
$77.15 billion
- note :: data are in Cuban Pesos at CUP 1 = US$ Official Exchange Rate (2013 est.)
*** GDP - real growth rate
1.3% (2014 est.)
2.7% (2013 est.)
3% (2012 est.)
- country comparison to the world :: 177
*** GDP - per capita (PPP)
$10,200 (2010 est.)
$10,000 (2009 est.)
$10,000 (2008 est.)
- note :: data are in 2010 US dollars
- country comparison to the world :: 131
*** Gross national saving
21.3% of GDP (2014 est.)
12.8% of GDP (2013 est.)
13.7% of GDP (2012 est.)
- country comparison to the world :: 68
*** GDP - composition, by end use
- household consumption :: 52.9%
- government consumption :: 24.9%
- investment in fixed capital :: 14.3%
- investment in inventories :: 0%
- exports of goods and services :: 28%
- imports of goods and services :: -20%
 (2014 est.)
*** GDP - composition, by sector of origin
- agriculture :: 3.8%
- industry :: 14.3%
- services :: 81.9% (2013 est.)
*** Agriculture - products
sugar, tobacco, citrus, coffee, rice, potatoes, beans; livestock
*** Industries
petroleum, nickel, cobalt, pharmaceuticals, tobacco, construction, steel, cement, agricultural machinery, sugar
*** Industrial production growth rate
4.6% (2014 est.)
- country comparison to the world :: 58
*** Labor force
5.092 million
- note :: state sector 72.3%, non-state sector 27.7% (2014 est.)
- country comparison to the world :: 77
*** Labor force - by occupation
- agriculture :: 18%
- industry :: 10%
- services :: 72% (2013 est.)
*** Unemployment rate
3.6% (2014 est.)
3.3% (2013 est.)
- note :: these are official rates; unofficial estimates are about double the official figures
- country comparison to the world :: 29
*** Population below poverty line
NA%
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $1.879 billion
- expenditures :: $1.994 billion (2013 est.)
*** Taxes and other revenues
2.4% of GDP (2013 est.)
*** Budget surplus (+) or deficit (-)
-0.1% of GDP (2013 est.)
*** Public debt
40.6% of GDP (2014 est.)
37.5% of GDP (2013 est.)
- country comparison to the world :: 94
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
5.3% (2014 est.)
6% (2013 est.)
- country comparison to the world :: 174
*** Central bank discount rate
NA%
*** Commercial bank prime lending rate
NA%
*** Stock of narrow money
$924.8 million (31 December 2014 est.)
$13.72 billion (31 December 2013 est.)
- country comparison to the world :: 153
*** Stock of broad money
$24.63 billion (31 December 2013 est.)
$24.08 billion (31 December 2012 est.)
- country comparison to the world :: 81
*** Stock of domestic credit
$NA
*** Current account balance
$1 billion (2014 est.)
$1 billion (2013 est.)
- country comparison to the world :: 115
*** Exports
$5.62 billion (2014 est.)
$5.566 billion (2013 est.)
- country comparison to the world :: 112
*** Exports - commodities
petroleum, nickel, medical products, sugar, tobacco, fish, citrus, coffee
*** Exports - partners
Venezuela 33.5%, Canada 15.9%, China 9.5%, Netherlands 4.5% (2014)
*** Imports
$14.7 billion (2014 est.)
$14.77 billion (2013 est.)
- country comparison to the world :: 89
*** Imports - commodities
petroleum, food, machinery and equipment, chemicals
*** Imports - partners
Venezuela 38.7%, China 9.8%, Spain 8.4%, Brazil 4.7%, Algeria 4.4% (2014)
*** Reserves of foreign exchange and gold
$10.4 billion (31 December 2014 est.)
$10.1 billion (31 December 2013 est.)
- country comparison to the world :: 76
*** Debt - external
$25.23 billion (31 December 2014 est.)
$24.65 billion (31 December 2013 est.)
- country comparison to the world :: 79
*** Stock of direct foreign investment - at home
$NA
*** Stock of direct foreign investment - abroad
$4.138 billion (2006 est.)
- country comparison to the world :: 65
*** Exchange rates
Cuban pesos (CUP) per US dollar -
22.57 (2014 est.)
1 (2013 est.)
1 (2012 est.)
0.98 (2011 est.)
0.93 (2010 est.)
** Energy
*** Electricity - production
19.14 billion kWh (2013 est.)
- country comparison to the world :: 80
*** Electricity - consumption
16.2 billion kWh (2013 est.)
- country comparison to the world :: 81
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 127
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 134
*** Electricity - installed generating capacity
6.055 million kW (2013 est.)
- country comparison to the world :: 71
*** Electricity - from fossil fuels
99.3% of total installed capacity (2013 est.)
- country comparison to the world :: 51
*** Electricity - from nuclear fuels
0% of total installed capacity (2013 est.)
- country comparison to the world :: 72
*** Electricity - from hydroelectric plants
0.7% of total installed capacity (2013 est.)
- country comparison to the world :: 142
*** Electricity - from other renewable sources
0.1% of total installed capacity (2013 est.)
- country comparison to the world :: 97
*** Crude oil - production
50,500 bbl/day (2013 est.)
- country comparison to the world :: 59
*** Crude oil - exports
74,000 bbl/day (2013 est.)
- country comparison to the world :: 40
*** Crude oil - imports
160,000 bbl/day (2013 est.)
- country comparison to the world :: 35
*** Crude oil - proved reserves
124 million bbl (1 January 2014 est.)
- country comparison to the world :: 70
*** Refined petroleum products - production
106,300 bbl/day (2012 est.)
- country comparison to the world :: 74
*** Refined petroleum products - consumption
148,800 bbl/day (2012 est.)
- country comparison to the world :: 62
*** Refined petroleum products - exports
11,320 bbl/day (12 est.)
- country comparison to the world :: 83
*** Refined petroleum products - imports
66,350 bbl/day (2010 est.)
- country comparison to the world :: 151
*** Natural gas - production
1.066 billion cu m (2013 est.)
- country comparison to the world :: 63
*** Natural gas - consumption
925.6 million cu m (2013 est.)
- country comparison to the world :: 90
*** Natural gas - exports
0 cu m (2013)
- country comparison to the world :: 82
*** Natural gas - imports
0 cu m (2013)
- country comparison to the world :: 181
*** Natural gas - proved reserves
70.79 billion cu m (1 January 2014 est.)
- country comparison to the world :: 57
*** Carbon dioxide emissions from consumption of energy
25.99 million Mt (2012 est.)
- country comparison to the world :: 80
** Communications
*** Telephones - fixed lines
- total subscriptions :: 1.26 million
- subscriptions per 100 inhabitants :: 11 (2014 est.)
- country comparison to the world :: 67
*** Telephones - mobile cellular
- total :: 2.5 million
- subscriptions per 100 inhabitants :: 23 (2014 est.)
- country comparison to the world :: 144
*** Telephone system
- general assessment :: greater investment beginning in 1994 and the establishment of a new Ministry of Information Technology and Communications in 2000 has resulted in improvements in the system; national fiber-optic system under development; 95% of switches digitized by end of 2006; mobile-cellular telephone service is expensive and must be paid in convertible pesos; around 1.3 million Cubans owned cell phones in 2011; state communications started service of email to cell phones through nauta.cu accounts; Cuban Government has opened Internet cafes around the island, which are expensive and offer slow-speed connections
- domestic :: fixed-line density remains low at 10 per 100 inhabitants; mobile-cellular service expanding but remains only about 10 per 100 persons
- international :: country code - 53; the ALBA-1 fiber-optic submarine cable links Cuba, Jamaica, and Venezuela; fiber-optic cable laid to but not linked to US network; satellite earth station - 1 Intersputnik (Atlantic Ocean region) (2011)
*** Broadcast media
government owns and controls all broadcast media with private ownership of electronic media prohibited; government operates 4 national TV networks and many local TV stations; government operates 6 national radio networks, an international station, and many local radio stations; Radio-TV Marti is beamed from the US (2007)
*** Radio broadcast stations
AM 169, FM 55, shortwave 1 (1998)
*** Television broadcast stations
58 (1997)
*** Internet country code
.cu
*** Internet users
- total :: 3 million
- percent of population :: 27.5%
- note :: private citizens are prohibited from buying computers or accessing the Internet without special authorization; foreigners may access the Internet in large hotels but are subject to firewalls; some Cubans buy illegal passwords on the black market or take advantage of public outlets to access limited email and the government-controlled "intranet" (2014 est.)
- country comparison to the world :: 85
** Transportation
*** Airports
133 (2013)
- country comparison to the world :: 43
*** Airports - with paved runways
- total :: 64
- over 3,047 m :: 7
- 2,438 to 3,047 m :: 10
- 1,524 to 2,437 m :: 16
- 914 to 1,523 m :: 4
- under 914 m :: 27 (2013)
*** Airports - with unpaved runways
- total :: 69
- 914 to 1,523 m :: 11
- under 914 m :: 
58 (2013)
*** Pipelines
gas 41 km; oil 230 km (2013)
*** Railways
- total :: 8,285 km
- standard gauge :: 8,125 km 1.435-m gauge (105 km electrified)
- narrow gauge :: 160 km 1.000-m gauge
- note :: 82 km of standard gauge track is not for public use (2014)
- country comparison to the world :: 25
*** Roadways
- total :: 60,858 km
- paved :: 29,820 km (includes 639 km of expressways)
- unpaved :: 31,038 km (2001)
- country comparison to the world :: 68
*** Waterways
240 km (almost all navigable inland waterways are near the mouths of rivers) (2011)
- country comparison to the world :: 94
*** Merchant marine
- total :: 3
- by type :: cargo 1, passenger 1, refrigerated cargo 1
- registered in other countries :: 5 (Curacao 1, Panama 2, unknown 2) (2010)
- country comparison to the world :: 135
*** Ports and terminals
- major seaport(s) :: Antilla, Cienfuegos, Guantanamo, Havana, Matanzas, Mariel, Nuevitas Bay, Santiago de Cuba
** Military
*** Military branches
Revolutionary Armed Forces (Fuerzas Armadas Revolucionarias, FAR): Revolutionary Army (Ejercito Revolucionario, ER, includes Territorial Militia Troops (Milicia de Tropas de Territoriales, MTT)), Revolutionary Navy (Marina de Guerra Revolucionaria, MGR, includes Marine Corps), Revolutionary Air and Air Defense Forces (Defensas Anti-Aereas y Fuerza Aerea Revolucionaria, DAAFAR); Youth Labor Army (Ejercito Juvenil del Trabajo, EJT) (2013)
*** Military service age and obligation
17-28 years of age for compulsory military service; 2-year service obligation; both sexes subject to military service (2012)
*** Manpower available for military service
- males age 16-49 :: 2,998,201
- females age 16-49 :: 2,919,107 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 2,446,131
- females age 16-49 :: 2,375,590 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 72,823
- female :: 69,108 (2010 est.)
*** Military - note
the collapse of the Soviet Union deprived the Cuban military of its major economic and logistic support and had a significant impact on the state of Cuban equipment; the army remains well trained and professional in nature; the lack of replacement parts for its existing equipment has increasingly affected operational capabilities (2013)
** Transnational Issues
*** Disputes - international
US Naval Base at Guantanamo Bay is leased to US and only mutual agreement or US abandonment of the facility can terminate the lease
*** Trafficking in persons
- current situation :: Cuba is a source country for adults and children subjected to sex trafficking, and possibly forced labor; child prostitution and child sex tourism reportedly occurs in Cuba, while some Cubans are forced into prostitution abroad; allegations have been made of Cubans being subjected to forced labor at Cuban work missions abroad; the scope of trafficking within Cuba is difficult to gauge due to a dearth of independent reporting, but the Cuban government provided information on human trafficking for the first time in 2013
- tier rating :: Tier 3 - Cuba does not fully comply with the minimum standards for the elimination of trafficking and is not making significant efforts to do so; the government has not established a legal framework criminalizing all forms of human trafficking but intends to amend its criminal code to comply with the 2000 UN TIP Protocol, which it acceded to in 2013; the government provided assistance to vulnerable women and children in 2013 but did not offer services specifically for trafficking victims; some prosecutions and convictions for sex trafficking occurred, but none for forced labor were registered (2014)
*** Illicit drugs
territorial waters and air space serve as transshipment zone for US- and European-bound drugs; established the death penalty for certain drug-related crimes in 1999 (2008)