** Introduction
*** Background
Although first sighted by an English navigator in 1592, the first landing (English) did not occur until almost a century later in 1690, and the first settlement (French) was not established until 1764. The colony was turned over to Spain two years later and the islands have since been the subject of a territorial dispute, first between Britain and Spain, then between Britain and Argentina. The UK asserted its claim to the islands by establishing a naval garrison there in 1833. Argentina invaded the islands on 2 April 1982. The British responded with an expeditionary force that landed seven weeks later and after fierce fighting forced an Argentine surrender on 14 June 1982. With hostilities ended and Argentine forces withdrawn, UK administration resumed. In response to renewed calls from Argentina for Britain to relinquish control of the islands, a referendum was held in March 2013, which resulted in 99.8% of the population voting to remain a part of the UK.
** Geography
*** Location
Southern South America, islands in the South Atlantic Ocean, about 500 km east of southern Argentina
*** Geographic coordinates
51 45 S, 59 00 W
*** Map references
South America
*** Area
- total :: 12,173 sq km
- land :: 12,173 sq km
- water :: 0 sq km
- note :: includes the two main islands of East and West Falkland and about 200 small islands
- country comparison to the world :: 165
*** Area - comparative
slightly smaller than Connecticut
*** Land boundaries
0 km
*** Coastline
1,288 km
*** Maritime claims
- territorial sea :: 12 nm
- continental shelf :: 200 nm
- exclusive fishing zone :: 200 nm
*** Climate
cold marine; strong westerly winds, cloudy, humid; rain occurs on more than half of days in year; average annual rainfall is 60 cm in Stanley; occasional snow all year, except in January and February, but typically does not accumulate
*** Terrain
rocky, hilly, mountainous with some boggy, undulating plains
*** Elevation extremes
- lowest point :: Atlantic Ocean 0 m
- highest point :: Mount Usborne 705 m
*** Natural resources
fish, squid, wildlife, calcified seaweed, sphagnum moss
*** Land use
- agricultural land :: 92.4%
arable land 0%; permanent crops 0%; permanent pasture 92.4%
- forest :: 0%
- other :: 7.6% (2011 est.)
*** Irrigated land
NA
*** Natural hazards
strong winds persist throughout the year
*** Environment - current issues
overfishing by unlicensed vessels is a problem; reindeer - introduced to the islands in 2001 from South Georgia - are part of a farming effort to produce specialty meat and diversify the islands' economy; this is the only commercial reindeer herd in the world unaffected by the 1986 Chornobyl disaster
*** Geography - note
deeply indented coast provides good natural harbors; short growing season
** People and Society
*** Nationality
- noun :: Falkland Islander(s)
- adjective :: Falkland Island
*** Ethnic groups
Falkland Islander 57%, British 24.6%, St. Helenian 9.8%, Chilean 5.3%, other 3.4% (2012 est.)
*** Languages
English 89%, Spanish 7.7%, other 3.3% (2006 est.)
*** Religions
Christian 66%, none 32%, other 2% (2012 est.)
*** Population
3,361 (July 2014 est.)
- country comparison to the world :: 230
*** Population growth rate
0.01% (2014 est.)
- country comparison to the world :: 193
*** Birth rate
10.9 births/1,000 population (2012 est.)
*** Death rate
4.9 deaths/1,000 population (2012 est.)
*** Net migration rate
NA
*** Urbanization
- urban population :: 76.2% of total population (2015)
- rate of urbanization :: 0.96% annual rate of change (2010-15 est.)
*** Major urban areas - population
STANLEY (capital) 2,000 (2014)
*** Sex ratio
- total population :: 1.11 male(s)/female
- note :: sex ratio is somewhat skewed by the high proportion of males at the Royal Air Force station, Mount Pleasant Airport (MPA); excluding MPA, the sex ratio of the total population would be 1.01 (2012 est.)
*** Infant mortality rate
- total :: NA
- male :: NA
- female :: NA
*** Life expectancy at birth
- total population :: 77.9
- male :: 75.6
- female :: 79.6 (2012 est.)
*** Total fertility rate
NA
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
** Government
*** Country name
- conventional long form :: none
- conventional short form :: Falkland Islands (Islas Malvinas)
*** Dependency status
overseas territory of the UK; also claimed by Argentina
*** Government type
NA
*** Capital
- name :: Stanley
- geographic coordinates :: 51 42 S, 57 51 W
- time difference :: UTC-4 (1 hour ahead of Washington, DC, during Standard Time)
*** Administrative divisions
none (overseas territory of the UK; also claimed by Argentina)
*** Independence
none (overseas territory of the UK; also claimed by Argentina)
*** National holiday
Liberation Day, 14 June (1982)
*** Constitution
previous 1985; latest entered into force 1 January 2009 (2011)
*** Legal system
English common law and local statutes
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: Queen ELIZABETH II (since 6 February 1952); represented by Governor Colin ROBERTS (since 28 April 2014)
- head of government :: Chief Executive Keith PADGETT (since 1 February 2012)
- cabinet :: Executive Council elected by the Legislative Council
- elections/appointments :: the monarchy is hereditary; governor appointed by the monarch; chief executive appointed by the governor
*** Legislative branch
- description :: unicameral Legislative Assembly, formerly the Legislative Council (10 seats; 8 members directly elected by majority vote and 2 appointed ex officio members - the chief executive, appointed by the governor, and the financial secretary; members serve 4-year terms)
- elections :: last held on 7 November 2013 (next to be held in November 2017)
- election results :: percent of vote - NA; seats - independent 8
*** Judicial branch
- highest resident court(s) :: Court of Appeal (consists of the court president, the chief justice as an ex officio, non-resident member, and 2 justices of appeal); Supreme Court (consists of the chief justice); note - appeals beyond the Court of Appeal are referred to the Judicial Committee of the Privy Council (in London)
- judge selection and term of office :: all justices appointed by the governor; tenure specified in each justice's instrument of appointment
- subordinate courts :: Magistrate's Court (senior magistrate presides over civil and criminal divisions); Court of Summary Jurisdiction
*** Political parties and leaders
none; all independents
*** Political pressure groups and leaders
Falkland Islands Association (supports freedom of the people from external causes)
*** International organization participation
UPU
*** Diplomatic representation in the US
none (overseas territory of the UK)
*** Diplomatic representation from the US
none (overseas territory of the UK; also claimed by Argentina)
*** Flag description
blue with the flag of the UK in the upper hoist-side quadrant and the Falkland Island coat of arms centered on the outer half of the flag; the coat of arms contains a white ram (sheep raising was once the major economic activity) above the sailing ship Desire (whose crew discovered the islands) with a scroll at the bottom bearing the motto DESIRE THE RIGHT
*** National symbol(s)
ram
*** National anthem
- name :: "Song of the Falklands""
- lyrics/music :: Christopher LANHAM
- note :: adopted 1930s; the song is the local unofficial anthem; as a territory of the United Kingdom, "God Save the Queen" is official (see United Kingdom)
** Economy
*** Economy - overview
The economy was formerly based on agriculture, mainly sheep farming, but fishing and tourism currently comprise the bulk of economic activity. In 1987, the government began selling fishing licenses to foreign trawlers operating within the Falkland Islands' exclusive fishing zone. These license fees net more than $40 million per year, which help support the island's health, education, and welfare system. The waters around the Falkland Islands are known for their squid, which account for around 75% of the annual 200,000 ton fish catch. Dairy farming supports domestic consumption; crops furnish winter fodder. Foreign exchange earnings come from shipments of high-grade wool to the UK and from the sale of postage stamps and coins. In 2001, the government purchased 100 reindeer with the intent to increase the number to 10,000 over the following 20 years so that venison could be exported to Scandinavia and Chile. Tourism, especially eco-tourism, is increasing rapidly, with about 69,000 visitors in 2009. The British military presence also provides a sizable economic boost. The islands are now self-financing except for defense. In 1993 the British Geological Survey announced a 200-mile oil exploration zone around the islands, and early seismic surveys suggest substantial reserves capable of producing 500,000 barrels per day. Political tensions between the UK and Argentina remain high following the start of oil drilling activities in the waters. In September 2011, a British exploration firm announced that it plans to commence oil production in 2016.
*** GDP (purchasing power parity)
$164.5 million (2007 est.)
$105.1 million (2002 est.)
- country comparison to the world :: 223
*** GDP (official exchange rate)
$164.5 million (2007 est.)
*** GDP - per capita (PPP)
$55,400 (2002 est.)
- country comparison to the world :: 15
*** GDP - composition, by sector of origin
- agriculture :: 95%
- industry :: NA%
- services :: NA% (1996)
*** Agriculture - products
fodder and vegetable crops; venison, sheep, dairy products; fish, squid
*** Industries
fish and wool processing; tourism
*** Industrial production growth rate
NA%
*** Labor force
1,944 (2012 est.)
- country comparison to the world :: 228
*** Labor force - by occupation
- agriculture :: 95% (mostly sheepherding and fishing)
- industry and services :: 5% (1996)
*** Unemployment rate
4.1% (2010)
- country comparison to the world :: 37
*** Population below poverty line
NA%
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $67.1 million
- expenditures :: $75.3 million (FY09/10)
*** Taxes and other revenues
40.8% of GDP (FY09/10)
- country comparison to the world :: 36
*** Budget surplus (+) or deficit (-)
-5% of GDP (FY09/10)
- country comparison to the world :: 164
*** Fiscal year
1 April - 31 March
*** Inflation rate (consumer prices)
1.2% (2003)
- country comparison to the world :: 76
*** Exports
$125 million (2004 est.)
- country comparison to the world :: 187
*** Exports - commodities
wool, hides, meat, venison, fish, squid
*** Imports
$90 million (2004 est.)
- country comparison to the world :: 214
*** Imports - commodities
fuel, food and drink, building materials, clothing
*** Debt - external
$NA
*** Exchange rates
Falkland pounds (FKP) per US dollar -
0.6003 (2014)
0.6391 (2013)
0.63 (2012)
0.624 (2011)
0.6472 (2010)
** Energy
*** Electricity - production
12 million kWh (2011 est.)
- country comparison to the world :: 215
*** Electricity - consumption
11.16 million kWh (2011 est.)
- country comparison to the world :: 215
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 138
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 145
*** Electricity - installed generating capacity
10,000 kW (2011 est.)
- country comparison to the world :: 207
*** Electricity - from fossil fuels
90% of total installed capacity (2011 est.)
- country comparison to the world :: 74
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 89
*** Electricity - from hydroelectric plants
0% of total installed capacity (2011 est.)
- country comparison to the world :: 170
*** Electricity - from other renewable sources
10% of total installed capacity (2011 est.)
- country comparison to the world :: 33
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 173
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 112
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 185
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 133
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 143
*** Refined petroleum products - consumption
320 bbl/day (2013 est.)
- country comparison to the world :: 209
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 176
*** Refined petroleum products - imports
312.5 bbl/day (2010 est.)
- country comparison to the world :: 207
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 131
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 143
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 97
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 193
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 138
*** Carbon dioxide emissions from consumption of energy
45,570 Mt (2012 est.)
- country comparison to the world :: 210
** Communications
*** Telephones - fixed lines
- total subscriptions :: 2,100
- subscriptions per 100 inhabitants :: 66 (2014 est.)
- country comparison to the world :: 214
*** Telephones - mobile cellular
- total :: 4,200
- subscriptions per 100 inhabitants :: 133 (2014 est.)
- country comparison to the world :: 216
*** Telephone system
- domestic :: government-operated radiotelephone and private VHF/CB radiotelephone networks provide effective service to almost all points on both islands
- international :: country code - 500; satellite earth station - 1 Intelsat (Atlantic Ocean) with links through London to other countries (2011)
*** Broadcast media
TV service provided by a multi-channel service provider; radio services provided by the public broadcaster, Falkland Islands Radio Service, broadcasting on both AM and FM frequencies, and by the British Forces Broadcasting Service (BFBS) (2007)
*** Radio broadcast stations
AM 1, FM 7, shortwave 0 (British Forces Broadcasting Service (BFBS) provides Radio 1 and Radio 2 service) (2006)
*** Television broadcast stations
2 (British Forces Broadcasting Service (BFBS) provides multi-channel satellite service to members of UK Forces as well as islanders); cable television is available in Stanley (2006)
*** Internet country code
.fk
*** Internet users
- total :: 2,900
- percent of population :: 92.4% (2009)
- country comparison to the world :: 209
** Transportation
*** Airports
7 (2013)
- country comparison to the world :: 170
*** Airports - with paved runways
- total :: 2
- 2,438 to 3,047 m :: 1
- 914 to 1,523 m :: 1 (2013)
*** Airports - with unpaved runways
- total :: 5
- under 914 m :: 
5 (2013)
*** Roadways
- total :: 440 km
- paved :: 50 km
- unpaved :: 390 km (2008)
- country comparison to the world :: 199
*** Ports and terminals
- major seaport(s) :: Stanley
** Military
*** Military branches
no regular military forces
*** Military - note
defense is the responsibility of the UK
** Transnational Issues
*** Disputes - international
Argentina, which claims the islands in its constitution and briefly occupied them by force in 1982, agreed in 1995 to no longer seek settlement by force; UK continues to reject Argentine requests for sovereignty talks