** Introduction
*** Background
The French annexed various Polynesian island groups during the 19th century. In September 1995, France stirred up widespread protests by resuming nuclear testing on the Mururoa Atoll after a three-year moratorium. The tests were halted in January 1996. In recent years, French Polynesia's autonomy has been considerably expanded.
** Geography
*** Location
Oceania, five archipelagoes (Archipel des Tuamotu, Iles Gambier, Iles Marquises, Iles Tubuai, Society Islands) in the South Pacific Ocean about halfway between South America and Australia
*** Geographic coordinates
15 00 S, 140 00 W
*** Map references
Oceania
*** Area
- total :: 4,167 sq km (118 islands and atolls; 67 are inhabited)
- land :: 3,827 sq km
- water :: 340 sq km
- country comparison to the world :: 175
*** Area - comparative
slightly less than one-third the size of Connecticut
*** Land boundaries
0 km
*** Coastline
2,525 km
*** Maritime claims
- territorial sea :: 12 nm
- exclusive economic zone :: 200 nm
*** Climate
tropical, but moderate
*** Terrain
mixture of rugged high islands and low islands with reefs
*** Elevation extremes
- lowest point :: Pacific Ocean 0 m
- highest point :: Mont Orohena 2,241 m
*** Natural resources
timber, fish, cobalt, hydropower
*** Land use
- agricultural land :: 12.5%
arable land 0.7%; permanent crops 6.3%; permanent pasture 5.5%
- forest :: 43.7%
- other :: 43.8% (2011 est.)
*** Irrigated land
10 sq km (2003)
*** Natural hazards
occasional cyclonic storms in January
*** Environment - current issues
NA
*** Geography - note
includes five archipelagoes: four volcanic (Iles Gambier, Iles Marquises, Iles Tubuai, Society Islands) and one coral (Archipel des Tuamotu); Makatea in French Polynesia is one of the three great phosphate rock islands in the Pacific Ocean - the others are Banaba (Ocean Island) in Kiribati and Nauru
** People and Society
*** Nationality
- noun :: French Polynesian(s)
- adjective :: French Polynesian
*** Ethnic groups
Polynesian 78%, Chinese 12%, local French 6%, metropolitan French 4%
*** Languages
French (official) 61.1%, Polynesian (official) 31.4%, Asian languages 1.2%, other 0.3%, unspecified 6% (2002 census)
*** Religions
Protestant 54%, Roman Catholic 30%, other 10%, no religion 6%
*** Population
282,703 (July 2015 est.)
- country comparison to the world :: 182
*** Age structure
- 0-14 years :: 23.31% (male 33,894/female 32,005)
- 15-24 years :: 16.36% (male 23,980/female 22,270)
- 25-54 years :: 44.1% (male 63,931/female 60,749)
- 55-64 years :: 8.83% (male 12,847/female 12,120)
- 65 years and over :: 7.4% (male 10,142/female 10,765) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 42.2%
- youth dependency ratio :: 31.5%
- elderly dependency ratio :: 10.7%
- potential support ratio :: 9.3% (2015 est.)
*** Median age
- total :: 31 years
- male :: 30.9 years
- female :: 31.2 years (2015 est.)
*** Population growth rate
0.94% (2015 est.)
- country comparison to the world :: 122
*** Birth rate
15.22 births/1,000 population (2015 est.)
- country comparison to the world :: 131
*** Death rate
5.02 deaths/1,000 population (2015 est.)
- country comparison to the world :: 189
*** Net migration rate
-0.84 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 145
*** Urbanization
- urban population :: 55.9% of total population (2015)
- rate of urbanization :: 0.85% annual rate of change (2010-15 est.)
*** Major urban areas - population
PAPEETE (capital) 133,000 (2014)
*** Sex ratio
- at birth :: 1.05 male(s)/female
- 0-14 years :: 1.06 male(s)/female
- 15-24 years :: 1.08 male(s)/female
- 25-54 years :: 1.05 male(s)/female
- 55-64 years :: 1.06 male(s)/female
- 65 years and over :: 0.94 male(s)/female
- total population :: 1.05 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 4.73 deaths/1,000 live births
- male :: 5.25 deaths/1,000 live births
- female :: 4.18 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 177
*** Life expectancy at birth
- total population :: 76.98 years
- male :: 74.72 years
- female :: 79.36 years (2015 est.)
- country comparison to the world :: 75
*** Total fertility rate
1.92 children born/woman (2015 est.)
- country comparison to the world :: 133
*** Drinking water source
- improved :: 
urban: 100% of population
rural: 100% of population
total: 100% of population
- unimproved :: 
urban: 0% of population
rural: 0% of population
total: 0% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 98.5% of population
rural: 98.5% of population
total: 98.5% of population
- unimproved :: 
urban: 1.5% of population
rural: 1.5% of population
total: 1.5% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
** Government
*** Country name
- conventional long form :: Overseas Lands of French Polynesia
- conventional short form :: French Polynesia
- local long form :: Pays d'outre-mer de la Polynesie Francaise
- local short form :: Polynesie Francaise
- former :: French Colony of Oceania
*** Dependency status
overseas lands of France; overseas territory of France from 1946-2003; overseas collectivity of France since 2003, though it is often referred to as an overseas country due to its degree of autonomy
*** Government type
parliamentary representative democratic French overseas collectivity
*** Capital
- name :: Papeete (located on Tahiti)
- geographic coordinates :: 17 32 S, 149 34 W
- time difference :: UTC-10 (5 hours behind Washington, DC, during Standard Time)
*** Administrative divisions
none (overseas lands of France); there are no first-order administrative divisions as defined by the US Government, but there are 5 second order administrative units named Iles Australes, Iles du Vent, Iles Marquises, Iles Sous le Vent, Iles Tuamotu et Gambier
*** Independence
none (overseas lands of France)
*** National holiday
Fete de la Federation, 14 July (1789); note - the local holiday is Internal Autonomy Day, 29 June (1880)
*** Constitution
4 October 1958 (French Constitution)
*** Legal system
the laws of France, where applicable, apply
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: President Francois HOLLANDE (since 15 May 2012), represented by High Commissioner of the Republic Lionel BEFFRE (since 16 September 2013)
- head of government :: President of French Polynesia Edouard FRITCH (since 12 September 2014)
- cabinet :: Council of Ministers approved by the Assembly from a list of its members submitted by the president
- elections/appointments :: French president directly elected by absolute majority popular vote in 2 rounds if needed for a 5-year term (eligible for a second term); high commissioner appointed by the French president on the advice of the French Ministry of Interior; French Polynesia president indirectly elected by Assembly of French Polynesia for a 5-year term (no term limits)
*** Legislative branch
- description :: unicameral Assembly of French Polynesia or Assemblee de la Polynesie Francaise (57 seats; elections held in two rounds; in the second round, 38 members directly elected in multi-seat constituencies by proportional representation vote; the party receiving the most votes get an additional 19 seats; to serve 5-year terms)
- elections :: last held on 21 April 2013 - first round and 5 May 2013 - second round (next to be held in 2018)
- election results :: percent of vote by party - Popular Rally 45.1%, Union for Democracy alliance 29.3%, A Tia Porinetia 25.6%; seats by party - Popular Rally 38, Union for Democracy alliance 11, A Tia Porinetia 8
- note :: two seats were elected to the French Senate on 20 September 2014 (next to be held in September 2022); results - percent of vote by party - NA; seats by party - Popular Rally 1, People's Servant Party 1; two seats were elected to the French National Assembly on 17 June 2012 (next to be held by June 2017); results - percent of vote by party - NA; seats by party - UMP 2; note - the UMP is France's ruling pary, the Union for a Popular Movement
*** Judicial branch
- highest court(s) :: Court of Appeal or Cour d'Appel (composition NA); note - appeals beyond the French Polynesia Court of Appeal are heard by the Court of Cassation (in Paris)
- judge selection and term of office :: NA
- subordinate courts :: Court of the First Instance or Tribunal de Premiere Instance; Court of Administrative Law or Tribunal Administratif
*** Political parties and leaders
A Tia Porinetia [Teva ROHFRITSCH]
Alliance for a New Democracy or ADN (includes the parties The New Star and This Country is Yours)
New Fatherland Party (Ai'a Api) [Emile VERNAUDON]
Our Home alliance
People's Servant Party (Tavini Huiraatira) [James CHANCELOR]
Popular Rally (Tahoeraa Huiraatira) [Gaston FLOSSE]
Union for Democracy alliance or UPD [Oscar TEMARU]
*** International organization participation
ITUC (NGOs), PIF (associate member), SPC, UPU, WMO
*** Diplomatic representation in the US
none (overseas lands of France)
*** Diplomatic representation from the US
none (overseas lands of France)
*** Flag description
two red horizontal bands encase a wide white band in a 1:2:1 ratio; centered on the white band is a disk with a blue and white wave pattern depicting the sea on the lower half and a gold and white ray pattern depicting the sun on the upper half; a Polynesian canoe rides on the wave pattern; the canoe has a crew of five represented by five stars that symbolize the five island groups; red and white are traditional Polynesian colors
- note :: similar to the red-white-red flag of Tahiti, the largest of the islands in French Polynesia, which has no emblem in the white band; the flag of France is used for official occasions
*** National symbol(s)
outrigger canoe; national colors: red, white
*** National anthem
- name :: "Ia Ora 'O Tahiti Nui" (Long Live Tahiti Nui)
- lyrics/music :: Maeva BOUGES, Irmine TEHEI, Angele TEROROTUA, Johanna NOUVEAU, Patrick AMARU, Louis MAMATUI, and Jean-Pierre CELESTIN (the compositional group created both the lyrics and music)
- note :: adopted 1993; serves as a local anthem; as a territory of France, "La Marseillaise" is official (see France)
*** Government - note
under certain acts of France, French Polynesia has acquired autonomy in all areas except those relating to police and justice, monetary policy, tertiary education, immigration, and defense and foreign affairs; the duties of its president are fashioned after those of the French prime minister
** Economy
*** Economy - overview
Since 1962, when France stationed military personnel in the region, French Polynesia has changed from a subsistence agricultural economy to one in which a high proportion of the work force is either employed by the military or supports the tourist industry. With the halt of French nuclear testing in 1996, the military contribution to the economy fell sharply. After growing at an average yearly rate of 4.2% from 1997-2007, GDP stagnated in 2008 and fell by 4.2% in 2009, marking French Polynesia’s entry into recession. GDP growth was positive in 2010-12. Following steady employment level increases between 2002 and 2007 that averaged 2.4% yearly, the number of workers fell by an annual average of 2.2% between 2008 and 2013, due in part to decreased tourism (down an average of 4% per year) in that time period. French Polynesia’s tourism-dominated service sector accounted for 85% of total value added for the economy in 2009, employing 80% of the workforce. A small manufacturing sector predominantly processes products from French Polynesia’s primary sector - 3% of total economy - including agriculture, pearl farming, and fishing.
*** GDP (purchasing power parity)
$7.15 billion (2012 est.)
$6.982 billion (2011 est.)
$6.963 billion (2010 est.)
- country comparison to the world :: 166
*** GDP (official exchange rate)
$7.15 billion (2012 est.)
*** GDP - real growth rate
2.4% (2012 est.)
0.3% (2011 est.)
2.2% (2010 est.)
- country comparison to the world :: 216
*** GDP - per capita (PPP)
$26,100 (2012 est.)
$26,000 (2010 est.)
- country comparison to the world :: 65
*** GDP - composition, by sector of origin
- agriculture :: 2.5%
- industry :: 13%
- services :: 84.5% (2009)
*** Agriculture - products
coconuts, vanilla, vegetables, fruits, coffee; poultry, beef, dairy products; fish
*** Industries
tourism, pearls, agricultural processing, handicrafts, phosphates
*** Industrial production growth rate
NA%
*** Labor force
114,300 (2012 est.)
- country comparison to the world :: 182
*** Labor force - by occupation
- agriculture :: 13%
- industry :: 19%
- services :: 68% (2013)
*** Unemployment rate
21.8% (2012)
11.7% (2010)
- country comparison to the world :: 167
*** Population below poverty line
19.7% (2009 est.)
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $1.891 billion
- expenditures :: $1.833 billion (2012)
*** Taxes and other revenues
26.4% of GDP (2012)
- country comparison to the world :: 96
*** Budget surplus (+) or deficit (-)
0.8% of GDP (2012)
- country comparison to the world :: 26
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
1.1% (2013 est.)
1.5% (2011 est.)
- country comparison to the world :: 63
*** Market value of publicly traded shares
$NA
*** Exports
$230 million (2013 est.)
$211 million (2005 est.)
- country comparison to the world :: 182
*** Exports - commodities
cultured pearls, coconut products, mother-of-pearl, vanilla, shark meat
*** Exports - partners
Japan 35%, US 24%, Hong Kong 17%, France 9.1%, China 4.2% (2014)
*** Imports
$1.72 billion (2013 est.)
$1.706 billion (2005 est.)
- country comparison to the world :: 170
*** Imports - commodities
fuels, foodstuffs, machinery and equipment
*** Imports - partners
France 24%, South Korea 10%, China 9.6%, USA 9.3%, New Zealand 8.5%, Singapore 8.2%, Australia 4% (2014)
*** Debt - external
$NA
*** Exchange rates
Comptoirs Francais du Pacifique francs (XPF) per US dollar -
89.85 (2013 est.)
90.56 2012 est.)
85.74 (2011 est.)
90.01 (2010 est.)
** Energy
*** Electricity - production
825 million kWh (2011 est.)
- country comparison to the world :: 153
*** Electricity - consumption
767.3 million kWh (2011 est.)
- country comparison to the world :: 161
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 141
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 148
*** Electricity - installed generating capacity
224,000 kW (2011 est.)
- country comparison to the world :: 159
*** Electricity - from fossil fuels
79% of total installed capacity (2011 est.)
- country comparison to the world :: 94
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 91
*** Electricity - from hydroelectric plants
21% of total installed capacity (2011 est.)
- country comparison to the world :: 92
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 175
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 175
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 114
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 187
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 135
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 145
*** Refined petroleum products - consumption
7,430 bbl/day (2013 est.)
- country comparison to the world :: 162
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 178
*** Refined petroleum products - imports
7,190 bbl/day (2010 est.)
- country comparison to the world :: 136
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 133
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 145
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 99
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 195
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 140
*** Carbon dioxide emissions from consumption of energy
1.071 million Mt (2012 est.)
- country comparison to the world :: 167
** Communications
*** Telephones - fixed lines
- total subscriptions :: 55,000
- subscriptions per 100 inhabitants :: 20 (2014 est.)
- country comparison to the world :: 159
*** Telephones - mobile cellular
- total :: 239,700
- subscriptions per 100 inhabitants :: 86 (2014 est.)
- country comparison to the world :: 180
*** Telephone system
- domestic :: combined fixed-line and mobile-cellular density is roughly 100 per 100 persons
- international :: country code - 689; satellite earth station - 1 Intelsat (Pacific Ocean) (2011)
*** Broadcast media
the publicly owned French Overseas Network (RFO), which operates in France's overseas departments and territories, broadcasts on 2 TV channels and 1 radio station; 1 government-owned TV station; a small number of privately owned radio stations (2008)
*** Radio broadcast stations
AM 2, FM 14, shortwave 2 (1998)
*** Television broadcast stations
7 (plus 17 repeaters) (1997)
*** Internet country code
.pf
*** Internet users
- total :: 161,100
- percent of population :: 57.5% (2014 est.)
- country comparison to the world :: 163
** Transportation
*** Airports
54 (2013)
- country comparison to the world :: 87
*** Airports - with paved runways
- total :: 45
- over 3,047 m :: 2
- 1,524 to 2,437 m :: 5
- 914 to 1,523 m :: 33
- under 914 m :: 5 (2013)
*** Airports - with unpaved runways
- total :: 9
- 914 to 1,523 m :: 4
- under 914 m :: 
5 (2013)
*** Heliports
1 (2013)
*** Roadways
- total :: 2,590 km
- paved :: 1,735 km
- unpaved :: 855 km (1999)
- country comparison to the world :: 172
*** Merchant marine
- registered in other countries :: 12 (Cambodia 1, France 11) (2010)
- country comparison to the world :: 107
*** Ports and terminals
- major seaport(s) :: Papeete
** Military
*** Military branches
no regular military forces (2011)
*** Manpower available for military service
- males age 16-49 :: 82,722 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 67,363
- females age 16-49 :: 66,053 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 2,498
- female :: 2,390 (2010 est.)
*** Military - note
defense is the responsibility of France
** Transnational Issues
*** Disputes - international
none