** Introduction
*** Background
Spain ceded Guam to the US in 1898. Captured by the Japanese in 1941, it was retaken by the US three years later. The military installations on the island are some of the most strategically important US bases in the Pacific.
** Geography
*** Location
Oceania, island in the North Pacific Ocean, about three-quarters of the way from Hawaii to the Philippines
*** Geographic coordinates
13 28 N, 144 47 E
*** Map references
Oceania
*** Area
- total :: 544 sq km
- land :: 544 sq km
- water :: 0 sq km
- country comparison to the world :: 195
*** Area - comparative
three times the size of Washington, DC
*** Land boundaries
0 km
*** Coastline
125.5 km
*** Maritime claims
- territorial sea :: 12 nm
- exclusive economic zone :: 200 nm
*** Climate
tropical marine; generally warm and humid, moderated by northeast trade winds; dry season (January to June), rainy season (July to December); little seasonal temperature variation
*** Terrain
volcanic origin, surrounded by coral reefs; relatively flat coralline limestone plateau (source of most fresh water), with steep coastal cliffs and narrow coastal plains in north, low hills in center, mountains in south
*** Elevation extremes
- lowest point :: Pacific Ocean 0 m
- highest point :: Mount Lamlam 406 m
*** Natural resources
aquatic wildlife (supporting tourism), fishing (largely undeveloped)
*** Land use
- agricultural land :: 33.4%
arable land 1.9%; permanent crops 16.7%; permanent pasture 14.8%
- forest :: 47.9%
- other :: 18.7% (2011 est.)
*** Irrigated land
2 sq km (2011)
*** Natural hazards
frequent squalls during rainy season; relatively rare but potentially destructive typhoons (June to December)
*** Environment - current issues
extirpation of native bird population by the rapid proliferation of the brown tree snake, an exotic, invasive species
*** Geography - note
largest and southernmost island in the Mariana Islands archipelago; strategic location in western North Pacific Ocean
** People and Society
*** Nationality
- noun :: Guamanian(s) (US citizens)
- adjective :: Guamanian
*** Ethnic groups
Chamorro 37.3%, Filipino 26.3%, white 7.1%, Chuukese 7%, Korean 2.2%, other Pacific Islander 2%, other Asian 2%, Chinese 1.6%, Palauan 1.6%, Japanese 1.5%, Pohnpeian 1.4%, mixed 9.4%, other 0.6% (2010 est.)
*** Languages
English 43.6%, Filipino 21.2%, Chamorro 17.8%, other Pacific island languages 10%, Asian languages 6.3%, other 1.1% (2010 est.)
*** Religions
Roman Catholic 85%, other 15% (1999 est.)
*** Population
161,785 (July 2015 est.)
- country comparison to the world :: 188
*** Age structure
- 0-14 years :: 25.47% (male 21,189/female 20,017)
- 15-24 years :: 17% (male 14,267/female 13,241)
- 25-54 years :: 39.23% (male 32,315/female 31,159)
- 55-64 years :: 9.4% (male 7,655/female 7,560)
- 65 years and over :: 8.89% (male 6,552/female 7,830) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 52%
- youth dependency ratio :: 38.7%
- elderly dependency ratio :: 13.3%
- potential support ratio :: 7.5% (2015 est.)
*** Median age
- total :: 30.1 years
- male :: 29.6 years
- female :: 30.7 years (2015 est.)
*** Population growth rate
0.54% (2015 est.)
- country comparison to the world :: 156
*** Birth rate
16.82 births/1,000 population (2015 est.)
- country comparison to the world :: 109
*** Death rate
5.12 deaths/1,000 population (2015 est.)
- country comparison to the world :: 184
*** Net migration rate
-6.34 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 202
*** Urbanization
- urban population :: 94.5% of total population (2015)
- rate of urbanization :: 1.36% annual rate of change (2010-15 est.)
*** Major urban areas - population
HAGATNA (capital) 143,000 (2014)
*** Sex ratio
- at birth :: 1.06 male(s)/female
- 0-14 years :: 1.06 male(s)/female
- 15-24 years :: 1.08 male(s)/female
- 25-54 years :: 1.04 male(s)/female
- 55-64 years :: 1.01 male(s)/female
- 65 years and over :: 0.84 male(s)/female
- total population :: 1.03 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 5.41 deaths/1,000 live births
- male :: 5.81 deaths/1,000 live births
- female :: 4.99 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 171
*** Life expectancy at birth
- total population :: 78.98 years
- male :: 75.94 years
- female :: 82.21 years (2015 est.)
- country comparison to the world :: 50
*** Total fertility rate
2.34 children born/woman (2015 est.)
- country comparison to the world :: 87
*** Drinking water source
- improved :: 
urban: 99.5% of population
rural: 99.5% of population
total: 99.5% of population
- unimproved :: 
urban: 0.5% of population
rural: 0.5% of population
total: 0.5% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 89.8% of population
rural: 89.8% of population
total: 89.8% of population
- unimproved :: 
urban: 10.2% of population
rural: 10.2% of population
total: 10.2% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
*** Unemployment, youth ages 15-24
- total :: 29.4%
- male :: 29.7%
- female :: 28.9% (2011 est.)
- country comparison to the world :: 25
** Government
*** Country name
- conventional long form :: Territory of Guam
- conventional short form :: Guam
- local long form :: Guahan
- local short form :: Guahan
*** Dependency status
organized, unincorporated territory of the US with policy relations between Guam and the US under the jurisdiction of the Office of Insular Affairs, US Department of the Interior
*** Government type
NA
*** Capital
- name :: Hagatna (Agana)
- geographic coordinates :: 13 28 N, 144 44 E
- time difference :: UTC+10 (15 hours ahead of Washington, DC, during Standard Time)
*** Administrative divisions
none (territory of the US)
*** Independence
none (territory of the US)
*** National holiday
Discovery Day (or Magellan Day), first Monday in March (1521)
*** Constitution
effective 1 July 1950; amended many times, last in 2012 (2013)
*** Legal system
common law modeled on US system; US federal laws apply
*** Suffrage
18 years of age; universal; note - Guamanians are US citizens but do not vote in US presidential elections
*** Executive branch
- chief of state :: President Barack H. OBAMA (since 20 January 2009); Vice President Joseph R. BIDEN (since 20 January 2009)
- head of government :: Governor Eddie CALVO (since 3 January 2011); Lieutenant Governor Ray TENORIO (since 3 January 2011)
- cabinet :: Cabinet appointed by the governor with the consent of the Legislature
- elections/appointments :: president and vice president indirectly elected on the same ballot by an Electoral College of 'electors' chosen from each state to serve a 4-year term (eligible for a second term); under the US Constitution, residents of unincorporated territories, such as Guam, do not vote in elections for US president and vice president; however, they may vote in Democratic and Republican presidential primary elections; governor and lieutenant governor elected on the same ballot by absolute majority vote in 2 rounds if needed for a 4-year term (eligible for 2 consecutive terms); election last held on 4 November 2014 (next to be held in November 2018)
- election results :: Eddie CALVO reelected governor; percent of vote - Eddie CALVO (Republican Party) 64%, Carl GUTIERREZ (Democratic Party) 36%; Ray TENORIO elected lieutenant governor
*** Legislative branch
- description :: unicameral Legislature of Guam or Liheslaturan Guahan (15 seats; members elected in a single countrywide constituency by simple majority vote to serve 2-year terms)
- elections :: last held on 4 November 2014 (next to be held on 8 November 2016)
- election results :: percent of vote by party - NA; seats by party - Democratic Party 9, Republican Party 6
- note :: Guam directly elects 1 member by simple majority vote to serve a 2-year term as a delegate to the US House of Representatives; the delegate can vote when serving on a committee and when the House meets as the Committee of the Whole House, but not when legislation is submitted for a “full floor” House vote; election of delegate last held on 6 November 2012 (next to be held on 8 November 2014)
*** Judicial branch
- highest court(s) :: Supreme Court of Guam (consists of 3 justices); note - appeals beyond the Supreme Court of Guam are heard by the US Supreme Court
- judge selection and term of office :: justices appointed by the governor and confirmed by the Guam legislature; justices appointed for life subject to retention election every 10 years
- subordinate courts :: Superior Court of Guam - includes several divisions; US Federal District Court for the District of Guam (a US territorial court; appeals beyond this court are heard before the US Court of Appeals for the Ninth Circuit)
*** Political parties and leaders
Democratic Party [Carlo BRANCH]
Republican Party [Mike BENITO]
*** Political pressure groups and leaders
Guam Commission on Decolonization
Guam Federation of Teachers' Union
Guam Waterworks Authority Workers
We Are Guahan
*** International organization participation
AOSIS (observer), IOC, PIF (observer), SPC, UPU
*** Diplomatic representation in the US
none (territory of the US)
*** Diplomatic representation from the US
none (territory of the US)
*** Flag description
territorial flag is dark blue with a narrow red border on all four sides; centered is a red-bordered, pointed, vertical ellipse containing a beach scene, a proa or outrigger canoe with sail, and a palm tree with the word GUAM superimposed in bold red letters; the proa is sailing in Agana Bay with the promontory of Punta Dos Amantes, near the capital, in the background; the shape of the central emblem is that of a Chamorro sling stone, used as a weapon for defense or hunting; blue represents the sea and red the blood shed in the struggle against oppression
- note :: the US flag is the national flag
*** National symbol(s)
coconut tree; national colors: deep blue, red
*** National anthem
- name :: "Fanohge Chamoru" (Stand Ye Guamanians)
- lyrics/music :: Ramon Manalisay SABLAN [English], Lagrimas UNTALAN [Chamoru]/Ramon Manalisay SABLAN
- note :: adopted 1919; the local anthem is also known as "Guam Hymn"; as a territory of the United States, "The Star-Spangled Banner," which generally follows the playing of "Stand Ye Guamanians," is official (see United States)
** Economy
*** Economy - overview
US national defense spending is the main driver of Guam’s economy, followed by tourism and other services. Total federal spending (defense and non-defense) amounted to $1.973 billion in 2014, or 40.4% of GDP. Service exports, mainly spending by foreign tourists while on Guam, amounted to $651 million in 2013, or 13.3% of GDP. In 2013, Guam’s economy grew 0.6%. Despite slow growth, Guam’s economy has been stable over the last decade. National defense spending cushions the island’s economy against fluctuations in tourism, its other major income source. Guam serves as a forward US base for the Western Pacific and is home to thousands of American military personnel. Federal grants amounted to $373.3 million in 2013, or 32.6% of Guam’s total revenues for fiscal year.
*** GDP (purchasing power parity)
$4.882 billion (2013 est.)
$4.756 billion (2012 est.)
$4.562 billion (2011 est.)
- country comparison to the world :: 175
*** GDP (official exchange rate)
$4.6 billion (2010 est.)
*** GDP - real growth rate
0.6% (2013 est.)
1.8% (2012)
-0.3% (2011)
- country comparison to the world :: 172
*** GDP - per capita (PPP)
$30,500 (2013 est.)
$29,800 (2012)
$28,600 (2011)
- country comparison to the world :: 58
*** GDP - composition, by end use
- household consumption :: 63.7%
- government consumption :: 64.9%
- investment in fixed assets :: 5.8%
- exports of goods and services :: 17%
- imports of goods and services :: 17% (2013)
*** GDP - composition, by sector of origin
- agriculture :: NA%
- industry :: NA%
- services :: NA%
*** Agriculture - products
fruits, copra, vegetables; eggs, pork, poultry, beef
*** Industries
national defense, tourism, construction, transshipment services, concrete products, printing and publishing, food processing, textiles
*** Industrial production growth rate
NA%
*** Labor force
70,490
- note :: this number is for the civilian labor force only (2013 est.)
- country comparison to the world :: 187
*** Labor force - by occupation
- agriculture :: 0.3%
- industry :: 21.6%
- services :: 78.1% (2013)
*** Unemployment rate
8.4% (2013 est.)
8.2% (2010 est.)
- country comparison to the world :: 93
*** Population below poverty line
23% (2001 est.)
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $1.147 billion
- expenditures :: $1.188 billion (2013 est.)
*** Taxes and other revenues
24.9% of GDP (2013 est.)
- country comparison to the world :: 156
*** Budget surplus (+) or deficit (-)
-0.9% of GDP (2013 est.)
- country comparison to the world :: 119
*** Public debt
32.1% of GDP (2013)
35.8% of GDP (2012)
*** Fiscal year
1 October - 30 September
*** Inflation rate (consumer prices)
1.8% (2014 est.)
4% (2011 est.)
- country comparison to the world :: 92
*** Exports
$828 million (2013 est.)
$795 million (2012)
- country comparison to the world :: 199
*** Exports - commodities
transshipments of refined petroleum products, construction materials, fish, foodstuffs and beverages
*** Imports
$2.501 billion (2013 est.)
$2.438 billion (2012)
- country comparison to the world :: 182
*** Imports - commodities
petroleum and petroleum products, food, manufactured goods
*** Debt - external
$NA
*** Exchange rates
the US dollar is used
** Energy
*** Electricity - production
1.566 billion kWh (2013 est.)
- country comparison to the world :: 140
*** Electricity - consumption
1.564 billion kWh (2012 est.)
- country comparison to the world :: 145
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 147
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 154
*** Electricity - installed generating capacity
552,000 kW (2011 est.)
- country comparison to the world :: 138
*** Electricity - from fossil fuels
100% of total installed capacity (2011 est.)
- country comparison to the world :: 16
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 99
*** Electricity - from hydroelectric plants
0% of total installed capacity (2011 est.)
- country comparison to the world :: 175
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 182
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 180
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 121
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 194
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 140
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 151
*** Refined petroleum products - consumption
12,000 bbl/day (2013 est.)
- country comparison to the world :: 150
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 182
*** Refined petroleum products - imports
6,579 bbl/day (2010 est.)
- country comparison to the world :: 139
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 139
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 150
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 107
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 201
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 145
*** Carbon dioxide emissions from consumption of energy
1.775 million Mt (2012 est.)
- country comparison to the world :: 153
** Communications
*** Telephones - fixed lines
- total subscriptions :: 67,400
- subscriptions per 100 inhabitants :: 42 (2014 est.)
- country comparison to the world :: 152
*** Telephones - mobile cellular
- total :: 98,000
- subscriptions per 100 inhabitants :: 62 (2004)
- country comparison to the world :: 191
*** Telephone system
- general assessment :: modern system, integrated with US facilities for direct dialing, including free use of 800 numbers
- domestic :: digital system, including mobile-cellular service and local access to the Internet
- international :: country code - 1-671; major landing point for submarine cables between Asia and the US (Guam is a transpacific communications hub for major carriers linking the US and Asia); satellite earth stations - 2 Intelsat (Pacific Ocean) (2011)
*** Broadcast media
about a dozen TV channels, including digital channels; multi-channel cable TV services are available; roughly 20 radio stations (2009)
*** Radio broadcast stations
AM 3, FM 11, shortwave 2 (2005)
*** Television broadcast stations
3 (2006)
*** Internet country code
.gu
*** Internet users
- total :: 107,800
- percent of population :: 67.0% (2014 est.)
- country comparison to the world :: 168
** Transportation
*** Airports
5 (2013)
- country comparison to the world :: 179
*** Airports - with paved runways
- total :: 4
- over 3,047 m :: 2
- 2,438 to 3,047 m :: 1
- 914 to 1,523 m :: 1 (2013)
*** Airports - with unpaved runways
- total :: 1
- under 914 m :: 
1 (2013)
*** Roadways
- total :: 1,045 km (2008)
- country comparison to the world :: 186
*** Ports and terminals
- major seaport(s) :: Apra Harbor
** Military
*** Manpower fit for military service
- males age 16-49 :: 38,358
- females age 16-49 :: 36,869 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 1,701
- female :: 1,608 (2010 est.)
*** Military - note
defense is the responsibility of the US
** Transnational Issues
*** Disputes - international
none