** Introduction
*** Background
Named in 1643 for the day of its discovery, the island was annexed and settlement began by the UK in 1888 with the discovery of the island's phosphate deposits. Following the Second World War, Christmas Island came under the jurisdiction of the new British Colony of Singapore. The island existed as a separate Crown colony from 1 January 1958 to 1 October 1958 when its transfer to Australian jurisdiction was finalized. That date is still celebrated on the first Monday in October as Territory Day. Almost two-thirds of the island has been declared a national park.
** Geography
*** Location
Southeastern Asia, island in the Indian Ocean, south of Indonesia
*** Geographic coordinates
10 30 S, 105 40 E
*** Map references
Southeast Asia
*** Area
- total :: 135 sq km
- land :: 135 sq km
- water :: 0 sq km
- country comparison to the world :: 222
*** Area - comparative
about three-quarters the size of Washington, DC
*** Land boundaries
0 km
*** Coastline
138.9 km
*** Maritime claims
- territorial sea :: 12 nm
- contiguous zone :: 12 nm
- exclusive fishing zone :: 200 nm
*** Climate
tropical with a wet season (December to April) and dry season; heat and humidity moderated by trade winds
*** Terrain
steep cliffs along coast rise abruptly to central plateau
*** Elevation extremes
- lowest point :: Indian Ocean 0 m
- highest point :: Murray Hill 361 m
*** Natural resources
phosphate, beaches
*** Land use
- agricultural land :: 0%
arable land 0%; permanent crops 0%; permanent pasture 0%
- other :: 100% (mainly tropical reainforest; 63% of the island is a national park) (2011 est.)
*** Irrigated land
NA
*** Natural hazards
the narrow fringing reef surrounding the island can be a maritime hazard
*** Environment - current issues
loss of rainforest; impact of phosphate mining
*** Geography - note
located along major sea lanes of Indian Ocean
** People and Society
*** Nationality
- noun :: Christmas Islander(s)
- adjective :: Christmas Island
*** Ethnic groups
Chinese 70%, European 20%, Malay 10%
- note :: no indigenous population (2001)
*** Languages
English (official), Chinese, Malay
*** Religions
Buddhist 16.9%, Christian 16.4%, Muslim 14.8%, other 1.3%, none 9.2%, unspecified 41.5% (2011 est.)
*** Population
1,530 (July 2014 est.)
- country comparison to the world :: 233
*** Population growth rate
1.11% (2014 est.)
- country comparison to the world :: 110
*** Sex ratio
NA (2009 est.)
*** Infant mortality rate
- total :: NA
- male :: NA
- female :: NA
*** Life expectancy at birth
- total population :: NA
- male :: NA
- female :: NA
*** Total fertility rate
NA
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
** Government
*** Country name
- conventional long form :: Territory of Christmas Island
- conventional short form :: Christmas Island
*** Dependency status
non-self governing territory of Australia; administered from Canberra by the Department of Regional Australia, Local Government, Arts and Sport
*** Government type
NA
*** Capital
- name :: The Settlement
- geographic coordinates :: 10 25 S, 105 43 E
- time difference :: UTC+7 (12 hours ahead of Washington, DC, during Standard Time)
*** Administrative divisions
none (territory of Australia)
*** Independence
none (territory of Australia)
*** National holiday
Australia Day, 26 January (1788)
*** Constitution
1 October 1958 (Christmas Island Act 1958); amended many times, last in 2010 (Territories Law Reform Act 2010) (2010)
*** Legal system
legal system is under the authority of the governor general of Australia and Australian law
*** Suffrage
18 years of age
*** Executive branch
- chief of state :: Queen ELIZABETH II (since 6 February 1952); represented by Governor General of the Commonwealth of Australia General Sir Peter COSGROVE (since28 March 2014)
- head of government :: Administrator Jon STANHOPE (since 5 October 2012)
- elections/appointments :: the monarchy is hereditary; governor general appointed by the monarch on the recommendation of the Australian prime minister; administrator appointed by the governor general of Australia for a 2-year term and represents the monarch and Australia
*** Legislative branch
- description :: unicameral Christmas Island Shire Council (9 seats; members directly elected by simple majority vote to serve 4-year terms with a portion of the membership renewed every 2 years)
- elections :: held every two years with half the members standing for election; last held In 2011 (next to be held in 2013)
- election results :: percent of vote - NA; seats - independents 9
*** Judicial branch
- highest court(s) :: under the terms of the Territorial Law Reform Act 1992, Western Australia provides court services as needed for the island including the Supreme Court and subordinate courts (District Court, Magistrate Court, Family Court, Children's Court, and Coroners' Court)
*** Political parties and leaders
none
*** Political pressure groups and leaders
none
*** International organization participation
none
*** Diplomatic representation in the US
none (territory of Australia)
*** Diplomatic representation from the US
none (territory of Australia)
*** Flag description
territorial flag; divided diagonally from upper hoist to lower fly; the upper triangle is green with a yellow image of the Golden Bosun Bird superimposed; the lower triangle is blue with the Southern Cross constellation, representing Australia, superimposed; a centered yellow disk displays a green map of the island
- note :: the flag of Australia is used for official purposes
*** National symbol(s)
golden bosun bird
*** National anthem
- note :: as a territory of Australia, "Advance Australia Fair" remains official as the national anthem, while "God Save the Queen" serves as the royal anthem (see Australia)

** Economy
*** Economy - overview
The main economic activities on Christmas Island are the mining of low grade phosphate, limited tourism, the provision of government services and more recently the construction and operation of the Immigration Detention Center. The government sector includes administration, health, education, policing, customs, quarantine and defense.
*** GDP (purchasing power parity)
$NA
*** Agriculture - products
NA
*** Industries
tourism, phosphate extraction (near depletion)
*** Labor force
NA
*** Budget
- revenues :: $NA
- expenditures :: $NA
*** Fiscal year
1 July - 30 June
*** Exports
$NA
*** Exports - commodities
phosphate
*** Imports
$NA
*** Imports - commodities
consumer goods
*** Exchange rates
Australian dollars (AUD) per US dollar -
1.098 (2014)
1.0358 (2013)
0.97 (2012)
0.9695 (2011)
1.0902 (2010)
** Communications
*** Telephone system
- general assessment :: service provided by the Australian network
- domestic :: GSM mobile-cellular telephone service replaced older analog system in February 2005
- international :: country code - 61-8; satellite earth station - 1 (Intelsat provides telephone and telex service) (2005)
*** Broadcast media
1 community radio station; satellite broadcasts of several Australian radio and TV stations (2009)
*** Radio broadcast stations
AM 1, FM 2, shortwave 0 (2006)
*** Television broadcast stations
0 (TV broadcasts received via satellite from mainland Australia) (2006)
*** Internet country code
.cx
*** Internet users
- total :: 464
- percent of population :: 16.7% (2001)
- country comparison to the world :: 217
** Transportation
*** Airports
1 (2013)
- country comparison to the world :: 215
*** Airports - with paved runways
- total :: 1
- 1,524 to 2,437 m :: 1 (2013)
*** Railways
- total :: 18 km
- standard gauge :: 18 km 1.435-m (not in operation) (2010)
- country comparison to the world :: 135
*** Roadways
- total :: 140 km
- paved :: 30 km
- unpaved :: 110 km (2011)
- country comparison to the world :: 212
*** Ports and terminals
- major seaport(s) :: Flying Fish Cove
** Military
*** Military - note
defense is the responsibility of Australia
** Transnational Issues
*** Disputes - international
none