** Introduction
*** Background
Modern-day Laos has its roots in the ancient Lao kingdom of Lan Xang, established in the 14th century under King FA NGUM. For 300 years Lan Xang had influence reaching into present-day Cambodia and Thailand, as well as over all of what is now Laos. After centuries of gradual decline, Laos came under the domination of Siam (Thailand) from the late 18th century until the late 19th century when it became part of French Indochina. The Franco-Siamese Treaty of 1907 defined the current Lao border with Thailand. In 1975, the communist Pathet Lao took control of the government ending a six-century-old monarchy and instituting a strict socialist regime closely aligned to Vietnam. A gradual, limited return to private enterprise and the liberalization of foreign investment laws began in 1988. Laos became a member of ASEAN in 1997 and the WTO in 2013.
** Geography
*** Location
Southeastern Asia, northeast of Thailand, west of Vietnam
*** Geographic coordinates
18 00 N, 105 00 E
*** Map references
Southeast Asia
*** Area
- total :: 236,800 sq km
- land :: 230,800 sq km
- water :: 6,000 sq km
- country comparison to the world :: 84
*** Area - comparative
slightly larger than Utah
*** Land boundaries
- total :: 5,274 km
- border countries (5) :: Burma 238 km, Cambodia 555 km, China 475 km, Thailand 1,845 km, Vietnam 2,161 km
*** Coastline
0 km (landlocked)
*** Maritime claims
none (landlocked)
*** Climate
tropical monsoon; rainy season (May to November); dry season (December to April)
*** Terrain
mostly rugged mountains; some plains and plateaus
*** Elevation extremes
- lowest point :: Mekong River 70 m
- highest point :: Phu Bia 2,817 m
*** Natural resources
timber, hydropower, gypsum, tin, gold, gemstones
*** Land use
- agricultural land :: 10.6%
arable land 6.2%; permanent crops 0.7%; permanent pasture 3.7%
- forest :: 67.9%
- other :: 21.5% (2011 est.)
*** Irrigated land
3,100 sq km (2005)
*** Total renewable water resources
333.5 cu km (2011)
*** Freshwater withdrawal (domestic/industrial/agricultural)
- total :: 3.49  cu km/yr (4%/5%/91%)
- per capita :: 588.9  cu m/yr (2005)
*** Natural hazards
floods, droughts
*** Environment - current issues
unexploded ordnance; deforestation; soil erosion; most of the population does not have access to potable water
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Endangered Species, Environmental Modification, Law of the Sea, Ozone Layer Protection
- signed, but not ratified :: none of the selected agreements
*** Geography - note
landlocked; most of the country is mountainous and thickly forested; the Mekong River forms a large part of the western boundary with Thailand
** People and Society
*** Nationality
- noun :: Lao(s) or Laotian(s)
- adjective :: Lao or Laotian
*** Ethnic groups
Lao 54.6%, Khmou 10.9%, Hmong 8%, Tai 3.8%, Phuthai 3.3%, Leu 2.2%, Katang 2.1%, Makong 2.1%, Akha 1.6%, other 10.4%, unspecified 1% (2005 est.)
*** Languages
Lao (official), French, English, various ethnic languages
*** Religions
Buddhist 66.8%, Christian 1.5%, other 31%, unspecified 0.7% (2005 est.)
*** Population
6,911,544 (July 2015 est.)
- country comparison to the world :: 104
*** Age structure
- 0-14 years :: 34.1% (male 1,190,119/female 1,166,774)
- 15-24 years :: 21.31% (male 731,531/female 741,107)
- 25-54 years :: 35.54% (male 1,211,600/female 1,245,010)
- 55-64 years :: 5.23% (male 177,142/female 184,409)
- 65 years and over :: 3.82% (male 119,392/female 144,460) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 62.8%
- youth dependency ratio :: 56.6%
- elderly dependency ratio :: 6.2%
- potential support ratio :: 16.1% (2015 est.)
*** Median age
- total :: 22.3 years
- male :: 22 years
- female :: 22.6 years (2015 est.)
*** Population growth rate
1.55% (2015 est.)
- country comparison to the world :: 79
*** Birth rate
24.25 births/1,000 population (2015 est.)
- country comparison to the world :: 60
*** Death rate
7.63 deaths/1,000 population (2015 est.)
- country comparison to the world :: 110
*** Net migration rate
-1.09 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 149
*** Urbanization
- urban population :: 38.6% of total population (2015)
- rate of urbanization :: 4.93% annual rate of change (2010-15 est.)
*** Major urban areas - population
VIENTIANE (capital) 997,000 (2015)
*** Sex ratio
- at birth :: 1.04 male(s)/female
- 0-14 years :: 1.02 male(s)/female
- 15-24 years :: 0.99 male(s)/female
- 25-54 years :: 0.97 male(s)/female
- 55-64 years :: 0.96 male(s)/female
- 65 years and over :: 0.83 male(s)/female
- total population :: 0.99 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 52.97 deaths/1,000 live births
- male :: 58.52 deaths/1,000 live births
- female :: 47.21 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 32
*** Life expectancy at birth
- total population :: 63.88 years
- male :: 61.88 years
- female :: 65.95 years (2015 est.)
- country comparison to the world :: 181
*** Total fertility rate
2.82 children born/woman (2015 est.)
- country comparison to the world :: 62
*** Contraceptive prevalence rate
49.8% (2011/12)
*** Health expenditures
2% of GDP (2013)
- country comparison to the world :: 181
*** Physicians density
0.18 physicians/1,000 population (2012)
*** Hospital bed density
1.5 beds/1,000 population (2012)
*** Drinking water source
- improved :: 
urban: 85.6% of population
rural: 69.4% of population
total: 75.7% of population
- unimproved :: 
urban: 14.4% of population
rural: 30.6% of population
total: 24.3% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 94.5% of population
rural: 56% of population
total: 70.9% of population
- unimproved :: 
urban: 5.5% of population
rural: 44% of population
total: 29.1% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
0.26% (2014 est.)
- country comparison to the world :: 91
*** HIV/AIDS - people living with HIV/AIDS
11,100 (2014 est.)
- country comparison to the world :: 91
*** HIV/AIDS - deaths
500 (2014 est.)
- country comparison to the world :: 86
*** Major infectious diseases
- degree of risk :: very high
- food or waterborne diseases :: bacterial and protozoal diarrhea, hepatitis A, and typhoid fever
- vectorborne diseases :: dengue fever and malaria
- note :: highly pathogenic H5N1 avian influenza has been identified in this country; it poses a negligible risk with extremely rare cases possible among US citizens who have close contact with birds (2013)
*** Obesity - adult prevalence rate
3% (2014)
- country comparison to the world :: 179
*** Children under the age of 5 years underweight
26.5% (2012)
- country comparison to the world :: 22
*** Education expenditures
2.8% of GDP (2010)
- country comparison to the world :: 147
*** Literacy
- definition :: age 15 and over can read and write
- total population :: 79.9%
- male :: 87.1%
- female :: 72.8% (2015 est.)
*** School life expectancy (primary to tertiary education)
- total :: 11 years
- male :: 11 years
- female :: 10 years (2013)
*** Child labor - children ages 5-14
- total number :: 175,138
- percentage :: 11% (2006 est.)
** Government
*** Country name
- conventional long form :: Lao People's Democratic Republic
- conventional short form :: Laos
- local long form :: Sathalanalat Paxathipatai Paxaxon Lao
- local short form :: Pathet Lao (unofficial)
*** Government type
Communist state
*** Capital
- name :: Vientiane (Viangchan)
- geographic coordinates :: 17 58 N, 102 36 E
- time difference :: UTC+7 (12 hours ahead of Washington, DC, during Standard Time)
*** Administrative divisions
17 provinces (khoueng, singular and plural) and 1 capital city* (nakhon luang, singular and plural); Attapu, Bokeo, Bolikhamxai, Champasak, Houaphan, Khammouan, Louangnamtha, Louangphabang, Oudomxai, Phongsali, Salavan, Savannakhet, Viangchan (Vientiane)*, Viangchan, Xaignabouli, Xaimsomboun, Xekong, Xiangkhouang
*** Independence
19 July 1949 (from France)
*** National holiday
Republic Day, 2 December (1975)
*** Constitution
previous 1947 (preindependence); latest promulgated 13-15 August 1991; amended 2003 (2003)
*** Legal system
civil law system similar in form to the French system
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; non-party state to the ICCt
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: President Lt. Gen. CHOUMMALI Saignason (since 8 June 2006); Vice President BOUN-GNANG Volachit (since 8 June 2006)
- head of government :: Prime Minister THONGSING Thammavong (since 24 December 2010); Deputy Prime Ministers SOMSAVAT Lengsavat (since 26 February 1998), THONGLOUN Sisoulit (since 27 March 2001), Maj. Gen. ASANG Laoli (since May 2002), BOUNPON Bouttanavong (since July 2014), PHANKHAM Viphavan (since July 2014)
- cabinet :: Council of Ministers appointed by the president, approved by the National Assembly
- elections/appointments :: president and vice president indirectly elected by the National Assembly for a 5-year term (no term limits); election last held on 30 April 2011 (next to be held in 2016); prime minister nominated by the president, elected by the National Assembly for 5-year term
- election results :: CHOUMMALI Saignason (LPRP) reelected president; BOUN-GNANG Volachit  reelected vice president; percent of National Assembly vote - NA; THONGSING Thammavong elected prime minister; percent of National Assembly vote - NA
*** Legislative branch
- description :: unicameral National Assembly or Sapha Heng Xat (132 seats; members directly elected in multi-seat constituencies by simple majority vote from candidate lists provided by the Lao People's Revolutionary Party; members serve 5-year terms)
- elections :: last held on 30 April 2011 (next to be held in 2016)
- election results :: percent of vote by party - NA; seats by party - LPRP 128, independent 4
*** Judicial branch
- highest court(s) :: People's Supreme Court (consists of NA judges)
- judge selection and term of office :: president of People's Supreme Court elected by National Assembly on recommendation of National Assembly Standing Committee; vice president of People's Supreme Court and judges appointed by National Assembly Standing Committee; judge tenure NA
- subordinate courts :: provincial, municipal, district, and military courts
*** Political parties and leaders
Lao People's Revolutionary Party or LPRP [CHOUMMALI Saignason]; other parties proscribed
*** Political pressure groups and leaders
NA
*** International organization participation
ADB, ARF, ASEAN, CP, EAS, FAO, G-77, IAEA, IBRD, ICAO, ICRM, IDA, IFAD, IFC, IFRCS, ILO, IMF, Interpol, IOC, IPU, ISO (subscriber), ITU, MIGA, NAM, OIF, OPCW, PCA, UN, UNCTAD, UNESCO, UNIDO, UNWTO, UPU, WCO, WFTU (NGOs), WHO, WIPO, WMO, WTO
*** Diplomatic representation in the US
- chief of mission :: Ambassador Mai SAYAVONGS (since 3 August 2015)
- chancery :: 2222 S Street NW, Washington, DC 20008
- telephone :: [1] (202) 332-6416
- FAX :: [1] (202) 332-4923
- consulate(s) :: New York
*** Diplomatic representation from the US
- chief of mission :: Ambassador David A. CLUNE (since 16 September 2013)
- embassy :: Thadeua Road, Kilometer 9, Ban Somvang Thai, Haysatfong District, Vientiane
- mailing address :: American Embassy Vientiane, Unit 8165, APO AP 96546
- telephone :: [856] 21-48-7000
- FAX :: [856] 21-48-7190
*** Flag description
three horizontal bands of red (top), blue (double width), and red with a large white disk centered in the blue band; the red bands recall the blood shed for liberation; the blue band represents the Mekong River and prosperity; the white disk symbolizes the full moon against the Mekong River, but also signifies the unity of the people under the Lao People's Revolutionary Party, as well as the country's bright future
*** National symbol(s)
elephant; national colors: red, white, blue
*** National anthem
- name :: "Pheng Xat Lao" (Hymn of the Lao People)
- lyrics/music :: SISANA Sisane/THONGDY Sounthonevichit
- note :: music adopted 1945, lyrics adopted 1975; the anthem's lyrics were changed following the 1975 Communist revolution that overthrew the monarchy

** Economy
*** Economy - overview
The government of Laos, one of the few remaining one-party communist states, began decentralizing control and encouraging private enterprise in 1986. The results, starting from an extremely low base, were striking - growth averaged 6% per year from 1988-2008 except during the short-lived drop caused by the Asian financial crisis that began in 1997. Laos' growth has more recently been amongst the fastest in Asia and averaged nearly 8% per year for the last decade. Despite this high growth rate, Laos remains a country with an underdeveloped infrastructure, particularly in rural areas. It has a basic, but improving, road system, and limited external and internal land-line telecommunications. Electricity is available to 83% of the population. Laos' economy is heavily dependent on capital-intensive natural resource exports. The labor force, however, still relies on agriculture, dominated by rice cultivation in lowland areas, which accounts for about 25% of GDP and 73% of total employment. Economic growth has reduced official poverty rates from 46% in 1992 to 26% in 2010. The economy also has benefited from high-profile foreign direct investment in hydropower dams along the Mekong river, copper and gold mining, logging, and construction though some projects in these industries have drawn criticism for their environmental impacts.  The strength of the natural resources and hydropower sectors have masked ongoing problems with the business environment that would have otherwise constrained growth.  These problems include onerous registration requirements, a gap between legislation and implementation, and unclear or conflicting business regulations.  Laos gained Normal Trade Relations status with the US in 2004 and applied for Generalized System of Preferences trade benefits in 2013 after being admitted to the World Trade Organization earlier in the year. Laos is in the process of implementing a value-added tax system. Simplified investment procedures and expanded bank credits for small farmers and small entrepreneurs will improve Laos' economic prospects. The government appears committed to raising the country's profile among foreign investors and has developed special economic zones replete with generous tax incentives, but a small labor pool of both skilled and unskilled workers remains an impediment to investment. Laos broadly appears to be on target to graduate from the UN Development Program's list of least-developed countries by 2020, and the country is preparing for implementation of the ASEAN Economic Community at the end of 2015 and for the rotating ASEAN chairmanship in 2016.
*** GDP (purchasing power parity)
$34.4 billion (2014 est.)
$32.03 billion (2013 est.)
$29.66 billion (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 116
*** GDP (official exchange rate)
$11.68 billion (2014 est.)
*** GDP - real growth rate
7.4% (2014 est.)
8% (2013 est.)
7.9% (2012 est.)
- country comparison to the world :: 13
*** GDP - per capita (PPP)
$5,000 (2014 est.)
$4,600 (2013 est.)
$4,300 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 167
*** Gross national saving
32.3% of GDP (2014 est.)
29.5% of GDP (2013 est.)
27.4% of GDP (2012 est.)
- country comparison to the world :: 24
*** GDP - composition, by end use
- household consumption :: 69.6%
- government consumption :: 13.9%
- investment in fixed capital :: 39.1%
- investment in inventories :: 0%
- exports of goods and services :: 37.3%
- imports of goods and services :: -59.9%
 (2014 est.)
*** GDP - composition, by sector of origin
- agriculture :: 23.7%
- industry :: 32.2%
- services :: 44.1% (2014 est.)
*** Agriculture - products
sweet potatoes, vegetables, corn, coffee, sugarcane, tobacco, cotton, tea, peanuts, rice; cassava (manioc, tapioca), water buffalo, pigs, cattle, poultry
*** Industries
mining (copper, tin, gold, gypsum); timber, electric power, agricultural processing, rubber, construction, garments, cement, tourism
*** Industrial production growth rate
9% (2014 est.)
- country comparison to the world :: 15
*** Labor force
3.445 million (2014 est.)
- country comparison to the world :: 100
*** Labor force - by occupation
- agriculture :: 73.1%
- industry :: 6.1%
- services :: 20.6% (2012 est.)
*** Unemployment rate
1.3% (2012 est.)
1.9% (2010 est.)
- country comparison to the world :: 6
*** Population below poverty line
22% (2013 est.)
*** Household income or consumption by percentage share
- lowest 10% :: 3.3%
- highest 10% :: 30.3% (2008)
*** Distribution of family income - Gini index
36.7 (2008)
34.6 (2002)
- country comparison to the world :: 82
*** Budget
- revenues :: $2.742 billion
- expenditures :: $3.297 billion (2014 est.)
*** Taxes and other revenues
23.4% of GDP (2014 est.)
- country comparison to the world :: 132
*** Budget surplus (+) or deficit (-)
-4.7% of GDP (2014 est.)
- country comparison to the world :: 158
*** Public debt
46.2% of GDP (2014 est.)
46.2% of GDP (2013 est.)
- country comparison to the world :: 78
*** Fiscal year
1 October - 30 September
*** Inflation rate (consumer prices)
4.1% (2014 est.)
6.4% (2013 est.)
- country comparison to the world :: 158
*** Central bank discount rate
4.3% (31 December 2010)
4% (31 December 2009)
- country comparison to the world :: 84
*** Commercial bank prime lending rate
24.5% (31 December 2014 est.)
23.2% (31 December 2013 est.)
- country comparison to the world :: 8
*** Stock of narrow money
$1.629 billion (31 December 2014 est.)
$1.414 billion (31 December 2013 est.)
- country comparison to the world :: 137
*** Stock of broad money
$5.411 billion (31 December 2014 est.)
$5.141 billion (31 December 2013 est.)
- country comparison to the world :: 128
*** Stock of domestic credit
$5.157 billion (31 December 2014 est.)
$4.665 billion (31 December 2013 est.)
- country comparison to the world :: 122
*** Market value of publicly traded shares
$1.012 billion (2012 est.)
$576.8 million (2011)
- country comparison to the world :: 107
*** Current account balance
-$2.907 billion (2014 est.)
-$593 million (2013 est.)
- country comparison to the world :: 111
*** Exports
$2.791 billion (2014 est.)
$2.448 billion (2013 est.)
- country comparison to the world :: 131
*** Exports - commodities
wood products, coffee, electricity, tin, copper, gold, cassava
*** Exports - partners
China 34.2%, Thailand 27.4%, Vietnam 15.7% (2014)
*** Imports
$4.074 billion (2014 est.)
$3.452 billion (2013 est.)
- country comparison to the world :: 141
*** Imports - commodities
machinery and equipment, vehicles, fuel, consumer goods
*** Imports - partners
Thailand 55.2%, China 25.6%, Vietnam 6.6% (2014)
*** Reserves of foreign exchange and gold
$845.8 million (31 December 2014 est.)
$664 million (31 December 2013 est.)
- country comparison to the world :: 140
*** Debt - external
$7.52 billion (31 December 2014 est.)
$6.861 billion (31 December 2013 est.)
- country comparison to the world :: 113
*** Stock of direct foreign investment - at home
$15.14 billion (31 December 2012 est.)
$12.44 billion (31 December 2011 est.)
- country comparison to the world :: 84
*** Exchange rates
kips (LAK) per US dollar -
8,052 (2014 est.)
7,852.7 (2013 est.)
8,007.3 (2012 est.)
8,035.1 (2011 est.)
8,258.8 (2010 est.)
** Energy
*** Electricity - production
12.24 billion kWh (2011 est.)
- country comparison to the world :: 91
*** Electricity - consumption
2.4 billion kWh (2012 est.)
- country comparison to the world :: 136
*** Electricity - exports
2.537 billion kWh (2013 est.)
- country comparison to the world :: 40
*** Electricity - imports
1 billion kWh (2011 est.)
- country comparison to the world :: 65
*** Electricity - installed generating capacity
3.217 million kW (2013 est.)
- country comparison to the world :: 88
*** Electricity - from fossil fuels
1.9% of total installed capacity (2011 est.)
- country comparison to the world :: 204
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 123
*** Electricity - from hydroelectric plants
98.1% of total installed capacity (2011 est.)
- country comparison to the world :: 7
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 193
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 189
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 141
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 207
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 153
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 161
*** Refined petroleum products - consumption
3,520 bbl/day (2013 est.)
- country comparison to the world :: 178
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 191
*** Refined petroleum products - imports
3,160 bbl/day (2010 est.)
- country comparison to the world :: 170
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 152
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 162
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 129
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 88
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 156
*** Carbon dioxide emissions from consumption of energy
1.623 million Mt (2012 est.)
- country comparison to the world :: 158
** Communications
*** Telephones - fixed lines
- total subscriptions :: 920,000
- subscriptions per 100 inhabitants :: 14 (2014 est.)
- country comparison to the world :: 81
*** Telephones - mobile cellular
- total :: 4.6 million
- subscriptions per 100 inhabitants :: 68 (2014 est.)
- country comparison to the world :: 122
*** Telephone system
- general assessment :: service to general public is improving; the government relies on a radiotelephone network to communicate with remote areas
- domestic :: 4 service providers with mobile cellular usage growing very rapidly
- international :: country code - 856; satellite earth station - 1 Intersputnik (Indian Ocean region) and a second to be developed by China (2012)
*** Broadcast media
6 TV stations operating out of Vientiane - 3 government-operated and the others commercial; 17 provincial stations operating with nearly all programming relayed via satellite from the government-operated stations in Vientiane; Chinese and Vietnamese programming relayed via satellite from Lao National TV; broadcasts available from stations in Thailand and Vietnam in border areas; multi-channel satellite and cable TV systems provide access to a wide range of foreign stations; state-controlled radio with state-operated Lao National Radio (LNR) broadcasting on 5 frequencies - 1 AM, 1 SW, and 3 FM; LNR's AM and FM programs are relayed via satellite constituting a large part of the programming schedules of the provincial radio stations; Thai radio broadcasts available in border areas and transmissions of multiple international broadcasters are also accessible (2012)
*** Radio broadcast stations
AM 3, FM 34, shortwave 3 (2010)
*** Television broadcast stations
28 (2010)
*** Internet country code
.la
*** Internet users
- total :: 300,000
- percent of population :: 5.8% (2009)
- country comparison to the world :: 142
** Transportation
*** Airports
41 (2013)
- country comparison to the world :: 103
*** Airports - with paved runways
- total :: 8
- 2,438 to 3,047 m :: 3
- 1,524 to 2,437 m :: 4
- 914 to 1,523 m :: 1 (2013)
*** Airports - with unpaved runways
- total :: 33
- 1,524 to 2,437 m :: 2
- 914 to 1,523 m :: 9
- under 914 m :: 
22 (2013)
*** Pipelines
refined products 540 km (2013)
*** Roadways
- total :: 39,586 km
- paved :: 5,415 km
- unpaved :: 34,171 km (2009)
- country comparison to the world :: 89
*** Waterways
4,600 km (primarily on the Mekong River and its tributaries; 2,900 additional km are intermittently navigable by craft drawing less than 0.5 m) (2012)
- country comparison to the world :: 23
** Military
*** Military branches
Lao People's Armed Forces (LPAF): Lao People's Army (LPA; includes Riverine Force), Air Force (2011)
*** Military service age and obligation
18 years of age for compulsory or voluntary military service; conscript service obligation - minimum 18-months (2012)
*** Manpower available for military service
- males age 16-49 :: 1,574,362
- females age 16-49 :: 1,607,856 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 1,111,629
- females age 16-49 :: 1,190,035 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 71,400
- female :: 73,038 (2010 est.)
*** Military expenditures
NA% (2012)
0.23% of GDP (2011)
NA% (2010)
*** Military - note
serving one of the world's least developed countries, the Lao People's Armed Forces (LPAF) is small, poorly funded, and ineffectively resourced; its mission focus is border and internal security, primarily in countering ethnic Hmong insurgent groups; together with the Lao People's Revolutionary Party and the government, the Lao People's Army (LPA) is the third pillar of state machinery, and as such is expected to suppress political and civil unrest and similar national emergencies; there is no perceived external threat to the state and the LPA maintains strong ties with the neighboring Vietnamese military (2012)
** Transnational Issues
*** Disputes - international
southeast Asian states have enhanced border surveillance to check the spread of avian flu; talks continue on completion of demarcation with Thailand but disputes remain over islands in the Mekong River; concern among Mekong River Commission members that China's construction of dams on the Mekong River and its tributaries will affect water levels; Cambodia and Vietnam are concerned about Laos' extensive upstream dam construction
*** Trafficking in persons
- current situation :: Laos is a source and, to a lesser extent, transit and destination country for men, women, and children subjected to forced labor and sex trafficking; Lao economic migrants may encounter conditions of forced labor or sexual exploitation in destination countries, most often Thailand; Lao women and girls are exploited in Thailand’s commercial sex trade, domestic service, factories, and agriculture; Lao men and boys are victims of forced labor in the Thai fishing, construction, and agriculture industries; some Vietnamese and Chinese women and girls are subjected to sex trafficking in Laos while others are trafficked through Laos to neighboring countries, particularly Thailand; some Lao adults and children are subject to sex and labor exploitation domestically
- tier rating :: Tier 2 Watch List – Laos does not fully comply with the minimum standards for the elimination of trafficking; however, it is making significant efforts to do so; authorities sustained moderate efforts to prosecute and convict trafficking offenders; the government failed to identify victims exploited within the country or among those deported from abroad; the government relies almost entirely on local and international organizations to implement its anti-trafficking programs, including providing assistance to trafficking victims (2014)
*** Illicit drugs
estimated opium poppy cultivation in 2008 was 1,900 hectares, about a 73% increase from 2007; estimated potential opium production in 2008 more than tripled to 17 metric tons; unsubstantiated reports of domestic methamphetamine production; growing domestic methamphetamine problem (2009)