** Introduction
*** Background
Following World War I, France acquired a mandate over the northern portion of the former Ottoman Empire province of Syria. The French demarcated the region of Lebanon in 1920 and granted this area independence in 1943. Since independence the country has been marked by periods of political turmoil interspersed with prosperity built on its position as a regional center for finance and trade. The country's 1975-90 civil war that resulted in an estimated 120,000 fatalities, was followed by years of social and political instability. Sectarianism is a key element of Lebanese political life. Neighboring Syria has historically influenced Lebanon's foreign policy and internal policies, and its military occupied Lebanon from 1976 until 2005. The Lebanon-based Hizballah militia and Israel continued attacks and counterattacks against each other after Syria's withdrawal, and fought a brief war in 2006. Lebanon's borders with Syria and Israel remain unresolved.
** Geography
*** Location
Middle East, bordering the Mediterranean Sea, between Israel and Syria
*** Geographic coordinates
33 50 N, 35 50 E
*** Map references
Middle East
*** Area
- total :: 10,400 sq km
- land :: 10,230 sq km
- water :: 170 sq km
- country comparison to the world :: 170
*** Area - comparative
about one-third the size of Maryland
- Area comparison map ::  
*** Land boundaries
- total :: 484 km
- border countries (2) :: Israel 81 km, Syria 403 km
*** Coastline
225 km
*** Maritime claims
- territorial sea :: 12 nm
*** Climate
Mediterranean; mild to cool, wet winters with hot, dry summers; the Lebanon Mountains experience heavy winter snows
*** Terrain
narrow coastal plain; El Beqaa (Bekaa Valley) separates Lebanon and Anti-Lebanon Mountains
*** Elevation extremes
- lowest point :: Mediterranean Sea 0 m
- highest point :: Qornet es Saouda 3,088 m
*** Natural resources
limestone, iron ore, salt, water-surplus state in a water-deficit region, arable land
*** Land use
- agricultural land :: 63.3%
arable land 11.9%; permanent crops 12.3%; permanent pasture 39.1%
- forest :: 13.4%
- other :: 23.3% (2011 est.)
*** Irrigated land
1,040 sq km (2003)
*** Total renewable water resources
4.5 cu km (2011)
*** Freshwater withdrawal (domestic/industrial/agricultural)
- total :: 1.31  cu km/yr (29%/11%/60%)
- per capita :: 316.8  cu m/yr (2005)
*** Natural hazards
dust storms, sandstorms
*** Environment - current issues
deforestation; soil erosion; desertification; air pollution in Beirut from vehicular traffic and the burning of industrial wastes; pollution of coastal waters from raw sewage and oil spills
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Hazardous Wastes, Law of the Sea, Ozone Layer Protection, Ship Pollution, Wetlands
- signed, but not ratified :: Environmental Modification, Marine Life Conservation
*** Geography - note
smallest country in continental Asia; Nahr el Litani is the only major river in Near East not crossing an international boundary; rugged terrain historically helped isolate, protect, and develop numerous factional groups based on religion, clan, and ethnicity
** People and Society
*** Nationality
- noun :: Lebanese (singular and plural)
- adjective :: Lebanese
*** Ethnic groups
Arab 95%, Armenian 4%, other 1%
- note :: many Christian Lebanese do not identify themselves as Arab but rather as descendents of the ancient Canaanites and prefer to be called Phoenicians
*** Languages
Arabic (official), French, English, Armenian
*** Religions
Muslim 54% (27% Sunni, 27% Shia), Christian 40.5% (includes 21% Maronite Catholic, 8% Greek Orthodox, 5% Greek Catholic, 6.5% other Christian), Druze 5.6%, very small numbers of Jews, Baha'is, Buddhists, Hindus, and Mormons
- note :: 18 religious sects recognized (2012 est.)
- religious affiliation ::  
*** Population
6,184,701 (July 2015 est.)
- country comparison to the world :: 109
*** Age structure
- 0-14 years :: 25.08% (male 793,837/female 757,120)
- 15-24 years :: 17.04% (male 539,232/female 514,394)
- 25-54 years :: 44.13% (male 1,378,852/female 1,350,506)
- 55-64 years :: 7.18% (male 205,933/female 237,849)
- 65 years and over :: 6.58% (male 179,983/female 226,995) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 47.3%
- youth dependency ratio :: 35.4%
- elderly dependency ratio :: 12%
- potential support ratio :: 8.3% (2015 est.)
*** Median age
- total :: 29.4 years
- male :: 28.8 years
- female :: 30 years (2015 est.)
*** Population growth rate
0.86% (2015 est.)
- country comparison to the world :: 128
*** Birth rate
14.59 births/1,000 population (2015 est.)
- country comparison to the world :: 133
*** Death rate
4.88 deaths/1,000 population (2015 est.)
- country comparison to the world :: 191
*** Net migration rate
-1.1 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 150
*** Urbanization
- urban population :: 87.8% of total population (2015)
- rate of urbanization :: 3.18% annual rate of change (2010-15 est.)
*** Major urban areas - population
BEIRUT (capital) 2.226 million (2015)
*** Sex ratio
- at birth :: 1.05 male(s)/female
- 0-14 years :: 1.05 male(s)/female
- 15-24 years :: 1.05 male(s)/female
- 25-54 years :: 1.02 male(s)/female
- 55-64 years :: 0.87 male(s)/female
- 65 years and over :: 0.79 male(s)/female
- total population :: 1 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 7.76 deaths/1,000 live births
- male :: 8.18 deaths/1,000 live births
- female :: 7.32 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 155
*** Life expectancy at birth
- total population :: 77.4 years
- male :: 76.18 years
- female :: 78.69 years (2015 est.)
- country comparison to the world :: 70
*** Total fertility rate
1.73 children born/woman (2015 est.)
- country comparison to the world :: 169
*** Health expenditures
7.2% of GDP (2013)
- country comparison to the world :: 73
*** Physicians density
3.2 physicians/1,000 population (2011)
*** Hospital bed density
3.5 beds/1,000 population (2012)
*** Drinking water source
- improved :: 
urban: 99% of population
rural: 99% of population
total: 99% of population
- unimproved :: 
urban: 1% of population
rural: 1% of population
total: 1% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 80.7% of population
rural: 80.7% of population
total: 80.7% of population
- unimproved :: 
urban: 19.3% of population
rural: 19.3% of population
total: 19.3% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
0.06% (2014 est.)
- country comparison to the world :: 116
*** HIV/AIDS - people living with HIV/AIDS
1,800 (2014 est.)
- country comparison to the world :: 117
*** HIV/AIDS - deaths
less than 100 (2014 est.)
- country comparison to the world :: 117
*** Obesity - adult prevalence rate
30.8% (2014)
- country comparison to the world :: 40
*** Education expenditures
2.6% of GDP (2012)
- country comparison to the world :: 162
*** Literacy
- definition :: age 15 and over can read and write
- total population :: 93.9%
- male :: 96%
- female :: 91.8% (2015 est.)
*** School life expectancy (primary to tertiary education)
- total :: 14 years
- male :: 14 years
- female :: 14 years (2013)
*** Child labor - children ages 5-14
- total number :: 54,387
- percentage :: 7% (2000 est.)
*** Unemployment, youth ages 15-24
- total :: 16.8%
- male :: 14.6%
- female :: 22.3% (2009 est.)
- country comparison to the world :: 71
** Government
*** Country name
- conventional long form :: Lebanese Republic
- conventional short form :: Lebanon
- local long form :: Al Jumhuriyah al Lubnaniyah
- local short form :: Lubnan
- former :: Greater Lebanon
*** Government type
republic
*** Capital
- name :: Beirut
- geographic coordinates :: 33 52 N, 35 30 E
- time difference :: UTC+2 (7 hours ahead of Washington, DC, during Standard Time)
- daylight saving time :: +1hr, begins last Sunday in March; ends last Sunday in October
*** Administrative divisions
6 governorates (mohafazat, singular - mohafazah); Beqaa, Beyrouth (Beirut), Liban-Nord, Liban-Sud, Mont-Liban, Nabatiye
- note :: two new governorates - Aakkar and Baalbek-Hermel - have been legislated but not yet implemented
*** Independence
22 November 1943 (from League of Nations mandate under French administration)
*** National holiday
Independence Day, 22 November (1943)
*** Constitution
drafted 15 May 1926, adopted 23 May 1926; amended several times, last in 2004 (2015)
*** Legal system
mixed legal system of civil law based on the French civil code, Ottoman legal tradition, and religious laws covering personal status, marriage, divorce, and other family relations of the Jewish, Islamic, and Christian communities
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; non-party state to the ICCt
*** Citizenship
- birthright citizenship :: 
- dual citizenship recognized :: yes
- residency requirement for naturalization :: 
*** Suffrage
21 years of age; compulsory for all males; authorized for women at age 21 with elementary education; excludes military personnel
*** Executive branch
- chief of state :: President (vacant); note - President Michel SULAYMAN's term expired on 25 May 2014; the prime minister and his cabinet are temporarily assuming the duties of the president; as of mid-2015, the National Assembly had failed to elect a president
- head of government :: Prime Minister Tamam SALAM (since 6 April 2013); Deputy Prime Minister Samir MOQBIL (since 7 July 2011)
- cabinet :: Cabinet chosen by the prime minister in consultation with the president and National Assembly
- elections/appointments :: president indirectly elected by the National Assembly for a 6-year term (eligible for non-consecutive terms); first round of election held on 23 April 2014 (next to be held in 2020); prime minister and deputy prime minister appointed by the president in consultation with the National Assembly
- election results :: NA; note - the April 2014 parliamentary vote failed to meet the required two-thirds majority vote threshold; subsequent voting from April 2014 through October 2015 also failed to meet a quorum or was postponed
*** Legislative branch
- description :: unicameral National Assembly or Majlis al-Nuwab in Arabic or Assemblee Nationale in French (128 seats; members directly elected in multi-seat constituencies by majority vote; members serve 4-year terms); note - seats are apportioned among the Christian and Muslim denominations
- elections :: last held on 7 June 2009 (next delayed until 16 November 2014)
- election results :: percent of vote by group - March 8 Coalition 54.7%, March 14 Coalition 45.3%; seats by group - March 14 Coalition 71; March 8 Coalition 57; seats by party following 16 July 2012 byelection held to fill one seat - March 14 Coalition 72, March 8 Coalition 56
*** Judicial branch
- highest court(s) :: Court of Cassation or Supreme Court (organized into 4 divisions, each with a presiding judge and 2 associate judges); Constitutional Council (consists of 10 members)
- judge selection and term of office :: Court of Cassation judges appointed by Supreme Judicial Council, headed by the chief justice, and includes other judicial officials; judge tenure NA; Constitutional Council members appointed - 5 by the Council of Ministers and 5 by parliament; members serve 5-year terms
- subordinate courts :: Courts of Appeal; Courts of First Instance; specialized tribunals, religious courts; military courts
*** Political parties and leaders
- 14 March Coalition :: 
Democratic Left [Ilyas ATALLAH]
Democratic Renewal Movement [Nassib LAHUD]
Future Movement Bloc [Sa'ad al-HARIRI]
Kataeb Party [Amine GEMAYEL]
Lebanese Forces [Samir JA'JA]
Tripoli Independent Bloc

- 8 March Coalition :: 
Development and Resistance Bloc [Nabih BERRI, leader of Amal Movement]
Free Patriotic Movement [Michel AWN]
Loyalty to the Resistance Bloc [Mohammad RA'AD] (includes Hizballah [Hassan NASRALLAH])
Nasserite Popular Movement [Usama SAAD]
Popular Bloc [Elias SKAFF]
Syrian Ba'th Party [Sayez SHUKR]
Syrian Social Nationalist Party [Ali QANSO]
Tashnaq [Hovig MEKHITIRIAN]

- Independent :: 
Democratic Gathering Bloc [Walid JUNBLATT, leader of Progressive Socialist Party]
Metn Bloc [Michel MURR]
*** Political pressure groups and leaders
Maronite Church [Patriarch Bishara al-Ra'i]
- note :: most sects retain militias and a number of militant groups operate in Palestinian refugee camps
*** International organization participation
ABEDA, AFESD, AMF, CAEU, FAO, G-24, G-77, IAEA, IBRD, ICAO, ICC (national committees), ICRM, IDA, IDB, IFAD, IFC, IFRCS, ILO, IMF, IMO, IMSO, Interpol, IOC, IPU, ISO, ITSO, ITU, LAS, MIGA, NAM, OAS (observer), OIC, OIF, OPCW, PCA, UN, UNCTAD, UNESCO, UNHCR, UNIDO, UNRWA, UNWTO, UPU, WCO, WFTU (NGOs), WHO, WIPO, WMO, WTO (observer)
*** Diplomatic representation in the US
- chief of mission :: Ambassador Antoine CHEDID (since 4 June 2008)
- chancery :: 2560 28th Street NW, Washington, DC 20008
- telephone :: [1] (202) 939-6300
- FAX :: [1] (202) 939-6324
- consulate(s) general :: Detroit, New York, Los Angeles
*** Diplomatic representation from the US
- chief of mission :: Ambassador David HALE (since 6 September 2013)
- embassy :: Awkar, Lebanon (Awkar facing the Municipality)
- mailing address :: P. O. Box 70-840, Antelias, Lebanon; from US: US Embassy Beirut, 6070 Beirut Place, Washington, DC 20521-6070
- telephone :: [961] (4) 542600, 543600
- FAX :: [961] (4) 544136
*** Flag description
three horizontal bands consisting of red (top), white (middle, double width), and red (bottom) with a green cedar tree centered in the white band; the red bands symbolize blood shed for liberation, the white band denotes peace, the snow of the mountains, and purity; the green cedar tree is the symbol of Lebanon and represents eternity, steadiness, happiness, and prosperity
*** National symbol(s)
cedar tree; national colors: red, white, green
*** National anthem
- name :: "Kulluna lil-watan" (All Of Us, For Our Country!)
- lyrics/music :: Rachid NAKHLE/Wadih SABRA
- note :: adopted 1927; chosen following a nationwide competition

** Economy
*** Economy - overview
Lebanon has a free-market economy and a strong laissez-faire commercial tradition. The government does not restrict foreign investment; however, the investment climate suffers from red tape, corruption, arbitrary licensing decisions, complex customs procedures, high taxes, tariffs, and fees, archaic legislation, and weak intellectual property rights. The Lebanese economy is service-oriented; main growth sectors include banking and tourism. The 1975-90 civil war seriously damaged Lebanon's economic infrastructure, cut national output by half, and derailed Lebanon's position as a Middle Eastern entrepot and banking hub. Following the civil war, Lebanon rebuilt much of its war-torn physical and financial infrastructure by borrowing heavily, mostly from domestic banks, which saddled the government with a huge debt burden. Pledges of economic and financial reforms made at separate international donor conferences during the 2000s have mostly gone unfulfilled, including those made during the Paris III Donor Conference in 2007, following the July 2006 war. Spillover from the Syrian conflict, including the influx of more than 1 million Syrian refugees, has increased internal tension and slowed economic growth to the 1-2% range in 2011-13, after four years of averaging 8% growth. Syrian refugees have increased the labor supply, but pushed more Lebanese into unemployment. Chronic fiscal deficits have made Lebanon’s debt-to-GDP ratio the third highest in the world; most of the debt is held internally by Lebanese banks. Weak economic growth limits tax revenues, while the largest government expenditures remain debt servicing and transfers to the electricity sector. These limitations constrain other government spending and limit the government’s ability to invest in necessary infrastructure improvements, such as water, electricity, and transportation.
*** GDP (purchasing power parity)
$81.12 billion (2014 est.)
$79.53 billion (2013 est.)
$77.59 billion (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 88
*** GDP (official exchange rate)
$49.92 billion (2014 est.)
*** GDP - real growth rate
2.3% (2014 est.)
2.5% (2013 est.)
2.8% (2012 est.)
- country comparison to the world :: 138
*** GDP - per capita (PPP)
$18,000 (2014 est.)
$17,600 (2013 est.)
$17,200 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 90
*** Gross national saving
-2.1% of GDP (2014 est.)
-2.6% of GDP (2013 est.)
-0.2% of GDP (2012 est.)
- country comparison to the world :: 136
*** GDP - composition, by end use
- household consumption :: 82.2%
- government consumption :: 14.8%
- investment in fixed capital :: 30.4%
- investment in inventories :: 1%
- exports of goods and services :: 15.5%
- imports of goods and services :: -43.9%
 (2014 est.)
*** GDP - composition, by sector of origin
- agriculture :: 6.3%
- industry :: 21.1%
- services :: 72.6% (2014 est.)
*** Agriculture - products
citrus, grapes, tomatoes, apples, vegetables, potatoes, olives, tobacco; sheep, goats
*** Industries
banking, tourism, food processing, wine, jewelry, cement, textiles, mineral and chemical products, wood and furniture products, oil refining, metal fabricating
*** Industrial production growth rate
4% (2014 est.)
- country comparison to the world :: 74
*** Labor force
1.481 million
- note :: does not include as many as 1 million foreign workers (2007 est.)
- country comparison to the world :: 132
*** Labor force - by occupation
- agriculture :: NA%
- industry :: NA%
- services :: NA%
*** Unemployment rate
NA%
*** Population below poverty line
28.6% (2004 est.)
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $10.24 billion
- expenditures :: $14.89 billion (2014 est.)
*** Taxes and other revenues
21.6% of GDP (2014 est.)
- country comparison to the world :: 149
*** Budget surplus (+) or deficit (-)
-9.8% of GDP (2014 est.)
- country comparison to the world :: 201
*** Public debt
142.4% of GDP (2014 est.)
139.9% of GDP (2013 est.)
- note :: data cover central government debt, and exclude debt instruments issued (or owned) by government entities other than the treasury; the data include treasury debt held by foreign entities; the data include debt issued by subnational entities, as well as intra-governmental debt; intra-governmental debt consists of treasury borrowings from surpluses in the social funds, such as for retirement, medical care, and unemployment
- country comparison to the world :: 4
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
1.9% (2014 est.)
5.6% (2013 est.)
- country comparison to the world :: 96
*** Central bank discount rate
3.5% (31 December 2010)
10% (31 December 2009)
- country comparison to the world :: 103
*** Commercial bank prime lending rate
7.2% (31 December 2014 est.)
7.35% (31 December 2013 est.)
- country comparison to the world :: 121
*** Stock of narrow money
$5.12 billion (11 December 2014 est.)
$5.007 billion (11 December 2013 est.)
- country comparison to the world :: 99
*** Stock of broad money
$48.04 billion (11 December 2014 est.)
$45.25 billion (11 December 2013 est.)
- country comparison to the world :: 68
*** Stock of domestic credit
$87.04 billion (30 December 2014 est.)
$83.21 billion (31 December 2013 est.)
- country comparison to the world :: 57
*** Market value of publicly traded shares
$11.22 billion (30 December 2014 est.)
$10.55 billion (30 December 2013)
$10.42 billion (28 December 2012 est.)
- country comparison to the world :: 72
*** Current account balance
-$12.45 billion (2014 est.)
-$5.05 billion (2013 est.)
- country comparison to the world :: 163
*** Exports
$4.092 billion (2014 est.)
$4.93 billion (2013 est.)
- country comparison to the world :: 121
*** Exports - commodities
jewelry, base metals, chemicals, consumer goods, fruit and vegetables, tobacco, construction minerals, electric power machinery and switchgear, textile fibers, paper
*** Exports - partners
Saudi Arabia 10.8%, UAE 9.7%, Syria 8.7%, Iraq 7.6%, South Africa 7%, Switzerland 4% (2014)
*** Imports
$20.08 billion (2014 est.)
$20.28 billion (2013 est.)
- country comparison to the world :: 78
*** Imports - commodities
petroleum products, cars, medicinal products, clothing, meat and live animals, consumer goods, paper, textile fabrics, tobacco, electrical machinery and equipment, chemicals
*** Imports - partners
China 11.8%, Italy 7.7%, US 6.8%, France 6.2%, Germany 5.4%, Russia 4.5%, Greece 4.1% (2014)
*** Reserves of foreign exchange and gold
$49.43 billion (30 December 2014 est.)
$47.85 billion (31 December 2013 est.)
- country comparison to the world :: 40
*** Debt - external
$31.61 billion (30 December 2014 est.)
$31.56 billion (30 December 2013 est.)
- country comparison to the world :: 72
*** Stock of direct foreign investment - at home
$NA
*** Stock of direct foreign investment - abroad
$NA
*** Exchange rates
Lebanese pounds (LBP) per US dollar -
1,507.5 (2014 est.)
1,507.5 (2013 est.)
1,507.5 (2012 est.)
1,507.5 (2011 est.)
1,507.5 (2010 est.)
** Energy
*** Electricity - production
15.42 billion kWh (2011 est.)
- country comparison to the world :: 81
*** Electricity - consumption
14.4 billion kWh (2011 est.)
- country comparison to the world :: 80
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 161
*** Electricity - imports
840 million kWh (2011 est.)
- country comparison to the world :: 69
*** Electricity - installed generating capacity
2.313 million kW (2011 est.)
- country comparison to the world :: 101
*** Electricity - from fossil fuels
88.1% of total installed capacity (2011 est.)
- country comparison to the world :: 81
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 124
*** Electricity - from hydroelectric plants
11.9% of total installed capacity (2011 est.)
- country comparison to the world :: 112
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 194
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 190
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 142
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 208
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 154
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 162
*** Refined petroleum products - consumption
104,400 bbl/day (2013 est.)
- country comparison to the world :: 76
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 192
*** Refined petroleum products - imports
120,400 bbl/day (2010 est.)
- country comparison to the world :: 45
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 153
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 163
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 130
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 89
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 157
*** Carbon dioxide emissions from consumption of energy
16.44 million Mt (2012 est.)
- country comparison to the world :: 89
** Communications
*** Telephones - fixed lines
- total subscriptions :: 970,000
- subscriptions per 100 inhabitants :: 16 (2014 est.)
- country comparison to the world :: 77
*** Telephones - mobile cellular
- total :: 4.4 million
- subscriptions per 100 inhabitants :: 75 (2014 est.)
- country comparison to the world :: 125
*** Telephone system
- general assessment :: repair of the telecommunications system, severely damaged during the civil war, now complete
- domestic :: two mobile-cellular networks provide good service; combined fixed-line and mobile-cellular subscribership roughly 100 per 100 persons
- international :: country code - 961; submarine cable links to Cyprus, Egypt, and Syria; satellite earth stations - 2 Intelsat (1 Indian Ocean and 1 Atlantic Ocean); coaxial cable to Syria (2011)
*** Broadcast media
7 TV stations, 1 of which is state owned; more than 30 radio stations, 1 of which is state owned; satellite and cable TV services available; transmissions of at least 2 international broadcasters are accessible through partner stations (2007)
*** Radio broadcast stations
AM 20, FM 30 (plus about a dozen unlicensed stations operating), shortwave 4 (2009)
*** Television broadcast stations
12 (2009)
*** Internet country code
.lb
*** Internet users
- total :: 4 million
- percent of population :: 67.2% (2014 est.)
- country comparison to the world :: 76
** Transportation
*** Airports
8 (2013)
- country comparison to the world :: 161
*** Airports - with paved runways
- total :: 5
- over 3,047 m :: 1
- 2,438 to 3,047 m :: 2
- 1,524 to 2,437 m :: 1
- under 914 m :: 1 (2013)
*** Airports - with unpaved runways
- total :: 3
- 914 to 1,523 m :: 2
- under 914 m :: 
1 (2013)
*** Heliports
1 (2013)
*** Pipelines
gas 88 km (2013)
*** Railways
- total :: 401 km
- standard gauge :: 319 km 1.435-m gauge
- narrow gauge :: 82 km 1.050-m gauge
- note :: rail system unusable due to damage sustained from fighting in the 1980s and in 2006 (2008)
- country comparison to the world :: 117
*** Roadways
- total :: 6,970 km (includes 170 km of expressways) (2005)
- country comparison to the world :: 146
*** Merchant marine
- total :: 29
- by type :: bulk carrier 4, cargo 7, carrier 17, vehicle carrier 1
- foreign-owned :: 2 (Syria 2)
- registered in other countries :: 34 (Barbados 2, Cambodia 5, Comoros 2, Egypt 1, Georgia 1, Honduras 2, Liberia 1, Malta 6, Moldova 1, Panama 2, Saint Vincent and the Grenadines 2, Sierra Leone 2, Togo 6, unknown 1) (2010)
- country comparison to the world :: 85
*** Ports and terminals
- major seaport(s) :: Beirut, Tripoli
- container port(s) (TEUs) :: Beirut (1,034,249)
** Military
*** Military branches
Lebanese Armed Forces (LAF): Lebanese Army ((Al Jaysh al Lubnani) includes Lebanese Navy (Al Quwwat al Bahiriyya al Lubnaniya), Lebanese Air Force (Al Quwwat al Jawwiya al Lubnaniya)) (2013)
*** Military service age and obligation
17-30 years of age for voluntary military service; 18-24 years of age for officer candidates; no conscription (2013)
*** Manpower available for military service
- males age 16-49 :: 1,081,016
- females age 16-49 :: 1,115,349 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 920,825
- females age 16-49 :: 941,806 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 36,856
- female :: 35,121 (2010 est.)
*** Military expenditures
4.04% of GDP (2012)
4.06% of GDP (2011)
4.04% of GDP (2010)
- country comparison to the world :: 11
** Transnational Issues
*** Disputes - international
lacking a treaty or other documentation describing the boundary, portions of the Lebanon-Syria boundary are unclear with several sections in dispute; since 2000, Lebanon has claimed Shab'a Farms area in the Israeli-occupied Golan Heights; the roughly 2,000-strong UN Interim Force in Lebanon has been in place since 1978
*** Refugees and internally displaced persons
- refugees (country of origin) :: 449,957 (Palestinian refugees (UNRWA)); 5,986 (Iraq) (2014); 1,078,338 (Syria) (2015)
- IDPs :: 19,719 (2007 Lebanese security forces' destruction of Palestinian refugee camp) (2014)
- stateless persons :: undetermined (2014); note - tens of thousands of persons are stateless in Lebanon, including many Palestinian refugees and their descendants, Syrian Kurds denaturalilzed in Syria in 1962, children born to Lebanese women married to foreign or stateless men; most babies born to Syrian refugees, and Lebanese children whose births are unregistered
*** Trafficking in persons
- current situation :: Lebanon is a source, transit, and destination country for women and children subjected to forced labor and sex trafficking; Eastern European women and children are transported through Lebanon for sexual exploitation in other Middle Eastern countries; women from Sri Lanka, the Philippines, Ethiopia, Kenya, Bangladesh, Nepal, Madagascar, Democratic Republic of the Congo, Togo, Cameroon, and Nigeria are recruited by agencies to work in domestic service but are often subject to conditions indicative of forced labor, including the withholding of passports, nonpayment of wages, restricted movement, threats, and abuse; Lebanon’s artiste visa program enabling women to work as dancers for three months in the adult entertainment industry sustains a significant sex trade; anecdotal information indicates some Lebanese children are victims of forced labor, such as street begging and commercial sexual exploitation; Syrian refugee women and children in Lebanon are at increased risked of sex trafficking
- tier rating :: Tier 2 Watch List – Lebanon does not fully comply with the minimum standards for the elimination of trafficking; however, it is making significant efforts to do so; the government has a written plan that, if implemented, would constitute a significant effort toward meeting the minimum standards for eliminating human trafficking; in 2013, authorities conducted an increased number of investigations of human trafficking and prosecuted and convicted some trafficking offenders; the government identified and referred some trafficking victims to NGO-run safe houses but did not directly fund protective services; Lebanon’s sponsorship system and the withholding of passports continued to put domestic workers at risk of exploitation (2014)
*** Illicit drugs
cannabis cultivation dramatically reduced to 2,500 hectares in 2002 despite continued significant cannabis consumption; opium poppy cultivation minimal; small amounts of Latin American cocaine and Southwest Asian heroin transit country on way to European markets and for Middle Eastern consumption; money laundering of drug proceeds fuels concern that extremists are benefiting from drug trafficking