** Introduction
*** Background
Settlement of freed slaves from the US in what is today Liberia began in 1822; by 1847, the Americo-Liberians were able to establish a republic. William TUBMAN, president from 1944-71, did much to promote foreign investment and to bridge the economic, social, and political gaps between the descendants of the original settlers and the inhabitants of the interior. In 1980, a military coup led by Samuel DOE ushered in a decade of authoritarian rule. In December 1989, Charles TAYLOR launched a rebellion against DOE's regime that led to a prolonged civil war in which DOE was killed. A period of relative peace in 1997 allowed for an election that brought TAYLOR to power, but major fighting resumed in 2000. An August 2003 peace agreement ended the war and prompted the resignation of former president Charles TAYLOR, who was convicted by the UN-backed Special Court for Sierra Leone in The Hague for his involvement in Sierra Leone's civil war. After two years of rule by a transitional government, democratic elections in late 2005 brought President Ellen JOHNSON SIRLEAF to power. She subsequently won reelection in 2011 and remains challenged to rebuild Liberia's economy, particularly following the 2014-15 Ebola epidemic, and to reconcile a nation still recovering from 14 years of fighting. The UN Security Council in September 2012 passed Resolution 2066 which calls for a halving of UN troops in Liberia by 2015, reducing the troop level to fewer than 4,000, and challenging Liberia's security sector to fill the gaps.
** Geography
*** Location
Western Africa, bordering the North Atlantic Ocean, between Cote d'Ivoire and Sierra Leone
*** Geographic coordinates
6 30 N, 9 30 W
*** Map references
Africa
*** Area
- total :: 111,369 sq km
- land :: 96,320 sq km
- water :: 15,049 sq km
- country comparison to the world :: 104
*** Area - comparative
slightly larger than Tennessee
*** Land boundaries
- total :: 1,667 km
- border countries (3) :: Guinea 590 km, Cote d'Ivoire 778 km, Sierra Leone 299 km
*** Coastline
579 km
*** Maritime claims
- territorial sea :: 200 nm
*** Climate
tropical; hot, humid; dry winters with hot days and cool to cold nights; wet, cloudy summers with frequent heavy showers
*** Terrain
mostly flat to rolling coastal plains rising to rolling plateau and low mountains in northeast
*** Elevation extremes
- lowest point :: Atlantic Ocean 0 m
- highest point :: Mount Wuteve 1,380 m
*** Natural resources
iron ore, timber, diamonds, gold, hydropower
*** Land use
- agricultural land :: 28.1%
arable land 5.2%; permanent crops 2.1%; permanent pasture 20.8%
- forest :: 44.6%
- other :: 27.3% (2011 est.)
*** Irrigated land
21 sq km (2003)
*** Total renewable water resources
232 cu km (2011)
*** Freshwater withdrawal (domestic/industrial/agricultural)
- total :: 0.13  cu km/yr (55%/37%/8%)
- per capita :: 43.66  cu m/yr (2005)
*** Natural hazards
dust-laden harmattan winds blow from the Sahara (December to March)
*** Environment - current issues
tropical rain forest deforestation; soil erosion; loss of biodiversity; pollution of coastal waters from oil residue and raw sewage
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Endangered Species, Hazardous Wastes, Law of the Sea, Ozone Layer Protection, Ship Pollution, Tropical Timber 83, Tropical Timber 94, Wetlands
- signed, but not ratified :: Environmental Modification, Marine Life Conservation
*** Geography - note
facing the Atlantic Ocean, the coastline is characterized by lagoons, mangrove swamps, and river-deposited sandbars; the inland grassy plateau supports limited agriculture
** People and Society
*** Nationality
- noun :: Liberian(s)
- adjective :: Liberian
*** Ethnic groups
Kpelle 20.3%, Bassa 13.4%, Grebo 10%, Gio 8%, Mano 7.9%, Kru 6%, Lorma 5.1%, Kissi 4.8%, Gola 4.4%, other 20.1% (2008 Census)
*** Languages
English 20% (official), some 20 ethnic group languages few of which can be written or used in correspondence
*** Religions
Christian 85.6%, Muslim 12.2%, Traditional 0.6%, other 0.2%, none 1.4% (2008 Census)
*** Population
4,195,666 (July 2015 est.)
- country comparison to the world :: 128
*** Age structure
- 0-14 years :: 42.75% (male 904,495/female 889,198)
- 15-24 years :: 18.3% (male 376,224/female 391,568)
- 25-54 years :: 31.51% (male 658,291/female 663,954)
- 55-64 years :: 4.3% (male 87,606/female 92,831)
- 65 years and over :: 3.13% (male 64,697/female 66,802) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 82.9%
- youth dependency ratio :: 77.4%
- elderly dependency ratio :: 5.5%
- potential support ratio :: 18.2% (2015 est.)
*** Median age
- total :: 18.1 years
- male :: 17.9 years
- female :: 18.3 years (2015 est.)
*** Population growth rate
2.47% (2015 est.)
- country comparison to the world :: 24
*** Birth rate
34.41 births/1,000 population (2015 est.)
- country comparison to the world :: 26
*** Death rate
9.69 deaths/1,000 population (2015 est.)
- country comparison to the world :: 51
*** Net migration rate
0 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 91
*** Urbanization
- urban population :: 49.7% of total population (2015)
- rate of urbanization :: 3.36% annual rate of change (2010-15 est.)
*** Major urban areas - population
MONROVIA (capital) 1.264 million (2015)
*** Sex ratio
- at birth :: 1.03 male(s)/female
- 0-14 years :: 1.02 male(s)/female
- 15-24 years :: 0.96 male(s)/female
- 25-54 years :: 0.99 male(s)/female
- 55-64 years :: 0.94 male(s)/female
- 65 years and over :: 0.97 male(s)/female
- total population :: 0.99 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 67.5 deaths/1,000 live births
- male :: 71.71 deaths/1,000 live births
- female :: 63.16 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 15
*** Life expectancy at birth
- total population :: 58.6 years
- male :: 56.94 years
- female :: 60.32 years (2015 est.)
- country comparison to the world :: 201
*** Total fertility rate
4.7 children born/woman (2015 est.)
- country comparison to the world :: 21
*** Contraceptive prevalence rate
20.2% (2013)
*** Health expenditures
10% of GDP (2013)
- country comparison to the world :: 3
*** Physicians density
0.01 physicians/1,000 population (2008)
*** Hospital bed density
0.8 beds/1,000 population (2010)
*** Drinking water source
- improved :: 
urban: 88.6% of population
rural: 62.6% of population
total: 75.6% of population
- unimproved :: 
urban: 11.4% of population
rural: 37.4% of population
total: 24.4% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 28% of population
rural: 5.9% of population
total: 16.9% of population
- unimproved :: 
urban: 72% of population
rural: 94.1% of population
total: 83.1% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
1.17% (2014 est.)
- country comparison to the world :: 39
*** HIV/AIDS - people living with HIV/AIDS
33,100 (2014 est.)
- country comparison to the world :: 66
*** HIV/AIDS - deaths
2,000 (2014 est.)
- country comparison to the world :: 56
*** Major infectious diseases
- degree of risk :: very high
- food or waterborne diseases :: bacterial and protozoal diarrhea, hepatitis A, and typhoid fever
- vectorborne diseases :: malaria, dengue fever, and yellow fever
- water contact disease :: schistosomiasis
- aerosolized dust or soil contact disease :: Lassa fever
- animal contact disease :: rabies (2013)
*** Obesity - adult prevalence rate
5.8% (2014)
- country comparison to the world :: 161
*** Children under the age of 5 years underweight
15.3% (2013)
- country comparison to the world :: 28
*** Education expenditures
2.8% of GDP (2012)
- country comparison to the world :: 144
*** Literacy
- definition :: age 15 and over can read and write
- total population :: 47.6%
- male :: 62.4%
- female :: 32.8% (2015 est.)
*** Child labor - children ages 5-14
- total number :: 177,160
- percentage :: 21% (2007 est.)
*** Unemployment, youth ages 15-24
- total :: 5.1%
- male :: 3.4%
- female :: 6.6% (2010 est.)
- country comparison to the world :: 126
** Government
*** Country name
- conventional long form :: Republic of Liberia
- conventional short form :: Liberia
*** Government type
republic
*** Capital
- name :: Monrovia
- geographic coordinates :: 6 18 N, 10 48 W
- time difference :: UTC 0 (5 hours ahead of Washington, DC, during Standard Time)
*** Administrative divisions
15 counties; Bomi, Bong, Gbarpolu, Grand Bassa, Grand Cape Mount, Grand Gedeh, Grand Kru, Lofa, Margibi, Maryland, Montserrado, Nimba, River Cess, River Gee, Sinoe
*** Independence
26 July 1847
*** National holiday
Independence Day, 26 July (1847)
*** Constitution
previous 1847 (at independence); latest drafted 19 October 1983, revised version adopted by referendum 3 July 1984, effective 6 January 1986; amended 2011 (2011)
*** Legal system
mixed legal system of common law (based on  Anglo-American law) and customary law
*** International law organization participation
accepts compulsory ICJ jurisdiction with reservations; accepts ICCt jurisdiction
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: President Ellen JOHNSON SIRLEAF (since 16 January 2006); Vice President Joseph BOAKAI (since 16 January 2006); note - the president is both chief of state and head of government
- head of government :: President Ellen JOHNSON SIRLEAF (since 16 January 2006); Vice President Joseph BOAKAI (since 16 January 2006)
- cabinet :: Cabinet appointed by the president, confirmed by the Senate
- elections/appointments :: president directly elected by absolute majority popular vote in 2 rounds if needed for a 6-year term (eligible for a second term); election last held on 11 October and 8 November 2011 (next to be held in 2017)
- election results :: Ellen JOHNSON SIRLEAF reelected president; percent of vote in second round - Ellen JOHNSON SIRLEAF (UP) 90.7%, Winston TUBMAN (NDPL) 9.3%
*** Legislative branch
- description :: bicameral National Assembly consists of the Senate (30 seats; members directly elected in 15 two-seat constituencies by simple majority vote to serve 9-year staggered terms with half the membership renewed at 3- and 6-year intervals; eligible for a second term; and the House of Representatives (73 seats; members directly elected in single-seat constituencies by simple majority vote to serve 6-year terms; eligible for a second term)
- elections :: Senate - last held on 20 December 2014 (originally scheduled for 14 October 2014, but postponed due to Ebola-virus epidemic; next to be held in fall 2020); House of Representatives - last held on 11 October 2011 (next to be held in 2017)
- election results :: Senate - percent of vote by party - NA; seats by party - UP 10, NPP 6, CDC 3, APD 2, NUDP 2, LDP 1, LP 1, NDC 1, NDPL 1, independent 3; House of Representatives - percent of vote by party - NA; seats by party - UP 24, CDC 11, LP 7, NUDP 6, NDC 5, APD 3, NPP 3, MPC 2, LDP 1, LTP 1, NRP 1, independent 9
*** Judicial branch
- highest court(s) :: Supreme Court (consists of a chief justice and 4 associate justices); note - the Supreme Court has jurisdiction for all constitutional cases
- judge selection and term of office :: chief justice and associate justices appointed by the president of Liberia with consent of the Senate; judges can serve until age 70
- subordinate courts :: judicial circuit courts; special courts including criminal, civil, labor, traffic; magistrate and traditional or customary courts
*** Political parties and leaders
Alliance for Peace and Democracy or APD [Marcus S. G. DAHN]
Alternative National Congress or ANC [Orishil GOULD]
Congress for Democratic Change or CDC [George WEAH]
Liberia Destiny Party or LDP [Nathaniel BARNES]
Liberia Transformation Party or LTP [Julius SUKU]
Liberty Party or LP [J. Fonati KOFFA]
Movement for Progressive Change or MPC [Simeon FREEMAN]
National Democratic Coalition or NDC [Dew MAYSON]
National Democratic Party of Liberia or NDPL [D. Nyandeh SIEH]
National Patriotic Party or NPP [Theophilus C. GOULD]
National Reformist Party or NRP [Maximillian T. W. DIABE]
National Union for Democratic Progress or NUDP [Victor BARNEY]
Unity Party or UP [Varney SHERMAN]
*** Political pressure groups and leaders
- other :: demobilized former military officers
*** International organization participation
ACP, AfDB, AU, ECOWAS, EITI (compliant country), FAO, G-77, IAEA, IBRD, ICAO, ICC (NGOs), ICCt, ICRM, IDA, IFAD, IFC, IFRCS, ILO, IMF, IMO, IMSO, Interpol, IOC, IOM, ISO (correspondent), ITU, ITUC (NGOs), MIGA, MINUSMA, NAM, OPCW, UN, UNCTAD, UNESCO, UNIDO, UNWTO, UPU, WCO, WFTU (NGOs), WHO, WIPO, WMO, WTO (observer)
*** Diplomatic representation in the US
- chief of mission :: Ambassador Jeremiah Congbeh SULUNTEH (since 25 April 2012)
- chancery :: 5201 16th Street NW, Washington, DC 20011
- telephone :: [1] (202) 723-0437
- FAX :: [1] (202) 723-0436
- consulate(s) general :: New York
*** Diplomatic representation from the US
- chief of mission :: Ambassador Deborah R. MALAC (since 26 July 2012)
- embassy :: U.S. Embassy, P.O. Box 98, 502 Benson Street, Monrovia
- mailing address :: P.O. Box 98, Monrovia
- telephone :: [231] 77-677-7000
- FAX :: [231] 77-677-7370
*** Flag description
11 equal horizontal stripes of red (top and bottom) alternating with white; a white five-pointed star appears on a blue square in the upper hoist-side corner; the stripes symbolize the signatories of the Liberian Declaration of Independence; the blue square represents the African mainland, and the star represents the freedom granted to the ex-slaves; according to the constitution, the blue color signifies liberty, justice, and fidelity, the white color purity, cleanliness, and guilelessness, and the red color steadfastness, valor, and fervor
- note :: the design is based on the US flag
*** National symbol(s)
white star; national colors: red, white, blue
*** National anthem
- name :: "All Hail, Liberia Hail!"
- lyrics/music :: Daniel Bashiel WARNER/Olmstead LUCA
- note :: lyrics adopted 1847, music adopted 1860; the anthem's author later became the third president of Liberia

** Economy
*** Economy - overview
Liberia is a low income country that relies heavily on foreign assistance. It is richly endowed with water, mineral resources, forests, and a climate favorable to agriculture. Its principal exports are iron ore, rubber, gold and timber. The Government has attempted to revive raw timber extraction and is encouraging oil exploration. In the 1990s and early 2000s, civil war and government mismanagement destroyed much of Liberia's economy, especially infrastructure in and around the capital. With the conclusion of fighting and the installation of a democratically elected government in 2006, businesses that had fled the country began to return. The country achieved high growth during 2010-13 due to favorable world prices for its commodities. However, in 2014 as the Ebolavirus began to spread, the economy declined and many businesses departed, taking capital and expertise with them. The epidemic forced the government to divert scarce resources to combat the spread of the virus, reducing funds available for needed public investment. Revitalizing the economy in the future will depend on increasing investment and trade, higher global commodity prices, sustained foreign aid and remittances, development of infrastructure and institutions, and maintaining political stability and security. The cost of addressing the Ebola epidemic will weigh heavily on public finances at the same time decreased economic activity reduces government revenue, although higher donor support will partly offset this loss.
*** GDP (purchasing power parity)
$3.691 billion (2014 est.)
$3.672 billion (2013 est.)
$3.38 billion (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 178
*** GDP (official exchange rate)
$2.028 billion (2014 est.)
*** GDP - real growth rate
0.5% (2014 est.)
8.7% (2013 est.)
8.2% (2012 est.)
- country comparison to the world :: 127
*** GDP - per capita (PPP)
$900 (2014 est.)
$900 (2013 est.)
$800 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 225
*** Gross national saving
NA
-35% of GDP (2012 est.)
-35% of GDP (2012 est.)
*** GDP - composition, by end use
- household consumption :: 116.3%
- government consumption :: 18.4%
- investment in fixed capital :: 25.4%
- investment in inventories :: -1.6%
- exports of goods and services :: 32.4%
- imports of goods and services :: -89.5%
 (2011 est.)
*** GDP - composition, by sector of origin
- agriculture :: 38.8%
- industry :: 16.4%
- services :: 44.7% (2012 est.)
*** Agriculture - products
rubber, coffee, cocoa, rice, cassava (manioc, tapioca), palm oil, sugarcane, bananas; sheep, goats; timber
*** Industries
mining (iron ore), rubber processing, palm oil processing, timber, diamonds
*** Industrial production growth rate
50% (2011 est.)
- country comparison to the world :: 2
*** Labor force
1.554 million (2014 est.)
- country comparison to the world :: 129
*** Labor force - by occupation
- agriculture :: 70%
- industry :: 8%
- services :: 22% (2000 est.)
*** Unemployment rate
85% (2003 est.)
- country comparison to the world :: 202
*** Population below poverty line
63.8% (2007 est.)
*** Household income or consumption by percentage share
- lowest 10% :: 2.4%
- highest 10% :: 30.1% (2007)
*** Budget
- revenues :: $490.5 million
- expenditures :: $581.7 million (2014 est.)
*** Taxes and other revenues
23.7% of GDP (2014 est.)
- country comparison to the world :: 130
*** Budget surplus (+) or deficit (-)
-4.4% of GDP (2014 est.)
- country comparison to the world :: 150
*** Public debt
8.1% of GDP (2014 est.)
4.1% of GDP (2013 est.)
- country comparison to the world :: 155
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
9.9% (2014 est.)
7.6% (2013 est.)
- country comparison to the world :: 211
*** Commercial bank prime lending rate
14% (31 December 2014 est.)
13.48% (31 December 2013 est.)
- country comparison to the world :: 50
*** Stock of narrow money
$512 million (31 December 2014 est.)
$459.1 million (31 December 2013 est.)
- country comparison to the world :: 163
*** Stock of broad money
$738.7 million (31 December 2014 est.)
$656 million (31 December 2013 est.)
- country comparison to the world :: 172
*** Stock of domestic credit
$605 million (31 December 2014 est.)
$690.9 million (31 December 2013 est.)
- country comparison to the world :: 165
*** Market value of publicly traded shares
$NA
*** Current account balance
-$646 million (2014 est.)
-$953.2 million (2013 est.)
- country comparison to the world :: 118
*** Exports
$897.9 million (2014 est.)
$831.4 million (2013 est.)
- country comparison to the world :: 163
*** Exports - commodities
rubber, timber, iron, diamonds, cocoa, coffee
*** Exports - partners
China 31.9%, Greece 8.8%, US 8.6%, Germany 8.2%, France 7.3%, Spain 4.8% (2014)
*** Imports
$2.615 billion (2014 est.)
$2.457 billion (2013 est.)
- country comparison to the world :: 154
*** Imports - commodities
fuels, chemicals, machinery, transportation equipment, manufactured goods; foodstuffs
*** Imports - partners
Singapore 33.9%, South Korea 25.6%, China 14.7%, Japan 9.1% (2014)
*** Debt - external
$625.9 million (31 December 2014 est.)
$586.9 million (31 December 2013 est.)
- country comparison to the world :: 171
*** Stock of direct foreign investment - at home
$17.01 billion (31 December 2014 est.)
$16.56 billion (31 December 2013 est.)
- country comparison to the world :: 81
*** Stock of direct foreign investment - abroad
$201 million (31 December 2013 est.)
$201 million (31 December 2012 est.)
- country comparison to the world :: 88
*** Exchange rates
Liberian dollars (LRD) per US dollar -
86.65 (2014 est.)
77.52 (2013 est.)
73.52 (2012 est.)
72.227 (2011 est.)
71.403 (2010 est.)
** Energy
*** Electricity - production
335 million kWh (2011 est.)
- country comparison to the world :: 169
*** Electricity - consumption
311.6 million kWh (2011 est.)
- country comparison to the world :: 176
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 162
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 168
*** Electricity - installed generating capacity
197,000 kW (2011 est.)
- country comparison to the world :: 160
*** Electricity - from fossil fuels
100% of total installed capacity (2011 est.)
- country comparison to the world :: 20
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 127
*** Electricity - from hydroelectric plants
0% of total installed capacity (2011 est.)
- country comparison to the world :: 180
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 195
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 191
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 144
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 210
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 156
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 164
*** Refined petroleum products - consumption
3,780 bbl/day (2013 est.)
- country comparison to the world :: 177
*** Refined petroleum products - exports
23 bbl/day (2010 est.)
- country comparison to the world :: 123
*** Refined petroleum products - imports
3,673 bbl/day (2010 est.)
- country comparison to the world :: 165
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 156
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 164
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 133
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 90
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 160
*** Carbon dioxide emissions from consumption of energy
541,600 Mt (2012 est.)
- country comparison to the world :: 180
** Communications
*** Telephones - fixed lines
- total subscriptions :: 10,000
- subscriptions per 100 inhabitants :: less than 1 (2014 est.)
- country comparison to the world :: 198
*** Telephones - mobile cellular
- total :: 3.2 million
- subscriptions per 100 inhabitants :: 79 (2014 est.)
- country comparison to the world :: 136
*** Telephone system
- general assessment :: the limited services available are found almost exclusively in the capital, Monrovia; fixed-line service stagnant and extremely limited; telephone coverage extended to a number of other towns and rural areas by four mobile-cellular network operators
- domestic :: mobile-cellular subscription base growing and teledensity reached 50 per 100 persons in 2011
- international :: country code - 231; satellite earth station - 1 Intelsat (Atlantic Ocean) (2010)
*** Broadcast media
3 private TV stations; satellite TV service available; 1 state-owned radio station; about 15 independent radio stations broadcasting in Monrovia, with another 25 local stations operating in other areas; transmissions of 2 international broadcasters are available (2007)
*** Radio broadcast stations
AM 0, FM 10, shortwave 2 (2007)
*** Television broadcast stations
5 (plus 4 repeaters) (2007)
*** Internet country code
.lr
*** Internet users
- total :: 177,600
- percent of population :: 4.3% (2014 est.)
- country comparison to the world :: 158
** Transportation
*** Airports
29 (2013)
- country comparison to the world :: 117
*** Airports - with paved runways
- total :: 2
- over 3,047 m :: 1
- 1,524 to 2,437 m :: 1 (2013)
*** Airports - with unpaved runways
- total :: 27
- 1,524 to 2,437 m :: 5
- 914 to 1,523 m :: 8
- under 914 m :: 
14 (2013)
*** Pipelines
oil 4 km (2013)
*** Railways
- total :: 429 km
- standard gauge :: 345 km 1.435-m gauge
- narrow gauge :: 84 km 1.067-m gauge
- note :: most sections of the railways inoperable due to damage sustained during the civil wars from 1980 to 2003, but many are being rebuilt (2008)
- country comparison to the world :: 116
*** Roadways
- total :: 10,600 km
- paved :: 657 km
- unpaved :: 9,943 km (2000)
- country comparison to the world :: 134
*** Merchant marine
- total :: 2,771
- by type :: barge carrier 5, bulk carrier 662, cargo 143, carrier 2, chemical tanker 248, combination ore/oil 8, container 937, liquefied gas 92, passenger 2, passenger/cargo 2, petroleum tanker 526, refrigerated cargo 102, roll on/roll off 5, specialized tanker 10, vehicle carrier 27
- foreign-owned :: 2,581 (Angola 1, Argentina 1, Australia 1, Belgium 1, Bermuda 4, Brazil 20, Canada 2, Chile 9, China 4, Croatia 1, Cyprus 9, Denmark 8, Egypt 3, Germany 1185, Gibraltar 5, Greece 505, Hong Kong 48, India 8, Indonesia 4, Israel 34, Italy 47, Japan 110, Latvia 5, Lebanon 1, Monaco 8, Netherlands 31, Nigeria 4, Norway 38, Poland 13, Qatar 5, Romania 3, Russia 109, Saudi Arabia 20, Singapore 22, Slovenia 7, South Korea 2, Sweden 12, Switzerland 25, Syria 1, Taiwan 94, Turkey 16, UAE 37, UK 32, Ukraine 10, Uruguay 1, US 53) (2010)
- country comparison to the world :: 2
*** Ports and terminals
- major seaport(s) :: Buchanan, Monrovia
** Military
*** Military branches
Armed Forces of Liberia (AFL): Army, Navy, Air Force
*** Military service age and obligation
18 years of age for voluntary military service; no conscription (2012)
*** Manpower available for military service
- males age 16-49 :: 815,826
- females age 16-49 :: 828,484 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 524,243
- females age 16-49 :: 544,349 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 36,585
- female :: 38,516 (2010 est.)
*** Military expenditures
0.82% of GDP (2012)
0.86% of GDP (2011)
0.82% of GDP (2010)
- country comparison to the world :: 114
** Transnational Issues
*** Disputes - international
although civil unrest continues to abate with the assistance of 6,500 UN Mission in Liberia peacekeepers, as of January 2013, Liberian refugees still remain in Guinea, Cote d'Ivoire, Sierra Leone, and Ghana; Liberia, in turn, shelters refugees fleeing turmoil in Cote d'Ivoire; despite the presence of over 9,000 UN forces in Cote d'Ivoire since 2004, ethnic conflict continues to spread into neighboring states who can no longer send their migrant workers to Ivorian cocoa plantations; UN sanctions ban Liberia from exporting diamonds and timber
*** Refugees and internally displaced persons
- refugees (country of origin) :: 38,102 (Cote d'Ivoire) (2015)
- IDPs :: up to 23,000 (civil war from 1990-2004; post-election violence in March and April 2011; unclear how many have found durable solutions; many dwell in slums in Monrovia) (2014)
*** Illicit drugs
transshipment point for Southeast and Southwest Asian heroin and South American cocaine for the European and US markets; corruption, criminal activity, arms-dealing, and diamond trade provide significant potential for money laundering, but the lack of well-developed financial system limits the country's utility as a major money-laundering center