** Introduction
*** Background
The exact origins of the Nauruans are unclear since their language does not resemble any other in the Pacific region. Germany annexed the island in 1888. A German-British consortium began mining the island's phosphate deposits early in the 20th century. Australian forces occupied Nauru in World War I; it subsequently became a League of Nations mandate. After the Second World War - and a brutal occupation by Japan - Nauru became a UN trust territory. It achieved independence in 1968 and joined the UN in 1999 as the world's smallest independent republic.
** Geography
*** Location
Oceania, island in the South Pacific Ocean, south of the Marshall Islands
*** Geographic coordinates
0 32 S, 166 55 E
*** Map references
Oceania
*** Area
- total :: 21 sq km
- land :: 21 sq km
- water :: 0 sq km
- country comparison to the world :: 240
*** Area - comparative
about 0.1 times the size of Washington, DC
*** Land boundaries
0 km
*** Coastline
30 km
*** Maritime claims
- territorial sea :: 12 nm
- contiguous zone :: 24 nm
- exclusive economic zone :: 200 nm
*** Climate
tropical with a monsoonal pattern; rainy season (November to February)
*** Terrain
sandy beach rises to fertile ring around raised coral reefs with phosphate plateau in center
*** Elevation extremes
- lowest point :: Pacific Ocean 0 m
- highest point :: unnamed elevation along plateau rim 61 m
*** Natural resources
phosphates, fish
*** Land use
- agricultural land :: 20%
arable land 0%; permanent crops 20%; permanent pasture 0%
- forest :: 0%
- other :: 80% (2011 est.)
*** Irrigated land
NA
*** Natural hazards
periodic droughts
*** Environment - current issues
limited natural freshwater resources, roof storage tanks collect rainwater but mostly dependent on a single, aging desalination plant; a century of intensive phosphate mining beginning in 1906 - mainly by a UK, Australia, and NZ consortium - left the central 90% of Nauru a wasteland and threatens limited remaining land resources
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Hazardous Wastes, Law of the Sea, Marine Dumping, Ozone Layer Protection, Whaling
- signed, but not ratified :: none of the selected agreements
*** Geography - note
world's smallest island country; situated just 53 km south of the Equator; Nauru is one of the three great phosphate rock islands in the Pacific Ocean - the others are Banaba (Ocean Island) in Kiribati and Makatea in French Polynesia
** People and Society
*** Nationality
- noun :: Nauruan(s)
- adjective :: Nauruan
*** Ethnic groups
Nauruan 58%, other Pacific Islander 26%, Chinese 8%, European 8%
*** Languages
Nauruan 93% (official, a distinct Pacific Island language), English 2% (widely understood, spoken, and used for most government and commercial purposes), other 5% (includes I-Kiribati 2% and Chinese 2%)
- note :: percentages represent main language spoken at home; Nauruan is spoken by 95% of the population, English by 66%, and other languages by 12% (2011 est.)
*** Religions
Protestant 60.4% (includes Nauru Congregational 35.7%, Assembly of God 13%, Nauru Independent Church 9.5%, Baptist 1.5%, and Seventh Day Adventist .7%), Roman Catholic 33%, other 3.7%, none 1.8%, unspecified 1.1% (2011 est.)
*** Population
9,540 (July 2015 est.)
- country comparison to the world :: 225
*** Age structure
- 0-14 years :: 32.45% (male 1,360/female 1,736)
- 15-24 years :: 16.13% (male 785/female 754)
- 25-54 years :: 43.19% (male 2,059/female 2,061)
- 55-64 years :: 6.11% (male 231/female 352)
- 65 years and over :: 2.12% (male 78/female 124) (2015 est.)
- population pyramid ::  
*** Median age
- total :: 25.7 years
- male :: 26.1 years
- female :: 25.3 years (2015 est.)
*** Population growth rate
0.55% (2015 est.)
- country comparison to the world :: 154
*** Birth rate
24.95 births/1,000 population (2015 est.)
- country comparison to the world :: 52
*** Death rate
5.87 deaths/1,000 population (2015 est.)
- country comparison to the world :: 171
*** Net migration rate
-13.63 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 218
*** Urbanization
- urban population :: 100% of total population (2015)
- rate of urbanization :: 0.19% annual rate of change (2010-15 est.)
*** Sex ratio
- at birth :: 0.83 male(s)/female
- 0-14 years :: 0.78 male(s)/female
- 15-24 years :: 1.04 male(s)/female
- 25-54 years :: 1 male(s)/female
- 55-64 years :: 0.66 male(s)/female
- 65 years and over :: 0.63 male(s)/female
- total population :: 0.9 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 8.07 deaths/1,000 live births
- male :: 10.34 deaths/1,000 live births
- female :: 6.17 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 154
*** Life expectancy at birth
- total population :: 66.75 years
- male :: 62.64 years
- female :: 70.19 years (2015 est.)
- country comparison to the world :: 170
*** Total fertility rate
2.88 children born/woman (2015 est.)
- country comparison to the world :: 58
*** Contraceptive prevalence rate
35.6% (2007)
*** Health expenditures
6.3% of GDP (2013)
- country comparison to the world :: 67
*** Physicians density
0.71 physicians/1,000 population (2010)
*** Drinking water source
- improved :: 
urban: 96.5% of population
total: 96.5% of population
- unimproved :: 
urban: 3.5% of population
total: 3.5% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 65.6% of population
total: 65.6% of population
- unimproved :: 
urban: 34.4% of population
total: 34.4% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
*** Obesity - adult prevalence rate
45.1% (2014)
- country comparison to the world :: 2
*** Children under the age of 5 years underweight
4.8% (2007)
- country comparison to the world :: 91
*** Education expenditures
NA
*** School life expectancy (primary to tertiary education)
- total :: 9 years
- male :: 9 years
- female :: 10 years (2008)
** Government
*** Country name
- conventional long form :: Republic of Nauru
- conventional short form :: Nauru
- local long form :: Republic of Nauru
- local short form :: Nauru
- former :: Pleasant Island
*** Government type
republic
*** Capital
no official capital; government offices in Yaren District
- time difference :: UTC+12 (17 hours ahead of Washington, DC, during Standard Time)
*** Administrative divisions
14 districts; Aiwo, Anabar, Anetan, Anibare, Baiti, Boe, Buada, Denigomodu, Ewa, Ijuw, Meneng, Nibok, Uaboe, Yaren
*** Independence
31 January 1968 (from the Australia-, NZ-, and UK-administered UN trusteeship)
*** National holiday
Independence Day, 31 January (1968)
*** Constitution
effective 29 January 1968; amended 1968, 2009; note - in early 2013, further amendments were introduced to be passed or denied by the legislature (2013)
*** Legal system
mixed legal system of common law based on the English model and customary law
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; accepts ICCt jurisdiction
*** Suffrage
20 years of age; universal and compulsory
*** Executive branch
- chief of state :: President Baron WAQA (since 11 June 2013); note - the president is both chief of state and head of government
- head of government :: President Baron WAQA (since 11 June 2013)
- cabinet :: Cabinet appointed by the president from among members of Parliament
- elections/appointments :: president indirectly elected by Parliament for a 3-year renewable term; election last held on 11 June 2013 (next to be held in 2016)
- election results :: Baron WAQA reelected president on 11 June 2013; Parliament vote - Baron WAQA (independent) 13, Roland KUN (Nauru First)  5
*** Legislative branch
- description :: unicameral parliament (19 seats; members directly elected in multi-seat constituencies by majority vote; members serve 3-year terms)
- elections :: last held on 8 June 2013 (next to be held in 2016)
- election results :: percent of vote - NA; seats - independent 19
*** Judicial branch
- highest court(s) :: Supreme Court (consists of a chief justice and 1 judge)
- judge selection and term of office :: judges appointed by the president to serve until age 65
- subordinate courts :: District Court, Family Court
*** Political parties and leaders
Democratic Party [Kennan ADEANG]
Nauru First (Naoero Amo) Party
Nauru Party (informal)
- note :: loose multiparty system
*** Political pressure groups and leaders
Woman Information and News Agency (women's issues)
*** International organization participation
ACP, ADB, AOSIS, C, FAO, G-77, ICAO, ICCt, IFAD, Interpol, IOC, IOM, ITU, OPCW, PIF, Sparteca, SPC, UN, UNCTAD, UNESCO, UPU, WHO
*** Diplomatic representation in the US
- chief of mission :: Ambassador Marlene Inemwin MOSES (since 10 February 2006)
- chancery :: 800 2nd Avenue, Suite 400 D, New York, NY 10017
- telephone :: [1] (212) 937-0074
- FAX :: [1] (212) 937-0079
- consulate(s) :: Agana (Guam)
*** Diplomatic representation from the US
the US does not have an embassy in Nauru; the US Ambassador to Fiji is accredited to Nauru
*** Flag description
blue with a narrow, horizontal, yellow stripe across the center and a large white 12-pointed star below the stripe on the hoist side; blue stands for the Pacific Ocean, the star indicates the country's location in relation to the Equator (the yellow stripe) and the 12 points symbolize the 12 original tribes of Nauru
*** National symbol(s)
frigatebird, calophyllum flower; national colors: blue, yellow, white
*** National anthem
- name :: "Nauru Bwiema" (Song of Nauru)
- lyrics/music :: Margaret HENDRIE/Laurence Henry HICKS
- note :: adopted 1968
** Economy
*** Economy - overview
Revenues of this tiny island - a coral atoll with a land area of 21 square kilometers - traditionally have come from exports of phosphates. Few other resources exist, with most necessities being imported, mainly from Australia, its former occupier and later major source of support. Primary reserves of phosphates were exhausted and mining ceased in 2006, but mining of a deeper layer of "secondary phosphate" in the interior of the island began the following year. The secondary phosphate deposits may last another 30 years. Earnings from Nauru’s export of phosphate remains an important source of income. The rehabilitation of mined land and the replacement of income from phosphates are serious long-term problems. In anticipation of the exhaustion of Nauru's phosphate deposits, substantial amounts of phosphate income were invested in trust funds to help cushion the transition and provide for Nauru's economic future. Although revenue sources for government are limited, the opening of the Australian Regional Processing Center for asylum seekers since 2012 has sparked growth in the economy. Revenue derived from fishing licenses under the vessel day scheme has also boosted government income. Housing, hospitals, and other capital plant are deteriorating. The cost to Australia of keeping the government and economy afloat continues to climb. Few comprehensive statistics on the Nauru economy exist with estimates of Nauru's GDP varying widely.
*** GDP (purchasing power parity)
$60 million (2005 est.)
- country comparison to the world :: 225
*** GDP (official exchange rate)
$NA
*** GDP - real growth rate
NA%
*** GDP - per capita (PPP)
$5,000 (2005 est.)
- country comparison to the world :: 168
*** GDP - composition, by sector of origin
- agriculture :: 6.1%
- industry :: 33%
- services :: 60.8% (2009 est.)
*** Agriculture - products
coconuts
*** Industries
phosphate mining, offshore banking, coconut products
*** Industrial production growth rate
NA%
*** Labor force - by occupation
- note :: most of the labor force is employed in phosphate mining, public administration, education, and transportation
*** Unemployment rate
23% (2011 est.)
90% (2004 est.)
- country comparison to the world :: 203
*** Population below poverty line
NA%
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $57.8 million
- expenditures :: $51.8 million (2010 est.)
*** Fiscal year
1 July - 30 June
*** Inflation rate (consumer prices)
-2.1% (2013 est.)
-0.8% (2013 est.)
- country comparison to the world :: 2
*** Exports
$125 million (2013 est.)
$150 million (2012 est.)
- country comparison to the world :: 220
*** Exports - commodities
phosphates
*** Imports
$143.1 million (2013 est.)
$41.2 million (2012 est.)
- country comparison to the world :: 220
*** Imports - commodities
food, fuel, manufactures, building materials, machinery
*** Debt - external
$33.3 million (2004 est.)
- country comparison to the world :: 196
*** Exchange rates
Australian dollars (AUD) per US dollar -
1.098 (2013)
1.0358 (2013 est.)
0.97 (2012 est.)
0.9695 (2011 est.)
1.0902 (2010)
** Energy
*** Electricity - consumption
23.25 million kWh (2011 est.)
- country comparison to the world :: 212
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 180
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 182
*** Electricity - installed generating capacity
6,040 kW (FY10/11 est.)
- country comparison to the world :: 209
*** Electricity - from fossil fuels
100% of total installed capacity (2011 est.)
- country comparison to the world :: 27
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 155
*** Electricity - from hydroelectric plants
0% of total installed capacity (2011 est.)
- country comparison to the world :: 191
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 111
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 207
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 165
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 107
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 174
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 183
*** Refined petroleum products - consumption
1,010 bbl/day (2013 est.)
- country comparison to the world :: 202
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 206
*** Refined petroleum products - imports
1,075 bbl/day (2010 est.)
- country comparison to the world :: 193
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 176
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 181
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 155
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 110
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 179
*** Carbon dioxide emissions from consumption of energy
168,700 Mt (2012 est.)
- country comparison to the world :: 198
** Communications
*** Telephones - fixed lines
- total subscriptions :: 0
- subscriptions per 100 inhabitants :: less than 1 (2014 est.)
- country comparison to the world :: 218
*** Telephones - mobile cellular
- total :: 6,800
- subscriptions per 100 inhabitants :: 73 (2012)
- country comparison to the world :: 214
*** Telephone system
- general assessment :: adequate local and international radiotelephone communication provided via Australian facilities
- international :: country code - 674; satellite earth station - 1 Intelsat (Pacific Ocean)
*** Broadcast media
1 government-owned TV station broadcasting programs from New Zealand sent via satellite or on videotape; 1 government-owned radio station, broadcasting on AM and FM, utilizes Australian and British programs (2009)
*** Radio broadcast stations
AM 1, FM 0, shortwave 0 (1998)
*** Television broadcast stations
1 (1997)
*** Internet country code
.nr
** Transportation
*** Airports
1 (2013)
- country comparison to the world :: 227
*** Airports - with paved runways
- total :: 1
- 1,524 to 2,437 m :: 1 (2013)
*** Roadways
- total :: 30 km
- paved :: 24 km
- unpaved :: 6 km (2002)
- country comparison to the world :: 220
*** Ports and terminals
- major seaport(s) :: Nauru
** Military
*** Military branches
no regular military forces (2012)
*** Manpower available for military service
- males age 16-49 :: 2,542 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 1,823
- females age 16-49 :: 2,034 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 74
- female :: 78 (2010 est.)
*** Military - note
Nauru maintains no defense forces; under an informal agreement, defense is the responsibility of Australia
** Transnational Issues
*** Disputes - international
none