** Introduction
*** Background
First settled by the French in the early 17th century, the islands represent the sole remaining vestige of France's once vast North American possessions.
** Geography
*** Location
Northern North America, islands in the North Atlantic Ocean, south of Newfoundland (Canada)
*** Geographic coordinates
46 50 N, 56 20 W
*** Map references
North America
*** Area
- total :: 242 sq km
- land :: 242 sq km
- water :: 0 sq km
- note :: includes eight small islands in the Saint Pierre and the Miquelon groups
- country comparison to the world :: 214
*** Area - comparative
one and half times the size of Washington, DC
*** Land boundaries
0 km
*** Coastline
120 km
*** Maritime claims
- territorial sea :: 12 nm
- exclusive economic zone :: 200 nm
*** Climate
cold and wet, with considerable mist and fog; spring and autumn are often windy
*** Terrain
mostly barren rock
*** Elevation extremes
- lowest point :: Atlantic Ocean 0 m
- highest point :: Morne de la Grande Montagne 240 m
*** Natural resources
fish, deepwater ports
*** Land use
- agricultural land :: 8.7%
arable land 8.7%; permanent crops 0%; permanent pasture 0%
- forest :: 12.5%
- other :: 78.8% (2011 est.)
*** Irrigated land
NA
*** Natural hazards
persistent fog throughout the year can be a maritime hazard
*** Environment - current issues
recent test drilling for oil in waters around Saint Pierre and Miquelon may bring future development that would impact the environment
*** Geography - note
vegetation scanty
** People and Society
*** Nationality
- noun :: Frenchman(men), Frenchwoman(women)
- adjective :: French
*** Ethnic groups
Basques and Bretons (French fishermen)
*** Languages
French (official)
*** Religions
Roman Catholic 99%, other 1%
*** Population
5,657 (July 2015 est.)
- country comparison to the world :: 228
*** Age structure
- 0-14 years :: 15.96% (male 465/female 438)
- 15-24 years :: 8.75% (male 256/female 239)
- 25-54 years :: 42.87% (male 1,199/female 1,226)
- 55-64 years :: 13.68% (male 404/female 370)
- 65 years and over :: 18.74% (male 443/female 617) (2015 est.)
- population pyramid ::  
*** Median age
- total :: 45.2 years
- male :: 44.8 years
- female :: 45.6 years (2015 est.)
*** Population growth rate
-1.08% (2015 est.)
- country comparison to the world :: 232
*** Birth rate
7.42 births/1,000 population (2015 est.)
- country comparison to the world :: 223
*** Death rate
9.72 deaths/1,000 population (2015 est.)
- country comparison to the world :: 50
*** Net migration rate
-8.49 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 210
*** Urbanization
- urban population :: 90.4% of total population (2015)
- rate of urbanization :: 0.1% annual rate of change (2010-15 est.)
*** Major urban areas - population
SAINT-PIERRE (capital) 5,000 (2014)
*** Sex ratio
- at birth :: 1.05 male(s)/female
- 0-14 years :: 1.06 male(s)/female
- 15-24 years :: 1.07 male(s)/female
- 25-54 years :: 0.98 male(s)/female
- 55-64 years :: 1.09 male(s)/female
- 65 years and over :: 0.72 male(s)/female
- total population :: 0.96 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 6.78 deaths/1,000 live births
- male :: 7.87 deaths/1,000 live births
- female :: 5.63 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 161
*** Life expectancy at birth
- total population :: 80.39 years
- male :: 78.06 years
- female :: 82.85 years (2015 est.)
- country comparison to the world :: 35
*** Total fertility rate
1.56 children born/woman (2015 est.)
- country comparison to the world :: 186
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
** Government
*** Country name
- conventional long form :: Territorial Collectivity of Saint Pierre and Miquelon
- conventional short form :: Saint Pierre and Miquelon
- local long form :: Departement de Saint-Pierre et Miquelon
- local short form :: Saint-Pierre et Miquelon
*** Dependency status
self-governing territorial overseas collectivity of France
*** Government type
parliamentary representative democracy
*** Capital
- name :: Saint-Pierre
- geographic coordinates :: 46 46 N, 56 11 W
- time difference :: UTC-3 (2 hours ahead of Washington, DC, during Standard Time)
- daylight saving time :: +1hr, begins second Sunday in March; ends first Sunday in November
*** Administrative divisions
none (territorial overseas collectivity of France); note - there are no first-order administrative divisions as defined by the US Government, but there are 2 communes at the second order - Saint Pierre, Miquelon
*** Independence
none (territorial collectivity of France; has been under French control since 1763)
*** National holiday
Fete de la Federation, 14 July (1789)
*** Constitution
4 October 1958 (French Constitution) (2013)
*** Legal system
French civil law
*** Suffrage
18 years of age; universal
*** Executive branch
- chief of state :: President Francois HOLLANDE (since 15 May 2012); represented by Prefect Jean-Christophe BOUVIER (since September 2014)
- head of government :: President of Territorial Council Stephane ARTANO (since 21 February 2007)
- cabinet :: Le Cabinet du Prefet
- elections/appointments :: French president directly elected by absolute majority popular vote in 2 rounds if needed for a 5-year term (eligible for a second term); election last held on 6 May 2012 (next to be held in 2017); prefect appointed by French president on the advice of French Ministry of Interior
*** Legislative branch
- description :: unicameral Territorial Council or Conseil Territorial (19 seats - 15 from Saint Pierre and 4 from Miquelon; members directly elected in single-seat constituencies by absolute majority vote to serve 6-year terms)
- note :: Saint Pierre and Miquelon elect one member to the French Senate; elections last held on 28 September 2014 (next to be held not later than September 2017); results - percent of vote by party - NA; seats by party - AD 1 (affiliated with UMP); Saint Pierre and Miquelon also elects one member to the French National Assembly; elections last held on 17 June 2012 (next to be held by June 2017); results - percent of vote by party - NA; seats by party - Ensemble pour l'Avenir 1 (affiliated with PRG)
- elections :: elections last held on 18 March 2012 (next to be held in March 2018)
- election results :: percent of vote by party - AD 52.5%, Ensemble pour l'Avenir 47.5%; seats by party - AD 14, Ensemble pour l'Avenir 5
*** Judicial branch
- highest court(s) :: Superior Tribunal of Appeals or Tribunal Superieur d'Appel (composition NA)
- judge selection and term of office :: judge selection and tenure NA
- subordinate courts :: NA
*** Political parties and leaders
Archipelago Tomorrow or AD [Stephane ARTANO] (affiliated with UMP)
Ensemble pour l'Avenir [Annick GIRARDIN] (affiliated with PRG)
*** Political pressure groups and leaders
NA
*** International organization participation
UPU, WFTU (NGOs)
*** Diplomatic representation in the US
none (territorial overseas collectivity of France)
*** Diplomatic representation from the US
none (territorial overseas collectivity of France)
*** Flag description
a yellow three-masted sailing ship facing the hoist side rides on a blue background with scattered, white, wavy lines under the ship; a continuous black-over-white wavy line divides the ship from the white wavy lines; on the hoist side, a vertical band is divided into three parts: the top part (called ikkurina) is red with a green diagonal cross extending to the corners overlaid by a white cross dividing the rectangle into four sections; the middle part has a white background with an ermine pattern; the third part has a red background with two stylized yellow lions outlined in black, one above the other; these three heraldic arms represent settlement by colonists from the Basque Country (top), Brittany, and Normandy; the blue on the main portion of the flag symbolizes the Atlantic Ocean and the stylized ship represents the Grande Hermine in which Jacques Cartier "discovered" the islands in 1536
- note :: the flag of France used for official occasions
*** National symbol(s)
16th-century sailing ship
*** National anthem
- note :: as a collectivity of France, "La Marseillaise" is official (see France)

** Economy
*** Economy - overview
The inhabitants have traditionally earned their livelihood by fishing and by servicing fishing fleets operating off the coast of Newfoundland. The economy has been declining, however, because of disputes with Canada over fishing quotas and a steady decline in the number of ships stopping at Saint Pierre. In 1992, an arbitration panel awarded the islands an exclusive economic zone of 12,348 sq km to settle a longstanding territorial dispute with Canada, although it represents only 25% of what France had sought. France heavily subsidizes the islands to the great betterment of living standards. The government hopes an expansion of tourism will boost economic prospects. Fish farming, crab fishing, and agriculture are being developed to diversify the local economy. Recent test drilling for oil may pave the way for development of the energy sector.
*** GDP (purchasing power parity)
$215.3 million (2006 est.)
- note :: supplemented by annual payments from France of about $60 million
- country comparison to the world :: 218
*** GDP (official exchange rate)
$215.3 million (2006 est.)
*** GDP - real growth rate
NA%
*** GDP - per capita (PPP)
$34,900 (2006 est.)
- country comparison to the world :: 48
*** GDP - composition, by sector of origin
- agriculture :: 2%
- industry :: 15%
- services :: 83% (2006 est.)
*** Agriculture - products
vegetables; poultry, cattle, sheep, pigs; fish
*** Industries
fish processing and supply base for fishing fleets; tourism
*** Industrial production growth rate
NA%
*** Labor force
3,194 (2006)
- country comparison to the world :: 224
*** Labor force - by occupation
- agriculture :: 18%
- industry :: 41%
- services :: 41% (1996 est.)
*** Unemployment rate
9.9% (2008 est.)
- country comparison to the world :: 112
*** Population below poverty line
NA%
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $70 million
- expenditures :: $60 million (1996 est.)
*** Taxes and other revenues
32.5% of GDP (1996)
- country comparison to the world :: 78
*** Budget surplus (+) or deficit (-)
4.6% of GDP (1996)
- country comparison to the world :: 8
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
4.5% (2010)
8.1% (2005)
- country comparison to the world :: 164
*** Exports
$6.641 million (2010 est.)
$5.5 million (2005 est.)
- country comparison to the world :: 216
*** Exports - commodities
fish and fish products, soybeans, animal feed, mollusks and crustaceans, fox and mink pelts
*** Imports
$95.35 million (2010 est.)
$68.2 million (2005 est.)
- country comparison to the world :: 213
*** Imports - commodities
meat, clothing, fuel, electrical equipment, machinery, building materials
*** Debt - external
$NA
*** Exchange rates
euros (EUR) per US dollar -
0.7489 (2014 est.)
0.7634 (2013 est.)
0.78 (2012 est.)
0.7185 (2011 est.)
0.755 (2010 est.)
** Energy
*** Electricity - production
42 million kWh (2011 est.)
- country comparison to the world :: 210
*** Electricity - consumption
39.06 million kWh (2011 est.)
- country comparison to the world :: 210
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 191
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 195
*** Electricity - installed generating capacity
26,600 kW (2011 est.)
- country comparison to the world :: 200
*** Electricity - from fossil fuels
97.7% of total installed capacity (2011 est.)
- country comparison to the world :: 56
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 173
*** Electricity - from hydroelectric plants
0% of total installed capacity (2011 est.)
- country comparison to the world :: 195
*** Electricity - from other renewable sources
2.3% of total installed capacity (2011 est.)
- country comparison to the world :: 74
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 211
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 175
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 116
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 182
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 189
*** Refined petroleum products - consumption
1,010 bbl/day (2013 est.)
- country comparison to the world :: 203
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 125
*** Refined petroleum products - imports
584 bbl/day (2010 est.)
- country comparison to the world :: 201
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 186
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 189
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 172
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 125
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 187
*** Carbon dioxide emissions from consumption of energy
151,100 Mt (2012 est.)
- country comparison to the world :: 204
** Communications
*** Telephones - fixed lines
- total subscriptions :: 4,800
- subscriptions per 100 inhabitants :: 81 (2014 est.)
- country comparison to the world :: 209
*** Telephone system
- general assessment :: adequate
- international :: country code - 508; radiotelephone communication with most countries in the world; satellite earth station - 1 in French domestic satellite system
*** Broadcast media
2 TV stations with a third repeater station, all part of the French Overseas Network; radio stations on St. Pierre and on Miquelon are part of the French Overseas Network (2007)
*** Radio broadcast stations
AM 1, FM 4, shortwave 0 (1998)
*** Television broadcast stations
0 (2 repeaters rebroadcast programs from France, Canada, and the US) (1997)
*** Internet country code
.pm
** Transportation
*** Airports
2 (2013)
- country comparison to the world :: 205
*** Airports - with paved runways
- total :: 2
- 1,524 to 2,437 m :: 1
- 914 to 1,523 m :: 1 (2013)
*** Roadways
- total :: 117 km
- paved :: 80 km
- unpaved :: 37 km (2009)
- country comparison to the world :: 215
*** Ports and terminals
- major seaport(s) :: Saint-Pierre
** Military
*** Manpower fit for military service
- males age 16-49 :: 1,064
- females age 16-49 :: 1,069 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 34
- female :: 32 (2010 est.)
*** Military - note
defense is the responsibility of France
** Transnational Issues
*** Disputes - international
none