** Introduction
*** Background
From the early 16th century through 1917, the area now known as the West Bank fell under Ottoman rule. Following World War I, the Allied powers (France, UK, Russia) allocated the area to the British Mandate of Palestine. After World War II, the UN passed a resolution to establish two states within the Mandate, and designated a territory including what is now known as the West Bank as part of the proposed Arab state. Following the 1948 Arab-Israeli War the area was captured by Transjordan (later renamed Jordan). Jordan annexed the West Bank in 1950. In June 1967, Israel captured the West Bank and East Jerusalem during the 1967 Six-Day War. With the exception of East Jerusalem and the former Israeli-Jordanian border zone, the West Bank remained under Israeli military control until Israel transferred security and civilian responsibility for many Palestinian-populated areas of the West Bank and Gaza Strip to the Palestinian Authority (PA) under a series of agreements signed between 1994 and 1999. Negotiations to determine the permanent status of the West Bank and Gaza Strip stalled after the outbreak of an intifada in mid-2000. In early 2003, the "Quartet" of the US, EU, UN, and Russia, presented a roadmap to a final peace settlement by 2005, calling for two states - Israel and a democratic Palestine. Following Palestinian leader Yasir ARAFAT's death in late 2004 and the subsequent election of Mahmud ABBAS (head of the Fatah political faction) as PA president, Israel and the Palestinians agreed to move the peace process forward. Israel in late 2005 unilaterally withdrew all of its settlers and soldiers and dismantled its military facilities in the Gaza Strip and redeployed its military from several West Bank settlements but continues to control maritime, airspace, and other access. In early 2006, the Islamic Resistance Movement, HAMAS, won the Palestinian Legislative Council election and took control of the PA government. Attempts to form a unity government failed, and violent clashes between Fatah and HAMAS supporters ensued, culminating in HAMAS's violent seizure of all military and governmental institutions in the Gaza Strip. Fatah and HAMAS have made several attempts at reconciliation, most recently signing an agreement in April 2014 following the collapse of US-brokered peace talks with Israel. The factions, however, have been unable to implement details on governance and security, and the status quo remains with HAMAS in de facto control of the Gaza Strip and the PA governing the West Bank.
** Geography
*** Location
Middle East, west of Jordan, east of Israel
*** Geographic coordinates
32 00 N, 35 15 E
*** Map references
Middle East
*** Area
- total :: 5,860 sq km
- land :: 5,640 sq km
- water :: 220 sq km
- note :: includes West Bank, Latrun Salient, and the northwest quarter of the Dead Sea, but excludes Mt. Scopus; East Jerusalem and Jerusalem No Man's Land are also included only as a means of depicting the entire area occupied by Israel in 1967
- country comparison to the world :: 172
*** Area - comparative
slightly smaller than Delaware
*** Land boundaries
- total :: 478 km
- border countries (2) :: Israel 330 km, Jordan 148 km
*** Coastline
0 km (landlocked)
*** Maritime claims
none (landlocked)
*** Climate
temperate; temperature and precipitation vary with altitude, warm to hot summers, cool to mild winters
*** Terrain
mostly rugged, dissected upland in west, flat plains descending to Jordan River valley to the east
*** Elevation extremes
- lowest point :: Dead Sea -408 m
- highest point :: Tall Asur 1,022 m
*** Natural resources
arable land
*** Land use
- agricultural land :: 43.3%
arable land 7.4%; permanent crops 11%; permanent pasture 24.9%
- forest :: 1.5%
- other :: 55.2%
- note :: includes Gaza Strip (2011 est.)
*** Irrigated land
240 sq km; note - includes Gaza Strip (2003)
*** Natural hazards
droughts
*** Environment - current issues
adequacy of freshwater supply; sewage treatment
*** Geography - note
landlocked; highlands are main recharge area for Israel's coastal aquifers; there are about 381 Israeli civilian sites, including about 212 settlements and 134 small outpost communities in the West Bank and 35 sites in East Jerusalem (2014 est.)
** People and Society
*** Nationality
- noun :: NA
- adjective :: NA
*** Ethnic groups
Palestinian Arab and other 83%, Jewish 17%
*** Languages
Arabic, Hebrew (spoken by Israeli settlers and many Palestinians), English (widely understood)
*** Religions
Muslim 80.0 - 85.0% (predominantly Sunni), Jewish 12.0 - 14.0%, Christian 1.0 - 2.5% (mainly Greek Orthodox), other, unaffiliated, unspecified 
note: the proportion of Christians continues to fall mainly as a result of the growth of the Muslim population but also because of the migration and the declining birth rate of the Christian population (2012 est.)
religious affiliation:
 
          
Population:
2,785,366 (represents Palestinian population only) (July 2014 est.)
note: approximately 356,000 Israeli settlers live in the West Bank; approximately 200,000 Israeli settlers live in East Jerusalem (2013) (July 2015 est.)
country comparison to the world:  142
Age structure:
0-14 years: 33.09% (male 473,108/female 448,612)
15-24 years: 21.52% (male 307,020/female 292,465)
25-54 years: 36.96% (male 529,094/female 500,375)
55-64 years: 4.57% (male 64,093/female 63,289)
65 years and over: 3.85% (male 45,303/female 62,007) (2015 est.)
population pyramid:
 
          
Dependency ratios:
total dependency ratio: 76%
youth dependency ratio: 70.8%
elderly dependency ratio: 5.2%
potential support ratio: 19.2%
note: data represents the Gaza and the West Bank (2015 est.)
Median age:
total: 22.7 years
male: 22.6 years
female: 22.9 years (2015 est.)
Population growth rate:
1.95% (2015 est.)
country comparison to the world:  51
Birth rate:
22.99 births/1,000 population (2015 est.)
country comparison to the world:  67
Death rate:
3.5 deaths/1,000 population (2015 est.)
country comparison to the world:  216
Net migration rate:
0 migrant(s)/1,000 population (2015 est.)
country comparison to the world:  111
Urbanization:
urban population: 75.3% of total population (2015)
rate of urbanization: 2.81% annual rate of change (2005-10 est.)
note: data represents Gaza Strip and West Bank
Sex ratio:
at birth: 1.06 male(s)/female
0-14 years: 1.06 male(s)/female
15-24 years: 1.05 male(s)/female
25-54 years: 1.06 male(s)/female
55-64 years: 1.01 male(s)/female
65 years and over: 0.73 male(s)/female
total population: 1.04 male(s)/female (2015 est.)
Infant mortality rate:
total: 13.08 deaths/1,000 live births
male: 14.7 deaths/1,000 live births
female: 11.37 deaths/1,000 live births (2015 est.)
country comparison to the world:  115
Life expectancy at birth:
total population: 75.91 years
male: 73.79 years
female: 78.17 years (2015 est.)
country comparison to the world:  92
Total fertility rate:
2.76 children born/woman (2015 est.)
country comparison to the world:  66
Contraceptive prevalence rate:
52.5% (includes Gaza Strip and the West Bank) (2010)
Physicians density:
1.3 physicians/1,000 population (2013)
Hospital bed density:
1.2 beds/1,000 population (2010)
Drinking water source:
improved: 
urban: 50.7% of population
rural: 81.5% of population
total: 58.4% of population
unimproved: 
urban: 49.3% of population
rural: 18.5% of population
total: 41.6% of population

note: includes Gaza and the West Bank (2015 est.)
Sanitation facility access:
improved: 
urban: 93% of population
rural: 90.2% of population
total: 92.3% of population
unimproved: 
urban: 7% of population
rural: 9.8% of population
total: 7.7% of population

note: includes Gaza and the West Bank (2015 est.)
HIV/AIDS - adult prevalence rate:
NA
HIV/AIDS - people living with HIV/AIDS:
NA
HIV/AIDS - deaths:
NA
Literacy:
definition: age 15 and over can read and write
total population: 96.5%
male: 98.4%
female: 94.5%
notes: estimates are for the Palestinian Territories (2015 est.)
School life expectancy (primary to tertiary education):
total: 13 years
male: 12 years
female: 14 years
note: data represents Gaza and West Bank (2013)
Unemployment, youth ages 15-24:
total: 38.8%
male: 34.5%
female: 62.2%
note: includes Gaza Strip (2012 est.)
country comparison to the world:  15

** Government
*** Country name
- conventional long form :: none
- conventional short form :: West Bank
** Economy
*** Economy - overview
Economic growth in the West Bank - the larger of the two areas comprising the Palestinian territories - has slowed since 2013, in part because of a decline in donor aid and government spending. Private sector development has been weak. Despite the Palestinian Authority's (PA) successful implementation of economic and security reforms and the easing of some movement and access restrictions by the Israeli government, Israeli closure policies continue to disrupt labor and trade flows, industrial capacity, and basic commerce, constraining the productive capacity of the West Bank economy. The biggest impediments to economic improvements in the West Bank remain Palestinians' inability to access land and resources in Israeli-controlled areas, import and export restrictions, and a high-cost capital structure. The PA for the foreseeable future will continue to rely heavily on donor aid for its budgetary needs and economic activity.
*** GDP (purchasing power parity)
$20.12 billion (2014 est.)
$20.02 billion (2013 est.)
$19.92 billion (2012 est.)
- note :: data are in 2011 US dollars; includes Gaza Strip
- country comparison to the world :: 141
*** GDP (official exchange rate)
$6.641 billion
- note :: includes Gaza Strip (2008 est.)
*** GDP - real growth rate
0.5% (2014 est.)
0.5% (2013 est.)
6.1% (2012 est.)
- note :: includes Gaza Strip
- country comparison to the world :: 195
*** GDP - per capita (PPP)
$4,900 (2012 est.)
$4,400 (2011 est.)
$4,100 (2010 est.)
- note :: includes Gaza Strip
- country comparison to the world :: 169
*** Gross national saving
-12.3% of GDP (2014 est.)
-5.6% of GDP (2013 est.)
-15.2% of GDP (2012 est.)
- country comparison to the world :: 178
*** GDP - composition, by end use
- household consumption :: 86.6%
- government consumption :: 26.6%
- investment in fixed capital :: 25.3%
- investment in inventories :: 1.8%
- exports of goods and services :: 20.4%
- imports of goods and services :: -60.7%
 (2014 est.)
*** GDP - composition, by sector of origin
- agriculture :: 2.9%
- industry :: 23.6%
- services :: 73.5%
- note :: includes Gaza Strip (2014 est.)
*** Agriculture - products
olives, citrus fruit, vegetables; beef, dairy products
*** Industries
small-scale manufacturing, quarrying, textiles, soap, olive-wood carvings, and mother-of-pearl souvenirs
*** Industrial production growth rate
1.5% (2014 est.)
- country comparison to the world :: 143
*** Labor force
1.066 million (2014 est.)
- country comparison to the world :: 142
*** Labor force - by occupation
- agriculture :: 11.5%
- industry :: 34.4%
- services :: 54.1%
- note :: includes Gaza Strip (2013 est.)
*** Unemployment rate
16% (2014 est.)
18.6% (2013 est.)
- country comparison to the world :: 150
*** Population below poverty line
18% (2011 est.)
*** Household income or consumption by percentage share
- lowest 10% :: 3.2%
- highest 10% :: 28.2%
- note :: includes Gaza Strip (2009 est.)
*** Distribution of family income - Gini index
34.5 (2009 est.)

- note :: includes Gaza Strip
*** Budget
- revenues :: $2.742 billion
- expenditures :: $4.279 billion
- note :: includes Palestinian Authority expenditures in the Gaza Strip (2014 est.)
*** Taxes and other revenues
41.3% of GDP (2014 est.)
- country comparison to the world :: 33
*** Budget surplus (+) or deficit (-)
-23.1% of GDP (2014 est.)
- country comparison to the world :: 212
*** Public debt
41% of GDP (2013 est.)
39% of GDP (2012 est.)
- country comparison to the world :: 92
*** Fiscal year
calendar year
*** Inflation rate (consumer prices)
1.7% (2014 est.)
1.7% (2013 est.)
- note :: includes Gaza Strip
- country comparison to the world :: 88
*** Commercial bank prime lending rate
7.5% (31 December 2014 est.)
7.5% (31 December 2013 est.)
- country comparison to the world :: 119
*** Stock of narrow money
$269.2 million (31 December 2014 est.)
$220.5 million (31 December 2013 est.)
- country comparison to the world :: 173
*** Stock of broad money
$2.399 billion (31 December 2014 est.)
$2.16 billion (31 December 2013 est.)
- country comparison to the world :: 146
*** Stock of domestic credit
$1.341 billion (31 December 2014 est.)
$1.168 billion (31 December 2013 est.)
- country comparison to the world :: 151
*** Market value of publicly traded shares
$2.634 billion (31 December 2012 est.)
$2.532 billion (31 December 2011)
$2.45 billion (31 December 2010 est.)
- country comparison to the world :: 97
*** Current account balance
-$2.894 billion (2014 est.)
-$2.034 billion (2013 est.)
- country comparison to the world :: 154
*** Exports
$2.107 billion (2014 est.)
$2.102 billion (2013 est.)
- note :: includes Gaza Strip
- country comparison to the world :: 143
*** Exports - commodities
stone, olives, fruit, vegetables, limestone
*** Imports
$7.674 billion (2014 est.)
$6.645 billion (2013 est.)
- note :: data include the Gaza Strip
- country comparison to the world :: 112
*** Imports - commodities
food, consumer goods, construction materials, petroleum, chemicals
*** Debt - external
$1.04 billion (2010 est.)
$1.3 billion (2007 est.)
- note :: data include the Gaza Strip
- country comparison to the world :: 161
*** Exchange rates
new Israeli shekels (ILS) per US dollar -
3.908 (2013 est.)
3.611 (2013 est.)
3.86 (2012 est.)
3.5781 (2011 est.)
3.739 (2010 est.)
** Energy
*** Electricity - production
535 million kWh (2011 est.)
- country comparison to the world :: 162
*** Electricity - consumption
5.12 billion kWh (2011 est.)
- country comparison to the world :: 113
*** Electricity - exports
0 kWh (2013)
- country comparison to the world :: 213
*** Electricity - imports
4.909 billion kWh (2012 est.)
- country comparison to the world :: 42
*** Electricity - installed generating capacity
140,000 kW
- note :: includes Gaza Strip (2011 est.)
- country comparison to the world :: 167
*** Electricity - from fossil fuels
100% of total installed capacity (2011 est.)
- country comparison to the world :: 40
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 205
*** Electricity - from hydroelectric plants
0% of total installed capacity (2011 est.)
- country comparison to the world :: 209
*** Electricity - from other renewable sources
0% of total installed capacity (2011 est.)
- country comparison to the world :: 141
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 143
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 205
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 142
*** Crude oil - proved reserves
0 bbl (1 January 2009 est.)
- country comparison to the world :: 207
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 208
*** Refined petroleum products - consumption
23,000 bbl/day (2013 est.)
- country comparison to the world :: 125
*** Refined petroleum products - exports
514.8 bbl/day (2010 est.)
- country comparison to the world :: 112
*** Refined petroleum products - imports
16,330 bbl/day (2010 est.)
- country comparison to the world :: 112
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 208
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 208
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 207
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 78
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 207
*** Carbon dioxide emissions from consumption of energy
3.008 million Mt (2012 est.)
- country comparison to the world :: 142
** Communications
*** Telephones - fixed lines
- total subscriptions :: 400,000 (includes Gaza Strip)
- subscriptions per 100 inhabitants :: 15 (2014 est.)
- country comparison to the world :: 104
*** Telephones - mobile cellular
- total :: 3.2 million (includes Gaza Strip)
- subscriptions per 100 inhabitants :: 117 (includes Gaza Strip) (2014 est.)
- country comparison to the world :: 135
*** Telephone system
- general assessment :: continuing political and economic instability has impeded significant liberalization of the telecommunications industry
- domestic :: Israeli company BEZEK and the Palestinian company PALTEL are responsible for fixed-line services; PALTEL plans to establish a fiber-optic connection to Jordan to route domestic mobile calls; the Palestinian JAWWAL company and WATANIYA PALESTINE provide cellular services
- international :: country code - 970; 1 international switch in Ramallah (2009)
*** Broadcast media
the Palestinian Authority operates 1 TV and 1 radio station; about 20 private TV and 40 radio stations; both Jordanian TV and satellite TV are accessible (2013)
*** Radio broadcast stations
AM 0, FM 27, shortwave 0 (2010)
*** Television broadcast stations
31 (2010)
*** Internet country code
.ps; note - same as Gaza Strip
*** Internet users
- total :: 1.4 million (includes Gaza Strip)
- percent of population :: 34.4% (2009)
- country comparison to the world :: 112
** Transportation
*** Airports
2 (2013)
- country comparison to the world :: 203
*** Airports - with paved runways
- total :: 2
- 1,524 to 2,437 m :: 1
- under 914 m :: 1 (2013)
*** Heliports
1 (2013)
*** Roadways
- total :: 4,686 km
- paved :: 4,686 km
- note :: includes Gaza Strip (2010)
- country comparison to the world :: 154
** Military
*** Manpower fit for military service
- males age 16-49 :: 579,248
- females age 16-49 :: 547,782 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 30,925
- female :: 29,440 (2010 est.)
** Transnational Issues
*** Disputes - international
the current status of the West Bank is subject to the Israeli-Palestinian Interim Agreement - permanent status to be determined through further negotiation; Israel continues construction of a "seam line" separation barrier along parts of the Green Line and within the West Bank; Israel withdrew from Gaza and four settlements in the northern West Bank in August 2005; since 1948, about 350 peacekeepers from the UN Truce Supervision Organization (UNTSO), headquartered in Jerusalem, monitor ceasefires, supervise armistice agreements, prevent isolated incidents from escalating, and assist other UN personnel in the region
*** Refugees and internally displaced persons
- refugees (country of origin) :: 762,288 (Palestinian refugees (UNRWA)) (2014)
- IDPs :: at least 263,500 (includes persons displaced within the Gaza strip due to the intensification of the Israeli-Palestinian conflict since June 2014 and other Palestinian IDPs in the Gaza Strip and West Bank who fled as long ago as 1967, although confirmed cumulative figures do not go back beyond 2006) (2015)