** Introduction
*** Background
New Zealand occupied the German protectorate of Western Samoa at the outbreak of World War I in 1914. It continued to administer the islands as a mandate and then as a trust territory until 1962, when the islands became the first Polynesian nation to reestablish independence in the 20th century. The country dropped the "Western" from its name in 1997.
** Geography
*** Location
Oceania, group of islands in the South Pacific Ocean, about halfway between Hawaii and New Zealand
*** Geographic coordinates
13 35 S, 172 20 W
*** Map references
Oceania
*** Area
- total :: 2,831 sq km
- land :: 2,821 sq km
- water :: 10 sq km
- country comparison to the world :: 178
*** Area - comparative
slightly smaller than Rhode Island
*** Land boundaries
0 km
*** Coastline
403 km
*** Maritime claims
- territorial sea :: 12 nm
- contiguous zone :: 24 nm
- exclusive economic zone :: 200 nm
*** Climate
tropical; rainy season (November to April), dry season (May to October)
*** Terrain
two main islands (Savaii, Upolu) and several smaller islands and uninhabited islets; narrow coastal plain with volcanic, rugged mountains in interior
*** Elevation extremes
- lowest point :: Pacific Ocean 0 m
- highest point :: Mount Silisili 1,857 m
*** Natural resources
hardwood forests, fish, hydropower
*** Land use
- agricultural land :: 12.4%
arable land 2.8%; permanent crops 7.8%; permanent pasture 1.8%
- forest :: 60.4%
- other :: 27.2% (2011 est.)
*** Irrigated land
NA
*** Natural hazards
occasional typhoons; active volcanism
- volcanism :: Savai'I Island (elev. 1,858 m), which last erupted in 1911, is historically active
*** Environment - current issues
soil erosion, deforestation, invasive species, overfishing
*** Environment - international agreements
- party to :: Biodiversity, Climate Change, Climate Change-Kyoto Protocol, Desertification, Hazardous Wastes, Law of the Sea, Ozone Layer Protection, Ship Pollution, Wetlands
- signed, but not ratified :: none of the selected agreements
*** Geography - note
occupies an almost central position within Polynesia
** People and Society
*** Nationality
- noun :: Samoan(s)
- adjective :: Samoan
*** Ethnic groups
Samoan 92.6%, Euronesians (persons of European and Polynesian blood) 7%, Europeans 0.4% (2001 census)
*** Languages
Samoan (Polynesian) (official), English
*** Religions
Protestant 57.4% (Congregationalist 31.8%, Methodist 13.7%, Assembly of God 8%, Seventh-Day Adventist 3.9%), Roman Catholic 19.4%, Mormon 15.2%, Worship Centre 1.7%, other Christian 5.5%, other 0.7%, none 0.1%, unspecified 0.1% (2011 est.)
*** Population
197,773
- note :: prior estimates used official net migration data by sex, but a highly unusual pattern for 1993 lead to a significant imbalance in the sex ratios (more men and fewer women) and a seeming reduction in the female population; the revised total was calculated using a 1993 number that was an average of the 1992 and 1994 migration figures (July 2015 est.)
- country comparison to the world :: 185
*** Age structure
- 0-14 years :: 32.72% (male 33,393/female 31,324)
- 15-24 years :: 19.96% (male 20,253/female 19,217)
- 25-54 years :: 35.58% (male 36,374/female 33,993)
- 55-64 years :: 6.24% (male 6,283/female 6,057)
- 65 years and over :: 5.5% (male 4,730/female 6,149) (2015 est.)
- population pyramid ::  
*** Dependency ratios
- total dependency ratio :: 74%
- youth dependency ratio :: 64.9%
- elderly dependency ratio :: 9.1%
- potential support ratio :: 11% (2015 est.)
*** Median age
- total :: 23.5 years
- male :: 23.3 years
- female :: 23.8 years (2015 est.)
*** Population growth rate
0.58% (2015 est.)
- country comparison to the world :: 152
*** Birth rate
20.87 births/1,000 population (2015 est.)
- country comparison to the world :: 78
*** Death rate
5.32 deaths/1,000 population (2015 est.)
- country comparison to the world :: 178
*** Net migration rate
-9.78 migrant(s)/1,000 population (2015 est.)
- country comparison to the world :: 215
*** Urbanization
- urban population :: 19.1% of total population (2015)
- rate of urbanization :: -0.24% annual rate of change (2010-15 est.)
*** Major urban areas - population
APIA (capital) 37,000 (2014)
*** Sex ratio
- at birth :: 1.05 male(s)/female
- 0-14 years :: 1.07 male(s)/female
- 15-24 years :: 1.05 male(s)/female
- 25-54 years :: 1.07 male(s)/female
- 55-64 years :: 1.04 male(s)/female
- 65 years and over :: 0.77 male(s)/female
- total population :: 1.04 male(s)/female (2015 est.)
*** Infant mortality rate
- total :: 19.57 deaths/1,000 live births
- male :: 23.1 deaths/1,000 live births
- female :: 15.87 deaths/1,000 live births (2015 est.)
- country comparison to the world :: 90
*** Life expectancy at birth
- total population :: 73.46 years
- male :: 70.58 years
- female :: 76.48 years (2015 est.)
- country comparison to the world :: 131
*** Total fertility rate
2.84 children born/woman (2015 est.)
- country comparison to the world :: 60
*** Contraceptive prevalence rate
28.7% (2009)
*** Health expenditures
7.5% of GDP (2013)
- country comparison to the world :: 83
*** Physicians density
0.45 physicians/1,000 population (2008)
*** Hospital bed density
1 beds/1,000 population (2005)
*** Drinking water source
- improved :: 
urban: 97.5% of population
rural: 99.3% of population
total: 99% of population
- unimproved :: 
urban: 2.5% of population
rural: 0.7% of population
total: 1% of population (2015 est.)
*** Sanitation facility access
- improved :: 
urban: 93.3% of population
rural: 91.1% of population
total: 91.5% of population
- unimproved :: 
urban: 6.7% of population
rural: 8.9% of population
total: 8.5% of population (2015 est.)
*** HIV/AIDS - adult prevalence rate
NA
*** HIV/AIDS - people living with HIV/AIDS
NA
*** HIV/AIDS - deaths
NA
*** Obesity - adult prevalence rate
41.6% (2014)
- country comparison to the world :: 6
*** Education expenditures
5.8% of GDP (2008)
- country comparison to the world :: 48
*** Literacy
- definition :: age 15 and over can read and write
- total population :: 99%
- male :: 99.1%
- female :: 98.8% (2015 est.)
*** Unemployment, youth ages 15-24
- total :: 16.1%
- male :: 13.8%
- female :: 22.2% (2011 est.)
- country comparison to the world :: 75
** Government
*** Country name
- conventional long form :: Independent State of Samoa
- conventional short form :: Samoa
- local long form :: Malo Sa'oloto Tuto'atasi o Samoa
- local short form :: Samoa
- former :: Western Samoa
- note :: the name "Samoa" is composed of two parts, "sa" meaning sacred and "moa" meaning center, so the name can mean Holy Center; alternatively, it can mean "place of the sacred moa bird" of Polynesian mythology
*** Government type
parliamentary democracy
*** Capital
- name :: Apia
- geographic coordinates :: 13 49 S, 171 46 W
- time difference :: UTC+13 (18 hours ahead of Washington, DC, during Standard Time)
+1hr, begins last Sunday in September; ends first Sunday in April
*** Administrative divisions
11 districts; A'ana, Aiga-i-le-Tai, Atua, Fa'asaleleaga, Gaga'emauga, Gagaifomauga, Palauli, Satupa'itea, Tuamasaga, Va'a-o-Fonoti, Vaisigano
*** Independence
1 January 1962 (from New Zealand-administered UN trusteeship)
*** National holiday
Independence Day Celebration, 1 June (1962); note - 1 January 1962 is the date of independence from the New Zealand-administered UN trusteeship; it is observed in June
*** Constitution
several previous (preindependence); latest 1 January 1962; amended several times, last in 2013 (2013)
*** Legal system
mixed legal system of English common law and customary law; judicial review of legislative acts with respect to fundamental rights of the citizen
*** International law organization participation
has not submitted an ICJ jurisdiction declaration; accepts ICCt jurisdiction
*** Suffrage
21 years of age; universal
*** Executive branch
- chief of state :: TUI ATUA Tupua Tamasese Efi (since 20 June 2007)
- head of government :: Prime Minister TUILA'EPA Lupesoliai Sailele Malielegaoi (since 1998); Deputy Prime Minister FONOTOE Pierre Lauofo (since 2011)
- cabinet :: Cabinet appointed by the chief of state on the prime minister's advice
- elections/appointments :: chief of state indirectly elected by the Legislative Assembly to serve a 5-year term (no term limits); election last held on 20 July 2012 (next to be held in 2017); following legislative elections, the leader of the majority party usually appointed prime minister by the chief of state, approved by the Legislative Assembly
- election results :: TUI ATUA Tupua Tamasese Efi unanimously elected by the Legislative Assembly
*** Legislative branch
- description :: unicameral Legislative Assembly or Fono (49 seats; 47 members - traditional family chiefs or matai and 2 members - part-Samoan or non-Samoan - directly elected by simple majority vote; members serve 5-year terms)
- elections :: election last held on 4 March 2011 (next election to be held no later than March 2016)
- election results :: percent of vote by party - NA; seats by party - HRPP 29, Tautua Samoa 13, independents 7
*** Judicial branch
- highest court(s) :: Court of Appeal (consists of the chief justice and 2 Supreme Court judges and meets once or twice a year); Supreme Court (consists of the chief justice and several judges)
- judge selection and term of office :: chief justice appointed by the head of state upon the advice of the prime minister; other Supreme Court judges appointed by the Judicial Service Commission, a 3-member body chaired by the chief justice and includes the attorney general and an appointee of the Minister of Justice; judges normally appointed until retirement at age 68
- subordinate courts :: District Court; Magistrates' Courts; Land and Titles Courts; village fono or village chief councils
*** Political parties and leaders
Human Rights Protection Party or HRPP [Sailele Malielegaoi TUILA'EPA]
Samoa Christian Party or TCP [Tuala Tiresa MALIETOA]
Samoa Progressive Political Party or SPPP [Toalepaiali'i Toesulusulu S'iueva POSE II]
Tautua Samoa [Leatinu'u Salole LESA]
*** Political pressure groups and leaders
NA
*** International organization participation
ACP, ADB, AOSIS, C, FAO, G-77, IBRD, ICAO, ICCt, ICRM, IDA, IFAD, IFC, IFRCS, ILO, IMF, IMO, Interpol, IOC, IPU, ITU, ITUC (NGOs), MIGA, OPCW, PIF, Sparteca, SPC, UN, UNCTAD, UNESCO, UNIDO, UPU, WCO, WHO, WIPO, WMO, WTO
*** Diplomatic representation in the US
- chief of mission :: Ambassador Aliioaiga Feturi ELISAIA (since 4 December 2003)
- chancery :: 800 Second Avenue, Suite 400J, New York, NY 10017
- telephone :: [1] (212) 599-6196 through 6197
- FAX :: [1] (212) 599-0797
- consulate(s) general :: Pago Pago (American Samoa)
*** Diplomatic representation from the US
- chief of mission :: the US does not have an embassy in Samoa; the US Ambassador to New Zealand is accredited to Samoa
- embassy :: Accident Corporation Building, 5th Floor, Matafele, Apia
- mailing address :: P. O. Box 3430, Matafele, Apia
- telephone :: [685] 21436/21631/21452/22696
- FAX :: [685] 22030
*** Flag description
red with a blue rectangle in the upper hoist-side quadrant bearing five white five-pointed stars representing the Southern Cross constellation; red stands for courage, blue represents freedom, and white signifies purity
*** National symbol(s)
Southern Cross constellation (five, five-pointed stars); national colors: red, white, blue
*** National anthem
- name :: "O le Fu'a o le Sa'olotoga o Samoa" (The Banner of Freedom)
- lyrics/music :: Sauni Liga KURESA
- note :: adopted 1962; also known as "Samoa Tula'i" (Samoa Arise)
** Economy
*** Economy - overview
The economy of Samoa has traditionally been dependent on development aid, family remittances from overseas, tourism, agriculture, and fishing.  It has a nominal GDP of $780 million.  Agriculture, including fishing, employs roughly two-thirds of the labor force and furnishes 90% of exports, featuring fish, coconut oil, nonu products, and taro. The manufacturing sector mainly processes agricultural products. One factory in the Foreign Trade Zone employs 1,000 people to make automobile electrical harnesses for an assembly plant in Australia, and is responsible for 65% of total exports.  Industry accounts for nearly 15% of GDP while employing less than 6% of the work force.  The service sector accounts for nearly three-quarters of GDP and employs approximately 50% of the labor force. Tourism is an expanding sector accounting for 25% of GDP; 132,000 tourists visited the islands in 2013. The country is vulnerable to devastating storms. In late September 2009, an earthquake and the resulting tsunami severely damaged Samoa, and nearby American Samoa, disrupting transportation and power generation, and resulting in about 200 deaths. In December 2012, extensive flooding and wind damage from Tropical Cyclone Evan killed four people, displaced over 6,000, and damaged or destroyed an estimated 1,500 homes in Samoa's Upolu Island. The Samoan Government has called for deregulation of the financial sector, encouragement of investment, and continued fiscal discipline, while at the same time protecting the environment. Foreign reserves are in a relatively healthy state and inflation is low, but the external debt is approximately 55% of GDP. Samoa became the 155th member of the WTO in May 2012, and graduated from least developed country (LDC) status in January 2014.
*** GDP (purchasing power parity)
$994 million (2014 est.)
$975.5 million (2013 est.)
$986.1 million (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 204
*** GDP (official exchange rate)
$826 million (2014 est.)
*** GDP - real growth rate
1.9% (2014 est.)
-1.1% (2013 est.)
1.2% (2012 est.)
- country comparison to the world :: 150
*** GDP - per capita (PPP)
$5,200 (2014 est.)
$5,100 (2013 est.)
$5,100 (2012 est.)
- note :: data are in 2014 US dollars
- country comparison to the world :: 164
*** GDP - composition, by sector of origin
- agriculture :: 11.4%
- industry :: 30.1%
- services :: 58.5% (2014 est.)
*** Agriculture - products
coconuts, nonu, bananas, taro, yams, coffee, cocoa
*** Industries
food processing, building materials, auto parts
*** Industrial production growth rate
1.5% (2014 est.)
- country comparison to the world :: 141
*** Labor force
48,580 (2012 est.)
- country comparison to the world :: 194
*** Labor force - by occupation
- agriculture :: 65%
- industry :: NA%
- services :: NA%
*** Unemployment rate
NA%
*** Population below poverty line
NA%
*** Household income or consumption by percentage share
- lowest 10% :: NA%
- highest 10% :: NA%
*** Budget
- revenues :: $214.7 million
- expenditures :: $257.6 million (2014 est.)
*** Taxes and other revenues
26% of GDP (2014 est.)
- country comparison to the world :: 111
*** Budget surplus (+) or deficit (-)
-5.2% of GDP (2014 est.)
- country comparison to the world :: 173
*** Fiscal year
June 1 - May 31
*** Inflation rate (consumer prices)
-1.2% (2014 est.)
0.6% (2013 est.)
- country comparison to the world :: 5
*** Commercial bank prime lending rate
10.2% (31 December 2014 est.)
10.19% (31 December 2013 est.)
- country comparison to the world :: 83
*** Stock of narrow money
$106.9 million (31 December 2014 est.)
$104.1 million (31 December 2013 est.)
- country comparison to the world :: 183
*** Stock of broad money
$366 million (31 December 2014 est.)
$318.7 million (31 December 2013 est.)
- country comparison to the world :: 184
*** Stock of domestic credit
$332.1 million (31 December 2014 est.)
$319.1 million (31 December 2013 est.)
- country comparison to the world :: 175
*** Market value of publicly traded shares
$NA
*** Current account balance
-$31 million (2014 est.)
-$76.11 million (2011 est.)
- country comparison to the world :: 75
*** Exports
$31.2 million (2012 est.)
$11.4 million (2011 est.)
- country comparison to the world :: 214
*** Exports - commodities
fish, coconut oil and cream, nonu, copra, taro, automotive parts, garments, beer
*** Exports - partners
American Samoa 56.8%, Australia 18.3% (2014)
*** Imports
$318.7 million (2011 est.)
$308.4 million (2012 est.)
- country comparison to the world :: 195
*** Imports - commodities
machinery and equipment, industrial supplies, foodstuffs
*** Imports - partners
Fiji 21.5%, NZ 20.5%, China 13.6%, South Korea 8.1%, Australia 5.9%, US 5.6%, Singapore 5.6% (2014)
*** Reserves of foreign exchange and gold
$170.9 million (31 December 2013 est.)
- country comparison to the world :: 163
*** Debt - external
$368.3 million (31 December 2011 est.)
$422.9 million (31 December 2012 est.)
- country comparison to the world :: 182
*** Exchange rates
tala (SAT) per US dollar -
2.329 (2014 est.)
2.3109 (2013 est.)
2.29 (2012 est.)
2.3175 (2011 est.)
2.4847 (2010 est.)
** Energy
*** Electricity - production
115.2 million kWh (2011 est.)
- country comparison to the world :: 198
*** Electricity - consumption
107.1 million kWh (2011 est.)
- country comparison to the world :: 198
*** Electricity - exports
0 kWh (2013 est.)
- country comparison to the world :: 215
*** Electricity - imports
0 kWh (2013 est.)
- country comparison to the world :: 217
*** Electricity - installed generating capacity
42,100 kW (2011 est.)
- country comparison to the world :: 195
*** Electricity - from fossil fuels
71.3% of total installed capacity (2011 est.)
- country comparison to the world :: 107
*** Electricity - from nuclear fuels
0% of total installed capacity (2011 est.)
- country comparison to the world :: 207
*** Electricity - from hydroelectric plants
28.5% of total installed capacity (2011 est.)
- country comparison to the world :: 80
*** Electricity - from other renewable sources
0.2% of total installed capacity (2011 est.)
- country comparison to the world :: 101
*** Crude oil - production
0 bbl/day (2013 est.)
- country comparison to the world :: 145
*** Crude oil - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 207
*** Crude oil - imports
0 bbl/day (2010 est.)
- country comparison to the world :: 144
*** Crude oil - proved reserves
0 bbl (1 January 2014 est.)
- country comparison to the world :: 209
*** Refined petroleum products - production
0 bbl/day (2010 est.)
- country comparison to the world :: 210
*** Refined petroleum products - consumption
1,130 bbl/day (2013 est.)
- country comparison to the world :: 199
*** Refined petroleum products - exports
0 bbl/day (2010 est.)
- country comparison to the world :: 145
*** Refined petroleum products - imports
1,149 bbl/day (2010 est.)
- country comparison to the world :: 192
*** Natural gas - production
0 cu m (2012 est.)
- country comparison to the world :: 210
*** Natural gas - consumption
0 cu m (2012 est.)
- country comparison to the world :: 210
*** Natural gas - exports
0 cu m (2012 est.)
- country comparison to the world :: 209
*** Natural gas - imports
0 cu m (2012 est.)
- country comparison to the world :: 80
*** Natural gas - proved reserves
0 cu m (1 January 2014 est.)
- country comparison to the world :: 209
*** Carbon dioxide emissions from consumption of energy
161,000 Mt (2012 est.)
- country comparison to the world :: 200
** Communications
*** Telephones - fixed lines
- total subscriptions :: 11,800
- subscriptions per 100 inhabitants :: 6 (2014 est.)
- country comparison to the world :: 196
*** Telephones - mobile cellular
- total :: 106,500
- subscriptions per 100 inhabitants :: 54 (2014 est.)
- country comparison to the world :: 190
*** Telephone system
- general assessment :: adequate
- domestic :: combined fixed-line and mobile-cellular teledensity roughly 100 telephones per 100 persons
- international :: country code - 685; satellite earth station - 1 Intelsat (Pacific Ocean) (2007)
*** Broadcast media
state-owned TV station privatized in 2008; 4 privately owned television broadcast stations; about a half dozen privately owned radio stations and one state-owned radio station; TV and radio broadcasts of several stations from American Samoa are available (2009)
*** Radio broadcast stations
AM 2, FM 5, shortwave 0 (2004)
*** Television broadcast stations
2 (2002)
*** Internet country code
.ws
*** Internet users
- total :: 27,600
- percent of population :: 14.1% (2014 est.)
- country comparison to the world :: 198
** Transportation
*** Airports
4 (2013)
- country comparison to the world :: 188
*** Airports - with paved runways
- total :: 1
- 2,438 to 3,047 m :: 1 (2013)
*** Airports - with unpaved runways
- total :: 3
- under 914 m :: 
3 (2013)
*** Roadways
- total :: 2,337 km
- paved :: 332 km
- unpaved :: 2,005 km (2001)
- country comparison to the world :: 173
*** Merchant marine
- total :: 2
- by type :: cargo 1, passenger/cargo 1
- foreign-owned :: 1 (NZ 1) (2010)
- country comparison to the world :: 145
*** Ports and terminals
- major seaport(s) :: Apia
** Military
*** Military branches
no regular military forces; Samoa Police Force (2008)
*** Manpower available for military service
- males age 16-49 :: 47,906 (2010 est.)
*** Manpower fit for military service
- males age 16-49 :: 38,260
- females age 16-49 :: 38,032 (2010 est.)
*** Manpower reaching militarily significant age annually
- male :: 2,221
- female :: 2,062 (2010 est.)
*** Military - note
Samoa has no formal defense structure or regular armed forces; informal defense ties exist with NZ, which is required to consider any Samoan request for assistance under the 1962 Treaty of Friendship
** Transnational Issues
*** Disputes - international
none